# sysone


<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

sysone turns a pretrained encoder into a Jev-style typed-decision model:
give it a state and typed questions (`choice`, `score`, `noul`) and get
calibrated probabilities from one forward pass, over any option set
named at request time. It packages the recipe
[Laya](https://huggingface.co/convaiinnovations/laya) proved, an anchor
token in front of every option, a small scorer on the anchors,
proper-scoring-rule training and temperature calibration, as a
fastai-shaped library: a one-line application API for the common case,
and every layer below it reachable when the case is not common.

Every answer is read off the anchor rows and the schema is filled by
code, so there is nothing to parse and no output tokens; k options are k
anchors, so a trained model is zero-shot over new label sets; and
several questions are several rows of one batch.

<div>

<figure class=''>

<div>

<img src="index_files/figure-commonmark/mermaid-figure-1.png"
style="width:15.33in;height:1.23in" />

</div>

</figure>

</div>

## The ten lines

``` python
from sysone.text import TypedDecisions, decision_learner
from sysone import Decider, load_learner

data  = TypedDecisions.from_hub("LocalLLaMA/typed-decisions", valid="test")
learn = decision_learner(data, "answerdotai/ModernBERT-large", train="head")  # frozen encoder, cached features
learn.lr_find()                       # LR range test, suggests a value
learn.fit_one_cycle(4, lr=1e-3)       # warmup + cosine, head LR and encoder LR separately
learn.calibrate()                     # temperatures per type and option count, on the held-out slice
learn.predict(state, questions)       # the Jev answer schema from the model in memory, before any export
learn.export("my-jev")                # head + sysone.json (template, budgets, temperatures), and Laya's format when it applies

jev = Decider.load("my-jev")          # the same answers from the exported folder, on CPU, CUDA or MPS
jev.predict(state, questions)         # choice / score / noul, probabilities, confidence
learn = load_learner("my-jev", data)  # the learner back, on any machine: evaluate, interpret or train on
```

`train="lora"`, `"mica"` or `"full"` trains the encoder too;
`decision_learner(data, "convaiinnovations/laya", init_from="convaiinnovations/laya", train="full")`
fine-tunes Laya’s own checkpoint as its notebook does;
`sysone.multimodal` puts screenshots in the state, with ModernVBERT by
default ([why](20_neomme.ipynb#which-encoder-by-default)) or with NeoMME
(`decision_learner(data, "Hcompany/NeoMME-260M")`); `sysone.protein`
asks typed questions about protein sequences with ProtST, zero-shot from
its joint space or with a head trained on its frozen towers;
`sysone.zeroshot` answers without training, from a two-tower model’s
similarity or a masked language model’s own prediction; a GLiNER2
checkpoint is a text encoder like any other (with `head="gliner2"` and
`init_from` set to the checkpoint, the head starts from its classifier),
while `sysone.gliner` drives whole GLiNER2 models through their own
package.

To see how good a model is, where it goes wrong and why:
`metrics=[F1Score(), BalancedAccuracy()]` adds fastai-style metrics to
what the learner reports every epoch ([metrics](04a_metrics.ipynb));
`Interpretation.from_learner(learn)` finds the worst decisions, the
confusions and how confidence compares with being right; and
`learn.explain(state, questions)` shows which tokens, pixels and
residues moved each option’s probability, by integrated gradients or by
occlusion ([interpret](09a_interpret.ipynb), and the [interpretation
tutorial](tutorials/08_interpretation.ipynb)).

To build a training set from data made for other models: converters turn
classification, pair, rating and multi-label datasets into records
([datasets](08_datasets.ipynb));
[`add_nouls`](https://sgaseretto.github.io/sysonelib/data.html#add_nouls),
[`add_score`](https://sgaseretto.github.io/sysonelib/data.html#add_score),
[`add_thresholds`](https://sgaseretto.github.io/sysonelib/data.html#add_thresholds)
and
[`add_none_of_these`](https://sgaseretto.github.io/sysonelib/data.html#add_none_of_these)
ask one label in several shapes, and the
[`Nouls`](https://sgaseretto.github.io/sysonelib/data.html#nouls),
[`NoneOfThese`](https://sgaseretto.github.io/sysonelib/data.html#noneofthese),
[`AsScore`](https://sgaseretto.github.io/sysonelib/data.html#asscore),
[`Thresholds`](https://sgaseretto.github.io/sysonelib/data.html#thresholds)
and
[`Rephrase`](https://sgaseretto.github.io/sysonelib/data.html#rephrase)
transforms draw those shapes anew every epoch, with one fixed draw for
validation ([data](02_data.ipynb#one-label-several-questions)). The
[reshaping tutorial](tutorials/09_reshaping_datasets.ipynb) does it for
text, and the [game-log tutorial](tutorials/10_game_logs.ipynb) for the
log of a system with rules.

To train elsewhere and keep track of it:
`remote("train.ipynb", on="colab", hw="t4", data=..., push=...)` runs a
notebook or a script as a job, in the background here or on Colab,
Kaggle or SageMaker, on the hardware named (`cpu`, `t4x2`, `l4`, `tpu`,
`trn1.2xlarge`, …), and
[`jobs()`](https://sgaseretto.github.io/sysonelib/cloud.html#jobs)
follows every job’s progress in one table ([cloud](40_cloud.ipynb)).
Every export carries a training record, the commit, packages, hardware,
data and fits that made it ([record](05a_record.ipynb));
`learn.push_to_hub(repo)` publishes it with a model card written from
that record ([hub](42_hub.ipynb)); `learn.track()` logs its training to
MLflow ([track](44_track.ipynb));
`login("hf" | "kaggle" | "colab" | "aws")` signs in from a notebook
([auth](43_auth.ipynb)); and `deploy(export, on=...)` serves it in
Docker or as a SageMaker endpoint, with
[`cloudformation`](https://sgaseretto.github.io/sysonelib/deploy.html#cloudformation)
and
[`cdk_app`](https://sgaseretto.github.io/sysonelib/deploy.html#cdk_app)
writing the infrastructure ([deploy](49_deploy.ipynb)). On TPUs and
Trainium, the `tpu` and `neuron` presets keep XLA’s graphs few
([xla](47_xla.ipynb)).

## What it answers

Three typed questions about one state, and the answers in the Jev
schema. The model here is the fixture the notebooks test against, a
random four-layer ModernBERT whose head trained for a few seconds, so
its probabilities are close to uniform: what matters is the shape of the
answers, one per question from one forward pass.

``` python
import json, logging, tempfile
from pathlib import Path
logging.getLogger("transformers").setLevel(logging.ERROR)
from sysone.text import TypedDecisions, decision_learner
data = TypedDecisions.from_json("fixtures/typed_decisions_tiny.jsonl", valid=0.25)
learn = decision_learner(data, "fixtures/tiny-modernbert", train="head", preset="cpu", cache_dir=tempfile.mkdtemp())
learn.fit_one_cycle(3, lr=3e-3)
state = {"from": "user@acme.com", "body": "I was charged twice for invoice 4411 and I am cancelling if this is not fixed today."}
questions = {"department": {"type": "choice", "instructions": "Which department should handle this?",
                            "criteria": {"billing": "invoices, refunds", "technical": "bugs, outages"}},
             "urgency":    {"type": "score", "instructions": "How urgent is it?", "criteria": ["not urgent", "soon", "critical"]},
             "churn_risk": {"type": "noul", "instructions": "Does the user threaten to leave?"}}
learn.predict(state, questions)
```

    {'eval_loss': '1.191', 'eval_accuracy': '0.4', 'eval_soft_accuracy': '0.3767', 'eval_brier': '0.26', 'eval_kl': '0.4434', 'eval_tv': '0.366', 'eval_ece': '0.07593', 'eval_score_mae': '0.838', 'eval_within_one': '0.6', 'eval_n': 25, 'eval_accuracy_choice': '0.4286', 'eval_accuracy_score': '0.2', 'eval_accuracy_noul': '0.625', 'eval_n_unanswerable': 0, 'eval_runtime': '0.0052', 'eval_samples_per_second': '4786', 'eval_steps_per_second': '382.9', 'epoch': '1'}
    {'loss': '0.7765', 'grad_norm': '0.005896', 'learning_rate': '0.002927', 'epoch': '1.111'}
    {'eval_loss': '1.191', 'eval_accuracy': '0.48', 'eval_soft_accuracy': '0.3767', 'eval_brier': '0.2599', 'eval_kl': '0.4433', 'eval_tv': '0.366', 'eval_ece': '0.1559', 'eval_score_mae': '0.8379', 'eval_within_one': '0.6', 'eval_n': 25, 'eval_accuracy_choice': '0.4286', 'eval_accuracy_score': '0.3', 'eval_accuracy_noul': '0.75', 'eval_n_unanswerable': 0, 'eval_runtime': '0.0045', 'eval_samples_per_second': '5577', 'eval_steps_per_second': '446.2', 'epoch': '2'}
    {'loss': '1.045', 'grad_norm': '0.01068', 'learning_rate': '0.001036', 'epoch': '2.222'}
    {'eval_loss': '1.191', 'eval_accuracy': '0.48', 'eval_soft_accuracy': '0.3767', 'eval_brier': '0.2599', 'eval_kl': '0.4433', 'eval_tv': '0.366', 'eval_ece': '0.1559', 'eval_score_mae': '0.8379', 'eval_within_one': '0.6', 'eval_n': 25, 'eval_accuracy_choice': '0.4286', 'eval_accuracy_score': '0.3', 'eval_accuracy_noul': '0.75', 'eval_n_unanswerable': 0, 'eval_runtime': '0.0044', 'eval_samples_per_second': '5678', 'eval_steps_per_second': '454.2', 'epoch': '3'}
    {'train_runtime': '0.0818', 'train_samples_per_second': '2385', 'train_steps_per_second': '330.2', 'train_loss': '0.9289', 'epoch': '3'}

    {'department': {'type': 'choice',
      'choice': 'technical',
      'probabilities': {'billing': 0.4999, 'technical': 0.5001},
      'confidence': 0.0,
      'answer_confidence': 0.5001},
     'urgency': {'type': 'score',
      'score': 1.0002,
      'legend': {'0': 'not urgent', '1': 'soon', '2': 'critical'},
      'probabilities': {'0': 0.3333, '1': 0.3333, '2': 0.3334},
      'confidence': 0.0,
      'answer_confidence': 0.3334},
     'churn_risk': {'type': 'noul',
      'noul': 0.5,
      'confidence': 0.5,
      'answer_confidence': 0.5}}

## Validated so far

Measured between 2026-09-26 and 2026-10-06 with the code in this
repository, on an M3 Pro (MPS, fp32) unless a row says otherwise:

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr>
<th>What</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr>
<td>Laya’s published typed-decisions checkpoint, loaded with
<code>Decider.load("convaiinnovations/laya/typed-decisions")</code>, on
the 2,000 test decisions</td>
<td><strong>0.766 accuracy</strong>, Laya’s reported number; the same
answer as <code>laya.Agent</code> on 200 of 200 compared decisions</td>
</tr>
<tr>
<td>Laya’s multilingual checkpoint,
<code>Decider.load("convaiinnovations/laya/multilingual")</code>
(mmBERT’s tokenizer, <code>&lt;mask&gt;</code> anchors, 1024-token
rows)</td>
<td>the same probabilities as <code>laya.Agent</code> on 153 of 153
decisions, 30 test cases and a Spanish one</td>
</tr>
<tr>
<td>Head-only ModernBERT-large, frozen, anchors cached (the ten lines
above)</td>
<td>0.504 accuracy, below the dataset card’s majority baseline (0.520):
a frozen encoder never tuned for decisions carries little of the task.
12 minutes end to end, of which 58 s is training</td>
</tr>
<tr>
<td>Laya’s general checkpoint, <code>convaiinnovations/laya</code>,
zero-shot on the same test split</td>
<td>0.362 accuracy: it was not trained on these four workflows</td>
</tr>
<tr>
<td>Laya’s general encoder, frozen, under a new head
(<code>decision_learner(data, "convaiinnovations/laya", train="head")</code>)</td>
<td>0.560 accuracy, against ModernBERT-large’s 0.504 under the same
recipe: an encoder already trained on decisions gives a new head more to
work with</td>
</tr>
<tr>
<td>GLiNER2.5-Decide’s encoder, frozen, under a new head
(<code>decision_learner(data, "fastino/GLiNER2.5-Decide")</code>)</td>
<td>0.645 accuracy under the same recipe, the best frozen encoder
measured so far; its own classifier, copied into the head with no
training, scores 0.476 (the <a
href="10_text.ipynb#regimes-on-the-laptop">text notebook’s
table</a>)</td>
</tr>
<tr>
<td>Rows built by <a
href="https://sgaseretto.github.io/sysonelib/template.html#rowbuilder"><code>RowBuilder</code></a>
on Laya’s template</td>
<td>token-for-token identical to Laya’s <code>build_sequence</code> on
every fixture row, on ModernBERT-large’s tokenizer too</td>
</tr>
<tr>
<td>A sysone export in Laya’s format</td>
<td>loads in <code>laya.Agent</code>, which returns the same answers;
its logits match Laya’s <code>DecisionModel</code></td>
</tr>
<tr>
<td>RLCD</td>
<td>equal to the loss in Laya’s fine-tuning notebook, pasted, under the
same seed</td>
</tr>
<tr>
<td>NeoMME image rows</td>
<td>the image part, ids and two-axis positions, identical to NeoMME’s
processor</td>
</tr>
<tr>
<td>NeoMME-260M on real images, frozen, a head on its anchors</td>
<td>a 10-way digit choice from 100 MNIST images: 0.41 (chance 0.10), and
0.57 with the digits at 112 px; a hot-dog noul from 80 photos: 0.74
(chance 0.50); with LoRA, 0.33 and 0.72. Both took standardising
NeoMME’s vectors, and LoRA the plain scorer (the <a
href="tutorials/01_neomme_images.ipynb">images tutorial</a>, with every
output; the multimodal notebook, section 7)</td>
</tr>
<tr>
<td>ModernVBERT on the same images and recipes, frozen, a head on its
anchors</td>
<td>the digit choice: 0.84, where NeoMME scored 0.31; the hot-dog noul:
0.94, where NeoMME scored 0.74; with LoRA on the text tower, 0.84 and
0.96. A probe on its image vectors reads 0.92 and 0.98 (the <a
href="tutorials/02_modernvbert_images.ipynb">ModernVBERT tutorial</a>;
the two encoders side by side in the <a
href="tutorials/03_neomme_vs_modernvbert.ipynb">comparison</a>)</td>
</tr>
<tr>
<td>ProtST-ESM1b loaded from its tensors alone
(<code>sysone.protein</code>, no remote code), zero-shot on 600 DeepLoc
test proteins</td>
<td>a 10-way location choice: 0.418 with ProtST’s label texts as
options, against 0.300 for the majority class, and 0.270 to 0.345 with
other wordings; a membrane noul: 0.758, against 0.578</td>
</tr>
<tr>
<td>The protein application: a pair head on ProtST’s frozen towers,
trained from vectors cached once for 1,200 proteins</td>
<td>0.828 on the location choice, 0.906 on the membrane noul, 0.896 on
four-way shortlists. At a 90% target, thresholds on the head’s
calibrated confidence act on 70% of the location questions, and the act
head’s on 57% (the <a
href="tutorials/04_protein_decisions.ipynb">protein tutorial</a>, 13
minutes on the laptop)</td>
</tr>
<tr>
<td>GLiNER2.5-Decide zero-shot on Fastino’s own benchmark (its published
development split: 17 domains, 1,700 rows)</td>
<td>0.629 over every head as the dataset card scores it (the card
reports 0.602 on its hidden test split), 0.685 over the 26 single-label
heads. sysone’s GLiNER2 backend scores 0.693, and the encoder under the
sysone head with the classifier copied in 0.684, giving the card’s label
on 95% of the decisions</td>
</tr>
<tr>
<td>Heads trained on half of each domain, scored on the other half</td>
<td>the copied classifier, trained: 0.684; a new head on the Decide
encoder: 0.690; a new head on ModernBERT-large: 0.420 (the <a
href="tutorials/05_gliner_decide.ipynb">GLiNER2.5-Decide tutorial</a>,
19 minutes on the laptop)</td>
</tr>
<tr>
<td>Web pages as text: Mind2Web’s steps in JevForge’s records, a 12-way
element choice on 8 held-out websites, frozen encoders under a new
head</td>
<td>NeoMME-260M 0.406, GLiNER2.5-Decide 0.393, ModernVBERT 0.384,
ModernBERT-large 0.374, against 0.083 for guessing; GLiNER2’s
classifier, zero-shot, 0.244 (the <a
href="tutorials/06_web_text.ipynb">text tutorial</a>, an hour on the
laptop)</td>
</tr>
<tr>
<td>Web pages as screenshots: a pilot on 467 Multimodal-Mind2Web steps,
191 of them on 9 held-out websites</td>
<td>on the operation question, ModernVBERT with the screenshot 0.885 and
NeoMME with it 0.812, against 0.801 for always CLICK; NeoMME without the
screenshot 0.880 (asked with the actions each step’s candidates allow,
which give the operation away on most steps). No head learned the 45-way
element question from 276 steps: 0.14 to 0.21, against 0.12 for guessing
(the <a href="tutorials/07_web_screens.ipynb">screens tutorial</a>, 32
minutes)</td>
</tr>
<tr>
<td>The masked diffusion model
<code>dllm-hub/Qwen3-0.6B-diffusion-mdlm-v0.1</code>, zero-shot in
jev-dllm’s layout (its own Yes against its No at each option), on
typed-decisions’ 2,000 test decisions, on a Kaggle T4</td>
<td>0.409 accuracy, where jev-dllm reports 0.4135 for the same model;
all 2,000 rows token for token the rows jev-dllm builds (the <a
href="24_mdlm.ipynb#on-the-real-checkpoint">diffusion model’s
notebook</a>)</td>
</tr>
<tr>
<td>The same model with a LoRA adapter, 300 steps on typed-decisions’
training split, on a Kaggle T4</td>
<td>0.768 accuracy, level with Laya’s checkpoint (0.766) and past
jev-dllm’s full fine-tune (0.5225); its export loads back to the same
answer on 200 of 200 decisions, and with the adapter off the model is
the published one exactly; published as <a
href="https://huggingface.co/sgaseretto/diffcider-typed-decisions"><code>sgaseretto/diffcider-typed-decisions</code></a>,
which scores the same on the decisions it was validated on when loaded
from the Hub (the <a
href="24_mdlm.ipynb#trained-on-the-real-checkpoint">diffusion model’s
notebook</a>)</td>
</tr>
<tr>
<td>The same model as a browser agent’s decider: LoRA on 1,500
Multimodal-Mind2Web steps read as text, every action offered on every
step and the operations balanced, scored on 300 steps from 9 held-out
websites, on a Kaggle T4</td>
<td>the operation 0.853, where always clicking gets 0.783 and the rarest
action offered 0.797 (a first adapter, trained on the steps as they
come, always clicked; untrained, the model answers DONE: 0.023); the
element among up to 45 0.647 (0.247 untrained); the whole step, typed
text included, 0.470; with the adapter off, it writes a typing step’s
text exactly from the goal 49% of the time in 8 unmasking steps (372
ms); published as <a
href="https://huggingface.co/sgaseretto/diffcider-browser"><code>sgaseretto/diffcider-browser</code></a>
(the <a href="24_mdlm.ipynb#every-action-offered">diffusion model’s
notebook</a>, and the <a href="tutorials/11_mdlm_browser.ipynb">browser
tutorial</a>)</td>
</tr>
<tr>
<td>Interpreting the three applications (the <a
href="tutorials/08_interpretation.ipynb">interpretation tutorial</a>, 17
minutes with warm feature caches)</td>
<td>emotions in tweets: LoRA on ModernBERT-large 0.768 accuracy and
macro-F1 0.736, where the frozen default scores 0.453; digits 0.87 and
hot dogs 0.938 with ModernVBERT; ProtST’s location head 0.788, macro-F1
0.572. Integrated gradients’ attributions added up for a tweet’s answer,
but not for the pixels or for one of two proteins, and its word scores
correlated with occlusion’s at a median of 0.21</td>
</tr>
</tbody>
</table>

Not yet run: the full fine-tune on Kaggle’s T4 pair that reproduces
Laya’s notebook from its released checkpoint (written in the text
notebook, launched with `sysone run`, which needs credentials), a full
run of the screenshot comparison (the pilot’s 276 training steps were
too few to learn the element question), and the zero-shot suites.

## Install

``` sh
pip install git+https://github.com/sgaseretto/sysonelib
```

Extras: `sysone[multimodal]` (pillow, torchvision, transformers ≥ 5.17
for NeoMME and ModernVBERT), `sysone[gliner]` (the `gliner2` package and
peft, on the same transformers 5 as the rest), `sysone[browser]` (the
Mind2Web converters), `sysone[shortlist]` (sentence-transformers),
`sysone[serve]` (FastAPI), `sysone[laya]` (Laya’s runtime, for its
export-compatibility check), `sysone[cloud]` (the Kaggle and Colab CLIs;
`uv tool install kaggle google-colab-cli` keeps them apart from the
project), `sysone[mlflow]` (MLflow, for tracking and its local server),
`sysone[aws]` (boto3 and the plugin for SageMaker’s managed MLflow),
`sysone[onnx]` (ONNX export of text models, served by
[`OnnxDecider`](https://sgaseretto.github.io/sysonelib/inference.html#onnxdecider)
on onnxruntime), `sysone[plots]` (matplotlib, for the figures of
`lr_find` and of the interpretations).

## How it is organised

<table>
<colgroup>
<col style="width: 33%" />
<col style="width: 33%" />
<col style="width: 33%" />
</colgroup>
<thead>
<tr>
<th>Layer</th>
<th>Modules</th>
<th>Holds</th>
</tr>
</thead>
<tbody>
<tr>
<td>Applications</td>
<td><code>sysone.text</code>, <code>sysone.multimodal</code>,
<code>sysone.protein</code>, <code>sysone.mdlm</code></td>
<td><a
href="https://sgaseretto.github.io/sysonelib/gliner_backend.html#decision_learner"><code>decision_learner</code></a>
per kind of input, with the encoder’s own defaults: text
(ModernBERT-large by default; mmBERT, Laya’s checkpoint, GLiNER2
checkpoints), images and text (ModernVBERT by default; NeoMME-260M),
proteins (ProtST), and a masked diffusion language model that decides
through its own Yes and No and, with its adapter off, writes (Qwen3-0.6B
MDLM)</td>
</tr>
<tr>
<td>Encoder adapters</td>
<td><code>sysone.multimodal</code> (NeoMME),
<code>sysone.modernvbert</code>, <code>sysone.models</code> (GLiNER2’s
encoder)</td>
<td>the methods an encoder adds to sysone’s generic functions (<a
href="https://sgaseretto.github.io/sysonelib/template.html#processor_rows"><code>processor_rows</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/template.html#default_image_side"><code>default_image_side</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/template.html#prepare_processor"><code>prepare_processor</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/models.html#encoder_inputs"><code>encoder_inputs</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/models.html#warm_start"><code>warm_start</code></a>),
dispatched on its classes with plum</td>
</tr>
<tr>
<td>Backends</td>
<td><code>sysone.zeroshot</code>, <code>sysone.gliner</code></td>
<td>answers in the same schema without sysone’s learner: zero-shot
deciders (<a
href="https://sgaseretto.github.io/sysonelib/zeroshot.html#similaritydecider"><code>SimilarityDecider</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/zeroshot.html#verbalizerdecider"><code>VerbalizerDecider</code></a>),
and GLiNER2 through its own package</td>
</tr>
<tr>
<td>High-level</td>
<td><code>sysone.data</code>, <code>sysone.learner</code>,
<code>sysone.inference</code>, <code>sysone.evaluate</code>,
<code>sysone.interpret</code></td>
<td><a
href="https://sgaseretto.github.io/sysonelib/data.html#typeddecisions"><code>TypedDecisions</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/learner.html#learner"><code>Learner</code></a>
(<code>lr_find</code>, <code>fit</code>, <code>fit_one_cycle</code>,
<code>freeze</code>, <code>calibrate</code>, <code>export</code>), <a
href="https://sgaseretto.github.io/sysonelib/inference.html#decider"><code>Decider</code></a>,
evaluation, <a
href="https://sgaseretto.github.io/sysonelib/interpret.html#interpretation"><code>Interpretation</code></a>
and attributions (<code>explain</code>, <a
href="https://sgaseretto.github.io/sysonelib/interpret.html#occlusion"><code>occlusion</code></a>)</td>
</tr>
<tr>
<td>Mid-level</td>
<td><code>sysone.template</code>, <code>sysone.models</code>,
<code>sysone.losses</code>, <code>sysone.metrics</code>,
<code>sysone.cache</code>, <code>sysone.datasets</code></td>
<td><a
href="https://sgaseretto.github.io/sysonelib/template.html#rowtemplate"><code>RowTemplate</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/template.html#rowbuilder"><code>RowBuilder</code></a>,
transforms and side streams, <a
href="https://sgaseretto.github.io/sysonelib/models.html#encoderspec"><code>EncoderSpec</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/models.html#decisionhead"><code>DecisionHead</code></a>
(readouts, queries, the act head), stream encoders and cross-attention,
regimes, soft CE and RLCD, temperatures, Laya’s metrics and coverage, <a
href="https://sgaseretto.github.io/sysonelib/metrics.html#preds"><code>Preds</code></a>
and fastai-style metrics (<a
href="https://sgaseretto.github.io/sysonelib/metrics.html#metric"><code>Metric</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/metrics.html#f1score"><code>F1Score</code></a>,
…), <a
href="https://sgaseretto.github.io/sysonelib/cache.html#featurecache"><code>FeatureCache</code></a>,
converters</td>
</tr>
<tr>
<td>Operations</td>
<td><code>sysone.record</code>, <code>sysone.hub</code>,
<code>sysone.auth</code>, <code>sysone.track</code>,
<code>sysone.cloud</code> with <code>sysone.colab</code>,
<code>sysone.kaggle</code> and <code>sysone.aws</code>,
<code>sysone.xla</code>, <code>sysone.deploy</code></td>
<td>the training record in every export, publishing with a model card,
logins, progress lines and MLflow, jobs on any backend and hardware (<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#remote"><code>remote</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#jobs"><code>jobs</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#local"><code>Local</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#colab"><code>Colab</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#kaggle"><code>Kaggle</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#sagemaker"><code>SageMaker</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#cpu"><code>CPU</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#gpu"><code>GPU</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#tpu"><code>TPU</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/cloud.html#neuron"><code>Neuron</code></a>),
XLA’s fixed shapes and the Inferentia2 export, endpoints and
infrastructure as code</td>
</tr>
<tr>
<td>Low-level</td>
<td><code>sysone.core</code></td>
<td><a
href="https://sgaseretto.github.io/sysonelib/core.html#question"><code>Question</code></a>
and its kinds (<a
href="https://sgaseretto.github.io/sysonelib/core.html#choice"><code>Choice</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/core.html#score"><code>Score</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/core.html#noul"><code>Noul</code></a>),
<a
href="https://sgaseretto.github.io/sysonelib/core.html#answer"><code>Answer</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/core.html#row"><code>Row</code></a>,
<a
href="https://sgaseretto.github.io/sysonelib/core.html#batch"><code>Batch</code></a>,
the answer schema’s generic functions, sysone’s dispatcher and <a
href="https://sgaseretto.github.io/sysonelib/core.html#load_adapter"><code>load_adapter</code></a></td>
</tr>
</tbody>
</table>

Around them: `sysone.cli`
(`sysone train | eval | predict | serve | run | jobs | publish | login | whoami`).

Where behaviour depends on the kind of question or on the encoder,
sysone uses generic functions: one name, a method per type, and the call
picks the method that fits (multiple dispatch, with plum). The
[core](00_core.ipynb#generic-functions-and-multiple-dispatch) notebook
explains them from the ground up, with examples, and lists every one
sysone has.

## Tutorials

- [NeoMME on images](tutorials/01_neomme_images.ipynb) trains the
  multimodal application on 100 MNIST digits (a 10-way choice) and 80
  food photos (a hot-dog noul). Its outputs show every step: the rows
  the encoder reads and the image patches in them, the training curves,
  the answers image by image, and the confusions. It compares the
  default head, the linear head and LoRA, and measures what the image
  size changes.
- [ModernVBERT on images](tutorials/02_modernvbert_images.ipynb) runs
  the same two tasks on ModernVBERT, with the same records and recipes.
  Its outputs show the rows with the image as one 512-pixel tile of 64
  image tokens, the three ways to train, the geometry of its vectors,
  and what more tiles change.
- [NeoMME and ModernVBERT, side by
  side](tutorials/03_neomme_vs_modernvbert.ipynb) trains both encoders
  on identical inputs, and compares their accuracy, calibration and
  cost, and where each one is wrong.
- [ProtST as a decision model](tutorials/04_protein_decisions.ipynb)
  asks three typed questions about each of 600 held-out proteins: a
  10-way location choice, a membrane noul, and a four-way shortlist that
  lacks the right answer a third of the time. It answers them zero-shot
  with ProtST, comparing four ways to write the options. Then it trains
  a head on the frozen towers from 1,200 proteins and compares the two,
  compartment by compartment. It ends with when to act and when to
  escalate: Laya’s act head against thresholds on the head’s own
  confidence.
- [GLiNER2.5-Decide under the sysone
  head](tutorials/05_gliner_decide.ipynb) runs Fastino’s decision model
  on its own benchmark three ways: as the dataset card scores it,
  through sysone’s GLiNER2 backend, and with its encoder under the
  sysone head and its classifier copied in. It measures how closely they
  agree before any training, then trains heads on half of each domain
  and scores them on the other half, beside a new head on
  ModernBERT-large. On the way, it shows why a learning rate suggested
  by `lr_find` needs a look at its curve.
- [Web pages as text](tutorials/06_web_text.ipynb) takes Mind2Web’s
  browser steps in JevForge’s ready-made records, a choice among 12 page
  elements on websites the heads never saw. It compares four frozen
  encoders under the same head: ModernBERT-large, GLiNER2.5-Decide’s
  encoder, and the multimodal application’s NeoMME and ModernVBERT
  reading text alone.
- [Web pages as screenshots](tutorials/07_web_screens.ipynb) is a pilot
  on Multimodal-Mind2Web, 467 browser steps with their screenshots,
  streamed as 0.5 GB of a 13.6 GB set. It asks whether NeoMME or
  ModernVBERT reads the pages better and whether the screenshot helps at
  all. It explains how the rows were chosen, the crop and the row
  budgets, and what a full run would need.
- [Interpreting decisions](tutorials/08_interpretation.ipynb) trains the
  three applications on small tasks and looks inside each: emotions in
  tweets (the text application, with LoRA), handwritten digits and
  photos of hot dogs (the multimodal application), and where in the cell
  a protein lives (ProtST). It reports metrics beyond accuracy, finds
  the confusions and the confident mistakes, and compares how sure the
  answers are with how often they are right. Then it attributes answers
  to words, pixels and residues, by integrated gradients and by
  occlusion, checks the two against each other, and pools occlusion over
  many decisions to show what a model has learned: the words of each
  emotion, and a mitochondrial targeting presequence.
- [Reshaping datasets](tutorials/09_reshaping_datasets.ipynb) turns
  datasets made for other models into typed decisions, and asks each
  label in more than one shape: AG News’s topics as a choice and as a
  statement per topic, restaurant reviews’ aspects (several per review)
  as statements and their sentiment as a choice, a score and two
  thresholds, and MASSIVE’s intents with their scenario as a second
  question and a third of them held out for a zero-shot test. It counts
  how many statements are true, softens labels that overlap, adds
  questions none of whose options is right, and draws statements and
  wordings anew every epoch, with one fixed draw for validation. Nothing
  is trained; the training runs are exercises.
- [Decisions from game logs](tutorials/10_game_logs.ipynb) turns 1,160
  logged tic-tac-toe moves into about 27 questions each: what was
  played, what the rules allow, what a perfect player would do, and how
  the game ends. It pools boards logged more than once into shares of
  the moves played, adds each board’s symmetric twins, and splits by
  board so that no twin crosses from training to validation. It runs in
  seconds, downloads nothing, and leaves the training runs as exercises.
- [A diffusion model as a browser
  agent](tutorials/11_mdlm_browser.ipynb) is an offline replica of
  laya-ultrafast on 300 recorded Mind2Web steps from websites the model
  never saw. One masked diffusion model decides each step’s operation
  and element through a LoRA adapter and, with the adapter off, writes
  what a typing step types. It counts what the untrained model picks
  (DONE), what a first adapter picks (CLICK, always) and what is left
  once the training shares are divided out (the rarest action a step
  offers), compares writing with `generate` and with `fill`, and reports
  the whole step, the typed text and the time each takes, beside
  laya-ultrafast’s numbers and the retrained adapter’s.

## Reading the notebooks

Read in order, the notebooks build the library up from its core, and
each one explains its part with flow charts and with tensor diagrams
drawn from the library’s own tensors (the [figures](90_figures.ipynb)
notebook draws them). Where the first implementation was wrong, or a
reference implementation misbehaves, a *Finding* note says what
happened, next to the evidence and the fix:

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr>
<th>Finding</th>
<th>Where</th>
</tr>
</thead>
<tbody>
<tr>
<td>Laya’s temperature fitter returns NaN on an underconfident model:
LBFGS without a line search takes a secant step of −1,812 in log T at an
inflection point</td>
<td><a href="04_losses.ipynb#fitting-one">losses</a></td>
</tr>
<tr>
<td>RLCD’s noise pulls its optimum towards distributions sharper than
the gold, in proportion to σ², which is why σ is annealed</td>
<td><a href="04_losses.ipynb#what-the-pieces-do">losses</a></td>
</tr>
<tr>
<td>A split by rows puts every held-out row’s state in training; sysone
splits by case</td>
<td><a href="02_data.ipynb#splits-by-case">data</a></td>
</tr>
<tr>
<td>Laya’s multilingual checkpoint anchors on <code>&lt;mask&gt;</code>,
not <code>[MASK]</code></td>
<td><a href="01_template.ipynb#laya-parity">template</a></td>
</tr>
<tr>
<td>BERT’s LoRA target names match nothing in ModernBERT, and a plain
<code>Wo</code> would also match its MLP</td>
<td><a href="03_models.ipynb#regimes">models</a></td>
</tr>
<tr>
<td>Unfreezing thawed the matrices MiCA keeps frozen</td>
<td><a href="03_models.ipynb#regimes">models</a></td>
</tr>
<tr>
<td>A new <code>TrainingArguments</code> resets the accelerator of a
live Trainer</td>
<td><a href="05_learner.ipynb#running-the-trainer">learner</a></td>
</tr>
<tr>
<td>With length grouping, the Trainer shuffles evaluation rows too</td>
<td><a href="05_learner.ipynb#predictions-and-metrics">learner</a></td>
</tr>
<tr>
<td>An export after <code>freeze</code> dropped the trained encoder;
bf16 checkpoints were served in bf16</td>
<td><a href="06_inference.ipynb#laya-compatibility">inference</a></td>
</tr>
<tr>
<td>A sampled weights fingerprint misses most weight changes; the first
cache served stale labels</td>
<td><a href="07_cache.ipynb#the-key">cache</a></td>
</tr>
<tr>
<td>NeoMME’s processor cannot build a decision row; what else did not
work</td>
<td><a
href="20_neomme.ipynb#what-did-not-work-and-what-to-watch">multimodal</a></td>
</tr>
<tr>
<td>One channel carries 97% of NeoMME’s vector norms: heads barely
learned until they standardised their input, and LoRA with Laya’s
two-layer head collapsed on small tasks</td>
<td><a
href="20_neomme.ipynb#two-small-image-tasks-on-the-real-checkpoint">multimodal</a></td>
</tr>
<tr>
<td>A float16 feature cache quantises that channel, so
<code>validate</code> and the <a
href="https://sgaseretto.github.io/sysonelib/inference.html#decider"><code>Decider</code></a>
disagreed on the same model’s calibration</td>
<td><a href="20_neomme.ipynb#a-head-only-run">multimodal</a></td>
</tr>
<tr>
<td>ModernVBERT’s processor enlarges every image to 2,048 px, so a 28-px
digit takes 17 tiles and 1,127 tokens; at 1,536 px, a batch of 8 rows is
80 tiles, and it held 8 GB of GPU memory</td>
<td><a href="23_modernvbert.ipynb#a-head-only-run">modernvbert</a></td>
</tr>
<tr>
<td>ModernVBERT’s anchors have a dominant channel too, 58% of each
vector’s length, and standardising them lifts the digits from 0.67 to
0.84</td>
<td><a
href="tutorials/02_modernvbert_images.ipynb#does-modernvbert-need-standardising">ModernVBERT
tutorial</a></td>
</tr>
<tr>
<td>NeoMME reads MNIST digits better at 56–112 px than at 224, and a
seeded split of stock photos leaves shoots on both sides</td>
<td><a
href="tutorials/01_neomme_images.ipynb#one-more-setting-the-image-size">images
tutorial</a></td>
</tr>
<tr>
<td>The published Mind2Web converter misses ARIA labels, field values
and <code>&lt;select&gt;</code> labels</td>
<td><a href="21_screens.ipynb">screens</a></td>
</tr>
<tr>
<td>ProtST-BinaryLocalization labels membrane-bound proteins 0, which
its card doesn’t say</td>
<td><a href="tutorials/04_protein_decisions.ipynb#the-data">protein
tutorial</a></td>
</tr>
<tr>
<td>An embedder built on the spot switched ProtST’s shared text tower
into training mode, and peft needs a <code>base_model_prefix</code> on a
stream encoder</td>
<td><a href="22_protein.ipynb#zero-shot">protein</a></td>
</tr>
<tr>
<td>Laya’s act head, trained on the rows the option head fits, ranked
answers worse than the head’s own confidence, and one threshold for
every question acted on no shortlist</td>
<td><a
href="tutorials/04_protein_decisions.ipynb#acting-or-escalating">protein
tutorial</a></td>
</tr>
<tr>
<td><code>gliner2</code> refuses an empty instruction, so the GLiNER2
backend stopped on questions without one; fixed, a question sent on its
own gets the benchmark card’s answer on all 2,600 decisions</td>
<td><a href="31_gliner_backend.ipynb#glinerdecider">gliner
backend</a></td>
</tr>
<tr>
<td><code>lr_find</code>’s valley for the same new head on the same 850
rows was 1.4e-6 with one batch order and 6.6e-4 with another</td>
<td><a
href="tutorials/05_gliner_decide.ipynb#how-fast-to-train">GLiNER2.5-Decide
tutorial</a></td>
</tr>
<tr>
<td>Tiled images shrank a cached head’s training batch as well, so a
sweep of image sizes compared batches of four rows with batches of
one</td>
<td><a href="23_modernvbert.ipynb#a-head-only-run">modernvbert</a></td>
</tr>
<tr>
<td>Image rows lost their case ids in the feature cache, so a per-case
look at a multimodal learner’s predictions put every row under one empty
id</td>
<td><a href="07_cache.ipynb#featurecache">cache</a></td>
</tr>
<tr>
<td>A Mind2Web question needs up to 1,500 tokens, so the multimodal
presets cut each of 45 options to 8 tokens, and the screenshots are
whole pages up to 40,000 pixels tall</td>
<td><a href="21_screens.ipynb#on-real-rows">screens</a></td>
</tr>
<tr>
<td>A batch of integrated-gradient steps went through a side encoder as
one row, since a side encoder encodes each distinct input once</td>
<td><a
href="09a_interpret.ipynb#integrated-gradients">interpret</a></td>
</tr>
<tr>
<td>Integrated gradients’ attributions didn’t add up on the real
encoders: on frozen ModernBERT-large an option’s log-probability is
jagged along the line, and even 2,049 exact gradients miss its change by
nats; through ModernVBERT’s pixels and ESM’s residues, the sums missed
by a sixth to more than the whole change</td>
<td><a
href="09a_interpret.ipynb#how-far-to-trust-an-attribution">interpret</a></td>
</tr>
<tr>
<td>A protein’s attribution held 20 GB, with eight integrated-gradient
steps through ESM-1b at once; <a
href="https://sgaseretto.github.io/sysonelib/interpret.html#attribute"><code>attribute</code></a>
now measures what a step keeps and batches to 2 GB</td>
<td><a
href="09a_interpret.ipynb#how-far-to-trust-an-attribution">interpret</a></td>
</tr>
<tr>
<td>The Colab CLI writes the code of every <code>colab exec</code>, its
<code>--env</code> values included, to a local history file, so a token
passed that way would sit there in plain text; jobs send secrets as an
uploaded file instead</td>
<td><a href="45_colab.ipynb">colab</a></td>
</tr>
<tr>
<td>MLflow 3.16’s file store refuses to log, and a SQLite store puts
artifacts in <code>./mlruns</code> under the current folder; sysone
keeps them beside the database</td>
<td><a href="44_track.ipynb#mlflow">track</a></td>
</tr>
<tr>
<td>floci runs SageMaker’s training jobs and endpoints in Docker, but a
training job’s <code>Environment</code> does not reach the container and
only <code>/opt/ml/model</code> is uploaded; jobs carry their settings
in <code>job.json</code>, and their outputs in the model on an
emulator</td>
<td><a href="48_aws.ipynb">aws</a></td>
</tr>
<tr>
<td>The SageMaker Python SDK as an extra downgraded <code>rich</code>
and <code>importlib-metadata</code> for every install, since
<code>uv</code> locks one version for all extras; the SDK is installed
beside sysone when wanted</td>
<td><a href="48_aws.ipynb#with-the-sagemaker-python-sdk">aws</a></td>
</tr>
<tr>
<td>On Docker Desktop, the SageMaker SDK’s local mode lost the model a
job wrote: it mounts a folder it has not made, which Docker Desktop then
makes inside its VM; <a
href="https://sgaseretto.github.io/sysonelib/aws.html#model_trainer"><code>model_trainer</code></a>
makes the folders first</td>
<td><a href="48_aws.ipynb#with-the-sagemaker-python-sdk">aws</a></td>
</tr>
<tr>
<td>Compiling for Inferentia2 without the hardware needed the Neuron
runtime library (from AWS’s apt repository, not pip),
<code>islpy==2026.1</code> (the compiler’s <code>islpy~=2026.1</code>
lets pip take a version that breaks it) and <code>libarchive</code>;
with them, the tiny model compiles for <code>inf2</code> in a Linux
container</td>
<td><a href="47_xla.ipynb#inferentia2">xla</a></td>
</tr>
<tr>
<td>On PyTorch/XLA, transformers’ default optimizer (the fused AdamW)
has no kernel, and the loss’s skipping of unanswerable rows stopped the
graph at every step; the <code>tpu</code> and <code>neuron</code>
presets use the unfused AdamW, and with every row answerable the loss
runs on whole batches: the tiny model’s second epoch compiled nothing
new</td>
<td><a href="47_xla.ipynb">xla</a></td>
</tr>
<tr>
<td>The Kaggle CLI decodes a kernel’s live log as Latin-1, so every
<code>█</code> of a progress bar arrived as <code>â</code> and two
invisible characters; written back out as Latin-1, the log is UTF-8
again</td>
<td><a href="46_kaggle.ipynb">kaggle</a></td>
</tr>
<tr>
<td>One poll’s <code>colab exec</code> stayed connected for over two
minutes, past its own timeout, on a VM busy training; a poll now gives
up after 240 s, and <code>wait</code> polls again after a failed
poll</td>
<td><a href="45_colab.ipynb">colab</a></td>
</tr>
<tr>
<td>A Colab poll fetched a job’s outputs while the runner was still
packing them, and brought back 773 KB of a 59 MB head; the runner now
renames the tarball into place when it is whole</td>
<td><a href="45_colab.ipynb">colab</a></td>
</tr>
<tr>
<td>A <a
href="https://sgaseretto.github.io/sysonelib/inference.html#decider"><code>Decider</code></a>
pickled as fastai pickles its learner, under transformers 5.17, would
not load under Kaggle’s 5.0, and a sysone learner cannot be pickled at
all; <a
href="https://sgaseretto.github.io/sysonelib/inference.html#load_learner"><code>load_learner</code></a>
rebuilds the learner from the export, which loaded under both</td>
<td><a href="06_inference.ipynb#load_learner">inference</a></td>
</tr>
<tr>
<td>transformers 5.17’s Trainer passes <code>every_n_layers</code> and
<code>offload</code> to gradient checkpointing, which sysone’s model
refused, so every GPU preset stopped as training started on Colab’s
T4</td>
<td><a href="03_models.ipynb">models</a></td>
</tr>
<tr>
<td>On two GPUs, every process printed each progress line and wrote the
export</td>
<td><a href="44_track.ipynb">track</a></td>
</tr>
<tr>
<td>transformers drops the last partial batch of evaluation too: the
<code>tpu</code> preset left up to 31 rows out of every metric, and the
fixture’s calibration split made no batch at all</td>
<td><a href="05_learner.ipynb">learner</a></td>
</tr>
<tr>
<td>pip keeps an installed sysone of the same version, so a job on a
SageMaker image would have run the image’s code; uv replaces it</td>
<td><a href="40_cloud.ipynb">cloud</a></td>
</tr>
<tr>
<td>A row built on read took its question from the case before the
transforms ran, so no transform could add a question, and with <a
href="https://sgaseretto.github.io/sysonelib/template.html#shuffle"><code>Shuffle</code></a>
10 of the fixture’s 100 rows differed from the static build at epoch
0</td>
<td><a href="02_data.ipynb#lazy-rows">data</a></td>
</tr>
<tr>
<td>fast-decisions’ restaurant reviews have aspects marked wrong: one
describes a burger and is marked as not talking about the food</td>
<td><a
href="tutorials/09_reshaping_datasets.ipynb#several-labels-at-once">reshaping
tutorial</a></td>
</tr>
<tr>
<td>Kaggle’s GPU image has torchao 0.10, which peft refuses, so the
first LoRA job stopped as its adapter was made; the runner removes
it</td>
<td><a href="40_cloud.ipynb">cloud</a></td>
</tr>
<tr>
<td>A kernel stopped at Kaggle’s time limit keeps its files but not its
tarball: an export with a 2.4 GB copy of the base model beside its
adapter took a finished run past two hours as it packed</td>
<td><a href="46_kaggle.ipynb">kaggle</a></td>
</tr>
<tr>
<td>A diffusion model fills every mask of a slot, so a value written
into a JSON string ran on into more JSON and <code>fill</code> matched
none of 120 typed texts; a quoted slot now ends at its closing
quote</td>
<td><a
href="24_mdlm.ipynb#browser-steps-on-the-real-checkpoint">mdlm</a></td>
</tr>
<tr>
<td>Trained on Mind2Web’s steps as they come, the browser adapter’s
operation answer was right exactly as often as always clicking, and it
never chose TYPE_TEXT: the rare operations need oversampling</td>
<td><a
href="24_mdlm.ipynb#browser-steps-on-the-real-checkpoint">mdlm</a></td>
</tr>
<tr>
<td>A Mind2Web step offers the operations its candidates allow, its own
always among them, so “the rarest action offered” is right on 80% of the
steps, and an adapter trained with the operations balanced learned
exactly that; <code>operations="all"</code> offers every action</td>
<td><a href="21_screens.ipynb#one-step-one-record">screens</a></td>
</tr>
</tbody>
</table>

## Developer guide

sysone is written as [nbdev](https://nbdev.fast.ai/) notebooks: `nbs/`
is the source, `sysone/` is generated by `nbdev-export` and never edited
by hand, and the notebooks’ examples are the test suite, run against
tiny fixtures (`nbs/fixtures/`) so the whole suite runs offline on a
CPU.

``` sh
uv sync                               # the environment, with the package installed editable
uv run nbdev-export                   # notebooks -> sysone/
uv run nbdev-test --n-workers 4       # every notebook, top to bottom
uv run nbdev-clean                    # before committing
```

Cells marked `#| eval: false` need a GPU, a download or a network; the
results of their last real run are pasted below them. Cells that need an
account, Docker or other hardware carry a flag, and `nbdev-test` skips
them unless it is given that flag: `hub`, `kaggle` and `colab` (a
login), `mlflow` (a local MLflow server), `floci` (Docker, with floci
and sysone’s image), `xla` (Docker, a Linux container with torch_xla),
`neuron` (the Neuron SDK), `sagemaker` (the SageMaker Python SDK). For
example, `uv run nbdev-test --flags floci nbs/48_aws.ipynb`.

The tensor diagrams are SVG files in `nbs/images/`, drawn by
`nbs/90_figures.ipynb` from the library’s own functions with
[tensordiagram](https://github.com/hardik-vala/tensordiagram); running
that notebook (the test suite does) redraws them, byte for byte when
nothing changed. The flow charts are [Mermaid](https://mermaid.js.org/)
text in the markdown cells, which Quarto renders. The docs site builds
with Quarto, which comes as a Python wheel in the `docs` group:

``` sh
uv sync --group docs
uv run nbdev-docs                     # the site in _docs/; nbdev-preview serves it while you edit
```

nbdev’s docs build re-runs every cell that imports something, in a fresh
kernel that skips the others, so keep imports in cells of their own: a
cell that imports and also uses a name from an earlier cell breaks the
build. It ignores the test flags, so a flagged cell must import nothing:
a `kaggle` cell with an import would start a Kaggle job during the
build.
