"""`sysone run train.py --on kaggle|colab`: a thin adapter over the Kaggle and Colab CLIs that packages a training script, submits it, polls it, and gets the export back.

Docs: https://sgaseretto.github.io/sysonelib/cloud.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/40_cloud.ipynb.

# %% auto #0
__all__ = ['WRAPPER', 'KAGGLE_ACCELERATORS', 'COLAB_GPUS', 'wrap_script', 'jobs_file', 'jobs_dir', 'Job', 'load_jobs', 'save_job',
           'CloudError', 'kaggle_kernel', 'kaggle_run', 'parse_kaggle_status', 'kaggle_status', 'kaggle_output',
           'colab_run', 'colab_download', 'colab_stop', 'run', 'status', 'fetch', 'publish_kaggle']

# %% ../nbs/40_cloud.ipynb #75dcb0ab
import glob, json, os, re, shlex, shutil, subprocess, tempfile, textwrap, time, uuid
from dataclasses import dataclass, field, asdict
from pathlib import Path

# %% ../nbs/40_cloud.ipynb #06771d34
WRAPPER = '''\
# generated by sysone.cloud: installs sysone, runs the training script, pushes the export to the Hub
import glob, os, subprocess, sys, tarfile
os.chdir({workdir!r})
subprocess.run([sys.executable, "-m", "pip", "install", "-q", {install!r}], check=True)
os.environ.update({env!r})
os.environ.setdefault("SYSONE_OUTPUT", {output!r})
open("sysone_train.py", "w").write({script!r})
cmd = ([sys.executable, "-m", "torch.distributed.run", "--standalone", "--nproc_per_node", str({gpus})] if {gpus} > 1 else [sys.executable])
subprocess.run(cmd + ["sysone_train.py"] + {args!r}, check=True)
out = os.environ["SYSONE_OUTPUT"]
if not os.path.isdir(out):   # the export the script wrote, wherever it wrote it: the newest folder with sysone.json
    found = [os.path.dirname(p) for p in glob.glob("**/sysone.json", recursive=True) + glob.glob("**/sysone_gliner.json", recursive=True)]
    out = max(found, key=os.path.getmtime) if found else out
if not os.path.isdir(out) and {push!r}: sys.exit("sysone: the script wrote no export (no folder with sysone.json), so nothing was pushed")
if os.path.isdir(out):
    with tarfile.open("sysone_export.tar.gz", "w:gz") as t: t.add(out, arcname=os.path.basename(out))
    if {push!r}:
        token = os.environ.get("HF_TOKEN")
        if token is None:
            try:
                from kaggle_secrets import UserSecretsClient
                token = UserSecretsClient().get_secret("HF_TOKEN")
            except Exception: pass
        from huggingface_hub import HfApi
        api = HfApi(token=token)
        api.create_repo({push!r}, exist_ok=True, private=True)
        api.upload_folder(folder_path=out, repo_id={push!r}, commit_message="sysone export")
        print("pushed", out, "to", {push!r})
'''

def wrap_script(script:str|Path, workdir:str, preset:str, gpus:int=1, push:str|None=None, install:str="sysone",
                output:str|None=None, env:dict|None=None, args:list|None=None) -> str:
    "The single file a cloud machine runs: install sysone, run `script` with `SYSONE_PRESET`, tar and push the export"
    if isinstance(script, Path) or "\n" not in str(script):      # a path, not inline code: it must exist
        if not Path(str(script)).exists(): raise FileNotFoundError(f"no such training script: {script}")
        body = Path(script).read_text()
    else: body = str(script)
    env = {"SYSONE_PRESET": preset} | (env or {})
    return WRAPPER.format(workdir=workdir, install=install, env=env, output=output or os.path.join(workdir, "export"),
                          script=body, gpus=int(gpus), args=list(args or []), push=push)

# %% ../nbs/40_cloud.ipynb #7e6047a0
KAGGLE_ACCELERATORS = {"NvidiaTeslaT4": ("t4x2", 2), "NvidiaL4": ("l4", 1), "NvidiaL4X1": ("l4", 1), "NvidiaTeslaA100": ("a100", 1),
                       "NvidiaH100": ("a100", 1), "NvidiaRtxPro6000": ("a100", 1)}
COLAB_GPUS = {"T4": ("t4", 1), "L4": ("l4", 1), "G4": ("l4", 1), "A100": ("a100", 1), "H100": ("a100", 1)}

# %% ../nbs/40_cloud.ipynb #2abd4427
def jobs_file() -> Path: return Path(os.environ.get("SYSONE_JOBS", Path.home() / ".config" / "sysone" / "jobs.json"))
def jobs_dir() -> Path: return Path(os.environ.get("SYSONE_JOBS_DIR", Path.home() / ".cache" / "sysone" / "jobs"))

@dataclass
class Job:
    "A training run submitted to Kaggle or Colab"
    backend:str; ref:str; script:str; machine:str; push:str|None = None; submitted:float = field(default_factory=time.time)
    folder:str|None = None; status:str = "submitted"

def load_jobs() -> list:
    f = jobs_file()
    return [Job(**j) for j in json.loads(f.read_text())] if f.exists() else []

def save_job(job:Job) -> Job:
    jobs = [j for j in load_jobs() if (j.backend, j.ref) != (job.backend, job.ref)] + [job]
    jobs_file().parent.mkdir(parents=True, exist_ok=True)
    jobs_file().write_text(json.dumps([asdict(j) for j in jobs], indent=2))
    return job

# %% ../nbs/40_cloud.ipynb #76081c4c
class CloudError(RuntimeError): "A cloud CLI reported a failure"

def _cli(cmd:list, dry_run:bool=False, check:bool=True):
    if dry_run: return {"cmd": cmd, "stdout": "", "returncode": 0}
    if shutil.which(cmd[0]) is None:
        raise CloudError(f"`{cmd[0]}` is not installed; pip install 'sysone[cloud]' (and authenticate: `kaggle auth login` or `colab --auth oauth2`)")
    r = subprocess.run(cmd, capture_output=True, text=True)
    out = {"cmd": cmd, "stdout": r.stdout, "stderr": r.stderr, "returncode": r.returncode}
    if check and (r.returncode != 0 or re.search(r"(push|creation) error", r.stdout, re.I)):
        raise CloudError(f"{shlex.join(cmd)} failed ({r.returncode}): {(r.stdout + r.stderr).strip()[-2000:]}")
    return out

# %% ../nbs/40_cloud.ipynb #719b1c75
def kaggle_kernel(script, slug:str, folder=None, accelerator:str="NvidiaTeslaT4", push:str|None=None, install:str="sysone",
                  datasets:list|None=None, models:list|None=None, private:bool=True, env:dict|None=None, args:list|None=None) -> Path:
    "A folder for `kaggle kernels push`: the wrapped script and its kernel-metadata.json"
    if "/" not in slug: raise ValueError("the kernel slug is 'owner/name'")
    preset, gpus = KAGGLE_ACCELERATORS.get(accelerator, ("t4", 1))
    folder = Path(folder or jobs_dir() / "kaggle" / slug.split("/")[1]); folder.mkdir(parents=True, exist_ok=True)
    (folder / "sysone_job.py").write_text(wrap_script(script, "/kaggle/working", preset, gpus, push, install, env=env, args=args))
    name = slug.split("/")[1]
    meta = {"id": slug, "title": name.replace("-", " ").title() if len(name) >= 5 else f"sysone {name}", "code_file": "sysone_job.py",
            "language": "python", "kernel_type": "script", "is_private": private, "enable_gpu": True, "enable_internet": True,
            "machine_shape": accelerator, "dataset_sources": list(datasets or []), "competition_sources": [],
            "kernel_sources": [], "model_sources": list(models or [])}
    (folder / "kernel-metadata.json").write_text(json.dumps(meta, indent=2))
    return folder

def kaggle_run(folder, accelerator:str="NvidiaTeslaT4", timeout:int=12 * 3600, dry_run:bool=False) -> Job:
    "Push a kernel folder and record the job"
    folder = Path(folder); meta = json.loads((folder / "kernel-metadata.json").read_text())
    _cli(["kaggle", "kernels", "push", "-p", str(folder), "--accelerator", accelerator, "-t", str(int(timeout))], dry_run)
    job = Job("kaggle", meta["id"], str(folder / "sysone_job.py"), accelerator, folder=str(folder))
    return job if dry_run else save_job(job)

def parse_kaggle_status(text:str) -> str:
    "The status word of `kaggle kernels status` output: queued, running, complete, error, cancelacknowledged"
    m = re.search(r'has status "([^"]+)"', text)
    if not m: raise CloudError(f"unrecognised status output: {text[:200]!r}")
    return m.group(1).split(".")[-1].replace("_", "").lower()

def kaggle_status(ref:str, dry_run:bool=False) -> str:
    "The kernel's status"
    out = _cli(["kaggle", "kernels", "status", ref], dry_run)
    return "dry-run" if dry_run else parse_kaggle_status(out["stdout"])

def kaggle_output(ref:str, dest, dry_run:bool=False) -> Path:
    "Download the kernel's outputs (the export tarball among them) to `dest`"
    dest = Path(dest); dest.mkdir(parents=True, exist_ok=True)
    _cli(["kaggle", "kernels", "output", ref, "-p", str(dest)], dry_run)
    return dest

# %% ../nbs/40_cloud.ipynb #b503b074
def colab_run(script, gpu:str="L4", session:str|None=None, push:str|None=None, keep:bool=True, install:str="sysone",
              timeout:int=24 * 3600, env:dict|None=None, args:list|None=None, dry_run:bool=False, folder=None) -> Job:
    "Run a training script on a Colab GPU VM (kept for downloading the export unless keep=False)"
    preset, gpus = COLAB_GPUS.get(gpu.upper(), ("t4", 1))
    session = session or f"sysone-{uuid.uuid4().hex[:6]}"
    folder = Path(folder or jobs_dir() / "colab" / session); folder.mkdir(parents=True, exist_ok=True)
    wrapped = folder / "sysone_job.py"
    wrapped.write_text(wrap_script(script, "/content", preset, gpus, push, install, env=env, args=args))
    cmd = ["colab", "run", "--gpu", gpu.upper(), "-s", session, "--timeout", str(int(timeout))] + (["--keep"] if keep else []) + [str(wrapped)]
    job = Job("colab", session, str(wrapped), gpu.upper(), push=push, folder=str(folder))
    if not dry_run: save_job(job)
    _cli(cmd, dry_run)
    if not dry_run: job.status = "complete"; save_job(job)
    return job

def colab_download(session:str, dest, dry_run:bool=False) -> Path:
    "Download a kept session's export tarball"
    dest = Path(dest); dest.mkdir(parents=True, exist_ok=True)
    _cli(["colab", "download", "-s", session, "/content/sysone_export.tar.gz", str(dest / "sysone_export.tar.gz")], dry_run)
    return dest

def colab_stop(session:str, dry_run:bool=False): return _cli(["colab", "stop", "-s", session], dry_run)

# %% ../nbs/40_cloud.ipynb #496ea1f0
def run(script, on:str="kaggle", accelerator:str|None=None, gpu:str|None=None, slug:str|None=None, push:str|None=None,
        data:str|None=None, keep:bool=True, install:str="sysone", dry_run:bool=False, **kw) -> Job:
    "Submit a training script to Kaggle or Colab"
    env = {"SYSONE_DATA": data} if data else {}
    if on == "kaggle":
        if slug is None:
            user = os.environ.get("KAGGLE_USERNAME")
            if not user: raise ValueError("name the kernel with slug='owner/name' (or set KAGGLE_USERNAME)")
            slug = f"{user}/sysone-{Path(str(script)).stem.replace('_', '-')}"
        acc = accelerator or "NvidiaTeslaT4"
        datasets = [data[len("kaggle:"):]] if data and data.startswith("kaggle:") else None
        folder = kaggle_kernel(script, slug, kw.pop("folder", None), acc, push, install, datasets=datasets, env=env, **kw)
        return kaggle_run(folder, acc, dry_run=dry_run)
    if on == "colab": return colab_run(script, gpu or "L4", push=push, keep=keep, install=install, env=env, dry_run=dry_run, **kw)
    raise ValueError(f"unknown backend {on!r}; use 'kaggle' or 'colab'")

def status(refresh:bool=True) -> list:
    "The recorded jobs, with Kaggle statuses refreshed"
    jobs = load_jobs()
    for j in jobs:
        if refresh and j.backend == "kaggle" and j.status not in ("complete", "error", "cancelacknowledged"):
            try: j.status = kaggle_status(j.ref); save_job(j)
            except CloudError as e: j.status = f"unknown ({str(e)[:60]})"
    return jobs

def fetch(job:Job, dest) -> Path:
    "Download a finished job's export tarball and unpack it"
    import tarfile
    dest = Path(dest)
    (kaggle_output(job.ref, dest) if job.backend == "kaggle" else colab_download(job.ref, dest))
    tb = dest / "sysone_export.tar.gz"
    if tb.exists():
        with tarfile.open(tb) as t: t.extractall(dest, filter="data")
    return dest

# %% ../nbs/40_cloud.ipynb #9c1a3891
def publish_kaggle(path, owner:str, model:str, variation:str="default", license:str="Apache 2.0", framework:str="pyTorch",
                   title:str|None=None, private:bool=True, dry_run:bool=False) -> dict:
    "Create a Kaggle Model and upload an export folder as one of its variations"
    path = Path(path)
    meta_dir = Path(tempfile.mkdtemp(prefix="sysone-kaggle-model-"))
    (meta_dir / "model-metadata.json").write_text(json.dumps({"ownerSlug": owner, "title": title or model, "slug": model,
        "subtitle": "", "isPrivate": private, "description": f"# {title or model}\n\nA typed-decision model exported by sysone.\n",
        "publishTime": "", "provenanceSources": ""}, indent=2))
    (path / "model-instance-metadata.json").write_text(json.dumps({"ownerSlug": owner, "modelSlug": model, "instanceSlug": variation,
        "framework": framework, "overview": "sysone export: sysone.json, head.safetensors, tokenizer/, encoder/",
        "usage": "from sysone.inference import Decider\nDecider.load(path).predict(state, questions)", "licenseName": license,
        "fineTunable": True, "trainingData": [], "modelInstanceType": "Unspecified", "baseModelInstance": "", "externalBaseModelUrl": ""}, indent=2))
    a = _cli(["kaggle", "models", "create", "-p", str(meta_dir)], dry_run)
    b = _cli(["kaggle", "models", "variations", "create", "-p", str(path), "-r", "zip"], dry_run)
    return {"model": a["cmd"], "variation": b["cmd"]}
