"""Jobs on Colab VMs through Google's `colab` CLI: a CPU, a T4, L4, G4, A100 or H100 GPU, or a v5e-1 or v6e-1 TPU; the job runs detached on the VM, short calls follow its log, and the VM is released as soon as the job ends.

Docs: https://sgaseretto.github.io/sysonelib/colab.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/45_colab.ipynb.

# %% auto #0
__all__ = ['COLAB_ROOT', 'COLAB_INBOX', 'COLAB_GPUS', 'COLAB_TPUS', 'COLAB_SHIP_MB', 'ColabError', 'colab_cmd', 'run_colab',
           'machine_colab_cpu', 'machine_colab_gpu', 'machine_colab_tpu', 'stage_colab_local', 'job_secrets',
           'start_code', 'poll_code', 'submit_colab', 'poll_colab', 'cancel_colab', 'collect_colab', 'colab_usage']

# %% ../nbs/45_colab.ipynb #8c8a97b6
import json, os, re, shlex, shutil, subprocess, sys, tempfile, time
from pathlib import Path

from .auth import refresh_colab_token
from .cloud import (Colab, CPU, GPU, TPU, Job, LocalPath, HubData, machine, stage, submit, poll, cancel, collect,
                          pack, unpack_outputs, save_job, load_jobs)

# %% ../nbs/45_colab.ipynb #49011d0c
class ColabError(RuntimeError): "The Colab CLI reported a failure"

COLAB_ROOT = "/content/sysone_jobs"
COLAB_INBOX = "/content"          # where uploads land: Colab's file API writes into folders that exist, and makes none
COLAB_GPUS = ("T4", "L4", "G4", "A100", "H100")
COLAB_TPUS = {"v5e-1": "v5e1", "v6e-1": "v6e1"}

def colab_cmd(b:Colab, job:Job|None, *args) -> list:
    "A `colab` command line with the backend's sign-in and, for a job, its own session-state file"
    cfg = ["--config", str(Path(job.folder) / "colab-sessions.json")] if job is not None and job.folder else []
    return ["colab", f"--auth={b.auth}"] + cfg + [str(a) for a in args]

def run_colab(cmd:list, input:str|None=None, timeout:float=600, check:bool=True) -> str:
    "Run a `colab` command and return its standard output (renewing sysone's Colab-only token first, see auth)"
    if shutil.which(cmd[0]) is None: raise ColabError("the Colab CLI is not installed: uv tool install google-colab-cli")
    try: refresh_colab_token()
    except Exception as e: print(f"sysone: could not renew the Colab token ({e}); the CLI will try", file=sys.stderr)
    try: r = subprocess.run(cmd, input=input, capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired: raise ColabError(f"{' '.join(cmd[:4])} took over {timeout:.0f} s") from None
    if check and r.returncode != 0:
        raise ColabError(f"{' '.join(c for c in cmd if not c.startswith('--config'))} failed ({r.returncode}): {(r.stdout + r.stderr).strip()[-1500:]}")
    return r.stdout

# %% ../nbs/45_colab.ipynb #c6f08065
COLAB_SHIP_MB = 100

@machine.register
def machine_colab_cpu(b:Colab, hw:CPU) -> str: return "--high-mem" if hw.high_mem else "cpu"

@machine.register
def machine_colab_gpu(b:Colab, hw:GPU) -> str:
    if hw.name not in COLAB_GPUS or hw.count != 1: raise ValueError(f"a Colab VM has one GPU of {', '.join(COLAB_GPUS)}, not {hw}")
    return f"--gpu {hw.name}" + (" --high-mem" if hw.high_mem else "")

@machine.register
def machine_colab_tpu(b:Colab, hw:TPU) -> str:
    if hw.kind not in COLAB_TPUS: raise ValueError(f"Colab's TPUs are {', '.join(COLAB_TPUS)}, not {hw.kind}")
    return f"--tpu {COLAB_TPUS[hw.kind]}"

def _size(p:Path) -> int: return p.stat().st_size if p.is_file() else sum(f.stat().st_size for f in p.rglob("*") if f.is_file())

@stage.register
def stage_colab_local(d:LocalPath, b:Colab, var:str) -> dict:
    mb = _size(Path(d.path)) / 2**20
    if mb > COLAB_SHIP_MB: raise ValueError(f"{d.path} is {mb:.0f} MB: push it to the Hub (sysone.hub.push_data) and pass hf:owner/name")
    return {"ship": {var: d.path}}

# %% ../nbs/45_colab.ipynb #a5a523b1
def job_secrets(b:Colab) -> dict:
    "The values of the backend's secrets on this machine (the Hub login for HF_TOKEN), for the names that have one"
    out = {}
    for name in b.secrets:
        v = os.environ.get(name)
        if v is None and name == "HF_TOKEN":
            from huggingface_hub import get_token
            v = get_token()
        if v: out[name] = v
    return out

# %% ../nbs/45_colab.ipynb #17119cf7
def _flags(machine:str) -> list: return [] if machine == "cpu" else shlex.split(machine)

def start_code(job:Job) -> str:
    "What the one `colab exec` that starts a job runs: unpack the job's folder and start its runner in the background"
    d, tar = f"{COLAB_ROOT}/{job.id}", f"{COLAB_INBOX}/{job.id}.tar.gz"
    return f"""import os, shutil, subprocess, sys, tarfile
os.makedirs({d!r}, exist_ok=True)
with tarfile.open({tar!r}) as t: t.extractall({d!r}, filter="data")
os.remove({tar!r})
if os.path.exists({tar + '.secrets'!r}): shutil.move({tar + '.secrets'!r}, os.path.join({d!r}, ".secrets.json"))
log = open(os.path.join({d!r}, "job.log"), "ab")
p = subprocess.Popen([sys.executable, os.path.join({d!r}, "sysone_job.py")], stdout=log, stderr=subprocess.STDOUT, cwd={d!r}, start_new_session=True)
print("SYSONE-PID", p.pid)
"""

def poll_code(job:Job, max_bytes:int=500_000) -> str:
    "What a poll's `colab exec` runs: the log from the job's offset, the runner's status when it has ended, and the GPU's use"
    d = f"{COLAB_ROOT}/{job.id}"
    return f"""import json, os, subprocess
log, st, txt = os.path.join({d!r}, "job.log"), os.path.join({d!r}, "outputs", "status.json"), b""
if os.path.exists(log):
    with open(log, "rb") as f: f.seek({job.offset}); txt = f.read({max_bytes})
gpu = None
try: gpu = subprocess.run(["nvidia-smi", "--query-gpu=utilization.gpu,memory.used,memory.total", "--format=csv,noheader,nounits"], capture_output=True, text=True, timeout=10).stdout.strip()
except Exception: pass
done = os.path.exists(st) and os.path.exists(os.path.join({d!r}, "outputs.tar.gz"))
print("SYSONE-POLL " + json.dumps({{"text": txt.decode("utf-8", "replace"), "n": len(txt), "status": json.load(open(st)) if done else None, "gpu": gpu}}))
"""

@submit.register
def submit_colab(b:Colab, job:Job) -> Job:
    folder = Path(job.folder)
    tar = folder.parent / f"{job.id}.tar.gz"; tar.write_bytes(pack(folder, skip=()))
    run_colab(colab_cmd(b, job, "new", "-s", job.id, *_flags(job.machine)), timeout=900)
    job.ref, job.status = job.id, "starting"; save_job(job)
    try:
        run_colab(colab_cmd(b, job, "upload", "-s", job.id, tar, f"{COLAB_INBOX}/{job.id}.tar.gz"))
        sec = job_secrets(b)
        if sec:
            fd, sp = tempfile.mkstemp(suffix=".json")
            try:
                with os.fdopen(fd, "w") as f: json.dump(sec, f)
                run_colab(colab_cmd(b, job, "upload", "-s", job.id, sp, f"{COLAB_INBOX}/{job.id}.tar.gz.secrets"))
            finally: os.remove(sp)
        out = run_colab(colab_cmd(b, job, "exec", "-s", job.id, "--timeout", "300"), input=start_code(job))
        if "SYSONE-PID" not in out: raise ColabError(f"the job did not start: {out[-500:]}")
    except Exception:
        run_colab(colab_cmd(b, job, "stop", "-s", job.id), check=False)     # a VM that runs nothing is released at once
        job.status = "error"; save_job(job)
        raise
    finally: tar.unlink(missing_ok=True)
    job.status = "running"
    return job

@poll.register
def poll_colab(b:Colab, job:Job) -> str:
    out = run_colab(colab_cmd(b, job, "exec", "-s", job.id, "--timeout", "120"), input=poll_code(job), timeout=240, check=False)   # see the finding below
    line = next((l for l in out.splitlines() if l.startswith("SYSONE-POLL ")), None)
    if line is None:
        if re.search(r"not found|404|401|lost", out, re.I): job.status = "error"
        return ""
    r = json.loads(line[len("SYSONE-POLL "):])
    job.offset += r["n"]
    text = r["text"]
    if r.get("gpu"):                     # the VM's GPU, as nvidia-smi sees it: a progress line of its own
        try:
            util, used, total = (float(x) for x in r["gpu"].splitlines()[0].split(","))
            text += "SYSONE " + json.dumps({"t": round(time.time(), 1), "event": "vm", "gpu_util": util,
                                            "gpu_mem_gb": round(used / 1024, 2), "gpu_total_gb": round(total / 1024, 2)}) + "\n"
        except ValueError: pass
    with open(Path(job.folder) / "job.log", "a") as f: f.write(text)
    if r["status"] is not None:          # ended: bring the outputs back, then release the VM
        run_colab(colab_cmd(b, job, "download", "-s", job.id, f"{COLAB_ROOT}/{job.id}/outputs.tar.gz", Path(job.folder) / "outputs.tar.gz"))
        if not b.keep: run_colab(colab_cmd(b, job, "stop", "-s", job.id), check=False)
        job.status, job.url = r["status"]["status"], r["status"].get("url") or job.url
    return text

@cancel.register
def cancel_colab(b:Colab, job:Job) -> Job:
    run_colab(colab_cmd(b, job, "stop", "-s", job.id), check=False)
    job.status = "stopped"
    return job

@collect.register
def collect_colab(b:Colab, job:Job, dest:Path) -> Path:
    tb = Path(job.folder) / "outputs.tar.gz"
    if not tb.exists():
        if job.status in ("stopped", "error") and not tb.exists(): raise ColabError(f"{job.id} ended {job.status}: there are no outputs to bring back")
        raise ColabError(f"{job.id} is {job.status}: wait for it to end (job.wait())")
    return unpack_outputs(tb, dest)

def colab_usage() -> str:
    "Your Colab compute units: balance and rate (`colab usage`)"
    return run_colab(["colab", "--auth=oauth2", "usage"])
