"""Typed questions, gold targets, the Jev answer schema, rows and batches: the small core every other layer builds on.

Docs: https://sgaseretto.github.io/sysonelib/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['dispatch', 'QTYPES', 'QTYPE_NAMES', 'NOUL_KEYS', 'KINDS', 'TEMP_MIN', 'TEMP_MAX', 'ROW_META', 'EXTRA_COLLATE',
           'ADAPTERS', 'methods', 'Question', 'Choice', 'Score', 'Noul', 'render_criterion', 'as_questions',
           'entropy_confidence', 'answer_confidence', 'Answer', 'answer_fields', 'fill_answer', 'answer_probs',
           'answer_index', 'temp_bucket', 'clamp_temperature', 'lookup_temperature', 'lookup_threshold', 'render_state',
           'load_record', 'Row', 'Batch', 'collate', 'load_adapter']

# %% ../nbs/00_core.ipynb #ae8b9cf4
import importlib, json, math, sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import torch
from fastcore.basics import patch
from plum import Dispatcher

# %% ../nbs/00_core.ipynb #37696ca3
dispatch = Dispatcher()      # sysone's generic functions: `@dispatch` defines one, `f.register(fn)` adds a method from anywhere

def methods(f) -> list:
    "The signatures a generic function has methods for, as tuples of class names, in the order they were added"
    name = lambda t: t.__name__ if isinstance(t, type) else str(t)
    return [tuple(name(t) for t in m.signature.types) for m in f.methods]

# %% ../nbs/00_core.ipynb #3981d44c
QTYPES = {"choice": 0, "score": 1, "noul": 2}
QTYPE_NAMES = {v: k for k, v in QTYPES.items()}
NOUL_KEYS = ("false", "true")

# %% ../nbs/00_core.ipynb #c1f539f0
def _check_label(qname, i, label):
    if isinstance(label, (list, dict, set, bytearray)):
        raise ValueError(f"question {qname!r}: choice label {i} is a {type(label).__name__}; a label is rendered "
                         f"as option text and used as the answer key, so it must be a scalar, got {label!r}")

def _check_question(qname, type, instructions, criteria, labels):
    "Reject a question that cannot be answered, naming it and what to fix (Laya's rules)"
    if type not in QTYPES: raise ValueError(f"question {qname!r}: unknown type {type!r}; use one of {sorted(QTYPES)}")
    if instructions is None: raise ValueError(f"question {qname!r}: no 'instructions'; add the text the model should answer")
    if type == "choice":
        if not isinstance(criteria, (dict, list)) or not criteria:
            raise ValueError(f"question {qname!r}: a choice question takes 'criteria' as a non-empty dict of "
                             "label -> description, or a list of labels")
        for i, label in enumerate(criteria if isinstance(criteria, list) else criteria.keys()): _check_label(qname, i, label)
    elif type == "score":
        if not isinstance(criteria, list) or not criteria:
            raise ValueError(f"question {qname!r}: a score question takes 'criteria' as a non-empty list of level "
                             "descriptions, index 0 first")
        if None in criteria: raise ValueError(f"question {qname!r}: score level {criteria.index(None)} is null")
    elif criteria is not None:
        if not isinstance(criteria, dict) or not {str(k).lower() for k in criteria} <= set(NOUL_KEYS):
            raise ValueError(f"question {qname!r}: a noul question takes 'criteria' keyed only 'true'/'false' "
                             "(either or both), or omits it")
    if labels is not None:
        if type != "noul": raise ValueError(f"question {qname!r}: 'labels' is only supported for noul questions")
        if (not isinstance(labels, dict) or set(labels) != set(NOUL_KEYS)
            or not all(isinstance(v, str) and v.strip() for v in labels.values())
            or labels["false"].strip() == labels["true"].strip()):
            raise ValueError(f"question {qname!r}: noul labels must map exactly 'false' and 'true' to distinct non-empty strings")

# %% ../nbs/00_core.ipynb #feec5cb6
class Question:
    "One typed question over a state: a `choice` among labels, an ordered `score` rubric, or a yes/no `noul`"
    def __init__(self,
                 type:str, # "choice", "score" or "noul"
                 instructions:str, # the text the model answers
                 criteria=None, # choice: {label: description} or [labels]; score: [level descriptions]; noul: {"false": .., "true": ..} or None
                 labels:dict|None=None, # noul only: the words shown for false and true, e.g. {"false": "no", "true": "yes"}
                 name:str|None=None): # the question's id within its case
        _check_question(name, type, instructions, criteria, labels)
        if not isinstance(instructions, str): instructions = json.dumps(instructions, ensure_ascii=False)
        self.type, self.instructions, self.criteria, self.labels, self.name = type, instructions, self._criteria(criteria), labels, name

    def __new__(cls, type:str|None=None, *args, **kwargs):
        "A question is made as its kind: `Question('noul', ...)` is a `Noul`"
        if cls is Question and type in KINDS: cls = KINDS[type]
        return super().__new__(cls)

    def _criteria(self, criteria): return criteria

    @classmethod
    def from_dict(cls, d:dict, name=None):
        "A `Question` from its Jev/typed-decisions definition"
        if isinstance(d, Question): return d
        if not isinstance(d, dict): raise ValueError(f"question {name!r}: definition must be a dict, got {type(d).__name__}")
        return cls(d.get("type"), d.get("instructions"), d.get("criteria"), d.get("labels"), name=name)

    def __repr__(self):
        ins = self.instructions if len(self.instructions) < 40 else self.instructions[:39] + "…"
        return f"Question({self.name or '?'}: {self.type}, {ins!r}, {self.k} options)"

class Choice(Question):
    "A choice among labels, answered by one of them: criteria as `{label: description}`, or a list of labels"
    def _criteria(self, criteria): return {c: None for c in criteria} if isinstance(criteria, list) else criteria

class Score(Question):
    "An ordered rubric of levels, level 0 first, answered by the expected level"

class Noul(Question):
    "A statement judged true or false, answered by p(true)"
    def _criteria(self, criteria): return None if criteria is None else {str(k).lower(): v for k, v in criteria.items()}

KINDS = {"choice": Choice, "score": Score, "noul": Noul}    # a type's name: its class

# %% ../nbs/00_core.ipynb #878224f7
def render_criterion(value) -> str:
    "A criterion value as text: strings pass through, anything structured becomes compact JSON"
    if isinstance(value, str): return value
    return json.dumps(value, ensure_ascii=False, separators=(", ", ": "), default=str)

_NOUL_DEFAULTS = {"false": "no, the statement does not hold", "true": "yes, the statement holds"}

@patch(as_prop=True)
def qtype(self:Question) -> int: "The type's integer id"; return QTYPES[self.type]

@patch(as_prop=True)
def keys(self:Choice) -> list: "A choice's answer keys: its labels"; return list(self.criteria)
@patch(as_prop=True)
def keys(self:Score) -> list: "A score's answer keys: its levels' indices, as strings"; return [str(i) for i in range(len(self.criteria))]
@patch(as_prop=True)
def keys(self:Noul) -> list: "A noul's answer keys: false, then true"; return list(NOUL_KEYS)

@patch(as_prop=True)
def k(self:Question) -> int: "Number of options"; return len(self.keys)

@patch(as_prop=True)
def options(self:Choice) -> list:
    "A choice's option texts, as Laya renders them: `label: description`, or the label alone"
    return [str(k) if v is None or v == "" else f"{k}: {render_criterion(v)}" for k, v in self.criteria.items()]

@patch(as_prop=True)
def options(self:Score) -> list:
    "A score's option texts: `level i: description`"
    return [f"level {i}: {render_criterion(c)}" for i, c in enumerate(self.criteria)]

@patch(as_prop=True)
def options(self:Noul) -> list:
    "A noul's option texts, false then true, with Laya's default descriptions when none is given"
    crit, labels = self.criteria or {}, self.labels or {"false": "false", "true": "true"}
    return [f"{labels[key].strip()}: " + (render_criterion(crit[key]) if crit.get(key) not in (None, "") else _NOUL_DEFAULTS[key])
            for key in NOUL_KEYS]

# %% ../nbs/00_core.ipynb #53fced97
@patch
def to_dict(self:Question) -> dict:
    "The Jev definition of this question"
    d = {"type": self.type, "instructions": self.instructions}
    if self.criteria is not None: d["criteria"] = list(self.criteria) if isinstance(self.criteria, list) else self.criteria
    if self.labels is not None: d["labels"] = self.labels
    return d

def as_questions(questions) -> dict:
    "`{qid: Question}` from a mapping of definitions (or `Question`s)"
    if isinstance(questions, str): questions = json.loads(questions)
    return {qid: Question.from_dict(q, name=qid) for qid, q in questions.items()}

# %% ../nbs/00_core.ipynb #65a6141d
def _two_point(score, n):
    "A distribution over n levels whose expected level is `score`"
    s = min(max(float(score), 0.0), n - 1.0)
    lo = int(math.floor(s)); p = [0.0] * n
    if lo >= n - 1: p[n - 1] = 1.0
    else: p[lo], p[lo + 1] = 1.0 - (s - lo), s - lo
    return p

def _noul_key(v) -> str:
    "A truth value's key: 'true' or 'false' for yes/no, booleans, 1/0"
    s = str(v).strip().lower()
    return {"yes": "true", "no": "false", "1": "true", "0": "false", "1.0": "true", "0.0": "false"}.get(s, s)

def _str_key(k) -> str:
    "A key as text, integral floats without their '.0'"
    return str(int(k)) if isinstance(k, float) and k.is_integer() else str(k)

@patch
def _label_index(self:Question, label) -> int:
    "Index of a gold label among the question's keys, or -1"
    if label is None: return -1
    keys = [_str_key(k) for k in self.keys]
    return keys.index(_str_key(label)) if _str_key(label) in keys else -1

@patch
def _label_index(self:Noul, label) -> int:
    "Index of a truth value among false and true, or -1"
    if label is None: return -1
    s = _noul_key(label)
    return NOUL_KEYS.index(s) if s in NOUL_KEYS else -1

@patch
def _bare_gold(self:Question, v) -> dict: "A bare gold value: a label"; return {"label": v}

@patch
def _bare_gold(self:Score, v) -> dict:
    "A bare gold value: an expected level when fractional, else a label"
    return {"score": v} if isinstance(v, float) and not v.is_integer() else {"label": v}

@patch
def _bare_gold(self:Noul, v) -> dict:
    "A bare gold value: p(true) when fractional, else a label"
    return {"noul": v} if isinstance(v, float) and not v.is_integer() else {"label": v}

@patch
def _probs_target(self:Question, probs:dict):
    "A gold distribution given as `{key: probability}`, in key order"
    pk = {_str_key(k): v for k, v in probs.items()}
    return [float(pk.get(_str_key(k), 0.0)) for k in self.keys]

@patch
def _probs_target(self:Noul, probs:dict):
    "A gold distribution over false and true, either side giving the other"
    pn = {_noul_key(k): v for k, v in probs.items()}
    pt, pf = pn.get("true"), pn.get("false")
    if pt is None and pf is None: return None
    pt = 1.0 - pf if pt is None else pt
    pf = 1.0 - pt if pf is None else pf
    return [float(pf), float(pt)]

@patch
def _field_target(self:Question, gold:dict): "The distribution the kind's own field of the gold gives (a choice has none)"; return None

@patch
def _field_target(self:Score, gold:dict):
    "A score's expected level, as the distribution over two neighbouring levels that has it"
    return _two_point(gold["score"], self.k) if gold.get("score") is not None else None

@patch
def _field_target(self:Noul, gold:dict):
    "A noul's p(true), as the distribution over false and true"
    return [1.0 - float(gold["noul"]), float(gold["noul"])] if gold.get("noul") is not None else None

@patch
def target(self:Question, gold) -> tuple:
    "The gold distribution over options (key order) and the gold label's index; `(None, -1)` without gold"
    if gold is None: return None, -1
    if isinstance(gold, (list, tuple)) and len(gold) == self.k and all(isinstance(v, (int, float)) for v in gold):
        t, label = [float(v) for v in gold], -1
    else:
        if not isinstance(gold, dict): gold = self._bare_gold(gold)      # a label, or an expected score or p(true) when fractional
        label, probs, t = self._label_index(gold.get("label")), gold.get("probabilities"), None
        if isinstance(probs, dict) and probs:
            t = self._probs_target(probs)
            if t is not None and sum(t) <= 0: t = None     # the distribution names none of the options
        if t is None: t = self._field_target(gold)         # a noul's p(true), a score's expected level
        if t is None and label >= 0: t = [float(i == label) for i in range(self.k)]
        if t is None: return None, -1
    s = sum(t)
    t = [v / s for v in t] if s > 0 else [1.0 / len(t)] * len(t)
    return t, (label if label >= 0 else int(np.argmax(t)))

# %% ../nbs/00_core.ipynb #b2ec2c13
@patch
def answerable(self:Question, gold) -> int:
    "1 if the gold answers the question with its options, 0 if it says none of them does (`{'answerable': False}`), -1 without gold"
    if gold is None: return -1
    if isinstance(gold, dict) and gold.get("answerable") is False: return 0
    return 1 if self.target(gold)[0] is not None else -1

# %% ../nbs/00_core.ipynb #61edcaef
def entropy_confidence(p) -> float:
    "1 − H(p)/log k: how concentrated the distribution is"
    p = np.asarray(p, dtype=np.float64); k = len(p)
    if k < 2: return 1.0
    ent = -(p * np.log(np.clip(p, 1e-12, 1.0))).sum()
    return float(np.clip(1.0 - ent / math.log(k), 0.0, 1.0))

def answer_confidence(p) -> float:
    "max(p): the probability of the reported answer"
    p = np.asarray(p, dtype=np.float64)
    return float(np.clip(p.max(), 0.0, 1.0)) if len(p) else 1.0

# %% ../nbs/00_core.ipynb #dadc1eca
class Answer(dict):
    "A typed answer in the Jev schema: a `dict`, with attribute access for convenience"
    def __getattr__(self, k):
        try: return self[k]
        except KeyError: raise AttributeError(k) from None

def _r(x, digits): return round(float(x), digits) if digits is not None else float(x)

@dispatch
def answer_fields(q:Choice, p, digits) -> dict:
    "A choice's answer: the likeliest label, and every label's probability"
    return dict(choice=q.keys[int(p.argmax())], probabilities={k: _r(v, digits) for k, v in zip(q.keys, p)})

@dispatch
def answer_fields(q:Score, p, digits) -> dict:
    "A score's answer: the expected level, the levels' legend, and every level's probability"
    return dict(score=_r((np.arange(q.k) * p).sum(), digits), legend={str(i): c for i, c in enumerate(q.criteria)},
                probabilities={str(i): _r(v, digits) for i, v in enumerate(p)})

@dispatch
def answer_fields(q:Noul, p, digits) -> dict:
    "A noul's answer: p(true), with its distance from a coin toss as its confidence"
    return dict(noul=_r(p[1], digits), confidence=_r(max(p[1], 1 - p[1]), digits))

def fill_answer(q:Question, probs, digits:int|None=4, act:float|None=None, act_threshold:float|dict|None=None) -> Answer:
    "The Jev answer for `q` from its option probabilities (its kind's `answer_fields`); `act`, from an act head, adds `action`"
    p = np.asarray(probs, dtype=np.float64)[:q.k]
    a = Answer(type=q.type, **answer_fields(q, p, digits))
    a.setdefault("confidence", _r(entropy_confidence(p), digits))       # a noul reports its own
    a["answer_confidence"] = _r(answer_confidence(p), digits)
    if act is not None:   # Laya's `action` field: whether to act on the answer or hand the case to a person
        thr = act_threshold if act_threshold is None or isinstance(act_threshold, (int, float)) else lookup_threshold(act_threshold, q.qtype, q.k)
        a["action"] = {"act_probability": _r(act, digits)} | ({"act": bool(act >= thr)} if thr is not None else {})
    return a

# %% ../nbs/00_core.ipynb #249b1870
@dispatch
def answer_probs(q:Question, a:dict):
    "The option probabilities an answer states, in key order, normalised: a choice's or a score's own"
    pr = a["probabilities"]                  # answers in memory keep a label's own type; over JSON every key is a string
    p = np.array([pr.get(k, pr.get(str(k), 1e-6)) for k in q.keys], dtype=np.float64)
    return p / p.sum()

@dispatch
def answer_probs(q:Noul, a:dict):
    "A noul's two sides, false then true, from its p(true)"
    return np.array([1 - a["noul"], a["noul"]])

@dispatch
def answer_index(q:Question, p) -> int: "The option an answer picks: its likeliest"; return int(np.argmax(p))

@dispatch
def answer_index(q:Noul, p) -> int: "A noul's pick: true when p(true) is at least a half"; return int(p[1] >= 0.5)

# %% ../nbs/00_core.ipynb #1702e864
def temp_bucket(qtype, k:int) -> str:
    "The calibration bucket of a question type (name or id) with k options, e.g. `choice:3-5`"
    name = qtype if isinstance(qtype, str) else QTYPE_NAMES[int(qtype)]
    size = "2" if k <= 2 else "3-5" if k <= 5 else "6-10" if k <= 10 else "11+"
    return f"{name}:{size}"

TEMP_MIN, TEMP_MAX = 0.5, 5.0

def clamp_temperature(t, lo=TEMP_MIN, hi=TEMP_MAX) -> float:
    "A usable temperature: `t` confined to [lo, hi], or 1.0 if it is not a finite number"
    try: t = float(t)
    except (TypeError, ValueError): return 1.0
    if not math.isfinite(t): return 1.0
    return min(hi, max(lo, t))

def lookup_temperature(temps:dict|None, qtype, k:int) -> float:
    "The temperature for a row: its bucket, else its type, else 1"
    if not temps: return 1.0
    name = qtype if isinstance(qtype, str) else QTYPE_NAMES[int(qtype)]
    return clamp_temperature(temps.get(temp_bucket(name, k), temps.get(name, 1.0)))

# %% ../nbs/00_core.ipynb #6ba68f1a
def lookup_threshold(thresholds, qtype, k:int) -> float|None:
    "The act threshold for a row: a single number, or from a dict its bucket's, else its type's, else the one over all rows (`all`)"
    if thresholds is None or isinstance(thresholds, (int, float)): return None if thresholds is None else float(thresholds)
    name = qtype if isinstance(qtype, str) else QTYPE_NAMES[int(qtype)]
    t = thresholds.get(temp_bucket(name, k), thresholds.get(name, thresholds.get("all")))
    return None if t is None else float(t)

# %% ../nbs/00_core.ipynb #f0713b9e
@dispatch
def render_state(state:object) -> str:
    "The text of a state: JSON for structured states"
    return json.dumps(state, ensure_ascii=False)

@dispatch
def render_state(state:str) -> str:
    "A string state is its own text"
    return state

# %% ../nbs/00_core.ipynb #72a9198a
def _parse_state(v):
    "A stored state: JSON when it parses, the text itself otherwise"
    if isinstance(v, str):
        try: return json.loads(v)
        except json.JSONDecodeError: return v
    return v

def load_record(r:dict, parse_state:bool=True) -> dict:
    "A case record with `questions` and `gold` parsed from JSON strings, and the `state` too when `parse_state`"
    r = dict(r)
    if "state" not in r or "questions" not in r: raise ValueError("a record needs 'state' and 'questions'")
    if parse_state: r["state"] = _parse_state(r["state"])
    r["questions"] = json.loads(r["questions"]) if isinstance(r["questions"], str) else r["questions"]
    if isinstance(r.get("gold"), str): r["gold"] = json.loads(r["gold"])
    as_questions(r["questions"])
    return r

# %% ../nbs/00_core.ipynb #63fef9ea
ROW_META = ("n_tokens", "case", "qid", "case_idx", "variant")   # bookkeeping columns of a row: never model inputs

@dataclass
class Row:
    "One question over one state, as token ids with the anchor position of every option"
    ids: list # token ids
    markers: list # position of the anchor before each option
    qtype: int # QTYPES id
    target: list|None = None # gold distribution over the options
    label: int = -1 # index of the gold option
    extras: dict = field(default_factory=dict) # pixel_values, position_ids, image_grid_hw, stream ids, features
    meta: dict = field(default_factory=dict) # case id, question id
    spans: list|None = None # (start, end) of each option's own tokens, after its anchor
    answerable: int = -1 # 1: the gold is among the options; 0: the record says none is; -1: no gold

    @property
    def n_tokens(self): return len(self.ids)
    @property
    def k(self): return len(self.markers)

    def to_dict(self) -> dict:
        "The row as dataset columns"
        d = {"input_ids": list(self.ids), "markers": list(self.markers), "qtype": self.qtype,
             "target": self.target, "label": self.label, "n_tokens": self.n_tokens, "answerable": self.answerable, **self.extras}
        if self.spans is not None: d["spans"] = [list(s) for s in self.spans]
        return d

    @classmethod
    def from_dict(cls, d:dict):
        "A row from dataset columns"
        known = {"input_ids", "markers", "qtype", "target", "label", "spans", "answerable", *ROW_META}
        spans = d.get("spans")
        return cls(list(d["input_ids"]), list(d["markers"]), int(d["qtype"]), d.get("target"), int(d.get("label", -1)),
                   extras={k: v for k, v in d.items() if k not in known},
                   meta={k: d[k] for k in ("case", "qid", "case_idx", "variant") if k in d},
                   spans=[tuple(int(x) for x in s) for s in spans] if spans is not None else None,
                   answerable=int(d.get("answerable", -1)))

# %% ../nbs/00_core.ipynb #1a0160ae
class Batch(dict):
    "A collated batch: `input_ids`, `attention_mask`, `marker_pos`, `marker_mask`, `qtype`, plus `target`/`label` and extras"
    def to(self, device):
        return Batch({k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in self.items()})

# how each extra is collated: "pad" along the last axis to the batch's length, "pad_rows" along the first axis to the
# batch's longest, "cat" along the first axis, "stack"; a kind may be a pair (kind, pad value)
EXTRA_COLLATE = {"position_ids": "pad", "token_type_ids": "pad", "pixel_values": "cat", "image_grid_hw": "cat",
                 "anchors": "pad_rows", "hidden": "pad_rows", "features": "pad_rows", "query": "stack", "first": "stack"}

def _as_tensor(v, dtype=None):
    return v.to(dtype) if isinstance(v, torch.Tensor) and dtype else v if isinstance(v, torch.Tensor) else torch.tensor(np.asarray(v), dtype=dtype)

def _collate_extra(name, vals, L):
    kind, pad = EXTRA_COLLATE.get(name, "stack"), 0
    if isinstance(kind, tuple): kind, pad = kind
    ts = [_as_tensor(v) for v in vals]
    if kind == "cat": return torch.cat(ts, 0)
    if kind == "pad":
        out = torch.full((len(ts), *ts[0].shape[:-1], L), pad, dtype=ts[0].dtype)
        for i, t in enumerate(ts): out[i, ..., :t.shape[-1]] = t
        return out
    if kind == "pad_rows":
        n = max(t.shape[0] for t in ts)
        out = torch.full((len(ts), n, *ts[0].shape[1:]), pad, dtype=ts[0].dtype)
        for i, t in enumerate(ts): out[i, :t.shape[0]] = t
        return out
    return torch.stack(ts)

def collate(rows, pad_id:int=0) -> Batch:
    "Pad rows (`Row`s or their dict form) into one `Batch`"
    rows = [r.to_dict() if isinstance(r, Row) else r for r in rows]
    n, L = len(rows), max(len(r["input_ids"]) for r in rows)
    K = max(len(r["markers"]) for r in rows)
    ids = torch.full((n, L), pad_id, dtype=torch.long)
    att = torch.zeros((n, L), dtype=torch.long)
    mpos = torch.zeros((n, K), dtype=torch.long)
    mmask = torch.zeros((n, K), dtype=torch.bool)
    for i, r in enumerate(rows):
        ids[i, :len(r["input_ids"])] = _as_tensor(r["input_ids"], torch.long)
        att[i, :len(r["input_ids"])] = 1
        k = len(r["markers"])
        mpos[i, :k] = _as_tensor(r["markers"], torch.long)
        mmask[i, :k] = True
    b = Batch(input_ids=ids, attention_mask=att, marker_pos=mpos, marker_mask=mmask,
              qtype=torch.tensor([int(r["qtype"]) for r in rows]))
    if any(r.get("target") is not None for r in rows):
        tgt = torch.zeros((n, K), dtype=torch.float32)
        for i, r in enumerate(rows):
            if r.get("target") is None: continue
            if len(r["target"]) > len(r["markers"]):
                raise ValueError(f"row {i} has {len(r['target'])} target entries but {len(r['markers'])} markers")
            tgt[i, :len(r["target"])] = _as_tensor(r["target"], torch.float32)
        b["target"] = tgt
        b["label"] = torch.tensor([int(r.get("label", -1)) for r in rows])
    if any(r.get("spans") is not None for r in rows):
        sp = torch.zeros((n, K, 2), dtype=torch.long)
        for i, r in enumerate(rows):
            if r.get("spans"): sp[i, :len(r["spans"])] = _as_tensor(r["spans"], torch.long).reshape(-1, 2)
        b["spans"] = sp
    if any("answerable" in r for r in rows): b["answerable"] = torch.tensor([int(r.get("answerable", -1)) for r in rows])
    skip = {"input_ids", "markers", "qtype", "target", "label", "spans", "answerable", *ROW_META}
    for name in [k for k in rows[0] if k not in skip]:
        if all(r.get(name) is not None for r in rows): b[name] = _collate_extra(name, [r[name] for r in rows], L)
    return b

# %% ../nbs/00_core.ipynb #f3871718
ADAPTERS = {"NeoMMEProcessor": "sysone.multimodal", "NeoMMEConfig": "sysone.multimodal",
            "Idefics3Processor": "sysone.modernvbert", "ModernVBertConfig": "sysone.modernvbert"}   # a class's name: the sysone module that adapts it

def load_adapter(obj) -> bool:
    "Import the sysone module that adapts `obj`'s class or one of its bases, if it isn't imported yet: whether one was"
    for cls in type(obj).__mro__:
        mod = ADAPTERS.get(cls.__name__)
        if mod is not None and mod not in sys.modules:
            importlib.import_module(mod)
            return True
    return False
