"""`TypedDecisions`: typed-decision cases from the Hub, JSON lines or pandas, split by case, turned into token rows by a `RowBuilder`, with the sampling strategies SetFit taught and transforms that ask one label several ways.

Docs: https://sgaseretto.github.io/sysonelib/data.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_data.ipynb.

# %% auto #0
__all__ = ['CASE_COLUMNS', 'ROW_FEATURES', 'NOUL_STATEMENT', 'THRESHOLD_STATEMENT', 'cases_from_records', 'as_cases',
           'case_record', 'case_groups', 'split_cases', 'TypedDecisions', 'file_ref', 'read_jsonl', 'row_features',
           'DecisionCollator', 'LazyRows', 'RowSampler', 'Shortlist', 'choice_nouls', 'add_nouls', 'add_none_of_these',
           'add_score', 'add_thresholds', 'Expansion', 'Nouls', 'NoneOfThese', 'AsScore', 'Thresholds', 'Rephrase',
           'expand_records', 'question_stats']

# %% ../nbs/02_data.ipynb #054571be
import hashlib, json, math, random, warnings
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
import torch
from datasets import Dataset, Features, Sequence, Value, load_dataset, get_dataset_config_names
from fastcore.basics import patch, store_attr

from .core import *
from .template import *

# %% ../nbs/02_data.ipynb #56c2d924
CASE_COLUMNS = ("id", "state", "questions", "gold")

def _enc_state(s):
    "A state as stored: JSON, so text states come back exactly as they went in"
    if isinstance(s, str) and s[:1] in "{[":               # typed-decisions' convention: structured states as JSON text
        try: s = json.loads(s)
        except json.JSONDecodeError: pass
    return json.dumps(s, ensure_ascii=False)
def _enc_json(v): return v if isinstance(v, str) else json.dumps(v, ensure_ascii=False)

def cases_from_records(records, prefix:str="case") -> Dataset:
    "A cases dataset from an iterable of records (dicts with `state`, `questions`, optional `gold` and `id`)"
    rows = []
    for i, r in enumerate(records):
        r = load_record(r, parse_state=False)
        extra = {k: (v if isinstance(v, (str, int, float, bool)) or v is None else json.dumps(v, ensure_ascii=False, default=str))
                 for k, v in r.items() if k not in CASE_COLUMNS}
        rows.append({"id": str(r.get("id", f"{prefix}_{i:06d}")), "state": _enc_state(r["state"]),
                     "questions": _enc_json(r["questions"]), "gold": _enc_json(r.get("gold") or {}), **extra})
    return Dataset.from_list(rows)

def as_cases(ds) -> Dataset:
    "A cases dataset from a `datasets.Dataset` with `state` and `questions` columns (strings or structures)"
    if not isinstance(ds, Dataset): return cases_from_records(ds)
    missing = {"state", "questions"} - set(ds.column_names)
    if missing: raise ValueError(f"cases need 'state' and 'questions' columns; missing {sorted(missing)}")
    cols = ["id", "state", "questions"] + (["gold"] if "gold" in ds.column_names else [])
    if all(c in ds.features and ds.features[c] == Value("string") for c in cols): return ds
    return cases_from_records(ds)

def case_record(cases:Dataset, i:int) -> dict:
    "Case i as a parsed record"
    return load_record(cases[i])

# %% ../nbs/02_data.ipynb #56b4cca9
def case_groups(cases:Dataset, groups) -> list:
    "The group of each case: a column of the cases, or `groups(record)`"
    if callable(groups): return [groups(case_record(cases, i)) for i in range(len(cases))]
    if groups not in cases.column_names: raise ValueError(f"no column {groups!r} in the cases; name a top-level field of the records or pass a function")
    return list(cases[groups])

def split_cases(cases:Dataset, frac, seed:int=0, groups=None):
    "Two datasets: the cases kept and the `frac` (a fraction or a count) held out; with `groups`, whole groups are held out"
    n = len(cases)
    k = int(round(frac * n)) if isinstance(frac, float) and frac < 1 else int(frac)
    if k <= 0: return cases, None
    if k >= n: raise ValueError(f"cannot hold out {k} of {n} cases")
    if groups is None: held = set(random.Random(seed).sample(range(n), k))
    else:
        members = {}
        for i, g in enumerate(case_groups(cases, groups)): members.setdefault(g, []).append(i)
        order = sorted(members, key=str); random.Random(seed).shuffle(order)
        held = set()
        for g in order:
            if len(held) >= k: break
            held.update(members[g])
        if len(held) >= n: raise ValueError(f"holding out {k} of {n} cases by group leaves nothing to train on; there are {len(members)} groups")
    return cases.select([i for i in range(n) if i not in held]), cases.select(sorted(held))

# %% ../nbs/02_data.ipynb #70490cf3
class TypedDecisions:
    "Typed-decision cases in train, valid and calib splits, and the token rows a `RowBuilder` makes from them"
    def __init__(self,
                 train, # training cases: a `datasets.Dataset` or a list of records
                 valid=None, # validation cases, for metrics
                 calib=None, # held-out training cases, for temperature fitting
                 template:RowTemplate|str|None=None, # row template; the encoder's default when None
                 tfms:list|None=None, # transforms, run on every record at training and inference
                 sampler=None, # a `RowSampler`; every record once when None
                 seed:int=0):
        self.cases = {"train": as_cases(train), "valid": as_cases(valid) if valid is not None else None,
                      "calib": as_cases(calib) if calib is not None else None}
        self.template, self.tfms, self.sampler, self.seed = template, list(tfms or []), sampler, seed
        self.builder, self._rows = None, {}
        self.source = None   # where the cases came from, set by the loaders below and kept in the training record

    def __repr__(self):
        n = ", ".join(f"{len(v)} {k}" for k, v in self.cases.items() if v is not None)
        t = self.builder.template if self.builder else self.template
        return f"TypedDecisions({n} cases · template {getattr(t, 'name', t) or 'default'} · {len(self.tfms)} tfms)"

# %% ../nbs/02_data.ipynb #c69c4e73
def _holdouts(train, valid, calib, seed, groups=None):
    if isinstance(valid, (int, float)) and not isinstance(valid, bool): train, valid = split_cases(train, valid, seed, groups)
    if isinstance(calib, (int, float)) and not isinstance(calib, bool): train, calib = split_cases(train, calib, seed + 1, groups)
    return train, valid, calib

@patch(cls_method=True)
def from_records(cls:TypedDecisions, records, valid=None, calib=0.1, seed:int=0, groups=None, **kw):
    "Cases from a list of records; `groups` (a field or a function of the record) keeps each group on one side of every split"
    train, valid, calib = _holdouts(cases_from_records(records), valid, calib, seed, groups)
    out = cls(train, valid, calib, seed=seed, **kw)
    out.source = {"kind": "records"}
    return out

def file_ref(path) -> dict:
    "A file's name and SHA-256: enough to tell later whether a model was trained on the same data, without its path"
    return {"name": Path(path).name, "sha256": hashlib.sha256(Path(path).read_bytes()).hexdigest()}

def read_jsonl(path) -> list:
    "Records from a JSON-lines file (or a JSON list)"
    text = Path(path).read_text()
    if text.lstrip().startswith("["): return json.loads(text)
    return [json.loads(l) for l in text.splitlines() if l.strip()]

@patch(cls_method=True)
def from_json(cls:TypedDecisions, path, valid=None, calib=0.1, seed:int=0, groups=None, **kw):
    "Cases from a JSON-lines file, one record per line; `valid` may be a second file"
    v = cases_from_records(read_jsonl(valid)) if isinstance(valid, (str, Path)) else valid
    out = cls.from_records(read_jsonl(path), valid=v, calib=calib, seed=seed, groups=groups, **kw)
    out.source = {"kind": "file", "files": [file_ref(p) for p in (path, valid) if isinstance(p, (str, Path))]}
    return out

@patch(cls_method=True)
def from_pandas(cls:TypedDecisions, df, valid=None, calib=0.1, seed:int=0, groups=None, **kw):
    "Cases from a DataFrame with `state` and `questions` (and `gold`) columns"
    out = cls.from_records(df.to_dict("records"), valid=valid, calib=calib, seed=seed, groups=groups, **kw)
    out.source = {"kind": "dataframe"}
    return out

def _pick_config(path, config):
    if config is not None: return config
    try: names = get_dataset_config_names(path)
    except Exception: return None
    if len(names) <= 1: return names[0] if names else None
    for c in ("all", "default"):
        if c in names: return c
    raise ValueError(f"{path} has several configs; name one of {names}")

@patch(cls_method=True)
def from_hub(cls:TypedDecisions, path:str, config:str|None=None, split:str="train", valid=None, calib=0.1,
             revision:str|None=None, seed:int=0, groups=None, **kw):
    "Cases from a Hub dataset in the typed-decisions format; `valid` is a split name or a fraction of `split`"
    config = _pick_config(path, config)
    source = {"kind": "hub", "id": path, "config": config, "split": split, "valid": valid if isinstance(valid, str) else None,
              "revision": revision}
    train = as_cases(load_dataset(path, config, split=split, revision=revision))
    if isinstance(valid, str): valid = as_cases(load_dataset(path, config, split=valid, revision=revision))
    train, valid, calib = _holdouts(train, valid, calib, seed, groups)
    out = cls(train, valid, calib, seed=seed, **kw)
    out.source = source
    return out

# %% ../nbs/02_data.ipynb #8fc1a0e0
ROW_FEATURES = Features({"input_ids": Sequence(Value("int32")), "markers": Sequence(Value("int32")), "qtype": Value("int8"),
                         "target": Sequence(Value("float32")), "label": Value("int32"), "answerable": Value("int8"),
                         "n_tokens": Value("int32"), "case": Value("string"), "qid": Value("string"), "case_idx": Value("int64"),
                         "variant": Value("int32")})

def row_features(builder:RowBuilder|None=None) -> Features:
    "The columns of a split's rows: `ROW_FEATURES`, the option spans, and each side stream's ids and mask"
    f = dict(ROW_FEATURES) | {"spans": Sequence(Sequence(Value("int32")))}
    for s in (builder.streams.values() if builder is not None else []): f |= {s.columns[0]: Sequence(Value("int32")), s.columns[1]: Sequence(Value("int8"))}
    return Features(f)

@patch
def bind(self:TypedDecisions, tokenizer, template:RowTemplate|str|None=None, streams=None):
    "Build rows with `tokenizer` (or a processor), `template` (else the data's, else the `auto` preset) and side `streams`"
    template = template if template is not None else self.template if self.template is not None else "auto"
    self.builder = RowBuilder(tokenizer, template, self.tfms, streams=streams)
    self._rows = {}
    return self

def _builder_key(b:RowBuilder) -> str:
    "What the rows depend on: template, transforms, tokenizer (and processor), side streams, and the library's version"
    import sysone
    tok = b.tok
    streams = json.dumps([s.to_json() | {"tok": getattr(s.tokenizer, "name_or_path", ""), "n": len(s.tokenizer)} for s in b.streams.values()])
    return f"{b.template.hash}:{hashlib.sha1(json.dumps(tfms_to_json(b.tfms), sort_keys=True).encode()).hexdigest()[:8]}:" \
           f"{getattr(tok, 'name_or_path', '')}:{len(tok)}:{type(b.processor).__name__}:{sysone.__version__}:" \
           f"{hashlib.sha1(streams.encode()).hexdigest()[:8]}"

# %% ../nbs/02_data.ipynb #39f88a04
def _rows_fn(builder, train, sampler):
    cols, stream_cols = row_features(builder), [c for s in builder.streams.values() for c in s.columns]
    def fn(batch, idx):
        out = {k: [] for k in cols}
        for i in range(len(batch["id"])):
            rec = load_record({k: batch[k][i] for k in batch})
            for v, r in enumerate(sampler.expand(rec, builder) if sampler is not None and train else [rec]):
                for row in builder.build_record(r, train=train, skip_errors=True):
                    if row.target is None and row.answerable != 0: continue     # no gold at all: nothing to learn from
                    d = row.to_dict()
                    if d["target"] is None: d["target"] = [0.0] * row.k                 # unanswerable: the option loss skips it
                    for k in ("input_ids", "markers", "qtype", "target", "label", "answerable", "n_tokens"): out[k].append(d[k])
                    out["spans"].append(d.get("spans") or [])
                    for c in stream_cols: out[c].append(d[c])
                    out["case"].append(str(row.meta.get("case"))); out["qid"].append(row.meta["qid"])
                    out["case_idx"].append(idx[i]); out["variant"].append(v)
        return out
    return fn

@patch
def _check_bound(self:TypedDecisions):
    if self.builder is None: raise ValueError("no tokenizer yet: call data.bind(tokenizer) or make a learner first")

@patch
def rows(self:TypedDecisions, split:str="train") -> Dataset:
    "The rows of a split (built once per binding)"
    self._check_bound()
    if split in self._rows: return self._rows[split]
    cases = self.cases[split]
    if cases is None: return None
    train = split == "train"
    fp = hashlib.sha1(f"{cases._fingerprint}:{_builder_key(self.builder)}:{train}:{self.sampler!r}".encode()).hexdigest()
    rows = cases.map(_rows_fn(self.builder, train, self.sampler), batched=True, batch_size=64, with_indices=True,
                     remove_columns=cases.column_names, features=row_features(self.builder), new_fingerprint=fp,
                     desc=f"rows ({split})")
    if train and self.sampler is not None: rows = self.sampler.resample(rows)
    s = self.builder.stats
    if s["rows"] and s["state_truncated"] / s["rows"] > 0.2:
        warnings.warn(f"{s['state_truncated']} of {s['rows']} rows had their state truncated to fit max_len="
                      f"{self.builder.template.max_len}; consider a Truncate transform or a longer budget")
    if s["dropped"]: warnings.warn(f"{s['dropped']} rows dropped: their options do not fit the template's budgets")
    self._rows[split] = rows
    return rows

# %% ../nbs/02_data.ipynb #c6799754
def _render_text(template:RowTemplate, record:dict, qid:str) -> str:
    "The row as text, before tokenization"
    q = as_questions(record["questions"])[qid]
    b = option_block(template, q)
    opts = b["header"] + (b["option"].format(mask=template.mask, text="") if shared_slot(b["option"]) else
                          b["sep"].join(b["option"].format(mask=template.mask, text=o) for o in q.options))
    vals = {r: (getattr(template, r) or "") for r in SPECIALS} | {"type": q.type, "instructions": q.instructions,
            "options": opts, "state": render_state(record["state"]), "image": template.image if record.get("images") else ""}
    return template.row.format(**vals)

@patch
def show_batch(self:TypedDecisions, n:int=2, split:str="train", max_chars:int=300):
    "Print the first `n` rows of a split"
    cases = self.cases[split]
    if self.builder is None:
        t = self.template if isinstance(self.template, RowTemplate) else \
            RowTemplate.preset(self.template if self.template not in (None, "auto") else "laya")
        shown = 0
        for i in range(len(cases)):
            rec = apply_tfms(list(t.tfms) + self.tfms, case_record(cases, i))
            for qid in rec["questions"]:
                s = _render_text(t, rec, qid)
                print((s if len(s) <= max_chars else s[:max_chars * 2 // 3] + " … " + s[-max_chars // 3:]) + "\n")
                shown += 1
                if shown >= n: return
        return
    rows = self.rows(split)
    for i in range(min(n, len(rows))): print(show_row(Row.from_dict(rows[i]), self.builder.tok, max_chars), end="\n\n")

# %% ../nbs/02_data.ipynb #f5a1243e
class DecisionCollator:
    "Collate dataset rows into a padded `Batch`"
    def __init__(self, pad_id:int=0): self.pad_id = pad_id
    def __call__(self, rows):
        b = collate(rows, self.pad_id)
        return b
    def __repr__(self): return f"DecisionCollator(pad_id={self.pad_id})"

@patch(as_prop=True)
def collator(self:TypedDecisions) -> DecisionCollator:
    "The collator for this data's tokenizer"
    self._check_bound()
    return DecisionCollator(self.builder.tok.pad_token_id or 0)

# %% ../nbs/02_data.ipynb #f3298ae0
class LazyRows(torch.utils.data.Dataset):
    "Rows built when read, from their case: for per-epoch augmentation and for image rows"
    def __init__(self, data:TypedDecisions, split:str="train"):
        self.data, self.split = data, split
        static = data.rows(split)
        self.index = list(zip(static["case_idx"], static["variant"], static["qid"], static["case"]))
        self.lengths = static["n_tokens"]
    def __len__(self): return len(self.index)
    def __getitem__(self, i):
        ci, v, qid, case = self.index[i]
        train = self.split == "train"
        rec = case_record(self.data.cases[self.split], ci)
        if train and self.data.sampler is not None: rec = self.data.sampler.expand(rec, self.data.builder)[v]
        rec = apply_tfms(self.data.builder.tfms, rec, train=train)      # the whole case, as the static build transforms it
        rec["questions"] = {qid: rec["questions"][qid]}
        rec["gold"] = {qid: (rec.get("gold") or {}).get(qid)}
        row = self.data.builder.build_record(rec, train=train, tfms=False)[0].to_dict()
        return row | {"case": case, "qid": qid, "case_idx": ci, "variant": v}      # which case and question, as the static rows say

@patch
def lazy_rows(self:TypedDecisions, split:str="train") -> LazyRows:
    "Rows of a split, built on read"
    self._check_bound()
    return LazyRows(self, split)

@patch(as_prop=True)
def needs_lazy_rows(self:TypedDecisions) -> bool:
    "Whether training rows must be rebuilt on read (train-only transforms, or a processor with images)"
    self._check_bound()
    return any(t.train_only for t in self.builder.tfms) or self.builder.processor is not None

# %% ../nbs/02_data.ipynb #2ee4e94f
class RowSampler:
    "Which rows a training epoch sees: `all`, `oversample`, or `negatives=k` / `hard` distractor sampling"
    def __init__(self, strategy:str="all", negatives:int|None=None, variants:int=1, model:str="BAAI/bge-small-en-v1.5", seed:int=0):
        if strategy not in ("all", "oversample", "negatives", "hard"): raise ValueError(f"unknown strategy {strategy!r}")
        if strategy in ("negatives", "hard") and not negatives: raise ValueError(f"strategy {strategy!r} needs negatives=k")
        store_attr(); self._embedder = None
    def __repr__(self): return f"RowSampler({self.strategy}, negatives={self.negatives}, variants={self.variants}, seed={self.seed})"

# %% ../nbs/02_data.ipynb #de91b394
def _gold_key(q:Question, gold):
    t, label = q.target(gold)
    return None if t is None else q.keys[label]

@patch
def _similar(self:RowSampler, texts:list, anchor:int) -> list:
    "Indices of `texts` by decreasing similarity to texts[anchor]"
    if self._embedder is None:
        from sentence_transformers import SentenceTransformer
        self._embedder = SentenceTransformer(self.model)
    e = self._embedder.encode(texts, normalize_embeddings=True)
    sims = e @ e[anchor]
    return [int(i) for i in np.argsort(-sims) if i != anchor]

@patch
def _sample_question(self:RowSampler, q:Question, gold, rng):
    "A definition of `q` with k options: the gold one and k − 1 distractors"
    k = self.negatives
    if not isinstance(q, Choice) or q.k <= k: return q.to_dict(), gold
    keys = list(q.criteria)
    g = _gold_key(q, gold)
    gi = keys.index(g) if g in keys else rng.randrange(len(keys))
    if self.strategy == "hard": pool = self._similar(q.options, gi)[:max(k - 1, 2 * (k - 1))]
    else: pool = [i for i in range(len(keys)) if i != gi]
    keep = sorted([gi] + rng.sample(pool, k - 1))
    crit = {keys[i]: q.criteria[keys[i]] for i in keep}
    if isinstance(gold, dict) and isinstance(gold.get("probabilities"), dict):
        gp = {str(k): v for k, v in gold["probabilities"].items()}
        p = {kk: gp.get(str(kk), 0.0) for kk in crit}
        s = sum(p.values()) or 1.0
        gold = {**gold, "probabilities": {kk: v / s for kk, v in p.items()}}
    return {**q.to_dict(), "criteria": crit}, gold

@patch
def expand(self:RowSampler, record:dict, builder=None) -> list:
    "The records one training record becomes (`variants` draws for the negative strategies)"
    if self.strategy not in ("negatives", "hard"): return [record]
    record = load_record(record, parse_state=False)
    out = []
    for v in range(self.variants):
        rng = random.Random(f"{self.seed}:{v}:{record.get('id')}")
        qs, gold = {}, dict(record.get("gold") or {})
        for qid, q in as_questions(record["questions"]).items():
            qs[qid], g = self._sample_question(q, gold.get(qid), rng)
            if qid in gold: gold[qid] = g
        out.append({**record, "questions": qs, "gold": gold, "id": f"{record.get('id')}" + (f"#{v}" if v else "")})
    return out

@patch
def resample(self:RowSampler, rows:Dataset) -> Dataset:
    "Oversample rare labels per question, cycling through their rows"
    if self.strategy != "oversample": return rows
    groups = defaultdict(lambda: defaultdict(list))
    for i, (qid, label) in enumerate(zip(rows["qid"], rows["label"])): groups[qid][label].append(i)
    idx = []
    for qid, by_label in groups.items():
        top = max(len(v) for v in by_label.values())
        for label, members in by_label.items(): idx += [members[j % len(members)] for j in range(top)]
    return rows.select(sorted(idx))

# %% ../nbs/02_data.ipynb #2d73f5d9
@transform("Shortlist")
class Shortlist(Transform):
    "Keep the k options of each choice question most similar to the state under a sentence-transformer"
    def __init__(self, model:str="BAAI/bge-small-en-v1.5", k:int=12, min_options:int|None=None):
        store_attr(); self._enc = None
    def _embed(self, texts):
        if self._enc is None:
            from sentence_transformers import SentenceTransformer
            self._enc = SentenceTransformer(self.model)
        return self._enc.encode(texts, normalize_embeddings=True)
    def __call__(self, record):
        qs, dropped = {}, dict(record.get("dropped") or {})
        state = render_state(record["state"])
        for qid, qd in record["questions"].items():
            q = Question.from_dict(qd, name=qid)
            if not isinstance(q, Choice) or q.k <= max(self.k, self.min_options or 0): qs[qid] = qd; continue
            e = self._embed([state] + q.options)
            order = np.argsort(-(e[1:] @ e[0]))[:self.k]
            keys = list(q.criteria)
            keep = [keys[i] for i in sorted(order)]
            qs[qid] = {**q.to_dict(), "criteria": {kk: q.criteria[kk] for kk in keep}}
            dropped[qid] = [kk for kk in keys if kk not in keep]
        return {**record, "questions": qs, "dropped": dropped}

# %% ../nbs/02_data.ipynb #27e44c0a
NOUL_STATEMENT = 'The answer to "{instructions}" is {option}.'
THRESHOLD_STATEMENT = 'The answer to "{instructions}" is {level} or higher.'

def _source_id(record) -> str: return str(record.get("id", render_state(record["state"])[:200]))

def _gold_dist(q:Question, gold):
    "The gold as a distribution over `q`'s keys: None without gold, all zeros when it says no option applies"
    if gold is None: return None
    if q.answerable(gold) == 0: return [0.0] * q.k
    return q.target(gold)[0]

def _noul_gold(p):
    "A noul's gold for p(true): a label when it is certain, else the probability"
    if p is None: return None
    p = round(float(p), 6)
    return {"label": "true"} if p >= 1 else {"label": "false"} if p <= 0 else {"noul": p}

def _picked(name:str, d:dict, qid, type:str, derived:bool=True) -> bool:
    "Whether to reshape question `name`: of `type`, and `qid` (a name or a list), or when `qid` is None any, made by a reshaping only if `derived`"
    if d.get("type") != type: return False
    if qid is None: return derived or "from" not in d
    return name == qid if isinstance(qid, str) else name in qid

def choice_nouls(q:Choice, gold=None, keys=None, statement:str=NOUL_STATEMENT, soft:dict|None=None) -> list:
    "A `(definition, gold)` noul per label of `q` (or of `keys`): the statement that the answer is that label, as true as the gold makes it"
    t = _gold_dist(q, gold)
    one = q.keys[t.index(1.0)] if t is not None and 1.0 in t else None     # a single gold label, which `soft` may qualify
    opts, out = dict(zip(q.keys, q.options)), []
    for k in (q.keys if keys is None else keys):
        if t is None: p = None
        elif one is not None and k != one and soft: p = float((soft.get(str(one)) or {}).get(str(k), 0.0))
        else: p = t[q.keys.index(k)]
        desc = q.criteria.get(k)
        text = statement.format(instructions=q.instructions, label=k, option=opts[k],
                                description=render_criterion(desc) if desc not in (None, "") else "")
        out.append(({"type": "noul", "instructions": text}, _noul_gold(p)))
    return out

def add_nouls(record:dict, qid=None, negatives:int|None=None, statement=NOUL_STATEMENT, soft:dict|None=None,
              keep:bool=True, rng=None) -> dict:
    "The record with its choice questions (or `qid`) also asked as nouls: one per label, or per gold label and `negatives` others"
    rng = rng or random.Random(_source_id(record))
    record = load_record(record, parse_state=False)
    qs, gold = {}, dict(record.get("gold") or {})
    for name, d in record["questions"].items():
        if not _picked(name, d, qid, "choice", derived=False): qs[name] = d; continue
        if keep: qs[name] = d
        q = Question.from_dict(d, name=name)
        t, keys = _gold_dist(q, gold.get(name)), list(q.keys)
        if negatives is not None:
            pos = [k for k, p in zip(keys, t) if p > 0] if t is not None else []
            rest = [k for k in keys if k not in pos]
            keys = pos + rng.sample(rest, min(negatives, len(rest)))
        rng.shuffle(keys)
        st = statement if isinstance(statement, str) else rng.choice(list(statement))
        for j, (nd, g) in enumerate(choice_nouls(q, gold.get(name), keys, st, soft)):
            qs[f"{name}:noul{j}"] = nd | {"from": {"question": name, "type": "choice"}}
            if g is not None: gold[f"{name}:noul{j}"] = g
        if not keep: gold.pop(name, None)
    return {**record, "questions": qs, "gold": gold}

# %% ../nbs/02_data.ipynb #05d6227b
def add_none_of_these(record:dict, qid=None, frac:float=1.0, seed:int=0) -> dict:
    "For a `frac` of records, a copy of their choice questions (or `qid`) without the gold options: a question none of its options answers"
    record = load_record(record, parse_state=False)
    if frac < 1 and random.Random(f"{seed}:{_source_id(record)}").random() >= frac: return record
    qs, gold = dict(record["questions"]), dict(record.get("gold") or {})
    for name, d in record["questions"].items():
        if not _picked(name, d, qid, "choice", derived=False): continue
        q = Question.from_dict(d, name=name)
        t = _gold_dist(q, gold.get(name))
        if t is None or not any(t): continue                        # no gold, or it already names none of the options
        rest = [k for k, p in zip(q.keys, t) if p <= 0]
        if not rest: continue                                       # every option is a gold one
        crit = rest if isinstance(d["criteria"], list) else {k: q.criteria[k] for k in rest}
        qs[f"{name}:none"] = {**d, "criteria": crit, "from": {"question": name, "type": "choice"}}
        gold[f"{name}:none"] = {"answerable": False}
    return {**record, "questions": qs, "gold": gold}

# %% ../nbs/02_data.ipynb #53e129a9
def add_score(record:dict, qid:str, levels:list|None=None, instructions:str|None=None, keep:bool=True) -> dict:
    "The record with choice `qid` also asked as a score, its labels in order (`levels`, else the choice's own order) as the levels"
    record = load_record(record, parse_state=False)
    d = record["questions"][qid]
    q = Question.from_dict(d, name=qid)
    if not isinstance(q, Choice): raise ValueError(f"question {qid!r} is a {q.type}, not a choice")
    keys = [str(k) for k in q.keys]
    levels = keys if levels is None else [str(l) for l in levels]
    if sorted(levels) != sorted(keys): raise ValueError(f"levels {levels} are not the labels of {qid!r}, {keys}")
    order = [keys.index(l) for l in levels]
    qs = {k: v for k, v in record["questions"].items() if keep or k != qid}
    gold, name = dict(record.get("gold") or {}), f"{qid}:score"
    qs[name] = {"type": "score", "instructions": instructions or q.instructions, "criteria": [q.options[i] for i in order],
                "from": {"question": qid, "type": "choice"}}
    t = _gold_dist(q, gold.get(qid))
    if t is not None:
        p = [t[i] for i in order]
        gold[name] = {"answerable": False} if not any(p) else {"label": str(p.index(1.0))} if 1.0 in p else \
                     {"probabilities": {str(i): v for i, v in enumerate(p)}}
    if not keep: gold.pop(qid, None)
    return {**record, "questions": qs, "gold": gold}

def add_thresholds(record:dict, qid=None, statement:str=THRESHOLD_STATEMENT, keep:bool=True) -> dict:
    "The record with its score questions (or `qid`) also asked as nouls, one per level above the first: is the answer that level or higher?"
    record = load_record(record, parse_state=False)
    qs, gold = {}, dict(record.get("gold") or {})
    for name, d in record["questions"].items():
        if not _picked(name, d, qid, "score"): qs[name] = d; continue
        if keep: qs[name] = d
        q = Question.from_dict(d, name=name)
        t = _gold_dist(q, gold.get(name))
        for i in range(1, q.k):
            nid = f"{name}:atleast{i}"
            qs[nid] = {"type": "noul", "instructions": statement.format(instructions=q.instructions, level=render_criterion(q.criteria[i]), i=i),
                       "from": {"question": name, "type": "score"}}
            if t is not None and any(t): gold[nid] = _noul_gold(sum(t[i:]))
        if not keep: gold.pop(name, None)
    return {**record, "questions": qs, "gold": gold}

# %% ../nbs/02_data.ipynb #9d3c94a8
class Expansion(Transform):
    "A training-only transform that adds questions to a record: drawn anew each epoch, under question ids that stay the same"
    train_only, _epoch = True, 0
    def set_epoch(self, epoch:int): self._epoch = int(epoch)
    def expand(self, record:dict, epoch:int=0) -> dict: return record
    def __call__(self, record): return self.expand(record, self._epoch)
    def _rng(self, record, epoch:int): return random.Random(f"{getattr(self, 'seed', 0)}:{epoch}:{_source_id(record)}")

@transform("Nouls")
class Nouls(Expansion):
    "Ask choice questions as nouls too (`add_nouls`), the negatives and the wording drawn anew each epoch"
    def __init__(self, qid=None, negatives:int|None=None, statement=NOUL_STATEMENT, soft:dict|None=None, keep:bool=True, seed:int=0):
        store_attr()
    def expand(self, record, epoch=0):
        return add_nouls(record, self.qid, self.negatives, self.statement, self.soft, self.keep, self._rng(record, epoch))

@transform("NoneOfThese")
class NoneOfThese(Expansion):
    "For a `frac` of records, add their choice questions without the gold options (`add_none_of_these`)"
    def __init__(self, qid=None, frac:float=1.0, seed:int=0): store_attr()
    def expand(self, record, epoch=0): return add_none_of_these(record, self.qid, self.frac, self.seed)

@transform("AsScore")
class AsScore(Expansion):
    "Ask an ordered choice as a score too (`add_score`)"
    def __init__(self, qid:str, levels:list|None=None, instructions:str|None=None, keep:bool=True): store_attr()
    def expand(self, record, epoch=0):
        record = load_record(record, parse_state=False)
        return add_score(record, self.qid, self.levels, self.instructions, self.keep) if self.qid in record["questions"] else record

@transform("Thresholds")
class Thresholds(Expansion):
    "Ask score questions as threshold nouls too (`add_thresholds`)"
    def __init__(self, qid=None, statement:str=THRESHOLD_STATEMENT, keep:bool=True): store_attr()
    def expand(self, record, epoch=0): return add_thresholds(record, self.qid, self.statement, self.keep)

@transform("Rephrase")
class Rephrase(Transform):
    "Ask questions in one of several wordings, drawn per record and epoch (training only); `wordings` maps a question id to its wordings"
    train_only = True
    def __init__(self, wordings:dict, seed:int=0): store_attr(); self._epoch = 0
    def set_epoch(self, epoch:int): self._epoch = int(epoch)
    def __call__(self, record):
        rng = random.Random(f"{self.seed}:{self._epoch}:{_source_id(record)}")
        qs = {k: {**d, "instructions": rng.choice(list(self.wordings[k]))} if k in self.wordings else d for k, d in record["questions"].items()}
        return {**record, "questions": qs}

# %% ../nbs/02_data.ipynb #98a637b1
def expand_records(records, tfms, epoch:int=0, variants:int=1) -> list:
    "The records with the questions `tfms`' expansions add, drawn as training draws them at `epoch` (and the epochs after, for `variants` > 1)"
    exps, out = [t for t in tfms if isinstance(t, Expansion)], []
    for r in records:
        r = load_record(r, parse_state=False)
        for v in range(variants):
            x = r
            for t in exps: x = t.expand(x, epoch + v)
            if variants > 1: x = {**x, "id": _source_id(r) + (f"#{v}" if v else ""), "parent": _source_id(r)}
            out.append(x)
    return out

@patch
def expand_eval(self:TypedDecisions, splits=("valid", "calib")):
    "Give `splits` one fixed draw of the expansions in `tfms`, so their metrics and temperatures cover the questions training adds"
    exps = [t for t in self.tfms if isinstance(t, Expansion)]
    for s in splits:
        if exps and self.cases.get(s) is not None:
            cases = self.cases[s]
            self.cases[s] = cases_from_records(expand_records([case_record(cases, i) for i in range(len(cases))], exps))
    self._rows = {}
    return self

def question_stats(records):
    "Per kind of question (its type, what it was made from, whether an option answers it): how many, per record, their options, and how often a noul's gold is true"
    import pandas as pd
    rows, n = [], 0
    for r in records:
        r, n = load_record(r, parse_state=False), n + 1
        gold = r.get("gold") or {}
        for name, d in r["questions"].items():
            q = Question.from_dict(d, name=name)
            g = gold.get(name)
            ok = q.answerable(g)
            kind = q.type + (f" from {d['from']['type']}" if "from" in d else "") + (", none of these" if ok == 0 else "")
            rows.append({"kind": kind, "options": q.k, "true": q.target(g)[0][1] if isinstance(q, Noul) and ok == 1 else np.nan})
    df = pd.DataFrame(rows)
    out = df.groupby("kind", sort=False).agg(questions=("options", "size"), options=("options", "mean"), true=("true", "mean"))
    out.insert(1, "per record", out["questions"] / max(n, 1))
    return out.rename(columns={"true": "gold true"}).round(3)
