"""Publish an export to the Hugging Face Hub with a model card written from its `sysone.json` and training record, private by default; and move datasets through private Hub repos, the way data reaches a remote job.

Docs: https://sgaseretto.github.io/sysonelib/hub.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/42_hub.ipynb.

# %% auto #0
__all__ = ['SKIP_METRICS', 'TASKS', 'REGIME_TAGS', 'read_meta', 'is_hub_id', 'card_metrics', 'hub_dataset', 'card_data',
           'source_text', 'fit_text', 'card_text', 'model_card', 'commit_summary', 'push_to_hub', 'push_data',
           'pull_data']

# %% ../nbs/42_hub.ipynb #9f47956a
import json, re, tempfile
from pathlib import Path

from fastcore.basics import patch
from huggingface_hub import EvalResult, HfApi, ModelCard, ModelCardData, snapshot_download

from .learner import Learner

# %% ../nbs/42_hub.ipynb #891755a3
def read_meta(path) -> dict:
    "An export's `sysone.json`"
    p = Path(path) / "sysone.json"
    if not p.exists(): raise FileNotFoundError(f"{path} is not a sysone export: it has no sysone.json")
    return json.loads(p.read_text())

def is_hub_id(s) -> bool:
    "Whether `s` names a Hub repo (`owner/name`) rather than a local folder"
    return isinstance(s, str) and re.fullmatch(r"[\w.-]+/[\w.-]+", s) is not None and not Path(s).exists()

SKIP_METRICS = {"epoch", "runtime", "samples_per_second", "steps_per_second", "n", "n_unanswerable"}

def card_metrics(meta:dict) -> dict:
    "The validation metrics of an export, rounded, without timings and counts"
    m = meta.get("metrics") or {}
    return {k: round(float(v), 4) for k, v in m.items()
            if k not in SKIP_METRICS and isinstance(v, (int, float)) and not isinstance(v, bool)}

def _training(meta:dict) -> dict: return meta.get("training") or {}

def hub_dataset(meta:dict) -> dict|None:
    "The Hub dataset an export trained on, from its training record, or None"
    src = (_training(meta).get("data") or {}).get("source") or {}
    return src if src.get("kind") == "hub" and src.get("id") else None

TASKS = {"text": "zero-shot-classification", "image": "zero-shot-image-classification", "multimodal": "zero-shot-image-classification"}
REGIME_TAGS = {"head": "head-only", "lora": "lora", "full": "full-finetune"}

def card_data(meta:dict, license:str|None=None, tags:list|None=None) -> ModelCardData:
    "The model card's metadata: library, base model, datasets, tags and, for Hub data, the validation metrics as model-index results"
    enc, ds = meta.get("encoder") or {}, hub_dataset(meta)
    regime = (meta.get("head") or {}).get("regime")
    tags = ["sysone", "typed-decisions", enc.get("modality") or "text", REGIME_TAGS.get(regime, regime)] + list(tags or [])
    results = [EvalResult(task_type=TASKS.get(enc.get("modality"), "zero-shot-classification"), dataset_type=ds["id"],
                          dataset_name=ds["id"].split("/")[-1], dataset_config=ds.get("config"),
                          dataset_split=ds.get("valid") or ds.get("split"), dataset_revision=ds.get("sha"),
                          metric_type=k, metric_value=v) for k, v in card_metrics(meta).items()] if ds else []
    return ModelCardData(library_name="sysone", base_model=enc.get("id") if is_hub_id(enc.get("id")) else None,
                         datasets=[ds["id"]] if ds else None, license=license, model_name=meta.get("name"),
                         tags=list(dict.fromkeys(t for t in tags if t)), eval_results=results or None)

# %% ../nbs/42_hub.ipynb #ed30f9cf
def _short(sha, n:int=8): return f"`{sha[:n]}`" if sha else "?"

def source_text(src:dict|None) -> str:
    "One line naming where the cases came from"
    if not src: return "not recorded"
    reg = f"the `{src['registry']}` dataset of sysone's registry, " if src.get("registry") else ""
    k = src.get("kind")
    if k == "hub":
        at = f" at {_short(src.get('sha'))}" if src.get("sha") else (f" at `{src['revision']}`" if src.get("revision") else "")
        return reg + f"[{src['id']}](https://huggingface.co/datasets/{src['id']})" + (f" (`{src['config']}`)" if src.get("config") else "") + at
    if k == "file": return reg + ", ".join(f"`{f['name']}` (SHA-256 {_short(f.get('sha256'), 12)})" for f in src.get("files", []))
    return reg + {"records": "records in memory", "dataframe": "a DataFrame"}.get(k, str(k))

def _num(x, fmt=".3g"): return format(x, fmt) if isinstance(x, (int, float)) else "?"

def _targets(t) -> str:
    "LoRA's target modules: a regular expression or a list of names"
    return f"`{t}`" if isinstance(t, str) else ", ".join(f"`{x}`" for x in t or [])

def _seconds(s) -> str:
    if not isinstance(s, (int, float)): return "?"
    return f"{s:.1f} s" if s < 120 else f"{s / 60:.1f} min" if s < 7200 else f"{s / 3600:.1f} h"

def fit_text(f:dict) -> str:
    "One line describing a fit from the training record"
    lr = f"lr {_num(f.get('lr_head'), '.2g')}" + (f" (encoder {_num(f.get('lr_encoder'), '.2g')})" if f.get("regime") != "head" else "")
    ep = f.get("epochs")
    return (f"{_num(ep, 'g')} epoch{'' if ep == 1 else 's'}, {f.get('schedule')}, {lr}, batch {f.get('batch_size')}×{f.get('grad_accum')}, "
            f"{f.get('precision')} on {f.get('device')}: {f.get('steps')} steps in {_seconds(f.get('seconds'))}, "
            f"peak memory {_num(f.get('peak_memory_gb'), 'g')} GB, final loss {_num(f.get('final_loss'), '.3f')}")

def card_text(meta:dict, repo_id:str|None=None) -> str:
    "The model card's page, from an export's `sysone.json`"
    tr, enc, head = _training(meta), meta.get("encoder") or {}, meta.get("head") or {}
    data, model, hw = tr.get("data") or {}, tr.get("model") or {}, tr.get("hardware") or {}
    regime = head.get("regime")
    lines = [f"# {meta.get('name') or 'sysone model'}", "",
             f"A typed-decision model made with [sysone](https://github.com/sgaseretto/sysonelib): the encoder `{enc.get('id')}` "
             f"({REGIME_TAGS.get(regime, regime)}) under a {head.get('layers')}-layer `{head.get('scorer')}` head, trained on "
             f"{source_text(data.get('source'))}.", "",
             "## Use it", "", "```python", "from sysone.inference import Decider", "",
             f'dec = Decider.load("{repo_id or "<this repo>"}")', "dec.predict(state, questions)   # answers in the Jev schema", "```"]
    if enc.get("weights") == "laya": lines += ["", "Laya's runtime loads it as well: the folder holds `rl_agent_config.json` and a single `model.safetensors`."]
    m = card_metrics(meta)
    if m:
        n = (meta.get("metrics") or {}).get("n")
        lines += ["", "## Results", "", f"On the validation split{f' ({n} decisions)' if n else ''}:", "", "| metric | value |", "|---|---|"]
        lines += [f"| {k} | {v:.4g} |" for k, v in m.items()]
    if meta.get("temperature"): lines += ["", "Calibration temperatures: " + ", ".join(f"{k} {v:.3g}" for k, v in meta["temperature"].items()) + "."]
    if tr:
        t, lora = tr.get("training") or {}, model.get("lora")
        splits = ", ".join(f"{v['cases']} {k}" for k, v in (data.get("splits") or {}).items())
        acc, host, run = hw.get("accelerator") or {}, hw.get("host") or {}, hw.get("run") or {}
        rows = [("Data", f"{source_text(data.get('source'))}; {splits} cases"),
                ("Encoder", f"`{enc.get('id')}`, {REGIME_TAGS.get(regime, regime)}" + (f" (LoRA r={lora.get('r')}, α={lora.get('lora_alpha')}, on {_targets(lora.get('target_modules'))})" if lora else "")),
                ("Head", f"{head.get('layers')} layers, `{head.get('scorer')}` scorer, readout `{head.get('readout')}`"),
                ("Loss", f"`{t.get('loss')}`, preset `{t.get('preset')}`, seed {t.get('seed')}")]
        prev = tr.get("resumed_from")
        if prev:                    # trained further from an export (load_learner)
            pt = prev.get("training") or {}
            pf, prun = len((pt.get("training") or {}).get("fits") or []), (pt.get("hardware") or {}).get("run") or {}
            rows.append(("Continued from", f"`{prev.get('source') or prev.get('name')}`, after {pf} fit{'s' if pf != 1 else ''} on a "
                                           f"{prun.get('backend') or 'local'} run" + (f" (job `{prun['job']}`)" if prun.get("job") else "")))
        rows += [(f"Fit {i + 1}", fit_text(f)) for i, f in enumerate(t.get("fits") or [])]
        rows += [("Machine", f"{host.get('cpu')}, {host.get('cores')} cores, {host.get('memory_gb')} GB; accelerator {acc.get('kind')}"
                  + (f" ({', '.join(str(d) for d in acc.get('devices') or [])})" if acc.get("devices") and acc.get("kind") != "mps" else "")
                  + f"; a {run.get('backend')} run" + (f" (job `{run.get('job')}`)" if run.get("job") else ""))]
        lines += ["", "## Training", "", "| | |", "|---|---|"] + [f"| {k} | {v} |" for k, v in rows]
        code, env = tr.get("code") or {}, tr.get("environment") or {}
        entry = code.get("entry") or {}
        lines += ["", "## Reproduce", ""]
        for label, g in (("Code", code.get("git") or {}), ("sysone", code.get("sysone_git") or {})):     # sysone's checkout, when it is another
            if g.get("commit"):
                lines.append(f"- {label}: `{g.get('repo')}` at commit {_short(g.get('commit'), 10)} ({g.get('branch')})"
                             + (f", with uncommitted changes in {g.get('n_changed')} files (diff SHA-256 {_short(g.get('diff_sha256'), 12)})" if g.get("dirty") else ""))
        if entry: lines.append(f"- Ran: `{entry.get('name')}`")
        pk = env.get("packages") or {}
        lines.append(f"- Python {env.get('python')}, " + ", ".join(f"{k} {v}" for k, v in pk.items()) + "; `environment.txt` lists every package")
        trk = (tr.get("tracking") or {}).get("mlflow")
        if trk: lines.append(f"- MLflow run `{trk.get('run_id')}` ({trk.get('tracking_uri')})")
    return "\n".join(lines) + "\n"

def model_card(path, repo_id:str|None=None, license:str|None=None, tags:list|None=None) -> ModelCard:
    "The Hub model card of an export: metadata from `card_data`, page from `card_text`"
    meta = read_meta(path)
    return ModelCard(f"---\n{card_data(meta, license, tags).to_yaml()}\n---\n\n{card_text(meta, repo_id)}")

# %% ../nbs/42_hub.ipynb #549b80ed
def commit_summary(meta:dict) -> str:
    "A one-line commit message: the model, its encoder and regime, its main metric and the code commit"
    enc, regime = (meta.get("encoder") or {}).get("id") or "encoder", (meta.get("head") or {}).get("regime")
    m = card_metrics(meta)
    main = next((f"{k} {m[k]:.3f}" for k in ("macro_f1", "accuracy") if k in m), None)
    c = _training(meta).get("code") or {}
    g = c.get("git") or c.get("sysone_git") or {}       # a job's entry may sit outside any repository
    code = f"code {g['commit'][:7]}{'+' if g.get('dirty') else ''}" if g.get("commit") else None
    return " · ".join(x for x in (f"{meta.get('name')}: {str(enc).split('/')[-1]} {REGIME_TAGS.get(regime, regime)}", main, code) if x)

def push_to_hub(path, repo_id:str, private:bool=True, card:bool=True, license:str|None=None, tags:list|None=None,
                commit_message:str|None=None, revision:str|None=None, tag:str|None=None, token=None, dry_run:bool=False) -> dict:
    "Upload an export folder to a Hub model repo, private by default, with a model card written from its sysone.json"
    path = Path(path); meta = read_meta(path)
    text = str(model_card(path, repo_id, license, tags)) if card else None
    files = sorted(str(p.relative_to(path)) for p in path.rglob("*") if p.is_file())
    plan = {"repo": repo_id, "private": private, "revision": revision or "main", "tag": tag,
            "message": commit_message or commit_summary(meta), "files": sorted(set(files) | ({"README.md"} if card else set()))}
    if dry_run: return plan | {"card": text}
    if card: (path / "README.md").write_text(text)
    api = HfApi(token=token)
    api.create_repo(repo_id, private=private, exist_ok=True)
    if revision not in (None, "main"): api.create_branch(repo_id, branch=revision, exist_ok=True)
    info = api.upload_folder(repo_id=repo_id, folder_path=path, commit_message=plan["message"], revision=revision)
    if tag: api.create_tag(repo_id, tag=tag, revision=info.oid)
    return plan | {"commit": info.oid, "url": info.commit_url}

@patch
def push_to_hub(self:Learner, repo_id:str, path=None, **kw) -> dict:
    "Export the learner (to a temporary folder named after the repo, unless `path` is given) and push the export to the Hub"
    path = self.export(Path(path) if path else Path(tempfile.mkdtemp()) / repo_id.split("/")[-1])
    return push_to_hub(path, repo_id, **kw)

# %% ../nbs/42_hub.ipynb #b4644c7d
def push_data(path, repo_id:str, private:bool=True, commit_message:str|None=None, token=None, dry_run:bool=False) -> dict:
    "Upload a file or a folder to a Hub dataset repo, private by default"
    path = Path(path)
    if not path.exists(): raise FileNotFoundError(path)
    files = sorted(str(p.relative_to(path)) for p in path.rglob("*") if p.is_file()) if path.is_dir() else [path.name]
    plan = {"repo": repo_id, "private": private, "files": files, "message": commit_message or f"sysone data: {path.name}"}
    if dry_run: return plan
    api = HfApi(token=token)
    api.create_repo(repo_id, repo_type="dataset", private=private, exist_ok=True)
    if path.is_dir(): info = api.upload_folder(repo_id=repo_id, repo_type="dataset", folder_path=path, commit_message=plan["message"])
    else: info = api.upload_file(path_or_fileobj=str(path), path_in_repo=path.name, repo_id=repo_id, repo_type="dataset",
                                 commit_message=plan["message"])
    return plan | {"commit": info.oid, "url": info.commit_url}

def pull_data(repo_id:str, revision:str|None=None, dest=None, token=None) -> Path:
    "Download a Hub dataset repo (at `revision`) and return its folder"
    return Path(snapshot_download(repo_id, repo_type="dataset", revision=revision, local_dir=dest, token=token))
