"""`Decider`: typed answers in the Jev schema from a trained model, in memory or loaded from an export folder that Laya's runtimes can read too.

Docs: https://sgaseretto.github.io/sysonelib/inference.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_inference.ipynb.

# %% auto #0
__all__ = ['DECIDER_BACKENDS', 'default_device', 'Decider', 'export_learner', 'PositionScores', 'export_onnx', 'OnnxDecider',
           'serve_app']

# %% ../nbs/06_inference.ipynb #bb48184b
import copy, json, math, os, shutil, time, warnings
from pathlib import Path

import numpy as np
import torch
from fastcore.basics import patch, store_attr
from transformers import AutoConfig, AutoModel, AutoTokenizer

import sysone
from .core import *
from .template import *
from .models import *
from .learner import Learner

# %% ../nbs/06_inference.ipynb #de81cc45
def default_device() -> torch.device:
    "CUDA, then MPS, then CPU"
    if torch.cuda.is_available(): return torch.device("cuda")
    if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available(): return torch.device("mps")
    return torch.device("cpu")

class Decider:
    "Typed answers from a decision model and the row builder it was trained with"
    def __init__(self,
                 model:EncoderDecisionModel, # encoder and head
                 builder:RowBuilder, # the template and transforms of training
                 temperatures:dict|None=None, # per type and option-count bucket
                 device=None, # where to run; the model stays where it is by default (`Decider.load` picks CUDA, MPS, CPU)
                 dtype=None, # autocast dtype; fp16 on CUDA, none (fp32) elsewhere
                 batch_size:int=64, # rows per forward pass
                 digits:int|None=4, # rounding of reported numbers, as Laya rounds
                 name:str="sysone", # the model name reported by the HTTP API
                 chunk:int|None=None, # score choices wider than this coarse to fine, in chunks of at most `chunk` options
                 meta:dict|None=None, # the export's sysone.json, when loaded from one
                 act_threshold:float|dict|None=None, # act where the act score ≥ this, per type and bucket (fitted by `learn.calibrate`)
                 act_score:str="head"): # the act score: the act head's p(act) ('head') or the calibrated top probability ('confidence')
        store_attr(but="model,device")
        self.device = torch.device(device) if device is not None else next(model.parameters()).device
        self.model = model.to(self.device).eval()
        if self.dtype is None and self.device.type == "cuda": self.dtype = torch.float16
        self.temperatures = temperatures or {}

    def __repr__(self):
        return f"Decider({self.name} · {self.builder.template.name or 'custom'} template · {self.device} · {len(self.temperatures)} temperatures)"

# %% ../nbs/06_inference.ipynb #ae97a97e
@patch
def _rows(self:Decider, state, questions):
    rec = apply_tfms(self.builder.tfms, load_record({"state": state, "questions": questions}), train=False)
    return rec, self.builder.build_record(rec, tfms=False)

@patch
@torch.no_grad()
def _scores(self:Decider, rows) -> tuple:
    "(logits (rows, K), p(act) per row or None)"
    out, acts, pad = [], [], self.builder.tok.pad_token_id or 0
    for i in range(0, len(rows), self.batch_size):
        b = collate(rows[i:i + self.batch_size], pad).to(self.device)
        for k in ("target", "label", "answerable"): b.pop(k, None)
        ctx = torch.autocast(self.device.type, dtype=self.dtype) if self.dtype is not None else torch.autocast("cpu", enabled=False)
        with ctx: res = self.model(**b)
        z, a = res if isinstance(res, tuple) else (res, None)
        out.append(z.float().cpu().numpy())
        if a is not None: acts.append(act_probability(a).cpu().numpy())
    K = max(z.shape[1] for z in out)
    return np.concatenate([np.pad(z, ((0, 0), (0, K - z.shape[1])), constant_values=-1e4) for z in out]), np.concatenate(acts) if acts else None

@patch
def _logits(self:Decider, rows) -> np.ndarray: return self._scores(rows)[0]

@patch
def _softmax(self:Decider, q:Question, z) -> np.ndarray:
    z = z[:q.k].astype(np.float64) / lookup_temperature(self.temperatures, q.qtype, q.k)
    p = np.exp(z - z.max())
    return p / p.sum()

@patch
def _probs(self:Decider, state, questions:dict) -> tuple:
    "`{qid: (question, probabilities, options a shortlist dropped, p(act) or None)}` for one state, and its number of input tokens"
    return self._probs_record(apply_tfms(self.builder.tfms, load_record({"state": state, "questions": questions}, parse_state=False)))

@patch
def _probs_record(self:Decider, rec:dict) -> tuple:
    "`_probs` for a record whose transforms have run"
    rows = self.builder.build_record(rec, tfms=False)
    if not rows: return {}, 0
    z, act = self._scores(rows)
    qs, dropped = as_questions(rec["questions"]), rec.get("dropped") or {}
    out = {r.meta["qid"]: (qs[r.meta["qid"]], self._softmax(qs[r.meta["qid"]], z[i]), dropped.get(r.meta["qid"]),
                           float(act[i]) if act is not None else None) for i, r in enumerate(rows)}
    return out, sum(r.n_tokens for r in rows)

@patch
def _answer(self:Decider, q:Question, p, dropped=None, act=None) -> Answer:
    if self.act_score == "confidence" and self.act_threshold is not None: act = float(np.max(np.asarray(p, dtype=np.float64)[:q.k]))
    a = fill_answer(q, p, self.digits, act=act, act_threshold=self.act_threshold)
    if dropped:   # options a shortlist removed are reported with probability 0
        a["probabilities"] = {kk: a["probabilities"].get(kk, 0.0) for kk in list(a["probabilities"]) + list(dropped)}
        a["shortlisted"] = True
    return a

# %% ../nbs/06_inference.ipynb #af1b1a23
@patch
def answer(self:Decider, state, questions:dict) -> tuple:
    "Answers in the Jev schema for one state, and the number of input tokens they took"
    if not questions: return {}, 0
    rec = apply_tfms(self.builder.tfms, load_record({"state": state, "questions": questions}, parse_state=False))
    if self._wide(rec["questions"]): return self._answer_wide(rec)        # wide after the transforms have had their say
    probs, n = self._probs_record(rec)
    return {qid: self._answer(q, p, d, a) for qid, (q, p, d, a) in probs.items()}, n

@patch
def predict(self:Decider, state, questions:dict) -> dict:
    "Answers `{qid: answer}` in the Jev schema for one state"
    return self.answer(state, questions)[0]

@patch
def predict_batch(self:Decider, states:list, questions:dict) -> list:
    "Answers for many states, their rows sharing forward passes"
    if not states: return []
    if not questions: return [{} for _ in states]
    if self._wide(questions): return [self.predict(s, questions) for s in states]
    built = [self._rows(s, questions) for s in states]
    flat = [r for _, rows in built for r in rows]
    (z, act), out, i = self._scores(flat), [], 0
    for rec, rows in built:
        qs, dropped = as_questions(rec["questions"]), rec.get("dropped") or {}
        out.append({r.meta["qid"]: self._answer(qs[r.meta["qid"]], self._softmax(qs[r.meta["qid"]], z[i + j]), dropped.get(r.meta["qid"]),
                                                float(act[i + j]) if act is not None else None)
                    for j, r in enumerate(rows)})
        i += len(rows)
    return out

# %% ../nbs/06_inference.ipynb #b910f67e
@patch
def _wide(self:Decider, questions:dict) -> dict:
    "For each choice question with more options than `chunk`, its keys dealt into interleaved chunks"
    if not getattr(self, "chunk", None): return {}
    out = {}
    for qid, q in as_questions(questions).items():
        if q.type == "choice" and q.k > self.chunk:
            n = math.ceil(q.k / self.chunk)
            out[qid] = [q.keys[c::n] for c in range(n)]
    return out

@patch
def _answer_wide(self:Decider, rec:dict) -> tuple:
    "Answers for a transformed record with wide questions: a first pass over interleaved chunks, a second over the winners"
    questions = rec["questions"]
    wide, qs, dropped = self._wide(questions), as_questions(questions), rec.get("dropped") or {}
    sub = lambda q, keys: {**q.to_dict(), "criteria": {k: q.criteria[k] for k in keys}}
    first = {qid: questions[qid] for qid in qs if qid not in wide}
    first |= {f"{qid}#{c}": sub(qs[qid], ks) for qid, chunks in wide.items() for c, ks in enumerate(chunks)}
    p1, n1 = self._probs_record({**rec, "questions": first, "dropped": {}})
    top = lambda q, p: q.keys[int(np.argmax(p))]
    winners = {qid: [top(*p1[f"{qid}#{c}"][:2]) for c in range(len(chunks))] for qid, chunks in wide.items()}
    p2, n2 = self._probs_record({**rec, "questions": {qid: sub(qs[qid], ws) for qid, ws in winners.items()}, "dropped": {}})
    answers = {qid: self._answer(q, p, dropped.get(qid), a) for qid, (q, p, d, a) in p1.items() if qid in qs}
    for qid, chunks in wide.items():
        fq, fp, _, fa = p2[qid]
        final = dict(zip(fq.keys, fp))
        prob = {}
        for c in range(len(chunks)):
            cq, cp, _, _ = p1[f"{qid}#{c}"]
            prob |= {k: final[winners[qid][c]] * v for k, v in zip(cq.keys, cp)}
        answers[qid] = self._answer(qs[qid], np.array([prob[k] for k in qs[qid].keys]), dropped.get(qid), fa)
        answers[qid]["chunks"] = len(chunks)
    return {qid: answers[qid] for qid in qs}, n1 + n2

# %% ../nbs/06_inference.ipynb #5eb6f709
def _encoder_ref(model, spec) -> dict:
    enc = model.encoder.get_base_model() if hasattr(model.encoder, "get_base_model") else model.encoder
    ref = spec.to_json() if spec is not None else {"id": getattr(enc.config, "_name_or_path", None), "revision": None,
                                                   "source": "transformers", "hidden_size": model.head.width,
                                                   "family": enc.config.model_type, "modality": "text"}
    ref["dtype"] = str(next(enc.parameters()).dtype).removeprefix("torch.")
    return ref

def _laya_config(model, template, temperatures, name) -> dict:
    t = temperatures or {}
    return {"encoder": model.spec.id if model.spec is not None else "answerdotai/ModernBERT-large",
            "head_layers": model.head.layers, "max_len": template.max_len, "head_max_len": template.head_max_len,
            "temperature": [clamp_temperature(t.get(n, 1.0)) for n in ("choice", "score", "noul")],
            "temperature_by_options": {k: v for k, v in t.items() if ":" in k}, "model_name": name, "exported_by": "sysone"}

def export_learner(learn:Learner, path, merge:bool=True, bundle:bool|None=None, laya="auto", dtype=None, name:str|None=None) -> Path:
    "Write a learner's model, template, transforms and temperatures to `path` (what `learn.export` calls)"
    self = learn
    path, model, b = Path(path), self.model, self.data.builder
    path.mkdir(parents=True, exist_ok=True)
    spec, ref = model.spec, _encoder_ref(model, model.spec)
    trained_encoder = model.regime != "head" or getattr(model, "encoder_trained", False)   # trained, then frozen again
    local_encoder = ref["id"] is not None and Path(ref["id"]).exists()
    bundle = (trained_encoder or local_encoder) if bundle is None else bundle
    if trained_encoder and not bundle: raise ValueError("the encoder was trained, so its weights must be exported (bundle=True)")
    write_laya = laya is True or (laya == "auto" and bundle and merge and is_laya_compatible(model, b.template, b.tfms, b.tok))
    if laya is True and not is_laya_compatible(model, b.template, b.tfms, b.tok):
        raise ValueError("Laya's format needs Laya's template (and budgets), Laya's head and no inference transforms")
    # tokenizer or processor
    (b.processor or b.tok).save_pretrained(path / ("processor" if b.processor is not None else "tokenizer"))
    for name, s in b.streams.items(): s.tokenizer.save_pretrained(path / "streams" / name)
    # encoder
    enc_dir = path / "encoder"
    keep_adapter = not merge and hasattr(model.encoder, "peft_config")
    if write_laya:
        merged_encoder(model).config.save_pretrained(enc_dir); weights = "laya"
        from safetensors.torch import save_file
        save_file(laya_state_dict(model, self.temperatures, dtype=dtype), str(path / "model.safetensors"))
        (path / "rl_agent_config.json").write_text(json.dumps(_laya_config(model, b.template, self.temperatures, name or path.name), indent=2))
    elif keep_adapter:   # the base encoder's own weights, and the adapter beside them
        copy.deepcopy(model.encoder).unload().save_pretrained(enc_dir)
        model.encoder.save_pretrained(path / "adapter"); weights = "adapter"
    elif bundle:
        enc = merged_encoder(model)
        (copy.deepcopy(enc).to(dtype) if dtype is not None else enc).save_pretrained(enc_dir); weights = "encoder"
    else: weights = "hub"
    # head
    from safetensors.torch import save_file
    sd = {k: (v.to(dtype) if dtype is not None and v.is_floating_point() else v).detach().cpu().contiguous()
          for k, v in model.head.state_dict().items()}
    save_file(sd, str(path / "head.safetensors"))
    meta = {"sysone_version": sysone.__version__, "backend": "sysone", "name": name or path.name,
            "encoder": ref | {"weights": weights}, **b.to_json(),
            "head": model.head.config() | {"regime": model.regime},
            "temperature": self.temperatures, "act_threshold": getattr(self, "act_threshold", None),
            "act_score": getattr(self, "act_score", None), "question_types": list(QTYPES),
            "metrics": self.recorder.metrics[-1] if self.recorder.metrics else None}
    (path / "sysone.json").write_text(json.dumps(meta, indent=2, default=str))
    return path

# %% ../nbs/06_inference.ipynb #3233a8b1
def _load_sysone(path:Path, device=None, **kw) -> Decider:
    meta = json.loads((path / "sysone.json").read_text())
    ref, weights = meta["encoder"], meta["encoder"].get("weights", "hub")
    dt = getattr(torch, ref.get("dtype") or "float32")          # the dtype the head was trained against
    if (path / "processor").exists():
        from transformers import AutoProcessor
        tok = AutoProcessor.from_pretrained(path / "processor")
    else: tok = AutoTokenizer.from_pretrained(path / "tokenizer")
    stream_toks = {p.name: AutoTokenizer.from_pretrained(p) for p in sorted((path / "streams").iterdir())} if (path / "streams").exists() else {}
    base = lambda d: load_stream_encoder(d, dt) if (d / "stream_encoder.json").exists() else AutoModel.from_pretrained(d, dtype=dt)
    if weights == "hub":
        if ref["id"] is None or (ref["id"].startswith(("/", ".")) and not Path(ref["id"]).exists()):
            raise FileNotFoundError(f"the export references encoder {ref['id']!r}, which is not available; export with bundle=True")
        if ref.get("source") in (None, "transformers"): enc = AutoModel.from_pretrained(ref["id"], revision=ref.get("revision"), dtype=dt)
        else: enc = EncoderSpec.from_pretrained(ref["id"], revision=ref.get("revision"), source=ref["source"]).load_encoder(dtype=dt)
    elif weights == "encoder": enc = base(path / "encoder")
    elif weights == "adapter":
        from peft import PeftModel
        enc = PeftModel.from_pretrained(base(path / "encoder"), path / "adapter")
    else:   # "laya": the encoder's tensors live in Laya's single weights file
        from safetensors.torch import load_file
        enc = AutoModel.from_config(AutoConfig.from_pretrained(path / "encoder"), dtype=dt)
        sd = {k[len("encoder."):]: v.to(dt) for k, v in load_file(str(path / "model.safetensors")).items() if k.startswith("encoder.")}
        enc.load_state_dict(sd, strict=False)
    h = meta["head"]
    head = DecisionHead.from_config(h)
    from safetensors.torch import load_file
    head.load_state_dict({k: v.float() for k, v in load_file(str(path / "head.safetensors")).items()})
    model = EncoderDecisionModel(enc, head)
    model.regime = h.get("regime", "full")
    builder = RowBuilder.from_json({"template": meta["template"], "tfms": meta.get("tfms", []), "streams": meta.get("streams")}, tok, stream_toks)
    return Decider(model, builder, meta.get("temperature") or {}, device=device, name=meta.get("name", "sysone"), meta=meta,
                   **({"act_threshold": meta.get("act_threshold"), "act_score": meta.get("act_score") or "head"} | kw))

def _load_laya(path:Path, device=None, **kw) -> Decider:
    model, tok, template, temps = load_laya(str(path))
    return Decider(model, RowBuilder(tok, template), temps, device=device, name="laya", **kw)

def _is_gliner(path:Path) -> bool:
    if (path / "sysone_gliner.json").exists(): return True
    cfg = path / "config.json"
    if not cfg.exists() or not (path / "encoder_config").exists(): return False
    c = json.loads(cfg.read_text())
    return c.get("model_type") == "extractor" or "architecture" in c

def _load_gliner(path:Path, device=None, **kw):
    from sysone.gliner import GlinerDecider
    return GlinerDecider.load(str(path), device=device, **kw)

DECIDER_BACKENDS = [("sysone", lambda p: (p / "sysone.json").exists(), _load_sysone),
                    ("laya", lambda p: (p / "rl_agent_config.json").exists(), _load_laya),
                    ("gliner2", _is_gliner, _load_gliner)]

def _local(path, subfolder=None, revision=None) -> Path:
    p = Path(path).expanduser()
    if p.exists(): return p / (subfolder or "")
    if str(path).startswith(("/", "./", "../", "~")): raise FileNotFoundError(f"no such folder: {path}")
    from huggingface_hub import snapshot_download
    pre = f"{subfolder}/" if subfolder else ""
    return Path(snapshot_download(str(path), revision=revision, allow_patterns=[pre + x for x in
        ("*.json", "*.safetensors", "tokenizer/*", "processor/*", "encoder/*", "encoder_config/*", "adapter/*", "*.txt", "*.model")])) / (subfolder or "")

@patch(cls_method=True)
def load(cls:Decider, path, device=None, subfolder:str|None=None, revision:str|None=None, **kw):
    "The decider stored at `path` (a folder, a Hub repo, or `owner/repo/subfolder`): sysone, Laya or GLiNER2"
    if subfolder is None: path, subfolder = split_repo(str(path))
    p = _local(path, subfolder, revision)
    device = device if device is not None else default_device()
    for name, detect, load in DECIDER_BACKENDS:
        if detect(p): return load(p, device=device, **kw)
    raise ValueError(f"{path}: neither a sysone export (sysone.json), a Laya checkpoint (rl_agent_config.json) nor a GLiNER2 checkpoint")

# %% ../nbs/06_inference.ipynb #e33ca674
class PositionScores(torch.nn.Module):
    "The encoder and the head as one module that scores every position: the graph `export_onnx` writes"
    def __init__(self, model:EncoderDecisionModel): super().__init__(); self.m = model
    def forward(self, input_ids, attention_mask, qtype):
        head = self.m.head
        h = head._standardized(self.m.encode(input_ids, attention_mask).to(head.type_emb.weight.dtype)) + head.type_emb(qtype)[:, None, :]
        pad = ~attention_mask.bool()
        for blk in head.blocks: h = blk(h, src_key_padding_mask=pad)
        return head.scorer(h).squeeze(-1).float()

def export_onnx(learn:Learner, path, **kw) -> Path:
    "An export (see `export_learner`) with the model as `model.onnx` beside it"
    b, hd = learn.data.builder, learn.model.head
    if b.processor is not None or b.streams: raise ValueError("ONNX export covers text models; multimodal and side-stream ones run through PyTorch")
    if hd.act or hd.query is not None or hd.readout != "anchor":
        raise ValueError("ONNX export covers heads that score each anchor on its own; an act head, a query or a span readout runs through PyTorch")
    path = export_learner(learn, path, **kw)
    m = EncoderDecisionModel(copy.deepcopy(merged_encoder(learn.model)).cpu().float(), copy.deepcopy(learn.model.head).cpu().float()).eval()
    row = b.build("an example state", {"type": "choice", "instructions": "an example question", "criteria": ["a", "b", "c"]})
    x = collate([row, row], b.tok.pad_token_id or 0)
    B, L = torch.export.Dim("batch"), torch.export.Dim("length")
    shapes = {"input_ids": {0: B, 1: L}, "attention_mask": {0: B, 1: L}, "qtype": {0: B}}
    with warnings.catch_warnings():   # torch names a shared axis once, and warns for every other input that has it
        warnings.filterwarnings("ignore", message="# The axis name")
        torch.onnx.export(PositionScores(m).eval(), (x["input_ids"], x["attention_mask"], x["qtype"]), str(path / "model.onnx"),
                          input_names=["input_ids", "attention_mask", "qtype"], output_names=["scores"], dynamic_shapes=shapes,
                          dynamo=True, verbose=False)
    meta = json.loads((path / "sysone.json").read_text()); meta["onnx"] = "model.onnx"
    (path / "sysone.json").write_text(json.dumps(meta, indent=2, default=str))
    return path

class OnnxDecider(Decider):
    "A `Decider` whose logits come from an exported ONNX graph run by onnxruntime"
    def __init__(self, session, builder:RowBuilder, temperatures:dict|None=None, batch_size:int=64, digits:int|None=4,
                 name:str="sysone", chunk:int|None=None, meta:dict|None=None):
        self.session, self.builder, self.temperatures = session, builder, dict(temperatures or {})
        self.batch_size, self.digits, self.name, self.chunk, self.meta = batch_size, digits, name, chunk, meta
        self.act_threshold, self.act_score = None, "head"
        self.model, self.device, self.dtype = None, torch.device("cpu"), None
    def __repr__(self): return f"OnnxDecider({self.name} · onnxruntime · {len(self.temperatures)} temperatures)"

    def _scores(self, rows) -> tuple: return self._logits(rows), None
    def _logits(self, rows) -> np.ndarray:
        out, pad = [], self.builder.tok.pad_token_id or 0
        for i in range(0, len(rows), self.batch_size):
            b = collate(rows[i:i + self.batch_size], pad)
            s = self.session.run(None, {k: b[k].numpy() for k in ("input_ids", "attention_mask", "qtype")})[0]
            out.append(np.where(b["marker_mask"].numpy(), np.take_along_axis(s, b["marker_pos"].numpy(), 1), -1e4))
        K = max(z.shape[1] for z in out)
        return np.concatenate([np.pad(z, ((0, 0), (0, K - z.shape[1])), constant_values=-1e4) for z in out])

    @classmethod
    def load(cls, path, providers=None, **kw):
        "The ONNX decider of an `export_onnx` folder"
        import onnxruntime as ort
        path = Path(path); meta = json.loads((path / "sysone.json").read_text())
        builder = RowBuilder.from_json({"template": meta["template"], "tfms": meta.get("tfms", [])}, AutoTokenizer.from_pretrained(path / "tokenizer"))
        sess = ort.InferenceSession(str(path / meta.get("onnx", "model.onnx")), providers=providers or ["CPUExecutionProvider"])
        return cls(sess, builder, meta.get("temperature"), name=meta.get("name", "sysone"), meta=meta, **kw)

# %% ../nbs/06_inference.ipynb #f12cb79b
def _server_paths(state):
    "Image values of a state that are not inline data URLs"
    if not isinstance(state, dict): return []
    return [v for k, v in state.items() if k in ("image", "images") for v in (v if isinstance(v, list) else [v])
            if isinstance(v, str) and not v.startswith("data:image/")]

def serve_app(decider:Decider, max_questions:int=64, allow_image_paths:bool=False):
    "A FastAPI app answering `POST /v1/systemone` and `GET /health` with `decider`"
    from fastapi import FastAPI, HTTPException, Request
    app = FastAPI(title=f"sysone · {decider.name}")

    @app.get("/health")
    def health(): return {"status": "ok", "model": decider.name, "device": str(decider.device)}

    @app.post("/v1/systemone")
    async def systemone(request: Request):
        try: body = await request.json()
        except Exception: raise HTTPException(400, "request body must be valid JSON")
        if not isinstance(body, dict) or not isinstance(body.get("questions"), dict):
            raise HTTPException(400, "request body must be an object with a 'questions' object")
        if len(body["questions"]) > max_questions: raise HTTPException(413, f"too many questions ({len(body['questions'])} > {max_questions})")
        if body.get("state") is None: raise HTTPException(400, "'state' is required")
        if not allow_image_paths and _server_paths(body["state"]):
            raise HTTPException(422, "send images inline as data URLs (data:image/png;base64,...); server paths are not read")
        try: answers, n = decider.answer(body["state"], body["questions"])
        except (ValueError, KeyError, TypeError, OSError) as e:   # the request's content: a question, a field, an image
            raise HTTPException(422, f"{type(e).__name__}: {e}")
        return {"model": decider.name, "answers": answers, "usage": {"input_tokens": n, "output_tokens": 0}}
    return app
