"""fastai's `Interpretation` for typed decisions (the worst cases, confusion, calibration and coverage), and attributions in the style of transformers-interpret: how much each token, pixel and residue moved each option's probability, by integrated gradients through a sysone model or by occlusion through any backend.

Docs: https://sgaseretto.github.io/sysonelib/interpret.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09a_interpret.ipynb.

# %% auto #0
__all__ = ['Interpretation', 'record_view', 'token_texts', 'special_ids', 'row_segments', 'input_embeddings', 'stream_embeddings',
           'gauss_legendre', 'gradients_through', 'TokenPart', 'ImagePart', 'SequencePart', 'black_row', 'log_odds',
           'attribute', 'Attribution', 'attribution_html', 'part_figure', 'occlusion', 'attribution_path']

# %% ../nbs/09a_interpret.ipynb #8fde562a
import base64, html, io, json, math, re, textwrap
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
from fastcore.basics import patch

from .core import *
from .template import *
from .models import StreamEncoder, SideEncoder
from .losses import coverage_curve, ece_score, row_thresholds
from .metrics import *
from .learner import Learner
from .inference import Decider

# %% ../nbs/09a_interpret.ipynb #66c08a5d
class Interpretation:
    "fastai's `Interpretation` for typed decisions: a split's decisions (or a backend's answers to records) beside their gold, with the records they came from"
    def __init__(self, preds:Preds, records:dict, decider=None, builder=None, act_threshold=None, act_score=None):
        self.preds, self.records, self.decider, self.builder = preds, records, decider, builder
        self.act_threshold, self.act_score = act_threshold, act_score

    def __repr__(self): return f"Interpretation({self.preds!r} · {len(self.records)} records)"

    @classmethod
    def from_learner(cls, learn:Learner, split:str="valid"):
        "The decisions of a learner's split, read through `get_preds` (from its feature cache, when it has one)"
        p = learn.get_preds(split)
        cases = learn.data.cases[split]
        recs = {int(i): load_record(cases[int(i)]) for i in sorted(set(p.case_idx.tolist()))}
        return cls(p, recs, decider=learn.decider(), builder=learn.data.builder, act_threshold=learn.act_threshold, act_score=learn.act_score)

    @classmethod
    def from_decider(cls, decider, records, batch_size:int=16):
        "The decisions any backend (anything with `predict`) makes on records with gold"
        recs = [load_record(r) for r in records]
        answers = _answer_all(decider, recs, batch_size)
        return cls(Preds.from_answers(recs, answers), dict(enumerate(recs)), decider=decider, builder=getattr(decider, "builder", None),
                   act_threshold=getattr(decider, "act_threshold", None), act_score=getattr(decider, "act_score", None))

def _answer_all(model, recs, batch_size):
    "Every record's answers: batched when the backend can and every record asks the same questions"
    same = len({json.dumps(r["questions"], sort_keys=True) for r in recs}) == 1
    if same and hasattr(model, "predict_batch"): return _predict_many(model, [r["state"] for r in recs], recs[0]["questions"], batch_size)
    return [model.predict(r["state"], r["questions"]) for r in recs]

def _predict_many(model, states, questions, batch_size):
    if not hasattr(model, "predict_batch"): return [model.predict(s, questions) for s in states]
    out = []
    for i in range(0, len(states), batch_size): out += model.predict_batch(states[i:i + batch_size], questions)
    return out

# %% ../nbs/09a_interpret.ipynb #db68f4ad
@patch(as_prop=True)
def losses(self:Interpretation) -> np.ndarray:
    "Each decision's cross-entropy against its gold (NaN where none of its options is right)"
    p = self.preds
    return np.where(p.ok, -(p.targets * np.log(np.clip(p.probs, 1e-12, 1))).sum(1), np.nan)

@patch
def top_losses(self:Interpretation, k:int|None=None, largest:bool=True, items:bool=False) -> tuple:
    "The `k` largest (or smallest) losses and their rows, and with `items` each row's record and question id"
    l = self.losses; idx = np.flatnonzero(~np.isnan(l))
    idx = idx[np.argsort(-l[idx] if largest else l[idx], kind="stable")][:k]
    return (l[idx], idx) + ((self.items(idx),) if items else ())

@patch
def items(self:Interpretation, idxs) -> list:
    "The record and the question id of each row"
    return [(self.records[int(self.preds.case_idx[i])], str(self.preds.qids[i])) for i in idxs]

# %% ../nbs/09a_interpret.ipynb #42613e2f
_INK, _GRAY, _BLUE, _LIGHT, _TRACK, _CARD = "#111111", "#6b6b6b", "#3b3ff5", "#9a9df7", "#d9d9de", "#f4f4f6"
_GREEN, _RED = (22, 163, 74), (220, 38, 38)

def _image_like(v) -> bool:
    "Whether a state value is an image: a PIL image, or a path to an image file"
    return hasattr(v, "convert") or (isinstance(v, (str, Path)) and re.search(r"\.(png|jpe?g|webp|bmp|gif)$", str(v), re.I) is not None)

def record_view(record:dict, builder=None) -> tuple:
    "How to show a record's input: ('image', a PIL image), ('sequence', its letters) or ('text', the state as text)"
    st = record["state"]
    if isinstance(st, str) and st[:1] in "{[":
        try: st = json.loads(st)
        except json.JSONDecodeError: pass
    for t in (builder.tfms if builder is not None else []):
        if isinstance(st, dict) and isinstance(t, Image) and st.get(t.key) is not None: return "image", load_image(st[t.key])
        if isinstance(st, dict) and isinstance(t, Stream) and st.get(t.key) is not None: return "sequence", str(st[t.key])
    if isinstance(st, dict):
        for v in st.values():
            if _image_like(v): return "image", load_image(v)
        if isinstance(st.get("sequence"), str): return "sequence", st["sequence"]
    return "text", render_state(st)

def _draw_view(ax, view, width:int=31, lines:int=12, size:float=7.5):
    "An input in a card's panel: an image, a protein's first residues, or wrapped text"
    kind, v = view
    ax.axis("off")
    if kind == "image":
        a = np.asarray(v); ax.imshow(a, interpolation="nearest" if max(a.shape[:2]) < 96 else "antialiased")
    else:
        wrapped = [v[i:i + 30] for i in range(0, len(v), 30)] if kind == "sequence" else textwrap.wrap(v, width)
        more = f"… {len(v)} residues" if kind == "sequence" else "…"
        text = "\n".join(wrapped[:lines] + ([more] if len(wrapped) > lines else [f"{len(v)} residues"] if kind == "sequence" else []))
        ax.text(0, 1, text, va="top", ha="left", fontsize=size, family="monospace" if kind == "sequence" else None,
                transform=ax.transAxes, clip_on=True)

def _bars(ax, keys, probs, gold, pred, top:int=4):
    "The likeliest options as bars, the answer dark, the gold ticked (shown even when it is not among them)"
    from matplotlib.patches import Rectangle
    order = list(np.argsort(-probs))[:top]
    if gold >= 0 and gold not in order: order[-1] = gold
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
    for i, o in enumerate(order):
        y = 1 - (i + 1) / (top + 0.3)
        ax.add_patch(Rectangle((0, y), 1, 0.08, color=_TRACK, lw=0))
        ax.add_patch(Rectangle((0, y), max(float(probs[o]), 0.004), 0.08, color=_BLUE if o == pred else _LIGHT, lw=0))
        ax.text(0, y + 0.1, f"{'✓' if o == gold else '✕'} {keys[o]}  {probs[o]:.0%}", fontsize=8, va="bottom",
                color=_INK if o in (gold, pred) else _GRAY, weight="bold" if o == gold else "normal")

@patch
def show_results(self:Interpretation, idxs, ncols:int=3):
    "Cards for some decisions: the input, the question, and the likeliest options beside the gold"
    import matplotlib.pyplot as plt
    idxs, p = list(idxs), self.preds
    nrows = max(1, -(-len(idxs) // ncols))
    fig = plt.figure(figsize=(4.4 * ncols, 2.5 * nrows))
    sfs = np.atleast_1d(fig.subfigures(nrows, ncols, wspace=0.03, hspace=0.06)).ravel()
    for sf, i in zip(sfs, idxs):
        (rec, qid), = self.items([i])
        keys, k = p.option_keys[i], int(p.k[i])
        q, loss, gold, pred = as_questions(rec["questions"])[qid], self.losses[i], int(p.labels[i]), int(p.pred[i])
        sf.set_facecolor(_CARD)
        sf.text(0.03, 0.95, f"{qid}: {textwrap.shorten(q.instructions, 62)}", fontsize=8, color=_GRAY, va="top")
        sf.text(0.03, 0.86, f"gold {keys[gold] if gold >= 0 else '(none of these)'} · answer {keys[pred]}" + ("" if np.isnan(loss) else f" · loss {loss:.2f}"),
                fontsize=9, weight="bold", color=_INK, va="top")
        _draw_view(sf.add_axes([0.03, 0.04, 0.42, 0.7]), record_view(rec, self.builder))
        _bars(sf.add_axes([0.5, 0.04, 0.47, 0.7]), keys, p.probs[i, :k], gold, pred)
    for sf in sfs[len(idxs):]: sf.set_facecolor("white")
    plt.close(fig)
    return fig

@patch
def plot_top_losses(self:Interpretation, k:int=6, largest:bool=True, ncols:int=3):
    "Cards for the `k` decisions with the largest (or smallest) losses"
    return self.show_results(self.top_losses(k, largest)[1], ncols)

# %% ../nbs/09a_interpret.ipynb #237de0e1
@patch
def _question(self:Interpretation, qid=None) -> tuple:
    "A question's id, its answerable rows, and every option key its rows offer, in the order they first appear"
    p = self.preds; qids = sorted(set(p.qids.tolist()))
    if qid is None:
        if len(qids) != 1: raise ValueError(f"the decisions come from {len(qids)} questions; name one with qid= ({qids[:8]})")
        qid = qids[0]
    if qid not in qids: raise ValueError(f"no decisions on question {qid!r}; the split has {qids[:8]}")
    rows = np.flatnonzero((p.qids == qid) & p.ok)
    keys = list(dict.fromkeys(k for i in rows for k in p.option_keys[i]))
    return qid, rows, keys

@patch
def confusion_matrix(self:Interpretation, qid=None, normalize:bool=False):
    "Gold labels (rows) against answers (columns) for one question, as counts or, normalised, as shares of each gold label"
    import pandas as pd
    qid, rows, keys = self._question(qid)
    p, M = self.preds, np.zeros((len(keys), len(keys)))
    for i in rows: M[keys.index(p.option_keys[i][p.labels[i]]), keys.index(p.option_keys[i][p.pred[i]])] += 1
    if normalize: M = M / np.clip(M.sum(1, keepdims=True), 1, None)
    return pd.DataFrame(M if normalize else M.astype(int), index=pd.Index(keys, name="gold"), columns=pd.Index(keys, name="answer"))

@patch
def plot_confusion_matrix(self:Interpretation, qid=None, normalize:bool=False, title:str|None=None, cmap:str="Blues", norm_dec:int=2,
                          plot_txt:bool=True):
    "One question's confusion matrix, drawn"
    import matplotlib.pyplot as plt
    cm = self.confusion_matrix(qid, normalize); M, keys = cm.values, list(cm.index)
    fig, ax = plt.subplots(figsize=(1.2 + 0.55 * len(keys), 1.0 + 0.5 * len(keys)))
    ax.imshow(M, cmap=cmap, vmin=0, vmax=M.max() if M.max() > 0 else 1)
    if plot_txt:
        for (r, c), v in np.ndenumerate(M):
            if v: ax.text(c, r, f"{v:.{norm_dec}f}" if normalize else int(v), ha="center", va="center", fontsize=8, color="white" if v > M.max() / 2 else _INK)
    ax.set_xticks(range(len(keys)), keys, rotation=45, ha="right", fontsize=8); ax.set_yticks(range(len(keys)), keys, fontsize=8)
    ax.set_xlabel("answer"); ax.set_ylabel("gold")
    counts = self.confusion_matrix(qid)
    ax.set_title(title or f"{self._question(qid)[0]}: accuracy {np.trace(counts.values) / max(counts.values.sum(), 1):.2f}" + (" (each gold label's shares)" if normalize else ""))
    for s in ("top", "right"): ax.spines[s].set_visible(True)
    fig.tight_layout(); plt.close(fig)
    return fig

@patch
def most_confused(self:Interpretation, qid=None, min_val:int=1) -> list:
    "The off-diagonal cells of one question's confusion matrix, largest first, as (gold, answer, count)"
    cm = self.confusion_matrix(qid)
    out = [(g, a, int(cm.loc[g, a])) for g in cm.index for a in cm.columns if g != a and cm.loc[g, a] >= min_val]
    return sorted(out, key=lambda x: -x[2])

@patch
def classification_report(self:Interpretation, qid=None):
    "Precision, recall, F1 and support of each of a question's options, then their macro and support-weighted averages"
    import pandas as pd
    cm = self.confusion_matrix(qid); C = cm.values.astype(float)
    tp, fp, fn, sup = np.diag(C), C.sum(0) - np.diag(C), C.sum(1) - np.diag(C), C.sum(1)
    pr, rc, f1 = tp / np.maximum(tp + fp, 1), tp / np.maximum(tp + fn, 1), 2 * tp / np.maximum(2 * tp + fp + fn, 1)
    df = pd.DataFrame({"precision": pr, "recall": rc, "f1": f1, "support": sup.astype(int)}, index=cm.index)
    has = sup > 0
    df.loc["macro avg"] = [pr[has].mean(), rc[has].mean(), f1[has].mean(), sup.sum()]
    df.loc["weighted avg"] = [(v * sup).sum() / max(sup.sum(), 1) for v in (pr, rc, f1)] + [sup.sum()]
    return df.astype({"support": int})

# %% ../nbs/09a_interpret.ipynb #c7509d64
@patch
def plot_calibration(self:Interpretation, bins:int=10, by:str|None=None):
    "A reliability diagram: how often answers are right against how sure they are, bin by bin, over the answers each bin holds (a panel per question type with `by='qtype'`)"
    import matplotlib.pyplot as plt
    p = self.preds
    groups = [("all questions", p.ok)] if by is None else [(QTYPE_NAMES[t], p.ok & (p.qtypes == t)) for t in sorted(set(p.qtypes[p.ok].tolist()))]
    fig, axs = plt.subplots(2, len(groups), figsize=(3.4 * len(groups), 3.6), squeeze=False, gridspec_kw={"height_ratios": [3, 1]}, sharex=True)
    edges = np.linspace(0, 1, bins + 1)
    for (name, m), ax, hx in zip(groups, axs[0], axs[1]):
        c, r = p.conf[m], p.correct[m].astype(float)
        b = np.clip(np.digitize(c, edges[1:-1]), 0, bins - 1)
        acc = np.array([r[b == i].mean() if (b == i).any() else np.nan for i in range(bins)])
        ax.bar(edges[:-1], acc, width=1 / bins, align="edge", color=_BLUE, alpha=0.8, edgecolor="white", label="share right")
        ax.plot([0, 1], [0, 1], "--", color=_GRAY, lw=1, label="calibrated")
        ax.set_title(f"{name}: ECE {ece_score(c, r, bins):.3f}"); ax.set_ylim(0, 1)
        hx.hist(c, bins=edges, color=_LIGHT); hx.set_xlabel("confidence (the answer's probability)")
    axs[0, 0].set_ylabel("share right"); axs[1, 0].set_ylabel("answers"); axs[0, 0].legend(loc="upper left")
    fig.tight_layout(); plt.close(fig)
    return fig

@patch
def plot_coverage(self:Interpretation, score:str|None=None):
    "Accuracy on the answers acted on, surest first, against the share acted on, with the act rule's point when there is one"
    import matplotlib.pyplot as plt
    p = self.preds
    score = score or ("act" if self.act_score == "head" and "act" in p else "confidence")
    s, cv = selection_scores(p, score), coverage_curve(selection_scores(p, score), p.right)
    fig, ax = plt.subplots(figsize=(5, 2.9))
    ax.plot(cv["coverage"], cv["accuracy"], color=_BLUE, lw=1.5, label=f"acting on the surest first ({score})")
    ax.axhline(p.right.mean(), color=_GRAY, ls="--", lw=1, label=f"acting on everything: {p.right.mean():.2f}")
    if self.act_threshold is not None and (score == "act") == (self.act_score == "head"):
        act = s >= row_thresholds(self.act_threshold, p.qtypes, p.k)
        ax.plot([act.mean()], [p.right[act].mean() if act.any() else np.nan], "o", color="C3", label=f"the act rule: acts on {act.mean():.0%}")
    ax.set(xlabel="coverage (share of decisions acted on)", ylabel="accuracy when acting", ylim=(0, 1.02))
    ax.legend(loc="lower left"); fig.tight_layout(); plt.close(fig)
    return fig

@patch
def metrics(self:Interpretation, metrics=None, by=None):
    "A table of metrics over every decision, and per group with `by`: 'qtype', 'qid', or a function of the record"
    if callable(by): by = [str(by(self.records[int(c)])) for c in self.preds.case_idx]
    return metrics_table(self.preds, metrics, by)

# %% ../nbs/09a_interpret.ipynb #1d681a28
def token_texts(tok, ids) -> list:
    "Each token as it reads in the decoded text: with the space before it, a word piece without its marker"
    out = []
    for i, t in enumerate(ids):
        if i == 0: out.append(tok.decode([t])); continue
        a, ab = tok.decode([ids[i - 1]]), tok.decode([ids[i - 1], t])
        out.append(ab[len(a):] if ab.startswith(a) else tok.decode([t]))
    return out

def _locate(seq:list, sub:list) -> tuple|None:
    "(start, end) of the longest stretch of `seq` equal to a prefix or a suffix of `sub` (a state cut on the right or on the left)"
    best, n = None, len(sub)
    if not n: return None
    for i, v in enumerate(seq):
        if v == sub[0]:
            j = 0
            while i + j < len(seq) and j < n and seq[i + j] == sub[j]: j += 1
            if best is None or j > best[1] - best[0]: best = (i, i + j)
        if v == sub[-1]:
            j = 0
            while i - j >= 0 and j < n and seq[i - j] == sub[n - 1 - j]: j += 1
            if best is None or j > best[1] - best[0]: best = (i - j + 1, i + 1)
    return best

def special_ids(builder:RowBuilder) -> set:
    "The ids a row's builder puts in itself: the tokenizer's special tokens, the template's, and an adapter's image tokens"
    tok, out = builder.tok, set(builder.tok.all_special_ids) | {v for v in builder.ids.values() if v is not None}
    for s in builder.extra_scrub:
        i = tok.convert_tokens_to_ids(s)
        if i is not None and i != tok.unk_token_id: out.add(i)
    return out

def row_segments(builder:RowBuilder, row:Row, record:dict) -> list:
    "What each position of a row holds: 'question', 'anchor i', 'option i', 'options' (between options), 'state' or 'special'"
    special = special_ids(builder)
    seg = ["special" if t in special else None for t in row.ids]
    spans = row.spans or [(m + 1, m + 1) for m in row.markers]
    for j, (m, (s, e)) in enumerate(zip(row.markers, spans)):
        seg[m] = f"anchor {j}"
        for i in range(s, min(e, row.n_tokens)):
            if seg[i] is None: seg[i] = f"option {j}"
    for i in range(min(row.markers), min(max(e for _, e in spans), row.n_tokens)):
        if seg[i] is None: seg[i] = "options"
    state = builder._encode([builder._scrub(render_state(record["state"]))])[0] if record.get("state") not in (None, "") else []
    at = _locate(list(row.ids), state)
    for i in range(*(at or (0, 0))):
        if seg[i] is None: seg[i] = "state"
    return [s or "question" for s in seg]

# %% ../nbs/09a_interpret.ipynb #7032b11a
def _base(enc): return enc.get_base_model() if hasattr(enc, "get_base_model") else enc

def input_embeddings(encoder) -> torch.nn.Module:
    "The module whose output is a row's token embeddings: what an attribution moves along its line for the tokens"
    enc = _base(encoder)
    return (enc.text if isinstance(enc, StreamEncoder) else enc).get_input_embeddings()

def stream_embeddings(encoder, name:str) -> torch.nn.Module:
    "The module whose output is a side stream's token embeddings"
    return _base(encoder).sides[name].model.get_input_embeddings()

def gauss_legendre(n:int) -> tuple:
    "The nodes and weights of the n-point Gauss–Legendre rule on [0, 1]"
    x, w = np.polynomial.legendre.leggauss(n)
    return (x + 1) / 2, w / 2

@contextmanager
def gradients_through(model):
    "While attributing: gradients reach a frozen encoder's inputs, dropout is off, and every side encoder encodes each row of a batch"
    frozen, was = model.frozen, model.training
    sides = [m for m in model.modules() if isinstance(m, SideEncoder)]
    model.frozen = False; model.eval()
    for s in sides: s.dedupe = False
    try: yield model
    finally:
        model.frozen = frozen; model.train(was)
        for s in sides: s.dedupe = True

# %% ../nbs/09a_interpret.ipynb #d2223dd3
@dataclass
class TokenPart:
    "A row's tokens (or a text's words), what each one is, and its attribution for every option explained (options × tokens)"
    texts:list; segments:list; scores:np.ndarray; name:str = "tokens"

@dataclass
class ImagePart:
    "An image as the encoder reads it (one array in [0, 1] per view), and each pixel's attribution for every option explained (per view: options × H × W)"
    images:list; scores:list; name:str = "pixels"

@dataclass
class SequencePart:
    "A side stream's units, such as a protein's residues, and each one's attribution for every option explained (options × units)"
    units:list; scores:np.ndarray; name:str = "stream"

def black_row(builder:RowBuilder, record:dict, row:Row) -> Row:
    "The same row with its image painted black, as the processor encodes it: the baseline of a pixel attribution"
    from PIL import Image as PILImage
    black = PILImage.new("RGB", record["images"][0].size, (0, 0, 0))
    qid = row.meta["qid"]
    return builder.build_record({**record, "questions": {qid: record["questions"][qid]}, "images": [black]}, tfms=False)[0]

class _Line:
    "One attributed input: a layer's output (tokens, a side stream) or a batch tensor (pixels), on the row (x1) and on its baseline (x0)"
    def __init__(self, name, x1, x0, module=None, key=None): self.name, self.x1, self.x0, self.module, self.key = name, x1, x0, module, key
    def at(self, a, grad:bool):
        "The points x0 + α (x1 − x0), one per α, as a batch; a batch tensor repeats its rows once per α"
        x0, x1 = self.x0, self.x1
        if self.module is None:
            reps = (len(a),) + (1,) * (x1.dim() - 1)
            x0, x1, a = x0.repeat(*reps), x1.repeat(*reps), a.repeat_interleave(self.x1.shape[0])
        return (x0 + a.view((-1,) + (1,) * (x1.dim() - 1)) * (x1 - x0)).detach().requires_grad_(grad)

def _lines(model, builder:RowBuilder, row:Row, record:dict, inputs, baseline) -> list:
    "The line of each input to attribute: 'tokens', 'pixels', 'stream:<name>'"
    dev, pad, special, out = model.device, builder.tok.pad_token_id or 0, special_ids(builder), []
    ref = {"pad": pad, "mask": builder.tok.mask_token_id, "unk": builder.tok.unk_token_id}.get(baseline, baseline)
    if ref is None or not isinstance(ref, (int, np.integer)): raise ValueError(f"baseline must be 'pad', 'mask', 'unk' or a token id, not {baseline!r}")
    for name in inputs:
        if name == "tokens":
            ids = torch.tensor(row.ids)
            keep = torch.tensor([t in special for t in row.ids]); keep[torch.tensor(row.markers)] = True
            lay = input_embeddings(model.encoder)
            with torch.no_grad(): x1, x0 = lay(ids[None].to(dev)).float(), lay(torch.where(keep, ids, int(ref))[None].to(dev)).float()
            out.append(_Line(name, x1, x0, module=lay))
        elif name.startswith("stream:"):
            s = name.removeprefix("stream:"); st = builder.streams[s].tokenizer
            ids = torch.tensor(row.extras[f"{s}_input_ids"])
            keep = torch.tensor([t in set(st.all_special_ids) for t in ids.tolist()])
            r = st.mask_token_id if st.mask_token_id is not None else (st.pad_token_id or 0)
            lay = stream_embeddings(model.encoder, s)
            with torch.no_grad(): x1, x0 = lay(ids[None].to(dev)).float(), lay(torch.where(keep, ids, r)[None].to(dev)).float()
            out.append(_Line(name, x1, x0, module=lay))
        elif name == "pixels":
            x1 = torch.as_tensor(row.extras["pixel_values"]).float().to(dev)
            x0 = torch.as_tensor(black_row(builder, record, row).extras["pixel_values"]).float().to(dev)
            if x0.shape != x1.shape: raise ValueError(f"the black image makes pixels {tuple(x0.shape)}, the image {tuple(x1.shape)}")
            out.append(_Line(name, x1, x0, key="pixel_values"))
        else: raise ValueError(f"unknown input {name!r}: use 'tokens', 'pixels' or 'stream:<name>'")
    return out

def _forward(model, row:Row, pad:int, lines:list, alphas, grad:bool, T:float, target:str) -> tuple:
    "The target (log-odds, log p, logit or p) of every option at the points `alphas` of every line, and the points, to take gradients against"
    a = torch.tensor(np.asarray(alphas), dtype=torch.float32, device=model.device)
    b = collate([row] * len(a), pad).to(model.device)
    for k in ("target", "label", "answerable"): b.pop(k, None)
    pts, hooks = [], []
    for ln in lines:
        t = ln.at(a, grad); pts.append(t)
        if ln.module is not None: hooks.append(ln.module.register_forward_hook(lambda m, i, o, t=t: t.to(o.dtype)))
        else: b[ln.key] = t.to(b[ln.key].dtype)
    try: out = model(**b)
    finally:
        for h in hooks: h.remove()
    z = ((out[0] if isinstance(out, tuple) else out).float() / T).masked_fill(~b["marker_mask"].bool(), -1e4)
    if target == "logodds": return log_odds(z), pts
    if target == "logprob": return torch.log_softmax(z, -1), pts
    if target == "logit": return z, pts
    if target == "prob": return torch.softmax(z, -1), pts
    raise ValueError(f"target must be 'logodds', 'logprob', 'logit' or 'prob', not {target!r}")

def log_odds(z):
    "Each option's log-odds against the others, log p / (1 − p): its logit less the log-sum-exp of the other logits (batch, K)"
    K = z.shape[-1]
    others = z.unsqueeze(-2).expand(*z.shape[:-1], K, K).masked_fill(torch.eye(K, dtype=torch.bool, device=z.device), float("-inf"))
    return z - torch.logsumexp(others, -1)

def _saved_bytes(model, fn) -> tuple:
    "fn()'s result, and the bytes of the tensors autograd saves for the backward pass while it runs, the model's weights left out"
    weights, seen, total = {p.data_ptr() for p in model.parameters()}, set(), 0
    def pack(t):
        nonlocal total
        key = (t.data_ptr(), t.numel())
        if t.data_ptr() not in weights and key not in seen: seen.add(key); total += t.numel() * t.element_size()
        return t
    with torch.autograd.graph.saved_tensors_hooks(pack, lambda t: t): out = fn()
    return out, total

def _default_options(probs, gold:int, top:int=3, every:int=6) -> list:
    "Every option up to `every`, else the `top` likeliest and the gold"
    order = [int(i) for i in np.argsort(-probs)]
    return order if len(order) <= every else order[:top] + ([gold] if gold >= 0 and gold not in order[:top] else [])

def _setup(model, builder:RowBuilder, state, questions:dict, qid, inputs, baseline, temperatures) -> tuple:
    "The transformed record, the question, its row, the line of each input, the temperature and the pad id"
    rec = apply_tfms(builder.tfms, load_record({"state": state, "questions": questions}, parse_state=False))
    qs = as_questions(rec["questions"])
    if qid is None:
        if len(qs) != 1: raise ValueError(f"the record asks {len(qs)} questions; name one with qid= ({list(qs)})")
        qid = next(iter(qs))
    q = qs[qid]
    rows = builder.build_record({**rec, "questions": {qid: rec["questions"][qid]}}, tfms=False)
    if not rows: raise ValueError(f"question {qid!r} does not fit the template's budgets")
    row = rows[0]
    if inputs is None:          # what makes up the state: its text, when it has any, its image and its side streams
        media = (["pixels"] if rec.get("images") and row.extras.get("pixel_values") is not None else []) + \
                [f"stream:{s}" for s in builder.streams if len(row.extras.get(f"{s}_input_ids") or [])]
        inputs = (["tokens"] if rec.get("state") not in (None, "", {}, []) or not media else []) + media
    return rec, q, row, _lines(model, builder, row, rec, inputs, baseline), lookup_temperature(temperatures, q.qtype, q.k), builder.tok.pad_token_id or 0

def attribute(model, builder:RowBuilder, state, questions:dict, qid=None, method:str="ig", options=None, target:str="logodds",
              inputs=None, n_steps:int=32, batch_size:int|None=None, baseline="pad", temperatures:dict|None=None, gold=None,
              memory:float=2.0):
    "How much every token (pixel, residue) moved each option's log-odds, for one question of one record: integrated gradients ('ig'), 'grad_x_input' or 'saliency'"
    if method not in ("ig", "grad_x_input", "saliency"):
        raise ValueError(f"method must be 'ig', 'grad_x_input' or 'saliency', not {method!r}; `occlusion` hides parts of the state instead")
    rec, q, row, lines, T, pad = _setup(model, builder, state, questions, qid, inputs, baseline, temperatures)
    g = q.target(gold)[1] if gold is not None else -1
    with gradients_through(model):
        with torch.no_grad():
            lp, _ = _forward(model, row, pad, lines, [0.0, 1.0], False, T, "logprob")
            probs = lp[1, :q.k].exp().cpu().numpy()
            options = _default_options(probs, g) if options is None else [q.keys.index(o) if o in q.keys else int(o) for o in options]
            fe, _ = _forward(model, row, pad, lines, [0.0, 1.0], False, T, target)
        f0, f1 = fe[0, options].cpu().numpy(), fe[1, options].cpu().numpy()
        alphas, weights = gauss_legendre(n_steps) if method == "ig" else (np.ones(1), np.ones(1))
        G = [torch.zeros((len(options),) + tuple(ln.x1.shape[1:] if ln.module is not None else ln.x1.shape), device=model.device) for ln in lines]
        def add(a, w, grads, j):
            for acc, gr, ln in zip(G, grads, lines):
                gr = gr.float()
                if ln.module is not None: acc[j] += (w.view(-1, *[1] * (gr.dim() - 1)) * gr).sum(0)
                else:
                    n = ln.x1.shape[0]
                    acc[j] += (w.repeat_interleave(n).view(-1, *[1] * (gr.dim() - 1)) * gr).view(len(a), n, *gr.shape[1:]).sum(0)
        s = 0
        while s < len(alphas):
            if batch_size is None:          # one step first, to measure what a step holds for the backward pass
                (ft, pts), per = _saved_bytes(model, lambda: _forward(model, row, pad, lines, alphas[:1], True, T, target))
                bs = int(max(1, min(32, memory * 2 ** 30 // max(per, 1))))
                a = alphas[:1]
            else:
                bs = batch_size; a = alphas[s:s + bs]
                ft, pts = _forward(model, row, pad, lines, a, True, T, target)
            w = torch.tensor(weights[s:s + len(a)], dtype=torch.float32, device=model.device)
            for j, o in enumerate(options): add(a, w, torch.autograd.grad(ft[:, o].sum(), pts, retain_graph=j < len(options) - 1), j)
            s += len(a)
            if batch_size is None: batch_size = bs
    if model.device.type == "mps": torch.mps.empty_cache()       # hand back what the steps cached, before the next attribution
    parts, total = {}, np.zeros(len(options))
    for ln, acc in zip(lines, G):
        d = ln.x1[0] - ln.x0[0] if ln.module is not None else ln.x1 - ln.x0
        if method == "saliency": v = acc.norm(dim=-1) if ln.module is not None else acc.abs()
        else: v = (acc * d).sum(-1) if ln.module is not None else acc * d
        v = v.cpu().numpy(); total += v.reshape(len(options), -1).sum(1)
        if ln.name == "tokens": parts["tokens"] = TokenPart(token_texts(builder.tok, row.ids), row_segments(builder, row, rec), v)
        elif ln.name == "pixels":
            images, maps = pixel_tiles(builder.processor, row, v)
            parts["pixels"] = ImagePart(images, maps)
        else:
            st = builder.streams[ln.name.removeprefix("stream:")].tokenizer
            parts[ln.name] = SequencePart(st.convert_ids_to_tokens(list(row.extras[f"{ln.name.removeprefix('stream:')}_input_ids"])), v, name=ln.name)
    return Attribution(q, probs, options, parts, method, target, gold=g, delta=total - (f1 - f0) if method == "ig" else None,
                       f_input=f1, f_baseline=f0, record=rec, batch_size=batch_size)

# %% ../nbs/09a_interpret.ipynb #7df9238c
class Attribution:
    "What drove one decision: for each option explained, a score for every unit (token, word, pixel, residue) of every input"
    def __init__(self, question, probs, options, parts:dict, method:str, target:str, gold:int=-1, delta=None, f_input=None, f_baseline=None,
                 record=None, batch_size=None):
        self.question, self.probs, self.options, self.parts, self.method, self.target = question, np.asarray(probs), list(options), parts, method, target
        self.gold, self.delta, self.f_input, self.f_baseline, self.record, self.batch_size = gold, delta, f_input, f_baseline, record, batch_size
        self.keys = [str(k) for k in question.keys]

    def __repr__(self):
        parts = ", ".join(f"{k}: {_units(p)}" for k, p in self.parts.items())
        return (f"Attribution({self.method} of {_TARGETS[self.target]} · {self.question.name}: answer "
                f"{self.keys[int(np.argmax(self.probs))]!r} · options {[self.keys[o] for o in self.options]} · {parts})")

    def _j(self, option) -> int:
        "The row of an option (a key, or an index among all options) among those explained"
        o = self.keys.index(str(option)) if str(option) in self.keys and not isinstance(option, (int, np.integer)) else int(option)
        if o not in self.options: raise ValueError(f"option {self.keys[o]!r} was not explained; these were: {[self.keys[i] for i in self.options]}")
        return self.options.index(o)

    def _repr_html_(self): return attribution_html(self)

_TARGETS = {"logodds": "log-odds", "logprob": "log p", "logit": "the logit", "prob": "p"}

def _units(p) -> str:
    if isinstance(p, ImagePart): return " and ".join(f"{a.shape[1]}×{a.shape[0]} px" for a in p.images)
    if isinstance(p, TokenPart): return f"{len(p.texts)} {'words' if p.name == 'words' else 'tokens'}"
    return f"{len(p.units)} units"

def _scores(p) -> list: return p.scores if isinstance(p.scores, list) else [p.scores]

@patch
def totals(self:Attribution) -> dict:
    "Each part's summed attribution, per option explained: with integrated gradients, together they make f(input) − f(baseline)"
    return {k: np.array([sum(float(np.sum(s[j])) for s in _scores(p)) for j in range(len(self.options))]) for k, p in self.parts.items()}

@patch
def by_segment(self:Attribution):
    "The share of each option's absolute attribution in each segment of the row (question, options, state) and in each other input"
    import pandas as pd
    out = {}
    for j, o in enumerate(self.options):
        row = {}
        for k, p in self.parts.items():
            if isinstance(p, TokenPart):
                for seg, s in zip(p.segments, p.scores[j]):
                    if seg == "special": continue
                    name = "options" if seg.startswith(("option", "anchor")) else seg
                    row[name] = row.get(name, 0.0) + abs(float(s))
            else: row[k] = row.get(k, 0.0) + sum(float(np.abs(s[j]).sum()) for s in _scores(p))
        tot = sum(row.values()) or 1.0
        out[self.keys[o]] = {k: v / tot for k, v in row.items()}
    return pd.DataFrame(out).T.fillna(0.0)

@patch
def words(self:Attribution, option=None, part:str="tokens", segments=None) -> list:
    "(word, score, segment) for one option (the first explained by default): the tokens joined into words, their scores summed"
    p, j, out = self.parts[part], self._j(option) if option is not None else 0, []
    for txt, seg, s in zip(p.texts, p.segments, p.scores[j]):
        if segments and seg.split(" ")[0] not in segments: continue
        if not out or seg != out[-1][2] or "special" in (seg, out[-1][2]) or txt[:1].isspace() or seg.startswith("anchor"): out.append([txt, float(s), seg])
        else: out[-1][0] += txt; out[-1][1] += float(s)
    return [(w.strip(), s, seg) for w, s, seg in out]

# %% ../nbs/09a_interpret.ipynb #24791538
def _bg(s:float, vmax:float) -> str:
    c = _GREEN if s > 0 else _RED
    return f"rgba({c[0]},{c[1]},{c[2]},{min(1.0, abs(s) / vmax) * 0.85:.2f})"

def _tokens_html(a:Attribution, part:TokenPart, j:int, vmax:float, segments, by_word:bool) -> str:
    units = a.words(a.options[j], part.name, segments) if by_word else \
            [(t, float(s), seg) for t, s, seg in zip(part.texts, part.scores[j], part.segments) if not segments or seg.split(" ")[0] in segments]
    out, prev = [], None
    for w, s, seg in units:
        if seg == "special":                                   # the template's markers, an image's placeholders: grey, runs collapsed
            if prev is not None and prev[0] == w: prev[1] += 1
            else: prev = [w, 1]; out.append(prev)
            continue
        prev = None
        if seg.startswith("anchor"): out.append(f'<span title="the anchor the head reads" style="color:#999">▸</span>'); continue
        out.append(f'<span title="{s:+.3f} · {html.escape(seg)}" style="background:{_bg(s, vmax)};border-radius:3px;padding:1px 2px">{html.escape(w)}</span>')
    return " ".join(f'<span style="color:#999;font-size:80%">{html.escape(x[0])}{"×" + str(x[1]) if x[1] > 1 else ""}</span>' if isinstance(x, list) else x for x in out)

def _num(x:float) -> str: return f"{x:+.2f}" if abs(x) >= 0.01 or x == 0 else f"{x:+.2g}"

def _png(fig, dpi:int=80) -> str:
    import matplotlib.pyplot as plt
    buf = io.BytesIO(); fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight"); plt.close(fig)
    return f'<img src="data:image/png;base64,{base64.b64encode(buf.getvalue()).decode()}" style="max-width:100%"/>'

def attribution_html(a:Attribution, segments=None, by_word:bool=True) -> str:
    "An attribution as HTML: a row per option explained, its words green where they raise its log-odds and red where they lower them, then its images and sequences"
    pred, toks = int(np.argmax(a.probs)), [p for p in a.parts.values() if isinstance(p, TokenPart)]
    of = _TARGETS[a.target]
    head = (f'<div style="margin-bottom:4px"><b>{html.escape(a.question.instructions)}</b> · answer <b>{html.escape(a.keys[pred])}</b> '
            f'({a.probs[pred]:.0%})' + (f' · gold <b>{html.escape(a.keys[a.gold])}</b>' if a.gold >= 0 else "") + f' · {a.method}, attributions of {of}</div>')
    tot, rows, ig = a.totals(), [], a.delta is not None           # Δ and Σ, the completeness check, only mean something for integrated gradients
    for j, o in enumerate(a.options):          # each row's colours are relative to its largest attribution, as transformers-interpret normalises each label's
        shown = [abs(float(s)) for p in toks for s, seg in zip(p.scores[j], p.segments) if not segments or seg.split(" ")[0] in segments]
        vmax = max(shown + [1e-12])
        cells = "".join(_tokens_html(a, p, j, vmax, segments, by_word) for p in toks)
        check = ""
        if ig:
            s, change = sum(t[j] for t in tot.values()), a.f_input[j] - a.f_baseline[j]
            off = abs(a.delta[j]) > 0.1 + 0.1 * abs(change)
            warn = ' style="color:#b45309" title="the attributions do not add up to the change"' if off else ""
            check = f'<td>{_num(change)}</td><td{warn}>{_num(s)}{" ⚠" if off else ""}</td>'
        rows.append(f'<tr><td style="text-align:left;white-space:nowrap"><b>{html.escape(a.keys[o])}</b>{" ✓" if o == a.gold else ""}</td>'
                    f'<td>{a.probs[o]:.2f}</td>{check}' + (f'<td style="color:#888">{vmax:.2g}</td>' if toks else "") +
                    f'<td style="text-align:left;line-height:1.9">{cells}</td></tr>')
    th = '<tr><th style="text-align:left">option</th><th>p</th>' + ('<th title="f(input) − f(baseline)">Δ</th><th title="the sum of the attributions">Σ</th>' if ig else "") + \
         ('<th title="the largest attribution in the row: its colours are relative to it">scale</th>' if toks else "")
    table = ('<table style="border-collapse:collapse;font-size:90%">' + th + '<th style="text-align:left">' + ("words" if toks else "") + "</th></tr>" +
             "".join(rows) + "</table>")
    return head + table + "".join(_png(part_figure(p, a)) for p in a.parts.values() if not isinstance(p, TokenPart))

# %% ../nbs/09a_interpret.ipynb #76c10fb8
@dispatch
def part_figure(part:ImagePart, a:Attribution):
    "An image's attributions: the image, then each option's map over it, green where pixels raised the option and pink where they lowered it, averaged over cells of 1/32 of the image"
    import matplotlib.pyplot as plt
    n, m, cmap = len(a.options), len(part.images), plt.get_cmap("PiYG")
    fig, axs = plt.subplots(m, n + 1, figsize=(2.3 * (n + 1), 2.4 * m), squeeze=False)
    for v, (img, sc) in enumerate(zip(part.images, part.scores)):
        sm = _cells(sc, max(1, max(img.shape[:2]) // 32))
        axs[v, 0].imshow(img); axs[v, 0].set_title("as the encoder reads it" if v == 0 else "global view", fontsize=8)
        for j, o in enumerate(a.options):           # each map relative to its own scale: the 98th percentile of its sizes, as Captum clips outliers
            ax, vmax = axs[v, j + 1], float(np.percentile(np.abs(sm[j]), 98)) or float(np.abs(sm[j]).max()) or 1.0
            rgba = cmap((np.clip(sm[j] / vmax, -1, 1) + 1) / 2)
            rgba[..., 3] = np.clip(np.abs(sm[j]) / vmax, 0, 1) * 0.85      # small values let the image show through
            ax.imshow(img, alpha=0.6); ax.imshow(rgba)
            ax.set_title(f"{a.keys[o]} ({a.probs[o]:.0%}), ±{vmax:.2g}", fontsize=8)
        for ax in axs[v]: ax.axis("off")
    fig.tight_layout()
    return fig

def _cells(sc:np.ndarray, cell:int) -> np.ndarray:
    "Per-pixel scores (…, H, W) averaged over square cells of `cell` pixels, at full size"
    if cell <= 1: return sc
    H, W = sc.shape[-2:]
    h, w = -(-H // cell), -(-W // cell)
    pad = np.zeros(sc.shape[:-2] + (h * cell, w * cell)); pad[..., :H, :W] = sc
    m = pad.reshape(*sc.shape[:-2], h, cell, w, cell).mean((-3, -1))
    return np.repeat(np.repeat(m, cell, -2), cell, -1)[..., :H, :W]

@dispatch
def part_figure(part:SequencePart, a:Attribution):
    "A sequence's attributions: a bar per unit and option, green where it raised the option and red where it lowered it, its letters below when there are few"
    import matplotlib.pyplot as plt
    n = len(a.options)
    fig, axs = plt.subplots(n, 1, figsize=(10, 1.5 * n + 0.4), squeeze=False, sharex=True)
    x = np.arange(len(part.units))
    for j, o in enumerate(a.options):
        ax, s = axs[j, 0], part.scores[j]
        vmax = float(np.abs(s).max()) or 1.0
        ax.bar(x, s, width=1.0, color=np.where(s > 0, "#16a34a", "#dc2626"))
        ax.set_ylim(-vmax, vmax); ax.set_ylabel(f"{a.keys[o]}\n{a.probs[o]:.0%}", rotation=0, ha="right", va="center", fontsize=8)
    if len(part.units) <= 100: axs[-1, 0].set_xticks(x, part.units, fontsize=6, family="monospace")
    axs[-1, 0].set_xlabel(f"{part.name}: position")
    fig.tight_layout()
    return fig

# %% ../nbs/09a_interpret.ipynb #db9d0029
@patch
def explain(self:Decider, state, questions:dict, qid=None, method:str="ig", **kw) -> Attribution:
    "Why this decider answered as it did: `attribute` (integrated gradients by default) through its model, or `occlusion` through its answers"
    if method == "occlusion": return occlusion(self, state, questions, qid, **kw)
    return attribute(self.model, self.builder, state, questions, qid, method=method, temperatures=self.temperatures, **kw)

@patch
def explain(self:Learner, state, questions:dict, qid=None, method:str="ig", **kw) -> Attribution:
    "Why this learner's model answers as it does (see `Decider.explain`)"
    return self.decider().explain(state, questions, qid, method=method, **kw)

# %% ../nbs/09a_interpret.ipynb #5f94328b
def occlusion(model, state, questions:dict, qid=None, key=None, kind:str|None=None, window:int|None=None, stride:int|None=None, fill=None,
              options=None, target:str="logodds", batch_size:int=16, gold=None) -> Attribution:
    "Attributions through any backend: hide a piece of the state at a time (words, a window of residues, a patch of the image) and measure how far each option's log-odds fall"
    qs = as_questions(questions)
    if qid is None:
        if len(qs) != 1: raise ValueError(f"name the question to explain with qid= ({list(qs)})")
        qid = next(iter(qs))
    q, questions = qs[qid], {qid: questions[qid]}
    st = load_record({"state": state, "questions": questions})["state"]
    if key is None and isinstance(st, dict):
        key = next((k for k in ("image", "sequence", "text") if st.get(k) not in (None, "")), None)
        if key is None: raise ValueError(f"name the part of the state to occlude with key= ({list(st)})")
        if key == "sequence" and kind is None: kind = "residues"
    value = st if key is None else st[key]
    kind = kind or ("patches" if _image_like(value) else "words")
    put = (lambda v: v) if key is None else (lambda v: {**st, key: v})
    if kind == "words":
        if not isinstance(value, str): raise ValueError(f"words are occluded in a text; the state's {key or 'value'} is a {type(value).__name__}")
        spans = [(m.start(), m.end()) for m in re.finditer(r"\S+", value)]
        if not spans: raise ValueError("the text to occlude has no words")
        window, stride = window or 1, stride or 1
        cover = [(i, min(i + window, len(spans))) for i in range(0, max(1, len(spans) - window + 1), stride)]
        variants = [put((value[:spans[a][0]] + value[spans[b - 1][1]:].lstrip(" ")).strip()) for a, b in cover]
        n = len(spans)
    elif kind == "residues":
        window, stride, fill = window or 10, stride or max(1, (window or 10) // 2), fill or "X"
        starts = list(range(0, max(1, len(value) - window + 1), stride))
        if starts[-1] + window < len(value): starts.append(len(value) - window)
        cover = [(a, min(a + window, len(value))) for a in starts]
        variants, n = [put(value[:a] + fill * (b - a) + value[b:]) for a, b in cover], len(value)
    elif kind == "patches":
        from PIL import ImageDraw
        img = load_image(value); W, H = img.size
        window = window or max(1, max(W, H) // 8); stride = stride or max(1, window // 2)
        color = {"black": (0, 0, 0), "gray": (128, 128, 128), "white": (255, 255, 255)}.get(fill or "black", fill)
        xs, ys = list(range(0, max(1, W - window + 1), stride)), list(range(0, max(1, H - window + 1), stride))
        if xs[-1] + window < W: xs.append(W - window)
        if ys[-1] + window < H: ys.append(H - window)
        cover, variants = [(x, y) for y in ys for x in xs], []
        for x, y in cover:
            im = img.copy(); ImageDraw.Draw(im).rectangle([x, y, x + window - 1, y + window - 1], fill=color); variants.append(put(im))
    else: raise ValueError(f"kind must be 'words', 'residues' or 'patches', not {kind!r}")
    f = {"logodds": lambda p: np.log(np.clip(p, 1e-300, 1)) - np.log(np.clip(1 - p, 1e-300, 1)), "logprob": lambda p: np.log(np.clip(p, 1e-300, 1)),
         "prob": lambda p: p}.get(target)
    if f is None: raise ValueError(f"occlusion's target must be 'logodds', 'logprob' or 'prob', not {target!r}")
    digits = getattr(model, "digits", None)
    if digits is not None: model.digits = None          # unrounded: a probability rounded to 0 has no logarithm
    try:
        p0 = np.asarray(answer_probs(q, _predict_many(model, [st], questions, batch_size)[0][qid]), dtype=np.float64)
        answers = _predict_many(model, variants, questions, batch_size)
    finally:
        if digits is not None: model.digits = digits
    g = q.target(gold)[1] if gold is not None else -1
    if options is None: options = list(dict.fromkeys([int(np.argmax(p0))] + ([g] if g >= 0 else [])))
    options = [q.keys.index(o) if o in q.keys else int(o) for o in options]
    drops = np.stack([f(p0)[options] - f(np.asarray(answer_probs(q, a[qid]), dtype=np.float64))[options] for a in answers])
    if kind == "patches":
        S, C = np.zeros((len(options), H, W)), np.zeros((H, W))
        for (x, y), d in zip(cover, drops): S[:, y:y + window, x:x + window] += d[:, None, None]; C[y:y + window, x:x + window] += 1
        part = ImagePart([np.asarray(img, dtype=np.float32) / 255], [S / np.maximum(C, 1)], name=key or "image")
    else:
        S, C = np.zeros((len(options), n)), np.zeros(n)
        for (a, b), d in zip(cover, drops): S[:, a:b] += d[:, None]; C[a:b] += 1
        S = S / np.maximum(C, 1)
        part = TokenPart([(" " if i else "") + value[s:e] for i, (s, e) in enumerate(spans)], ["state"] * n, S, name="words") if kind == "words" \
               else SequencePart(list(value), S, name=key or "sequence")
    return Attribution(q, p0, options, {part.name: part}, "occlusion", target, gold=g, f_input=f(p0)[options], record={"state": st, "questions": questions})

# %% ../nbs/09a_interpret.ipynb #be737c00
@patch
def explain(self:Interpretation, i:int, method:str="ig", **kw) -> Attribution:
    "The attribution of decision `i`: through the model when the backend is a sysone one, by occlusion otherwise"
    (rec, qid), = self.items([i])
    if method != "occlusion" and not hasattr(self.decider, "model"):
        raise ValueError("gradient attributions need a sysone model; use method='occlusion' with this backend")
    return self.decider.explain(rec["state"], rec["questions"], qid, method=method, gold=(rec.get("gold") or {}).get(qid), **kw)

# %% ../nbs/09a_interpret.ipynb #1a7dbcd1
def attribution_path(model, builder:RowBuilder, state, questions:dict, qid=None, option=None, inputs=None, steps:int=200, baseline="pad",
                     temperatures:dict|None=None, target:str="logodds", lo:float=0.0, hi:float=1.0) -> tuple:
    "The points α from `lo` to `hi` and an option's log-odds (or `target`) there, on the line integrated gradients integrates over: baseline at α = 0, input at α = 1"
    rec, q, row, lines, T, pad = _setup(model, builder, state, questions, qid, inputs, baseline, temperatures)
    alphas, out = np.linspace(lo, hi, steps), []
    with gradients_through(model), torch.no_grad():
        if option is None: o = int(_forward(model, row, pad, lines, [1.0], False, T, "logit")[0][0, :q.k].argmax())    # the answer
        else: o = q.keys.index(option) if option in q.keys else int(option)
        for s in range(0, steps, 16): out.append(_forward(model, row, pad, lines, alphas[s:s + 16], False, T, target)[0][:, o].cpu().numpy())
    return alphas, np.concatenate(out)
