"""`DecisionTrainer`, a `transformers.Trainer` with two overrides, and `Learner`, fastai's verbs over it: `lr_find`, `fit`, `fit_one_cycle`, `freeze`, `calibrate`.

Docs: https://sgaseretto.github.io/sysonelib/learner.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_learner.ipynb.

# %% auto #0
__all__ = ['PRESETS', 'pack_labels', 'unpack_labels', 'unpack_answerable', 'DecisionTrainer', 'training_args', 'default_preset',
           'SigmaSchedule', 'OptionShuffle', 'Recorder', 'CalibrationCallback', 'peak_memory_gb', 'FitLog', 'LRFinder',
           'Learner', 'SuggestedLRs', 'valley', 'steep', 'decision_learner']

# %% ../nbs/05_learner.ipynb #648d56db
import contextlib, copy, dataclasses, datetime, json, math, os, sys, tempfile, time, warnings
from pathlib import Path

import numpy as np
import torch
from fastcore.basics import patch, store_attr
from transformers import Trainer, TrainingArguments, TrainerCallback

from .core import *
from .template import *
from .data import *
from .models import *
from .losses import *
from .metrics import Preds, as_metric

# %% ../nbs/05_learner.ipynb #a76a42d7
def pack_labels(b) -> torch.Tensor:
    "Target, marker mask, question type, label and answerability of a batch as one (batch, K, 5) tensor"
    K = b["marker_mask"].shape[1]
    tgt = b["target"].float() if "target" in b else torch.zeros_like(b["marker_mask"], dtype=torch.float)
    rep = lambda v: v.float()[:, None].expand(-1, K)
    lab = b["label"] if "label" in b else torch.full_like(b["qtype"], -1)
    ans = b["answerable"] if "answerable" in b else torch.full_like(b["qtype"], -1)
    return torch.stack([tgt, b["marker_mask"].float(), rep(b["qtype"]), rep(lab), rep(ans)], -1)

def unpack_labels(packed):
    "targets, masks, qtypes, labels from `pack_labels` output gathered by the Trainer (padded with -100)"
    packed = np.asarray(packed)
    mask = packed[..., 1] == 1
    return np.where(mask, packed[..., 0], 0.0), mask, packed[:, 0, 2].astype(int), packed[:, 0, 3].astype(int)

def unpack_answerable(packed):
    "Each row's answerability from `pack_labels` output (1 answerable, 0 not, -1 no gold)"
    packed = np.asarray(packed)
    return packed[:, 0, 4].astype(int) if packed.shape[-1] > 4 else np.ones(len(packed), dtype=int)

# %% ../nbs/05_learner.ipynb #f7716249
@contextlib.contextmanager
def _keep_last(args):
    "Evaluate and predict on every row: `dataloader_drop_last` (which the XLA presets set, for fixed shapes) is for training"
    old, args.dataloader_drop_last = args.dataloader_drop_last, False
    try: yield
    finally: args.dataloader_drop_last = old

class DecisionTrainer(Trainer):
    "A `Trainer` with the decision loss, head and encoder learning rates, and an optional LR-range or one-cycle schedule"
    def __init__(self, *args, loss_fn=None, lr_head:float|None=None, lr_encoder:float|None=None, act_weight:float=0.5, **kwargs):
        super().__init__(*args, **kwargs)
        self.loss_fn, self.lr_head, self.lr_encoder, self.act_weight = loss_fn or soft_ce, lr_head, lr_encoder, act_weight
        self.model_accepts_loss_kwargs = False   # the loss is a mean; gradient accumulation must scale it
        self.all_answerable = False              # every training row has an answer: the loss runs on whole batches (no host sync, for XLA)
        self.schedule = None                     # None (the args' scheduler), ("range", start, end) or ("onecycle", pct_start)

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        inputs = dict(inputs)
        target, label = inputs.pop("target", None), inputs.pop("label", None)
        out = model(**inputs)
        logits, act = out if isinstance(out, tuple) else (out, None)
        fn = self.loss_fn if model.training else soft_ce
        if target is None: loss = logits.sum() * 0
        else:
            if self.all_answerable and model.training: loss = fn(logits, target, inputs["marker_mask"], inputs["qtype"])
            else:
                rows = target.sum(-1) > 0               # an unanswerable row teaches the act head only
                loss = fn(logits[rows], target[rows], inputs["marker_mask"][rows], inputs["qtype"][rows]) if bool(rows.any()) else logits.sum() * 0
            if act is not None and label is not None:
                loss = loss + self.act_weight * act_loss(act, logits, label, inputs.get("answerable", torch.ones_like(label)))
        return (loss, {"logits": logits, "act": act}) if return_outputs else loss

    def prediction_step(self, model, inputs, prediction_loss_only, ignore_keys=None):
        inputs = self._prepare_inputs(inputs)
        with torch.no_grad(), self.compute_loss_context_manager():
            loss, out = self.compute_loss(model, inputs, return_outputs=True)
        if prediction_loss_only: return loss.detach(), None, None
        preds = out["logits"].detach().float()
        return loss.detach(), (preds, out["act"].detach().float()) if out["act"] is not None else preds, pack_labels(inputs)

    def _get_eval_sampler(self, eval_dataset):
        # predictions come back in dataset order (the Trainer would group evaluation rows by length too)
        if eval_dataset is None or not hasattr(eval_dataset, "__len__"): return None
        return torch.utils.data.SequentialSampler(eval_dataset) if self.args.world_size <= 1 else None

    def get_eval_dataloader(self, eval_dataset=None):
        with _keep_last(self.args): return super().get_eval_dataloader(eval_dataset)

    def get_test_dataloader(self, test_dataset):
        with _keep_last(self.args): return super().get_test_dataloader(test_dataset)

# %% ../nbs/05_learner.ipynb #057eba61
@patch
def create_optimizer(self:DecisionTrainer, model=None):
    opt_model = self.model if model is None else model
    if self.optimizer is None:
        decay = set(self.get_decay_parameter_names(opt_model))
        lr = {"head": self.lr_head or self.args.learning_rate, "encoder": self.lr_encoder or self.args.learning_rate}
        buckets = {}
        for n, p in opt_model.named_parameters():
            if p.requires_grad: buckets.setdefault(("encoder" if n.startswith("encoder.") else "head", n in decay), []).append(p)
        groups = [{"params": ps, "lr": lr[part], "weight_decay": self.args.weight_decay if d else 0.0,
                   "name": f"{part}/{'decay' if d else 'no_decay'}"}
                  for (part, d), ps in sorted(buckets.items(), key=lambda kv: (kv[0][0] != "head", not kv[0][1]))]
        cls, kw = self.get_optimizer_cls_and_kwargs(self.args, opt_model)
        self.optimizer = cls(groups, **kw)
    return self.optimizer

@patch
def create_scheduler(self:DecisionTrainer, num_training_steps:int, optimizer=None):
    if self.schedule is None or self.lr_scheduler is not None:
        return Trainer.create_scheduler(self, num_training_steps, optimizer)
    optimizer = self.optimizer if optimizer is None else optimizer
    if self.schedule[0] == "range":
        start, end = self.schedule[1:]
        gamma = (end / start) ** (1.0 / max(1, num_training_steps - 1))
        scale = start / (self.lr_head or self.args.learning_rate)
        self.lr_scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lambda s: scale * gamma ** s)
    else:
        self.lr_scheduler = torch.optim.lr_scheduler.OneCycleLR(
            optimizer, max_lr=[g["lr"] for g in optimizer.param_groups], total_steps=max(2, num_training_steps),
            pct_start=self.schedule[1], anneal_strategy="cos", cycle_momentum=False)
    self._created_lr_scheduler = True
    return self.lr_scheduler

# %% ../nbs/05_learner.ipynb #305baf33
_TA_FIELDS = {f.name for f in dataclasses.fields(TrainingArguments)}

def _compat(kw:dict) -> dict:
    "Translate TrainingArguments keywords between transformers versions"
    kw = dict(kw)
    if "warmup_steps" in kw and "warmup_ratio" in _TA_FIELDS and isinstance(kw["warmup_steps"], float) and kw["warmup_steps"] < 1:
        kw["warmup_ratio"] = kw.pop("warmup_steps")
    if kw.get("train_sampling_strategy") == "group_by_length" and "train_sampling_strategy" not in _TA_FIELDS:
        kw.pop("train_sampling_strategy"); kw["group_by_length"] = True
    if "eval_strategy" in kw and "eval_strategy" not in _TA_FIELDS: kw["evaluation_strategy"] = kw.pop("eval_strategy")
    unknown = set(kw) - _TA_FIELDS
    if unknown: raise TypeError(f"TrainingArguments does not take {sorted(unknown)} in this transformers version")
    return kw

def training_args(output_dir, **kw) -> TrainingArguments:
    "`TrainingArguments` with sysone's defaults, overridable by keyword"
    base = dict(output_dir=str(output_dir), report_to="none", save_strategy="no", logging_strategy="steps", logging_steps=10,
                remove_unused_columns=False, label_names=["target"], max_grad_norm=1.0, weight_decay=0.01,
                lr_scheduler_type="cosine", warmup_steps=0.1, train_sampling_strategy="group_by_length",
                length_column_name="n_tokens", per_device_train_batch_size=8, per_device_eval_batch_size=16,
                dataloader_pin_memory=torch.cuda.is_available(), seed=0)
    return TrainingArguments(**_compat(base | kw))

# %% ../nbs/05_learner.ipynb #90d13c23
PRESETS = {
    "cpu":     dict(use_cpu=True, per_device_train_batch_size=8, per_device_eval_batch_size=16),
    "macbook": dict(per_device_train_batch_size=4, per_device_eval_batch_size=8, dataloader_pin_memory=False),
    "t4":      dict(fp16=True, gradient_checkpointing=True, per_device_train_batch_size=8, gradient_accumulation_steps=4,
                    per_device_eval_batch_size=16),
    "t4x2":    dict(fp16=True, gradient_checkpointing=True, per_device_train_batch_size=8, gradient_accumulation_steps=4,
                    per_device_eval_batch_size=16, ddp_find_unused_parameters=False),
    "l4":      dict(bf16=True, gradient_checkpointing=True, per_device_train_batch_size=16, gradient_accumulation_steps=2,
                    per_device_eval_batch_size=32),
    "a100":    dict(bf16=True, per_device_train_batch_size=32, per_device_eval_batch_size=64),
    "tpu":     dict(bf16=True, per_device_train_batch_size=16, per_device_eval_batch_size=32, dataloader_drop_last=True,
                    dataloader_pin_memory=False, optim="adamw_torch"),     # the fused AdamW has no XLA kernel
    "neuron":  dict(bf16=True, per_device_train_batch_size=8, per_device_eval_batch_size=16, dataloader_drop_last=True,
                    dataloader_pin_memory=False, optim="adamw_torch"),
}

def default_preset() -> str:
    "`SYSONE_PRESET`, else a guess from the hardware"
    if os.environ.get("SYSONE_PRESET"): return os.environ["SYSONE_PRESET"]
    if torch.cuda.is_available():
        name = torch.cuda.get_device_name(0)
        if "T4" in name: return "t4x2" if torch.cuda.device_count() > 1 else "t4"
        if "L4" in name: return "l4"
        return "a100"
    if os.environ.get("PJRT_DEVICE") == "TPU" or os.environ.get("TPU_ACCELERATOR_TYPE"): return "tpu"
    if os.environ.get("NEURON_RT_VISIBLE_CORES") or Path("/dev/neuron0").exists(): return "neuron"
    if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available(): return "macbook"
    return "cpu"

# %% ../nbs/05_learner.ipynb #849e8508
def _epoch(state) -> int: return int(round(state.epoch or 0))

class SigmaSchedule(TrainerCallback):
    "Anneal RLCD's σ once per epoch"
    def __init__(self, loss): self.loss = loss
    def on_epoch_begin(self, args, state, control, **kw):
        if hasattr(self.loss, "set_epoch"): self.loss.set_epoch(_epoch(state), math.ceil(state.num_train_epochs or 1))

class OptionShuffle(TrainerCallback):
    "Give every transform with `set_epoch` the current epoch (`Shuffle`, `Rephrase`, an `Expansion`), so option orders, wordings and added questions change between epochs"
    def __init__(self, tfms): self.tfms = [t for t in tfms if hasattr(t, "set_epoch")]
    def on_epoch_begin(self, args, state, control, **kw):
        for t in self.tfms: t.set_epoch(_epoch(state))

class Recorder(TrainerCallback):
    "Training losses and evaluation metrics, per step and per epoch"
    def __init__(self): self.losses, self.lrs, self.metrics = [], [], []
    def on_log(self, args, state, control, logs=None, **kw):
        if logs and "loss" in logs: self.losses.append(logs["loss"]); self.lrs.append(logs.get("learning_rate"))
    def on_evaluate(self, args, state, control, metrics=None, **kw):
        if metrics: self.metrics.append({"epoch": state.epoch, **{k.removeprefix("eval_"): v for k, v in metrics.items()}})

class CalibrationCallback(TrainerCallback):
    "Fit the learner's temperatures on its calib split when training ends"
    def __init__(self, learner): self.learner, self.active = learner, True
    def on_train_end(self, args, state, control, **kw):
        if self.active and self.learner.data.cases.get("calib") is not None: self.learner.calibrate()

def peak_memory_gb(device:str, mps_bytes:int=0) -> float|None:
    "The most memory a fit used: CUDA's peak since the last reset, the MPS driver's largest allocation seen, or the process's peak RSS"
    if device == "cuda": b = torch.cuda.max_memory_allocated()
    elif device == "mps": b = mps_bytes
    else:
        try: import resource
        except ImportError: return None
        b = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss * (1 if sys.platform == "darwin" else 1024)
    return round(b / 2**30, 2)

class FitLog(TrainerCallback):
    "One entry per fit for the training record: what was asked for (epochs, learning rates, schedule, batch) and what it took"
    def __init__(self, learner): self.learner, self.fits, self._entry = learner, [], None
    def on_train_begin(self, args, state, control, **kw):
        t = self.learner.trainer
        if t.schedule is not None and t.schedule[0] == "range": self._entry = None; return   # lr_find's range test is not a fit
        self._device, self._mps, self._t0 = args.device.type, 0, time.time()
        if self._device == "cuda": torch.cuda.reset_peak_memory_stats()
        sched = t.schedule[0] if t.schedule is not None else getattr(args.lr_scheduler_type, "value", args.lr_scheduler_type)
        self._entry = {"started": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
                       "regime": self.learner.model.regime, "epochs": args.num_train_epochs, "max_steps": args.max_steps,
                       "lr_head": t.lr_head, "lr_encoder": t.lr_encoder, "schedule": str(sched), "warmup": args.warmup_steps,
                       "batch_size": args.per_device_train_batch_size, "grad_accum": args.gradient_accumulation_steps,
                       "precision": "bf16" if args.bf16 else "fp16" if args.fp16 else "fp32", "device": self._device}
    def on_step_end(self, args, state, control, **kw):
        if self._entry is not None and self._device == "mps": self._mps = max(self._mps, torch.mps.driver_allocated_memory())
    def on_train_end(self, args, state, control, **kw):
        if self._entry is None: return
        losses = [l["loss"] for l in state.log_history if "loss" in l]
        self.fits.append(self._entry | {"steps": state.global_step, "seconds": round(time.time() - self._t0, 1),
                                        "final_loss": losses[-1] if losses else None,
                                        "peak_memory_gb": peak_memory_gb(self._device, self._mps)})
        self._entry = None

class LRFinder(TrainerCallback):
    "Record (lr, loss) every step and stop when the smoothed loss diverges"
    def __init__(self, factor:float=4.0, beta:float=0.98, stop_div:bool=True):
        store_attr(); self.lrs, self.losses, self.avg, self.best, self.n = [], [], 0.0, math.inf, 0
    def on_log(self, args, state, control, logs=None, **kw):
        if not logs or "loss" not in logs: return
        loss = logs["loss"]; self.n += 1
        self.avg = self.beta * self.avg + (1 - self.beta) * loss
        smooth = self.avg / (1 - self.beta ** self.n)
        self.lrs.append(logs["learning_rate"]); self.losses.append(smooth)
        self.best = min(self.best, smooth)
        if self.stop_div and (not math.isfinite(loss) or smooth > self.factor * self.best): control.should_training_stop = True
        return control

# %% ../nbs/05_learner.ipynb #23c0fb34
def _lrs(lr, default_head:float=1e-4, ratio:float=0.25):
    "(encoder, head) learning rates from a head LR or a pair"
    if lr is None: lr = default_head
    return (float(lr[0]), float(lr[1])) if isinstance(lr, (tuple, list)) else (float(lr) * ratio, float(lr))

class Learner:
    "Data, model, loss and a `DecisionTrainer`, with fastai's training verbs"
    def __init__(self,
                 data:TypedDecisions, # cases, bound to the encoder's tokenizer
                 model:EncoderDecisionModel, # encoder and head, regime already set
                 loss=None, # 'soft_ce', 'rlcd', a callable, or the data's default
                 cache:str|None=None, # 'masks' or 'rows' to train a frozen encoder's head from cached features
                 lr=1e-4, # head LR, or (encoder, head)
                 preset:str|None=None, # a key of PRESETS; SYSONE_PRESET or the hardware's by default
                 path=None, # where the Trainer writes; a temporary folder by default
                 cache_dir=None, # where feature caches live; ~/.cache/sysone/features by default
                 cache_dtype:str="float16", # how a feature cache stores the vectors; float32 for an encoder whose vectors float16 cannot hold
                 calibrate_after_fit:bool=True, # fit temperatures on the calib split after every fit
                 callbacks:list|None=None, # extra TrainerCallbacks
                 act_weight:float=0.5, # the act head's loss weight, beside the option loss
                 metrics:list|None=None, # more metrics, beside Laya's: functions of a `Preds`, or `Metric`s (see metrics)
                 **args): # extra TrainingArguments
        self.data, self.model, self.cache, self.lr, self.cache_dir, self.cache_dtype = data, model, cache, lr, cache_dir, cache_dtype
        self.path = Path(path) if path else Path(tempfile.mkdtemp(prefix="sysone-"))
        self.preset = preset or default_preset()
        self.loss = get_loss(loss, data.rows("train")["target"])
        self.temperatures, self.calibrate_after_fit, self._features, self.act_threshold, self.act_score = {}, calibrate_after_fit, {}, None, None
        self.metrics, self._keys = [as_metric(m) for m in metrics or []], {}
        if cache is not None: self._check_cache(cache)
        self.recorder, self.calibration, self.fit_log = Recorder(), CalibrationCallback(self), FitLog(self)
        self.calibration.active = calibrate_after_fit
        self.args = training_args(self.path / "trainer", **(PRESETS[self.preset] | args))
        cbs = [SigmaSchedule(self.loss), OptionShuffle(data.builder.tfms), self.recorder, self.calibration, self.fit_log] + list(callbacks or [])
        enc, head = _lrs(lr)
        self.trainer = DecisionTrainer(model=model, args=self.args, data_collator=data.collator, loss_fn=self.loss,
                                       compute_metrics=self._metrics, callbacks=cbs, lr_head=head, lr_encoder=enc, act_weight=act_weight)
        if self.preset in ("tpu", "neuron"):     # XLA: batches of few shapes, a step with no decisions on the host
            from sysone.xla import prepare_xla
            prepare_xla(self)
        if os.environ.get("SYSONE_PROGRESS") or os.environ.get("SYSONE_TRACK"):   # inside a sysone job: report on itself
            import sysone.track
            if os.environ.get("SYSONE_PROGRESS"): self.progress()
            t = os.environ.get("SYSONE_TRACK", "")
            if t: self.track(**(json.loads(t) if t.startswith("{") else {}))

    def __repr__(self):
        n = self.model.n_params()
        return (f"Learner({self.model.spec.id if self.model.spec else 'encoder'} · regime {self.model.regime} · "
                f"head {self.model.head.layers} layers/{self.model.head.scorer_kind} · cache {self.cache} · "
                f"loss {getattr(self.loss, '__name__', self.loss)} · {n['trainable']:,} of {n['encoder'] + n['head']:,} params train)")

# %% ../nbs/05_learner.ipynb #d9b1237d
@patch
def _check_cache(self:Learner, mode):
    if mode not in ("masks", "rows"): raise ValueError(f"cache must be 'masks' or 'rows', not {mode!r}")
    if not self.model.frozen: raise ValueError("a feature cache needs a frozen encoder (train='head')")
    if mode == "masks" and self.model.head.layers:
        raise ValueError("cache='masks' stores anchor vectors only, which feed a head without layers; use cache='rows'")

def _split_preds(predictions):
    "(logits, p(act) or None) from what the Trainer gathered"
    logits, act = predictions if isinstance(predictions, (tuple, list)) else (predictions, None)
    return logits, (act_probability(torch.as_tensor(act)).numpy() if act is not None else None)

@patch
def _metrics(self:Learner, p) -> dict:
    t, m, q, l = unpack_labels(p.label_ids)
    logits, act = _split_preds(p.predictions)
    ans = unpack_answerable(p.label_ids)
    out = decision_metrics(np.where(m, logits, -1e4), t, m, q, l, act=act, answerable=ans)
    if self.metrics:            # the Trainer evaluates the valid split, in order: its rows say which question each one is
        meta = self.row_meta("valid") if len(t) == len(self.dataset("valid") or []) else {}
        pr = Preds(logits, t, m, q, l, answerable=ans, act=act, qids=meta.get("qid"), case_idx=meta.get("case_idx"),
                   option_keys=self.option_keys("valid") if meta else None)
        out |= {mm.name: mm(pr) for mm in self.metrics}
    return out

@patch
def dataset(self:Learner, split:str="train"):
    "What the Trainer reads for a split: cached features, rows built on read, or static rows"
    if self.data.cases.get(split) is None: return None
    if self.cache is not None:
        if split not in self._features:
            from sysone.cache import FeatureCache
            self._features[split] = FeatureCache(self.model, self.data, self.cache, cache_dir=self.cache_dir, dtype=self.cache_dtype,
                                                 batch_size=self.args.per_device_eval_batch_size).features(split)
        return self._features[split]
    if split == "train" and self.data.needs_lazy_rows: return self.data.lazy_rows(split)
    if self.data.builder.processor is not None: return self.data.lazy_rows(split)
    return self.data.rows(split)

# %% ../nbs/05_learner.ipynb #178f2905
@patch
def _run(self:Learner, epochs=None, lr=None, max_steps=None, schedule=None, eval=True, record=True, **args):
    if not self.model.head.standardizer_fitted: self.fit_standardizer()
    enc, head = _lrs(lr if lr is not None else self.lr)
    if record and any(p.requires_grad for p in self.model.encoder.parameters()):
        self.model.encoder_trained = True     # the export must then carry the encoder, whatever the regime is later
    t = self.trainer
    t.lr_head, t.lr_encoder, t.schedule, t.optimizer, t.lr_scheduler = head, enc, schedule, None, None
    kw = dict(learning_rate=head, num_train_epochs=epochs or 1, max_steps=max_steps or -1) | args
    if eval and self.data.cases["valid"] is not None: kw.setdefault("eval_strategy", "epoch")
    else: kw["eval_strategy"] = "no"
    train_ds = self.dataset("train")
    if self.cache is not None or not hasattr(train_ds, "column_names"): kw.setdefault("train_sampling_strategy", "random")
    kw = _compat(kw)
    # set the fields on the live arguments and put them back after: a new TrainingArguments object would
    # re-run its device setup, which resets accelerate's state under the Trainer's accelerator
    old = {k: getattr(t.args, k) for k in kw}
    for k, v in kw.items(): setattr(t.args, k, v)
    t.train_dataset, t.eval_dataset = train_ds, self.dataset("valid") if kw["eval_strategy"] != "no" else None
    try: out = t.train()
    finally:
        for k, v in old.items(): setattr(t.args, k, v)
    return out

# %% ../nbs/05_learner.ipynb #1df235b8
_NOT_INPUTS = ("input_ids", "attention_mask", "marker_pos", "marker_mask", "qtype", "target", "label", "spans", "answerable", "query", "first")

@patch
def fit_standardizer(self:Learner, n:int=512, batch_size:int=8):
    "Fit the head's per-dimension standardisation on up to `n` training rows"
    head, ds = self.model.head, self.dataset("train")
    idx, queries = list(range(min(n, len(ds)))), None
    col = lambda c: [torch.as_tensor(np.asarray(ds[i][c], dtype=np.float32)) for i in idx]
    if self.cache in ("masks", "rows"):
        vecs = torch.cat(col("anchors" if self.cache == "masks" else "hidden"))
        if head.stream_query: queries = torch.stack(col("query"))
    else:
        model, out, qs, was = self.model, [], [], self.model.training
        model.eval()
        try:
            with torch.no_grad():
                for s in range(0, len(idx), batch_size):
                    b = self.data.collator([ds[j] for j in idx[s:s + batch_size]]).to(model.device)
                    o = model.encode_full(b["input_ids"], b["attention_mask"], **{k: v for k, v in b.items() if k not in _NOT_INPUTS})
                    h = o.last_hidden_state.float()
                    if head.stream_query: qs.append(model.stream_query(o).float().cpu())
                    if head.layers: out.append(h[b["attention_mask"].bool()].cpu())
                    else: out.append(head._readout(h, b["marker_pos"], b.get("spans"))[b["marker_mask"].bool()].cpu())
        finally: model.train(was)
        vecs, queries = torch.cat(out), torch.cat(qs) if qs else None
    head.fit_standardizer(vecs, query=queries)
    return self

# %% ../nbs/05_learner.ipynb #f026c5e6
@patch
def row_meta(self:Learner, split:str="valid") -> dict:
    "Each row's question id, case index and case id, in the order the Trainer reads the split"
    ds = self.dataset(split)
    if ds is None: raise ValueError(f"no {split!r} split")
    if hasattr(ds, "column_names"): return {"qid": [str(v) for v in ds["qid"]], "case_idx": [int(v) for v in ds["case_idx"]], "case": [str(v) for v in ds["case"]]}
    return {"qid": [x[2] for x in ds.index], "case_idx": [int(x[0]) for x in ds.index], "case": [x[3] for x in ds.index]}

@patch
def option_keys(self:Learner, split:str="valid") -> list:
    "Each row's option keys, in the order the Trainer reads a held-out split (looked up once per split)"
    if split not in self._keys:
        meta, cases, ds, recs, out = self.row_meta(split), self.data.cases[split], self.dataset(split), {}, []
        ks = [len(x) for x in ds["markers"]] if hasattr(ds, "column_names") else [None] * len(meta["qid"])
        for ci, qid, k in zip(meta["case_idx"], meta["qid"], ks):
            rec = recs.setdefault(ci, case_record(cases, ci))
            q = as_questions(rec["questions"])[qid]
            if k is not None and q.k != k:          # a transform changed the options (a shortlist): its keys are the transformed question's
                q = as_questions(apply_tfms(self.data.builder.tfms, rec)["questions"])[qid]
            out.append([str(x) for x in q.keys])
        self._keys[split] = out
    return self._keys[split]

@patch
def get_preds(self:Learner, split:str="valid") -> Preds:
    "Every row of a split as a `Preds`: logits, gold, masks, kinds and labels, p(act) with an act head, each row's question, case and option keys, and the learner's temperatures"
    ds = self.dataset(split)
    if ds is None: raise ValueError(f"no {split!r} split")
    out = self.trainer.predict(ds)
    t, m, q, l = unpack_labels(out.label_ids)
    logits, act = _split_preds(out.predictions)
    meta = self.row_meta(split)
    return Preds(logits, t, m, q, l, answerable=unpack_answerable(out.label_ids), act=act, qids=meta["qid"], case_idx=meta["case_idx"],
                 temperatures=self.temperatures, option_keys=self.option_keys(split))

def _acting_right(p) -> np.ndarray:
    "Whether acting on each row would be right: its gold is among the options and the top option is it"
    return (p["logits"].argmax(-1) == p["labels"]) & (p["answerable"] == 1)

def _act_scores(p, temperatures, how) -> tuple:
    "The scores an act threshold applies to, and their name: the act head's p(act) ('head'), or the calibrated top probability ('confidence')"
    if how == "auto": how = "head" if "act" in p else None
    if how is None: return None, None
    if how == "head":
        if "act" not in p: raise ValueError("act_score='head' needs an act head (act=True); act_score='confidence' works without one")
        return p["act"], "head"
    if how != "confidence": raise ValueError(f"act_score must be 'head', 'confidence' or 'auto', not {how!r}")
    T = np.array([lookup_temperature(temperatures, int(q), int(k)) for q, k in zip(p["qtypes"], p["masks"].sum(1))])
    z = p["logits"] / T[:, None]; z = np.exp(z - z.max(1, keepdims=True)) * p["masks"]
    return (z / z.sum(1, keepdims=True)).max(1), "confidence"

@patch
def validate(self:Learner, split:str="valid", calibrated:bool=True, metrics:list|None=None) -> dict:
    "The notebook's metrics on a split, the learner's own `metrics`, and any more given here"
    p = self.get_preds(split)
    m = decision_metrics(p["logits"], p["targets"], p["masks"], p["qtypes"], p["labels"], self.temperatures if calibrated else None,
                         act=p.get("act"), answerable=p["answerable"])
    if self.act_threshold is not None:
        s, _ = _act_scores(p, self.temperatures, self.act_score or "auto")
        if s is not None: m |= selective_metrics(s, _acting_right(p), row_thresholds(self.act_threshold, p["qtypes"], p["masks"].sum(1)))
    if not calibrated: p.temperatures = None
    return m | {mm.name: mm(p) for mm in self.metrics + [as_metric(x) for x in metrics or []]}

# %% ../nbs/05_learner.ipynb #6d0463c2
@patch
def calibrate(self:Learner, split:str="calib", min_rows:int=10, act_accuracy:float|None=0.9, act_score:str|None=None) -> dict:
    "Fit temperatures per question type and option-count bucket on held-out rows, and act thresholds on p(act) or ('confidence') the calibrated top probability"
    if self.data.cases.get(split) is None:
        if self.data.cases.get("valid") is None: raise ValueError("calibration needs held-out rows: a calib or valid split")
        warnings.warn(f"no {split!r} split; calibrating on 'valid'"); split = "valid"
    p = self.get_preds(split)
    self.temperatures = fit_temperatures(p["logits"], p["targets"], p["masks"], p["qtypes"], min_rows)
    s, how = _act_scores(p, self.temperatures, act_score or self.act_score or "auto")
    if s is not None and act_accuracy is not None:
        self.act_threshold = fit_thresholds(s, _acting_right(p), p["qtypes"], p["masks"].sum(1), act_accuracy, min_rows)
        self.act_score = how
    return self.temperatures

# %% ../nbs/05_learner.ipynb #acbac6e4
@patch
def _after_fit(self:Learner):
    return self.recorder.metrics[-1] if self.recorder.metrics else None

@patch
def fit(self:Learner, epochs:int, lr=None, warmup:float=0.1, **args):
    "Train for `epochs`: linear warmup, then a constant learning rate"
    self._run(epochs, lr, lr_scheduler_type="constant_with_warmup", warmup_steps=warmup, **args)
    return self._after_fit()

@patch
def fit_one_cycle(self:Learner, epochs:int, lr=None, pct_start:float=0.25, onecycle:bool=False, **args):
    "Train for `epochs` with warmup then cosine annealing (`onecycle=True`: torch's OneCycleLR)"
    if onecycle: self._run(epochs, lr, schedule=("onecycle", pct_start), **args)
    else: self._run(epochs, lr, lr_scheduler_type="cosine", warmup_steps=pct_start, **args)
    return self._after_fit()

# %% ../nbs/05_learner.ipynb #65944eed
@patch
def freeze(self:Learner):
    "Train the head only (and use the feature cache, if one is configured)"
    set_regime(self.model, "head")
    if getattr(self, "_saved_cache", None): self.cache, self._saved_cache, self._features = self._saved_cache, None, {}
    return self

@patch
def unfreeze(self:Learner):
    "Train the encoder too (its adapters, for a LoRA model); the feature cache is set aside"
    if getattr(self.model, "adapter_params", None) and hasattr(self.model.encoder, "peft_config"): thaw_adapters(self.model)
    else: set_regime(self.model, "full")
    if self.cache is not None: self._saved_cache, self.cache, self._features = self.cache, None, {}
    return self

@patch
def freeze_to(self:Learner, n:int):
    "Freeze the encoder's embeddings and first n layers"
    freeze_to(self.model, n)
    if self.cache is not None: self._saved_cache, self.cache, self._features = self.cache, None, {}
    return self

# %% ../nbs/05_learner.ipynb #0257c8f1
class SuggestedLRs(dict):
    "Learning rates suggested by `lr_find`"
    def __getattr__(self, k):
        try: return self[k]
        except KeyError: raise AttributeError(k) from None
    def __repr__(self): return "SuggestedLRs(" + ", ".join(f"{k}={v:.2e}" for k, v in self.items()) + ")"

def valley(lrs, losses):
    "fastai's valley: halfway along the longest run over which the loss keeps falling"
    n = len(losses)
    if n < 3: return float(lrs[int(np.argmin(losses))])
    max_start, max_end, lds = 0, 0, [1] * n
    for i in range(1, n):
        for j in range(i):
            if losses[i] < losses[j] and lds[i] < lds[j] + 1: lds[i] = lds[j] + 1
            if lds[max_end] < lds[i]: max_end, max_start = i, i - lds[i]
    sections = (max_end - max_start) / 3
    return float(lrs[max_start + int(sections) + int(sections / 2)])

def steep(lrs, losses):
    "The LR where the loss falls fastest against log LR"
    if len(losses) < 3: return lrs[0]
    g = np.gradient(np.asarray(losses), np.log(np.asarray(lrs)))
    return float(lrs[int(np.argmin(g))])

# %% ../nbs/05_learner.ipynb #0850ed65
@patch
def lr_find(self:Learner, start:float=1e-7, end:float=1.0, steps:int=100, stop_div:bool=True, plot:bool=False) -> SuggestedLRs:
    "LR range test: suggests `valley` and `steep`, and restores the model afterwards"
    if not self.model.head.standardizer_fitted: self.fit_standardizer()   # before the snapshot, which the test restores
    state = copy.deepcopy(self.model.state_dict())
    finder = LRFinder(stop_div=stop_div)
    t, calibrating, seen = self.trainer, self.calibration.active, len(self.recorder.losses)
    t.add_callback(finder); self.calibration.active = False
    try:
        self._run(epochs=1, lr=start, max_steps=steps, schedule=("range", start, end), eval=False, record=False,
                  logging_steps=1, max_grad_norm=0.0, **({"logging_nan_inf_filter": False} if "logging_nan_inf_filter" in _TA_FIELDS else {}))
    finally:
        t.remove_callback(finder); self.calibration.active = calibrating
        del self.recorder.losses[seen:], self.recorder.lrs[seen:]     # the range test is not training
        self.model.load_state_dict(state); t.optimizer, t.lr_scheduler = None, None
    lrs, losses = finder.lrs, finder.losses
    if len(losses) < steps and len(losses) > 8: lrs, losses = lrs[:-3], losses[:-3]   # stopped on divergence: drop the blow-up
    self.lr_curve = (lrs, losses)
    sugg = SuggestedLRs(valley=valley(lrs, losses), steep=steep(lrs, losses))
    if plot: self.plot_lr_find(sugg)
    return sugg

@patch
def plot_lr_find(self:Learner, sugg=None):
    "Plot the last `lr_find` curve (needs matplotlib)"
    import matplotlib.pyplot as plt
    lrs, losses = self.lr_curve
    fig, ax = plt.subplots(figsize=(6, 3.5))
    ax.plot(lrs, losses); ax.set_xscale("log"); ax.set_xlabel("learning rate"); ax.set_ylabel("loss (smoothed)")
    for (name, v), c in zip((sugg or {}).items(), ("C1", "C2", "C3", "C4")): ax.axvline(v, ls="--", lw=1, color=c, label=f"{name} {v:.1e}")
    if sugg: ax.legend()
    return fig

# %% ../nbs/05_learner.ipynb #aa8e1e8f
@patch
def show_batch(self:Learner, n:int=2, split:str="train", max_chars:int=300):
    "Print the first `n` rows of a split with their anchors visible"
    self.data.show_batch(n, split, max_chars)

# %% ../nbs/05_learner.ipynb #17e257c6
@patch
def decider(self:Learner, **kw):
    "A `sysone.inference.Decider` over the learner's model in memory"
    from sysone.inference import Decider
    return Decider(self.model, self.data.builder, dict(self.temperatures),
                   **({"act_threshold": self.act_threshold, "act_score": self.act_score or "head"} | kw))

@patch
def predict(self:Learner, state, questions:dict, **kw) -> dict:
    "Answers in the Jev schema from the model in memory"
    return self.decider(**kw).predict(state, questions)

@patch
def export(self:Learner, path, **kw):
    "Write the model, template, transforms and temperatures to `path` (see `sysone.inference.export_learner`); on several GPUs, the main process writes"
    from sysone.inference import export_learner
    if self.trainer.is_world_process_zero(): path = export_learner(self, path, **kw)
    self.trainer.accelerator.wait_for_everyone()          # the others wait until it is written
    return Path(path)

# %% ../nbs/05_learner.ipynb #23f1d894
def decision_learner(data:TypedDecisions, encoder, train="head", cache:str|None=None, template=None, head:str="laya",
                     head_layers:int|None=None, init_from:str|None=None, loss=None, lr=None, preset:str|None=None,
                     dtype=None, lora:dict|None=None, standardize:bool=False, readout:str="anchor", query:str|None=None,
                     act:bool=False, pair_dim:int=256, **kw) -> Learner:
    "A `Learner` for `data` on the encoder `encoder` (a Hub id, a folder or an `EncoderSpec`), with regime `train`"
    spec = encoder if isinstance(encoder, EncoderSpec) else EncoderSpec.from_pretrained(encoder)
    template = template if template is not None else data.template if data.template is not None else spec.template
    if isinstance(template, str): template = RowTemplate.preset(template, tokenizer=spec.tokenizer)
    data.bind(spec.processor or spec.tokenizer, template, streams=list(spec.streams.values()))
    scorer = {"laya": "laya", "mlp": "laya", "linear": "linear", "gliner2": "gliner2", "pair": "pair"}[head]
    layers = head_layers if head_layers is not None else 0 if (head in ("mlp", "linear", "gliner2", "pair") or cache == "masks") else 2
    enc = spec.load_encoder(**({"dtype": dtype} if dtype is not None else {}))    # float32 unless told otherwise
    qw = None
    if query is not None and query.startswith("stream:"):
        name = query.removeprefix("stream:")
        if name not in getattr(enc, "sides", {}): raise ValueError(f"query {query!r} needs a stream encoder with a {name!r} stream")
        qw = enc.sides[name].out_width
    hd = DecisionHead(spec.width, layers, scorer, init_from=init_from, standardize=standardize, readout=readout, query=query,
                      query_width=qw, pair_dim=pair_dim, act=act)
    model = EncoderDecisionModel(enc, hd, spec)
    set_regime(model, train, **(lora or {}))
    return Learner(data, model, loss=loss, cache=cache, lr=lr if lr is not None else 1e-4, preset=preset, **kw)
