"""Masked diffusion language models as decision models: a Qwen3 MDLM made bidirectional with transformers' own classes, its own Yes and No as the head, and the layout jev-dllm reads decisions in.

Docs: https://sgaseretto.github.io/sysonelib/mdlm.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/24_mdlm.ipynb.

# %% auto #0
__all__ = ['ENCODER', 'JEV_SYSTEM', 'JEV_USER', 'JEV_KINDS', 'JEV_ROW', 'A2DQwen3Config', 'A2DQwen3Model', 'decision_learner',
           'zero_shot', 'lm_logits', 'mdlm_sample']

# %% ../nbs/24_mdlm.ipynb #02373638
import math
import torch
import torch.nn.functional as F
from fastcore.meta import delegates
from transformers import AutoConfig, AutoModel, Qwen3Config, Qwen3Model
from transformers.masking_utils import create_bidirectional_mask
from transformers.models.qwen3.modeling_qwen3 import Qwen3Attention

from .core import *
from .template import *
from .data import TypedDecisions
from .models import *
from .losses import SoftCE
from .learner import Learner
from .learner import decision_learner as _decision_learner
from .inference import Decider, sample, adapters_off

# %% ../nbs/24_mdlm.ipynb #83cdf0aa
class A2DQwen3Config(Qwen3Config):
    "Qwen3's configuration under the model type the diffusion checkpoints carry"
    model_type = "a2d-qwen3"

class A2DQwen3Model(Qwen3Model):
    "Qwen3 attending both ways: every token sees every other, padding aside, as a masked diffusion model needs"
    config_class = A2DQwen3Config
    def __init__(self, config):
        super().__init__(config)
        for m in self.modules():
            if isinstance(m, Qwen3Attention): m.is_causal = False
    def forward(self, input_ids=None, attention_mask=None, inputs_embeds=None, **kw):
        kw.pop("use_cache", None); kw.pop("past_key_values", None)
        if inputs_embeds is None: inputs_embeds = self.embed_tokens(input_ids)
        if not isinstance(attention_mask, dict):
            m = create_bidirectional_mask(self.config, inputs_embeds, attention_mask)      # positional: the argument was renamed in 5.x
            attention_mask = {t: m for t in set(self.config.layer_types)}
        return super().forward(inputs_embeds=inputs_embeds, attention_mask=attention_mask, use_cache=False, **kw)

AutoConfig.register("a2d-qwen3", A2DQwen3Config, exist_ok=True)
AutoModel.register(A2DQwen3Config, A2DQwen3Model, exist_ok=True)

# %% ../nbs/24_mdlm.ipynb #2c24b2ad
ENCODER = "dllm-hub/Qwen3-0.6B-diffusion-mdlm-v0.1"
JEV_SYSTEM = "You are a helpful assistant."
JEV_USER = "State:\n{state}\n\nQuestion:\n{instructions}\n\n{options}"
_JEV_OPTIONS = {"header": "For each option, mark Yes if it answers the question, otherwise No.\n", "option": "{text}: {mask}", "sep": "\n"}
JEV_KINDS = {"choice": _JEV_OPTIONS, "score": _JEV_OPTIONS, "noul": {"header": "Answer Yes or No.\nAnswer:", "option": "{mask}", "sep": ""}}
JEV_ROW = "<|im_start|>system\n" + JEV_SYSTEM + "<|im_end|>\n<|im_start|>user\n" + JEV_USER + "<|im_end|>\n"

register_preset("jev", start=None, sep=None, end=None, mask="<|mask|>", row=JEV_ROW, option="{text}: {mask}", option_sep="\n",
                kinds=JEV_KINDS, max_len=4096, head_max_len=2048, option_tokens=512, truncate="right")
FAMILIES["a2d-qwen3"] = ("jev", ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"])

# %% ../nbs/24_mdlm.ipynb #bce7de42
@delegates(_decision_learner, keep=True)
def decision_learner(data:TypedDecisions, encoder=ENCODER, train="lora", head:str="yesno", loss=None, lr=(2e-4, 1e-3),
                     lora:dict|None=None, cache="auto", cache_dtype:str="float32", **kw) -> Learner:
    "A masked diffusion model's `Learner`: its own Yes/No at each option's slot, LoRA on every linear layer, soft cross-entropy with an RPS term"
    if cache == "auto": cache = "masks" if train == "head" else None          # a frozen model's slots, computed once
    lora = ({"r": 16, "alpha": 32} | (lora or {})) if train in ("lora", "mica") else lora
    learn = _decision_learner(data, encoder, train=train, head=head, loss=loss if loss is not None else SoftCE(0.25), lr=lr, lora=lora,
                              cache=cache, cache_dtype=cache_dtype, **kw)
    learn.merge_adapters = False        # its exports keep the base model, which writes, beside the adapter, which decides
    return learn

def zero_shot(encoder=ENCODER, dtype=torch.float32, **kw) -> Decider:
    "The untrained model as a decider: its own Yes against its No at each answer slot"
    spec = encoder if isinstance(encoder, EncoderSpec) else EncoderSpec.from_pretrained(encoder)
    enc = spec.load_encoder(dtype=dtype)
    head = DecisionHead(spec.width, layers=0, scorer="yesno").init_yesno(enc, spec.tokenizer)
    return Decider(EncoderDecisionModel(enc, head, spec), spec.builder(), **kw)

# %% ../nbs/24_mdlm.ipynb #ec15939f
def lm_logits(model, ids, at, attention_mask=None):
    "The model's logits for the tokens at positions `at` (a boolean mask over `ids`), from its tied input embeddings"
    h = model(input_ids=ids, attention_mask=attention_mask).last_hidden_state[at]
    base = model.get_base_model() if hasattr(model, "get_base_model") else model
    return F.linear(h, base.get_input_embeddings().weight.to(h.dtype)).float()

def mdlm_sample(config:A2DQwen3Config, model, ids, tokenizer=None, max_new_tokens:int=0, steps:int|None=None, block_size:int=32,
                temperature:float=0.0, remasking:str="low_confidence", mask_id:int|None=None):
    "Fill every mask of `ids` and `max_new_tokens` more: block by block from the left, each block over its share of `steps`, most confident first"
    if ids.shape[0] != 1: raise ValueError("the sampler writes one sequence at a time")
    mask_id = tokenizer.mask_token_id if mask_id is None else mask_id
    x = torch.cat([ids, torch.full((1, max_new_tokens), mask_id, dtype=ids.dtype, device=ids.device)], 1)
    todo = (x[0] == mask_id).nonzero().flatten()
    blocks = todo.split(block_size)
    per = max(1, (steps or len(todo)) // max(1, len(blocks)))            # steps per block
    for blk in blocks:
        for s in range(per):
            left = blk[x[0, blk] == mask_id]
            if not len(left): break
            at = torch.zeros_like(x, dtype=torch.bool); at[0, left] = True
            z = lm_logits(model, x, at)
            z[:, mask_id] = float("-inf")                                       # a mask is never an answer
            if temperature > 0:      # the Gumbel trick, in float64 as dllm does: argmax of p / (−log u)^τ
                pick = (z.double().softmax(-1) / (-torch.rand_like(z, dtype=torch.float64).log()) ** temperature).argmax(-1)
            else: pick = z.argmax(-1)
            conf = z.softmax(-1).gather(-1, pick[:, None])[:, 0] if remasking == "low_confidence" else torch.rand(len(left), device=z.device)
            keep = conf.topk(min(math.ceil(len(left) / (per - s)), len(left))).indices      # what is left, spread over the steps left
            x[0, left[keep]] = pick[keep]
    return x

sample.register(mdlm_sample)
