"""ModernVBERT under the sysone head: its image tiles spliced into Laya's row, the pixel batches its encoder expects, and its image defaults, so the multimodal application runs it beside NeoMME.

Docs: https://sgaseretto.github.io/sysonelib/modernvbert.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/23_modernvbert.ipynb.

# %% auto #0
__all__ = ['IDEFICS3_TOKENS', 'ENCODER', 'idefics3_block', 'build_idefics3_rows', 'modernvbert_inputs', 'tiles_for',
           'idefics3_image_side', 'idefics3_prepare']

# %% ../nbs/23_modernvbert.ipynb #26e9049a
import torch

from transformers import Idefics3Processor, ModernVBertConfig

from .core import *
from .template import *
from .models import *

# %% ../nbs/23_modernvbert.ipynb #59c7c712
IDEFICS3_TOKENS = ("<fake_token_around_image>", "<global-img>") + tuple(f"<row_{i}_col_{j}>" for i in range(1, 7) for j in range(1, 7))

def idefics3_block(builder:RowBuilder, image) -> tuple:
    "The ids of one image as an Idefics3 processor lays it out (its tiles, then the global view), and its pixels and pixel mask"
    proc = builder.processor
    feat = proc.image_processor(images=[[image]], return_row_col_info=True, return_tensors="pt")
    text = proc.replace_image_token({"rows": feat["rows"], "cols": feat["cols"]}, 0)
    return builder.tok(text, add_special_tokens=False)["input_ids"], feat["pixel_values"][0], feat["pixel_attention_mask"][0]

def build_idefics3_rows(processor:Idefics3Processor, builder:RowBuilder, record:dict, *, skip_errors:bool=False) -> list:
    "Rows of a transformed record for an Idefics3-style processor: text by the builder's budgets, the image as tiles of <image> tokens"
    images = record.get("images") or []
    if len(images) > 1: raise ValueError("a ModernVBERT row holds one image")
    for s in IDEFICS3_TOKENS:                                     # user text never smuggles in an image token
        if s not in builder.extra_scrub: builder.extra_scrub.append(s)
    ids_img, pixels, mask = idefics3_block(builder, images[0]) if images else (None, None, None)
    extras = {"pixel_values": pixels, "pixel_attention_mask": mask, "image_tiles": len(pixels)} if images else {"image_tiles": 0}
    gold, rows = record.get("gold") or {}, []
    for qid, q, ids, markers, _, spans in builder._layout(record, ids_img, skip_errors):
        target, label = q.target(gold.get(qid))
        rows.append(Row(ids, markers, q.qtype, target, label, meta={"qid": qid, "case": record.get("id")}, extras=dict(extras),
                        spans=spans, answerable=q.answerable(gold.get(qid))))
    return rows

processor_rows.register(build_idefics3_rows)
EXTRA_COLLATE["pixel_attention_mask"] = "cat"            # tiles concatenate, as `pixel_values` do; the hook below regroups them

# %% ../nbs/23_modernvbert.ipynb #e545541b
def modernvbert_inputs(config:ModernVBertConfig, inputs:dict) -> dict:
    "A batch's concatenated tiles regrouped per row, (batch, max tiles, 3, H, W), zero-padded, and the pixel mask alike"
    kw = dict(inputs); n = kw.pop("image_tiles", None)
    pv, pm = kw.get("pixel_values"), kw.get("pixel_attention_mask")
    if n is None or pv is None: return kw
    n = [int(v) for v in n.reshape(-1).tolist()]
    if max(n) == 0: kw.pop("pixel_values"); kw.pop("pixel_attention_mask", None); return kw
    out = pv.new_zeros(len(n), max(n), *pv.shape[1:])
    mask = pm.new_zeros(len(n), max(n), *pm.shape[1:]) if pm is not None else None
    s = 0
    for b, k in enumerate(n):
        out[b, :k] = pv[s:s + k]
        if mask is not None: mask[b, :k] = pm[s:s + k]
        s += k
    kw["pixel_values"] = out
    if mask is not None: kw["pixel_attention_mask"] = mask
    return kw

encoder_inputs.register(modernvbert_inputs)

# %% ../nbs/23_modernvbert.ipynb #b734a8c4
ENCODER = "ModernVBERT/modernvbert"

def tiles_for(side:int|None, tile:int=512) -> int:
    "The tiles a square image makes at `side` pixels (None: the checkpoint's 2,048): one up to a tile, else a grid and the global view"
    n = -(-(side or 2048) // tile)
    return 1 if n <= 1 else n * n + 1

def idefics3_image_side(processor:Idefics3Processor) -> int:
    "An Idefics3 processor's default image side: one tile, the processor's own tile size (512 pixels for ModernVBERT)"
    return processor.image_processor.max_image_size["longest_edge"]

def idefics3_prepare(processor:Idefics3Processor, side:int|None) -> int:
    "Tile at `side` pixels (None: the processor's own size): the tiles a square image then makes, the global view included"
    if side is not None: processor.image_processor.size = {"longest_edge": side}
    return tiles_for(side, processor.image_processor.max_image_size["longest_edge"])

default_image_side.register(idefics3_image_side)
prepare_processor.register(idefics3_prepare)
