"""`EncoderSpec`, `DecisionHead` and `EncoderDecisionModel`: an encoder becomes a decision model through what the checkpoint offers, Laya's head sized to it, and a training regime.

Docs: https://sgaseretto.github.io/sysonelib/models.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_models.ipynb.

# %% auto #0
__all__ = ['FAMILIES', 'ENCODER_SOURCES', 'SOURCE_MODULES', 'MODEL_TYPES', 'CHECKPOINTS', 'ensure_source', 'ensure_model_type', 'EncoderSpec', 'PairScorer', 'YesNoScorer', 'make_scorer', 'DecisionHead', 'shared_pairs', 'act_probability', 'to_laya_names', 'from_laya_names', 'read_tensors', 'Checkpoint', 'SysoneExport', 'LayaCheckpoint', 'split_repo', 'checkpoint', 'head_weights', 'warm_start', 'encoder_inputs', 'EncoderDecisionModel', 'StreamOutput', 'distinct_rows', 'ProjMLP', 'SideEncoder', 'stream_memo', 'StreamEncoder', 'lora_config', 'set_regime', 'thaw_adapters', 'encoder_layers', 'freeze_to', 'GatedCrossAttention', 'XAttnLayer', 'add_cross_attention', 'save_stream_encoder', 'load_stream_encoder', 'merged_encoder', 'laya_temperatures', 'load_laya', 'laya_state_dict', 'is_laya_compatible', 'is_gliner_checkpoint', 'load_gliner_encoder', 'GlinerCheckpoint', 'gliner_warm_start']

# %% ../nbs/03_models.ipynb #3c0f3c0a
import copy, importlib, json, os, re, struct, urllib.request, warnings
from contextlib import contextmanager, nullcontext
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from fastcore.basics import patch, store_attr
from transformers import AutoConfig, AutoModel, AutoTokenizer

from .core import *
from .template import RowTemplate, RowBuilder

# %% ../nbs/03_models.ipynb #0ab359e7
# family: (row template preset, LoRA target modules on the attention projections)
FAMILIES = {
    "modernbert": ("laya", r".*\.attn\.(Wqkv|Wo)"),
    "neomme": ("neomme", ["q_proj", "k_proj", "v_proj", "o_proj"]),
    "modernvbert": ("modernvbert", r"text_model\.layers\.\d+\.attn\.(Wqkv|Wo)"),     # the text tower's attention; the image tower stays frozen
    "deberta-v2": ("laya", ["query_proj", "key_proj", "value_proj", "attention.output.dense"]),
    "bert": ("auto", ["query", "key", "value", "attention.output.dense"]),
    "roberta": ("auto", ["query", "key", "value", "attention.output.dense"]),
    "xlm-roberta": ("auto", ["query", "key", "value", "attention.output.dense"]),
    "electra": ("auto", ["query", "key", "value", "attention.output.dense"]),
}
ENCODER_SOURCES = []   # (name, detect(id, revision) -> bool, spec(id, revision, **kw) -> EncoderSpec)

def _text_config(config): return getattr(config, "text_config", None) or config

def _is_multimodal(config):
    return getattr(config, "vision_config", None) is not None or getattr(config, "image_token_id", None) is not None

SOURCE_MODULES = {"protst": "sysone.protein"}   # sources that sysone's own modules register, imported when a spec or an export names them

def ensure_source(source:str|None):
    "Import the sysone module that registers `source`, when it is one of sysone's own"
    if source in SOURCE_MODULES: importlib.import_module(SOURCE_MODULES[source])

MODEL_TYPES = {"a2d-qwen3": "sysone.mdlm"}   # model types that sysone's own modules register with transformers

def ensure_model_type(src=None, revision:str|None=None, model_type:str|None=None):
    "Import the sysone module that registers a model type with transformers (`model_type`, or the one `src`'s config names), when it is one of sysone's own"
    if model_type is None and src is not None:
        from transformers import PretrainedConfig
        try: model_type = PretrainedConfig.get_config_dict(str(src), revision=revision)[0].get("model_type")
        except Exception: return
    if model_type in MODEL_TYPES: importlib.import_module(MODEL_TYPES[model_type])

class EncoderSpec:
    "What an encoder checkpoint offers: width, context, family, modality, special tokens, default template, side streams"
    def __init__(self, id:str, config, tokenizer, processor=None, revision:str|None=None, source:str="transformers",
                 template:RowTemplate|None=None, loader=None, streams:list|None=None):
        store_attr()
        self.streams = {s.name: s for s in streams or []}
        self.width = _text_config(config).hidden_size
        self.context = getattr(_text_config(config), "max_position_embeddings", None) or 512
        self.family = getattr(config, "model_type", None)
        self.modality = "multimodal" if processor is not None else "text"
        if self.template is None: self.template = self._default_template()

    @classmethod
    def from_pretrained(cls, id:str, revision:str|None=None, source:str|None=None, **kw):
        "The spec of a Hub id or local folder (`source` names a registered source, skipping detection)"
        ensure_source(source); ensure_model_type(id, revision)
        for name, detect, make in ENCODER_SOURCES:
            if source is not None and name == source: return make(id, revision=revision, **kw)
        for name, detect, make in ENCODER_SOURCES:
            if detect(id, revision): return make(id, revision=revision, **kw)
        config = AutoConfig.from_pretrained(id, revision=revision)
        processor = None
        if _is_multimodal(config):
            from transformers import AutoProcessor
            processor = AutoProcessor.from_pretrained(id, revision=revision)
        tokenizer = processor.tokenizer if processor is not None else AutoTokenizer.from_pretrained(id, revision=revision)
        return cls(id, config, tokenizer, processor, revision=revision)

    def __repr__(self):
        streams = f", streams {list(self.streams)}" if self.streams else ""
        return (f"EncoderSpec({self.id}: {self.family}, width {self.width}, context {self.context}, {self.modality}, "
                f"template {self.template.name}{streams})")

# %% ../nbs/03_models.ipynb #0bf95656
@patch
def _default_template(self:EncoderSpec) -> RowTemplate:
    preset = FAMILIES.get(self.family, ("auto", None))[0]
    t = RowTemplate.preset(preset, tokenizer=self.tokenizer)
    return t.replace(max_len=min(t.max_len, self.context)) if t.max_len > self.context else t

@patch(as_prop=True)
def specials(self:EncoderSpec) -> dict:
    "The tokenizer's special tokens"
    return {r: getattr(self.tokenizer, f"{r}_token", None) for r in ("cls", "sep", "mask", "pad", "unk", "bos", "eos")}

@patch(as_prop=True)
def lora_targets(self:EncoderSpec):
    "Default LoRA target modules for this family"
    t = FAMILIES.get(self.family, (None, None))[1]
    if t is None: raise ValueError(f"no default LoRA targets for {self.family!r}; pass a peft.LoraConfig")
    return t

@patch
def builder(self:EncoderSpec, template=None, tfms=None) -> RowBuilder:
    "A `RowBuilder` on this encoder's tokenizer (or processor), with its side streams"
    return RowBuilder(self.processor or self.tokenizer, template or self.template, tfms, streams=list(self.streams.values()))

@patch
def to_json(self:EncoderSpec) -> dict:
    "The encoder reference written to `sysone.json`"
    return {"id": self.id, "revision": self.revision, "source": self.source, "hidden_size": self.width,
            "family": self.family, "modality": self.modality}

# %% ../nbs/03_models.ipynb #bad80e8b
@patch
def load_encoder(self:EncoderSpec, dtype=torch.float32, **kw):
    "The encoder model, returning one hidden state per position, in float32 unless told otherwise ('auto': the checkpoint's)"
    if self.loader is not None: return self.loader(self, dtype=dtype, **kw)
    return AutoModel.from_pretrained(self.id, revision=self.revision, dtype=dtype, **kw)

# %% ../nbs/03_models.ipynb #9b434a8f
class PairScorer(nn.Module):
    "Scores an option vector against a query vector: an MLP over [o, q, o·q], both projected to `dim` first"
    def __init__(self, width:int, query_width:int, dim:int=256):
        super().__init__()
        self.po, self.pq = nn.Linear(width, dim), nn.Linear(query_width, dim)
        self.mlp = nn.Sequential(nn.LayerNorm(3 * dim), nn.Linear(3 * dim, dim), nn.GELU(), nn.Linear(dim, 1))
    def forward(self, m, q):
        a, b = self.po(m), self.pq(q)[:, None, :].expand(-1, m.shape[1], -1)
        return self.mlp(torch.cat([a, b, a * b], -1))

class YesNoScorer(nn.Module):
    "A language model's own answer at a slot: the log-odds of its Yes token over its No token, h·(E_Yes − E_No), with a learned correction and scale"
    def __init__(self, width:int):
        super().__init__()
        self.register_buffer("w0", torch.zeros(width))      # E_Yes − E_No, saved with the head; `init_yesno` copies it in
        self.delta = nn.Parameter(torch.zeros(width))        # a learned correction to that direction
        self.log_scale = nn.Parameter(torch.zeros(()))       # a learned scale, as its log: weight decay pulls it towards 1
    def forward(self, m): return (m * (self.w0 + self.delta).to(m.dtype)).sum(-1, keepdim=True) * self.log_scale.exp().to(m.dtype)

def make_scorer(kind:str, width:int, query_width:int|None=None, dim:int=256) -> nn.Module:
    "The per-option scorer: `laya` (alias `mlp`), `linear`, `gliner2` (GLiNER2's classifier MLP), `pair` (against a query vector), or `yesno` (a language model's own Yes/No)"
    if kind in ("laya", "mlp"): return nn.Sequential(nn.LayerNorm(width), nn.Linear(width, width), nn.GELU(), nn.Linear(width, 1))
    if kind == "linear": return nn.Linear(width, 1)
    if kind == "gliner2": return nn.Sequential(nn.Linear(width, 2 * width), nn.ReLU(), nn.Linear(2 * width, 1))
    if kind == "pair":
        if query_width is None: raise ValueError("the pair scorer scores options against a query; give the head query='first' or 'stream:<name>'")
        return PairScorer(width, query_width, dim)
    if kind == "yesno": return YesNoScorer(width)
    raise ValueError(f"unknown scorer {kind!r}; use 'laya', 'mlp', 'linear', 'gliner2', 'pair' or 'yesno'")

class DecisionHead(nn.Module):
    "Type embedding, `layers` transformer layers and a shared scorer over the options; optionally a query vector and an act head"
    def __init__(self,
                 width:int, # the encoder's hidden size
                 layers:int=2, # transformer layers over the encoder output; 0 scores the anchors directly
                 scorer:str="laya", # "laya", "mlp", "linear", "gliner2", "pair" or "yesno"
                 dropout:float=0.1, # dropout in the transformer layers
                 nhead:int|None=None, # attention heads; width // 64 by default
                 init_from:str|None=None, # a Laya checkpoint, a sysone export or a GLiNER2 checkpoint to copy weights from
                 standardize:bool=False, # standardise the encoder's output per dimension before anything else (see `fit_standardizer`)
                 readout:str="anchor", # an option's vector: the one at its "anchor", or the mean over its own tokens ("span")
                 query:str|None=None, # a vector the pair scorer and the act head read: "first" (the row's first position) or "stream:<name>"
                 query_width:int|None=None, # a side stream query's width
                 pair_dim:int=256, # the pair scorer's projection width
                 act:bool=False): # an act head, Laya's: whether to act on the answer or escalate the case
        super().__init__()
        if readout not in ("anchor", "span"): raise ValueError(f"readout must be 'anchor' or 'span', not {readout!r}")
        if query is not None and query != "first" and not str(query).startswith("stream:"):
            raise ValueError(f"query must be None, 'first' or 'stream:<name>', not {query!r}")
        self.width, self.layers, self.scorer_kind, self.dropout, self.standardize = width, layers, scorer, dropout, standardize
        self.readout, self.query, self.pair_dim, self.act = readout, query, pair_dim, act
        self.query_width = None if query is None else width if query == "first" else query_width
        if query is not None and self.query_width is None: raise ValueError(f"give the width of the {query!r} vector (query_width=...)")
        if standardize: self.register_buffer("in_mean", torch.zeros(width)); self.register_buffer("in_std", torch.ones(width))
        if standardize and self.stream_query:
            self.register_buffer("q_mean", torch.zeros(self.query_width)); self.register_buffer("q_std", torch.ones(self.query_width))
        self.nhead = nhead or max(1, width // 64)
        self.type_emb = nn.Embedding(len(QTYPES), width)
        block = nn.TransformerEncoderLayer(width, self.nhead, 4 * width, dropout, batch_first=True, norm_first=True)
        self.blocks = nn.ModuleList([copy.deepcopy(block) for _ in range(layers)])
        self.scorer = make_scorer(scorer, width, self.query_width, pair_dim)
        if act: self.act_head = nn.Sequential(nn.Linear(width + (self.query_width if self.stream_query else 0) + 4, 256), nn.GELU(), nn.Linear(256, 2))
        if init_from: self.load_from(init_from)

    @property
    def stream_query(self) -> str|None:
        "The side stream whose pooled vector is the query, if the query is one"
        return self.query.removeprefix("stream:") if self.query and self.query.startswith("stream:") else None
    @property
    def needs_first(self) -> bool:
        "Whether the head reads the row's first position (an act head, or query='first')"
        return self.act or self.query == "first"

    def config(self) -> dict:
        "The head's shape, as written to `sysone.json`"
        return {"width": self.width, "layers": self.layers, "scorer": self.scorer_kind, "dropout": self.dropout, "nhead": self.nhead,
                "standardize": self.standardize, "readout": self.readout, "query": self.query, "query_width": self.query_width,
                "pair_dim": self.pair_dim, "act": self.act}

    @classmethod
    def from_config(cls, cfg:dict):
        "A head of the shape `config()` describes (weights not included)"
        keys = ("width", "layers", "scorer", "dropout", "nhead", "standardize", "readout", "query", "query_width", "pair_dim", "act")
        return cls(**{k: cfg[k] for k in keys if k in cfg})

# %% ../nbs/03_models.ipynb #ec705886
@patch
def score(self:DecisionHead, m, marker_mask, query=None):
    "Logits from option vectors (batch, K, width), against `query` when the scorer pairs; padded options get -1e4"
    z = self.scorer(m, query) if self.scorer_kind == "pair" else self.scorer(m)
    return z.squeeze(-1).float().masked_fill(~marker_mask.bool(), -1e4)

@patch
def _readout(self:DecisionHead, h, marker_pos, spans=None):
    "One vector per option: the one at its anchor, or the mean over its own tokens (an empty span falls back to the anchor)"
    at = torch.gather(h, 1, marker_pos.clamp(min=0)[:, :, None].expand(-1, -1, h.size(-1)))
    if self.readout == "anchor": return at
    if spans is None: raise ValueError("this head reads option spans (readout='span'); the batch has none")
    cs = torch.cat([h.new_zeros(h.shape[0], 1, h.shape[2]), h.cumsum(1)], 1)
    s, e = spans[..., 0].clamp(0, h.shape[1]), spans[..., 1].clamp(0, h.shape[1])
    pick = lambda i: torch.gather(cs, 1, i[:, :, None].expand(-1, -1, h.size(-1)))
    mean = (pick(e) - pick(s)) / (e - s).clamp(min=1)[:, :, None].to(h.dtype)
    return torch.where((e > s)[:, :, None], mean, at)

def shared_pairs(z, marker_pos, marker_mask):
    "Logits where a two-option row whose markers are one slot reads that slot's score s as the pair (0, s): its no, then its yes"
    if marker_pos is None or z.shape[1] < 2: return z
    pair = (marker_mask.sum(-1) == 2) & (marker_pos[:, 0] == marker_pos[:, 1])
    return torch.cat([torch.where(pair, torch.zeros_like(z[:, 0]), z[:, 0])[:, None], z[:, 1:]], 1)

@patch
def _decide(self:DecisionHead, m, marker_mask, first=None, query=None, marker_pos=None):
    "Logits from option vectors, and with an act head `(logits, act_logits)`"
    if self.stream_query and query is None: raise ValueError(f"this head scores options against {self.query!r}; the batch carries no such vector")
    q = first if self.query == "first" else self._standardized_query(query) if self.stream_query else None
    logits = shared_pairs(self.score(m, marker_mask, q), marker_pos, marker_mask)
    return (logits, self._act_logits(logits, marker_mask, first, q)) if self.act else logits

@patch
def forward(self:DecisionHead, h, attention_mask, marker_pos, marker_mask, qtype, spans=None, query=None):
    "Logits (batch, K) from the encoder's hidden states (batch, L, width); `(logits, act_logits)` with an act head"
    h = self._standardized(h.to(self.type_emb.weight.dtype)) + self.type_emb(qtype)[:, None, :]
    pad = ~attention_mask.bool()
    for blk in self.blocks: h = blk(h, src_key_padding_mask=pad)
    return self._decide(self._readout(h, marker_pos, spans), marker_mask, h[:, 0], query, marker_pos)

@patch
def forward_anchors(self:DecisionHead, anchors, marker_mask, qtype, query=None, first=None, marker_pos=None):
    "Logits from cached option vectors (batch, K, width), with the cached first position and query when the head reads them; only for `layers=0`"
    if self.layers: raise ValueError("anchor features only feed a head without layers; cache 'rows' for a head with layers")
    if self.needs_first and first is None: raise ValueError("this head reads the row's first position (an act head, or query='first'); cache it too")
    te = self.type_emb(qtype)
    m = self._standardized(anchors.to(te.dtype)) + te[:, None, :]
    f = self._standardized(first.to(te.dtype)) + te if first is not None else None
    return self._decide(m, marker_mask, f, query, marker_pos)

@patch
def _standardized(self:DecisionHead, x):
    "The encoder's vectors standardised per dimension, when the head standardises"
    return (x - self.in_mean) / self.in_std if self.standardize else x

@patch
def _standardized_query(self:DecisionHead, q):
    "A side stream's query vector, standardised with its own statistics when the head standardises"
    q = q.to(self.type_emb.weight.dtype)
    return (q - self.q_mean) / self.q_std if hasattr(self, "q_mean") else q

@patch(as_prop=True)
def standardizer_fitted(self:DecisionHead) -> bool:
    "Whether the standardisation's statistics have been set (a head without one needs none)"
    unset = lambda m, s: bool((m == 0).all()) and bool((s == 1).all())
    return not self.standardize or not (unset(self.in_mean, self.in_std) or (hasattr(self, "q_mean") and unset(self.q_mean, self.q_std)))

@patch
def fit_standardizer(self:DecisionHead, vectors, query=None):
    "Set the per-dimension mean and standard deviation from encoder vectors (..., width), and a stream query's from `query` (n, query_width)"
    if not self.standardize: raise ValueError("this head does not standardise; build it with DecisionHead(..., standardize=True)")
    v = torch.as_tensor(vectors).float().reshape(-1, self.width)
    with torch.no_grad():
        self.in_mean.copy_(v.mean(0)); self.in_std.copy_(v.std(0).clamp_min(1e-6))
        if hasattr(self, "q_mean"):
            if query is None: raise ValueError(f"this head standardises its {self.query!r} query too; pass its vectors (query=...)")
            qv = torch.as_tensor(query).float().reshape(-1, self.query_width)
            self.q_mean.copy_(qv.mean(0)); self.q_std.copy_(qv.std(0).clamp_min(1e-6))
    return self

# %% ../nbs/03_models.ipynb #434ee075
@patch
def init_yesno(self:DecisionHead, encoder, tokenizer, yes:str="Yes", no:str="No"):
    "Start a `yesno` head as the model's own answer: copy its Yes and No embedding rows (its tied output layer), and zero the type embedding"
    if self.scorer_kind != "yesno": raise ValueError(f"init_yesno is for a head with scorer='yesno', not {self.scorer_kind!r}")
    ids = [tokenizer(w, add_special_tokens=False)["input_ids"] for w in (yes, no)]
    if any(len(i) != 1 for i in ids): raise ValueError(f"{yes!r} and {no!r} must each be one token of this tokenizer, not {ids}")
    base = encoder.get_base_model() if hasattr(encoder, "get_base_model") else encoder
    E = base.get_input_embeddings().weight
    with torch.no_grad():
        self.scorer.w0.copy_((E[ids[0][0]] - E[ids[1][0]]).detach().float())
        self.type_emb.weight.zero_()
    return self

# %% ../nbs/03_models.ipynb #fc18d76e
@patch
def _act_logits(self:DecisionHead, logits, marker_mask, first, q=None):
    "Laya's act head: the first position (and a stream query) with the top probability, the top-1 margin, the normalised entropy and k/255"
    p = torch.softmax(logits.detach(), -1)
    k = marker_mask.sum(-1).clamp(min=2).float()
    ent = -(p * torch.log(p.clamp_min(1e-9))).sum(-1) / torch.log(k)
    top2 = p.topk(2, -1).values if p.size(-1) >= 2 else torch.cat([p, torch.zeros_like(p)], -1)
    feats = torch.stack([top2[:, 0], top2[:, 0] - top2[:, 1], ent, k / 255.0], -1)
    pooled = first.float() if not self.stream_query else torch.cat([first.float(), q.float()], -1)
    return self.act_head(torch.cat([pooled, feats], -1).to(self.act_head[0].weight.dtype)).float()

def act_probability(act_logits):
    "p(act) from act logits: the first class of a softmax over two, Laya's convention"
    return torch.softmax(torch.as_tensor(act_logits).float(), -1)[..., 0]

# %% ../nbs/03_models.ipynb #bfe8c9af
def to_laya_names(sd:dict) -> dict:
    "Head state-dict keys renamed to Laya's"
    return {re.sub(r"^blocks\.", "head.layers.", k): v for k, v in sd.items()}

def from_laya_names(sd:dict) -> dict:
    "Laya head keys renamed to `DecisionHead`'s, the act head's included (other keys dropped)"
    out = {}
    for k, v in sd.items():
        if k.startswith("head.layers."): out["blocks." + k[len("head.layers."):]] = v
        elif k.startswith(("type_emb.", "scorer.", "act_head.")): out[k] = v
    return out

# %% ../nbs/03_models.ipynb #6f9cc764
_ST_DTYPES = {"F32": np.float32, "F16": np.float16, "BF16": None, "I64": np.int64, "I32": np.int32, "U8": np.uint8, "BOOL": np.bool_}

def _to_tensor(buf, dtype, shape):
    if dtype == "BF16":
        a = np.frombuffer(buf, dtype=np.uint16).astype(np.uint32) << 16
        return torch.from_numpy(a.view(np.float32).reshape(shape).copy()).to(torch.bfloat16)
    return torch.from_numpy(np.frombuffer(buf, dtype=_ST_DTYPES[dtype]).reshape(shape).copy())

def _local_file(repo, filename, revision):
    p = Path(repo) / filename
    if p.exists(): return p
    if Path(repo).exists(): return None
    from huggingface_hub import try_to_load_from_cache
    c = try_to_load_from_cache(repo, filename, revision=revision)
    return Path(c) if isinstance(c, str) else None

def read_tensors(repo:str, filename:str="model.safetensors", select=None, revision:str|None=None) -> dict:
    "Tensors of a safetensors file (local, cached, or on the Hub via range requests) whose names pass `select`"
    select = select or (lambda k: True)
    local = _local_file(repo, filename, revision)
    if local is not None:
        from safetensors import safe_open
        with safe_open(str(local), "pt") as f: return {k: f.get_tensor(k) for k in f.keys() if select(k)}
    from huggingface_hub import hf_hub_url
    from huggingface_hub.utils import build_hf_headers
    url, headers = hf_hub_url(repo, filename, revision=revision), build_hf_headers()
    def get(a, b):
        req = urllib.request.Request(url, headers={**headers, "Range": f"bytes={a}-{b}"})
        with urllib.request.urlopen(req) as r: return r.read()
    n = struct.unpack("<Q", get(0, 7))[0]
    header = json.loads(get(8, 8 + n - 1)); header.pop("__metadata__", None)
    out = {}
    for k, v in header.items():
        if not select(k): continue
        a, b = v["data_offsets"]
        out[k] = _to_tensor(get(8 + n + a, 8 + n + b - 1), v["dtype"], v["shape"]) if b > a else torch.empty(v["shape"])
    return out

# %% ../nbs/03_models.ipynb #f612c28a
class Checkpoint:
    "A head's source, a folder or a Hub repo (optionally a `subfolder` of it): its subclass says what its files hold"
    def __init__(self, src:str, subfolder:str|None=None): self.src, self.subfolder = str(src), subfolder
    def __repr__(self): return f"{type(self).__name__}({self.src!r}" + (f", {self.subfolder!r})" if self.subfolder else ")")

class SysoneExport(Checkpoint): "A sysone export: the head's weights in `head.safetensors`"
class LayaCheckpoint(Checkpoint): "A Laya checkpoint: `rl_agent_config.json`, and the head beside the encoder in `model.safetensors`"

def split_repo(src:str):
    "A Hub id with an optional subfolder: 'owner/repo/sub' -> ('owner/repo', 'sub'); local paths pass through"
    src = str(src)
    if Path(src).exists() or src.startswith(("/", ".", "~")) or src.count("/") < 2: return src, None
    parts = src.split("/")
    return "/".join(parts[:2]), "/".join(parts[2:])

def _is_laya(src, subfolder=None):
    p = Path(src) / (subfolder or "")
    if p.exists(): return (p / "rl_agent_config.json").exists()
    try:
        from huggingface_hub import file_exists
        return file_exists(src, f"{subfolder + '/' if subfolder else ''}rl_agent_config.json")
    except Exception: return False

def _is_export(src, subfolder=None): return (Path(src) / (subfolder or "") / "head.safetensors").exists()

CHECKPOINTS = [(_is_export, SysoneExport), (_is_laya, LayaCheckpoint)]    # (detect(src, subfolder) -> bool, kind), tried in order

def checkpoint(src, subfolder:str|None=None) -> Checkpoint:
    "The checkpoint at `src`, typed by the first kind in `CHECKPOINTS` whose files it holds"
    if isinstance(src, Checkpoint): return src
    if subfolder is None: src, subfolder = split_repo(src)
    for detect, kind in CHECKPOINTS:
        if detect(src, subfolder): return kind(src, subfolder)
    raise ValueError(f"{src!r} is not a Laya checkpoint, a sysone export or a known head source")

@dispatch
def head_weights(ckpt:SysoneExport) -> dict:
    "A sysone export's head weights"
    return read_tensors(str(Path(ckpt.src) / (ckpt.subfolder or "")), "head.safetensors")

@dispatch
def head_weights(ckpt:LayaCheckpoint) -> dict:
    "A Laya checkpoint's head weights, under sysone's names"
    fn = f"{ckpt.subfolder}/model.safetensors" if ckpt.subfolder else "model.safetensors"
    return from_laya_names(read_tensors(ckpt.src, fn, select=lambda k: not k.startswith("encoder.")))

@dispatch
def warm_start(head:DecisionHead, ckpt:Checkpoint, *, strict:bool=True):
    "Copy a checkpoint's head weights into `head`, every name and shape checked: dispatched on the checkpoint's kind"
    sd, own, src = head_weights(ckpt), head.state_dict(), ckpt.src
    if not head.act: sd = {k: v for k, v in sd.items() if not k.startswith("act_head.")}     # a head without one ignores it
    bad = [f"{k}: {tuple(v.shape)} vs {tuple(own[k].shape)}" for k, v in sd.items() if k in own and v.shape != own[k].shape]
    if bad: raise ValueError(f"head shapes do not match {src!r} (width {head.width}, {head.layers} layers): {bad[:3]}")
    missing = [k for k in own if k not in sd and k not in ("in_mean", "in_std")]    # statistics of an encoder, not weights
    extra = [k for k in sd if k not in own]
    if missing and strict: raise ValueError(f"{src!r} lacks head parameters {missing[:3]}")
    if extra and strict: raise ValueError(f"{src!r} has head parameters this head lacks ({extra[:3]}): match its layers, or strict=False")
    head.load_state_dict({k: v.to(own[k].dtype) for k, v in sd.items() if k in own}, strict=False)
    return head

@patch
def load_from(self:DecisionHead, src, subfolder:str|None=None, strict:bool=True):
    "Copy weights from a Laya checkpoint, a sysone export or any kind in `CHECKPOINTS`"
    return warm_start(self, checkpoint(src, subfolder), strict=strict)

# %% ../nbs/03_models.ipynb #ae3c9eda
@dispatch
def encoder_inputs(config:object, inputs:dict) -> dict:
    "The keyword arguments an encoder is called with, reshaped where its adapter says so: dispatched on the encoder config's class"
    if load_adapter(config): return encoder_inputs(config, inputs)
    return inputs

class EncoderDecisionModel(nn.Module):
    "An encoder and a `DecisionHead`: logits over each row's options"
    def __init__(self, encoder:nn.Module, head:DecisionHead, spec:EncoderSpec|None=None):
        super().__init__()
        self.encoder, self.head, self.spec = encoder, head, spec
        self.frozen, self.regime = False, "full"

    def encode_full(self, input_ids, attention_mask, **encoder_kwargs):
        "The encoder's output: its `last_hidden_state`, and a stream encoder's `stream_vectors`"
        encoder_kwargs = encoder_inputs(getattr(self.encoder, "config", None), encoder_kwargs)
        with torch.no_grad() if self.frozen else nullcontext():
            return self.encoder(input_ids=input_ids, attention_mask=attention_mask, **encoder_kwargs)

    def encode(self, input_ids, attention_mask, **encoder_kwargs):
        "The encoder's last hidden state"
        return self.encode_full(input_ids, attention_mask, **encoder_kwargs).last_hidden_state

    def stream_query(self, out):
        "The head's query vector from an encoder output, when the query is a side stream's"
        name = self.head.stream_query
        if name is None: return None
        vecs = getattr(out, "stream_vectors", None) or {}
        if name not in vecs: raise ValueError(f"the head's query is stream {name!r}, which the encoder did not return: is it a StreamEncoder with that stream, and does the batch carry it?")
        return vecs[name]

    def forward(self, input_ids=None, attention_mask=None, marker_pos=None, marker_mask=None, qtype=None,
                anchors=None, hidden=None, query=None, first=None, spans=None, answerable=None, **encoder_kwargs):
        if anchors is not None: return self.head.forward_anchors(anchors, marker_mask, qtype, query=query, first=first, marker_pos=marker_pos)
        if hidden is None:
            out = self.encode_full(input_ids, attention_mask, **encoder_kwargs)
            hidden, query = out.last_hidden_state, query if query is not None else self.stream_query(out)
        return self.head(hidden, attention_mask, marker_pos, marker_mask, qtype, spans=spans, query=query)

    def train(self, mode:bool=True):
        super().train(mode)
        if self.frozen: self.encoder.eval()
        return self

# %% ../nbs/03_models.ipynb #412a97b8
@patch
def gradient_checkpointing_enable(self:EncoderDecisionModel, gradient_checkpointing_kwargs=None, **kw):
    "Checkpoint the encoder's layers (what `TrainingArguments(gradient_checkpointing=True)` calls; newer transformers adds `every_n_layers` and `offload`)"
    gk = {"use_reentrant": False} | (gradient_checkpointing_kwargs or {})
    self.encoder.gradient_checkpointing_enable(gradient_checkpointing_kwargs=gk, **kw)

@patch
def gradient_checkpointing_disable(self:EncoderDecisionModel): self.encoder.gradient_checkpointing_disable()

@patch(as_prop=True)
def device(self:EncoderDecisionModel): return self.head.type_emb.weight.device

@patch
def n_params(self:EncoderDecisionModel) -> dict:
    "Total and trainable parameter counts, for the encoder and the head"
    c = lambda m, t: sum(p.numel() for p in m.parameters() if p.requires_grad or not t)
    return {"encoder": c(self.encoder, False), "head": c(self.head, False),
            "trainable": c(self.encoder, True) * (not self.frozen) + c(self.head, True)}

# %% ../nbs/03_models.ipynb #6c853ef8
@dataclass
class StreamOutput:
    "A stream encoder's output: the text's hidden states, and each side stream's pooled vector"
    last_hidden_state: torch.Tensor
    stream_vectors: dict = field(default_factory=dict)

def distinct_rows(ids, mask) -> tuple:
    "The first index of each distinct (ids, mask) row of a batch, and each row's distinct index"
    seen, first, inverse = {}, [], []
    for i, key in enumerate(map(tuple, torch.cat([ids, mask.to(ids.dtype)], -1).tolist())):
        j = seen.setdefault(key, len(first))
        if j == len(first): first.append(i)
        inverse.append(j)
    return first, inverse

class ProjMLP(nn.Sequential):
    "Linear → ReLU → Linear: the projection head of a CLIP-style tower"
    def __init__(self, dims):
        super().__init__(nn.Linear(dims[0], dims[1]), nn.ReLU(), nn.Linear(dims[1], dims[2])); self.dims = list(dims)

class SideEncoder(nn.Module):
    "A side stream's encoder: a transformers model over its tokens, pooled to one vector per input (the mean over its non-special tokens, optionally projected), run once per distinct input of a batch"
    def __init__(self, model:nn.Module, special_ids=(), proj:ProjMLP|None=None):
        super().__init__()
        self.model, self.proj, self.special_ids = model, proj, [int(i) for i in special_ids]
        self.memo = None                            # {input: pooled vector} while `stream_memo` holds one
        self.dedupe = True                          # encode each distinct input once; an attribution turns it off (its batch is one row, repeated)
    @property
    def width(self) -> int: return self.model.config.hidden_size
    @property
    def out_width(self) -> int: return self.proj.dims[-1] if self.proj is not None else self.width

    def _run(self, ids, mask):
        h = self.model(input_ids=ids, attention_mask=mask).last_hidden_state
        keep = mask.bool()
        for s in self.special_ids: keep = keep & (ids != s)
        pooled = (h * keep[..., None].to(h.dtype)).sum(1) / keep.sum(1, keepdim=True).clamp(min=1).to(h.dtype)
        return h, (self.proj(pooled) if self.proj is not None else pooled)

    def forward(self, ids, mask, states:bool=False):
        "(hidden states (batch, P, width) if asked, else None; pooled vectors (batch, out_width))"
        first, inverse = distinct_rows(ids, mask) if self.dedupe else (list(range(len(ids))),) * 2
        inv = torch.tensor(inverse, device=ids.device)
        if self.memo is None or states or torch.is_grad_enabled():
            h, pooled = self._run(ids[first], mask[first])
            return (h[inv] if states else None), pooled[inv]
        keys = [ids[i][mask[i].bool()].cpu().numpy().tobytes() for i in first]
        todo = [j for j, k in enumerate(keys) if k not in self.memo]
        if todo:
            rows = [first[j] for j in todo]
            self.memo.update(zip([keys[j] for j in todo], self._run(ids[rows], mask[rows])[1]))
        return None, torch.stack([self.memo[k] for k in keys])[inv]

@contextmanager
def stream_memo(module:nn.Module):
    "While the block runs, every side encoder in `module` encodes each distinct input once, however the rows are batched (no-grad passes)"
    sides = [m for m in module.modules() if isinstance(m, SideEncoder)]
    for s in sides: s.memo = {}
    try: yield module
    finally:
        for s in sides: s.memo = None

class StreamEncoder(nn.Module):
    "A text encoder beside side-stream encoders: with `late` fusion they run apart and the head joins them; with `xattn` the text attends to a stream"
    base_model_prefix = ""                          # peft reads it off a model with a config: the towers sit at the top level
    def __init__(self, text:nn.Module, sides:dict):
        super().__init__()
        self.text, self.sides = text, nn.ModuleDict(sides)
        self.proj = nn.ModuleDict()                 # stream -> text width, for cross-attention
        self.config = text.config                   # the text encoder's: what the width, the family and the hooks read
        self.fusion, self.xattn, self._memory = "late", None, {}

    def forward(self, input_ids=None, attention_mask=None, **kw):
        vectors, memory = {}, {}
        for name, side in self.sides.items():
            ids, mask = kw.pop(f"{name}_input_ids", None), kw.pop(f"{name}_attention_mask", None)
            if ids is None: continue
            need = name in self.proj
            states, vectors[name] = side(ids, mask, states=need)
            if need: memory[name] = (self.proj[name](states), mask.bool())
        self._memory = memory
        try: out = self.text(input_ids=input_ids, attention_mask=attention_mask, **kw)
        finally: self._memory = {}
        return StreamOutput(out.last_hidden_state, vectors)

    def gradient_checkpointing_enable(self, **kw): self.text.gradient_checkpointing_enable(**kw)
    def gradient_checkpointing_disable(self): self.text.gradient_checkpointing_disable()
    def save_pretrained(self, path, **kw): return save_stream_encoder(self, path)

# %% ../nbs/03_models.ipynb #756ceb42
def lora_config(regime:str="lora", spec:EncoderSpec|None=None, r:int=8, alpha:int=16, dropout:float=0.05, targets=None, **kw):
    "The `peft.LoraConfig` of the `lora` or `mica` regime"
    from peft import LoraConfig
    targets = targets or (spec.lora_targets if spec is not None else None)
    if targets is None: raise ValueError("name the LoRA target modules (targets=...) or pass an EncoderSpec")
    if regime == "mica": kw.setdefault("init_lora_weights", "mica")
    return LoraConfig(r=r, lora_alpha=alpha, lora_dropout=dropout, target_modules=targets, **kw)

def set_regime(model:EncoderDecisionModel, regime="head", **lora_kw) -> EncoderDecisionModel:
    "Set what trains: 'head', 'lora', 'mica', 'full', 'xattn' (a stream encoder's cross-attention), or a peft config"
    from peft import PeftConfig, get_peft_model
    for p in model.head.parameters(): p.requires_grad_(True)
    if isinstance(regime, PeftConfig) or regime in ("lora", "mica"):
        cfg = regime if isinstance(regime, PeftConfig) else lora_config(regime, model.spec, **lora_kw)
        model.encoder = get_peft_model(model.encoder, cfg)
        model.frozen, model.regime = False, regime if isinstance(regime, str) else type(regime).__name__
        # exactly what peft left trainable: MiCA keeps its B matrices frozen, and unfreezing must not thaw them
        model.adapter_params = {n for n, p in model.encoder.named_parameters() if p.requires_grad}
        model.adapter_regime = model.regime
    elif regime == "head":
        for p in model.encoder.parameters(): p.requires_grad_(False)
        model.frozen, model.regime = True, "head"
    elif regime == "full":
        for p in model.encoder.parameters(): p.requires_grad_(True)
        model.frozen, model.regime = False, "full"
    elif regime == "xattn":
        if getattr(model.encoder, "fusion", None) != "xattn": raise ValueError("the xattn regime needs cross-attention: add_cross_attention(model.encoder, stream) first")
        for n, p in model.encoder.named_parameters(): p.requires_grad_(".block." in n or n.startswith("proj."))
        model.frozen, model.regime = False, "xattn"
    else: raise ValueError(f"unknown regime {regime!r}; use 'head', 'lora', 'mica', 'full', 'xattn' or a peft config")
    model.train(model.training)
    return model

def thaw_adapters(model:EncoderDecisionModel) -> EncoderDecisionModel:
    "Make trainable again exactly the adapter parameters `set_regime` made trainable"
    for n, p in model.encoder.named_parameters(): p.requires_grad_(n in model.adapter_params)
    for p in model.head.parameters(): p.requires_grad_(True)
    model.frozen, model.regime = False, model.adapter_regime
    model.train(model.training)
    return model

# %% ../nbs/03_models.ipynb #fe0fdec4
def encoder_layers(encoder:nn.Module) -> nn.ModuleList:
    "The encoder's stack of transformer layers"
    base = encoder.get_base_model() if hasattr(encoder, "get_base_model") else encoder
    best, kind = None, lambda c: type(c.layer) if getattr(c, "is_xattn", False) else type(c)     # a cross-attention wrapper counts as its layer
    for m in base.modules():
        if isinstance(m, nn.ModuleList) and len(m) and len({kind(c) for c in m}) == 1 and (best is None or len(m) > len(best)): best = m
    if best is None: raise ValueError("could not find the encoder's layers")
    return best

def freeze_to(model:EncoderDecisionModel, n:int):
    "Freeze the encoder's embeddings and its first n layers; train the rest (on an adapter model, the rest's adapters)"
    adapters = getattr(model, "adapter_params", None) and hasattr(model.encoder, "peft_config")
    if adapters: thaw_adapters(model)
    else: set_regime(model, "full")
    allowed = {id(p) for nm, p in model.encoder.named_parameters() if nm in model.adapter_params} if adapters else None
    layers = encoder_layers(model.encoder)
    base = model.encoder.get_base_model() if hasattr(model.encoder, "get_base_model") else model.encoder
    layer_params = {id(p) for l in layers for p in l.parameters()}
    for p in base.parameters():
        if id(p) not in layer_params: p.requires_grad_(False)          # embeddings
    for i, l in enumerate(layers):
        for p in l.parameters(): p.requires_grad_(i >= n and (allowed is None or id(p) in allowed))
    if not adapters:
        for name, mod in base.named_children():                         # a final norm after the stack trains
            if "norm" in name.lower():
                for p in mod.parameters(): p.requires_grad_(True)
    model.regime = f"freeze_to({n})"
    return model

# %% ../nbs/03_models.ipynb #2ad12b26
class GatedCrossAttention(nn.Module):
    "Text states attend to a side stream's states; `tanh(gate)` scales what they read, and the gate starts at 0, so the block starts as the identity"
    def __init__(self, width:int, heads:int):
        super().__init__()
        self.norm, self.attn = nn.LayerNorm(width), nn.MultiheadAttention(width, heads, batch_first=True)
        self.gate = nn.Parameter(torch.zeros(1))
    def forward(self, h, memory, memory_mask):
        a, _ = self.attn(self.norm(h), memory, memory, key_padding_mask=~memory_mask, need_weights=False)
        return h + torch.tanh(self.gate).to(h.dtype) * a

class XAttnLayer(nn.Module):
    "An encoder layer followed by a gated cross-attention block over its stream encoder's current memory"
    is_xattn = True
    def __init__(self, layer:nn.Module, block:GatedCrossAttention, owner:nn.Module, stream:str):
        super().__init__()
        self.layer, self.block, self.stream = layer, block, stream
        object.__setattr__(self, "_owner", owner)          # a reference, not a submodule: the owner holds this layer
    def __getattr__(self, name):                            # what the encoder reads off its layers (ModernBERT: attention_type)
        try: return super().__getattr__(name)
        except AttributeError: return getattr(super().__getattr__("layer"), name)
    def forward(self, *args, **kw):
        out = self.layer(*args, **kw)
        mem = self._owner._memory.get(self.stream)
        if mem is None: return out
        h = out[0] if isinstance(out, tuple) else out
        if h.dim() != 3: raise ValueError("cross-attention needs padded (batch, length, width) states; this encoder runs unpadded")
        h = self.block(h, *mem)
        return (h, *out[1:]) if isinstance(out, tuple) else h

def add_cross_attention(encoder:StreamEncoder, stream:str, every:int=4, heads:int|None=None) -> StreamEncoder:
    "Insert a gated cross-attention block over `stream` after every `every`-th layer of the text encoder (in place)"
    if stream not in encoder.sides: raise ValueError(f"no side stream {stream!r}; the encoder has {list(encoder.sides)}")
    if encoder.xattn is not None: raise ValueError("this encoder already has cross-attention")
    layers, width = encoder_layers(encoder.text), encoder.text.config.hidden_size
    heads = heads or max(1, width // 64)
    encoder.proj[stream] = nn.Linear(encoder.sides[stream].width, width)
    for i in range(every - 1, len(layers), every): layers[i] = XAttnLayer(layers[i], GatedCrossAttention(width, heads), encoder, stream)
    encoder.fusion, encoder.xattn = "xattn", {"stream": stream, "every": every, "heads": heads}
    return encoder

# %% ../nbs/03_models.ipynb #b13b63b8
def save_stream_encoder(enc:StreamEncoder, path) -> Path:
    "Write a stream encoder: transformers folders for the text and the side models, and a file for the projections and cross-attention blocks"
    from safetensors.torch import save_file
    path = Path(path); path.mkdir(parents=True, exist_ok=True)
    layers = encoder_layers(enc.text) if enc.xattn else []
    wrapped = {i: l for i, l in enumerate(layers) if getattr(l, "is_xattn", False)}
    try:
        for i, l in wrapped.items(): layers[i] = l.layer          # the text encoder as transformers knows it
        enc.text.save_pretrained(path / "text")
    finally:
        for i, l in wrapped.items(): layers[i] = l
    extra = {f"proj.{k}": v for k, v in enc.proj.state_dict().items()}
    for name, side in enc.sides.items():
        side.model.save_pretrained(path / "sides" / name)
        if side.proj is not None: extra |= {f"sides.{name}.proj.{k}": v for k, v in side.proj.state_dict().items()}
    for i, l in wrapped.items(): extra |= {f"xattn.{i}.{k}": v for k, v in l.block.state_dict().items()}
    if extra: save_file({k: v.detach().cpu().contiguous() for k, v in extra.items()}, str(path / "stream_encoder.safetensors"))
    meta = {"fusion": enc.fusion, "xattn": enc.xattn,
            "sides": {n: {"special_ids": s.special_ids, "proj": s.proj.dims if s.proj is not None else None} for n, s in enc.sides.items()}}
    (path / "stream_encoder.json").write_text(json.dumps(meta, indent=1))
    return path

def load_stream_encoder(path, dtype=torch.float32) -> StreamEncoder:
    "A stream encoder written by `save_stream_encoder`"
    from safetensors.torch import load_file
    from transformers.utils import logging as hf_logging
    path = Path(path); meta = json.loads((path / "stream_encoder.json").read_text())
    level = hf_logging.get_verbosity(); hf_logging.set_verbosity_error()      # a pooler a side model never had is not news
    try:
        sides = {n: SideEncoder(AutoModel.from_pretrained(path / "sides" / n, dtype=dtype), m["special_ids"], ProjMLP(m["proj"]) if m["proj"] else None)
                 for n, m in meta["sides"].items()}
        enc = StreamEncoder(AutoModel.from_pretrained(path / "text", dtype=dtype), sides)
    finally: hf_logging.set_verbosity(level)
    if meta.get("xattn"): add_cross_attention(enc, **meta["xattn"])
    sd = load_file(str(path / "stream_encoder.safetensors")) if (path / "stream_encoder.safetensors").exists() else {}
    part = lambda pre: {k[len(pre):]: v for k, v in sd.items() if k.startswith(pre)}
    for n, s in enc.sides.items():
        if s.proj is not None: s.proj.load_state_dict(part(f"sides.{n}.proj."))
    enc.proj.load_state_dict(part("proj."))
    for i, l in enumerate(encoder_layers(enc.text) if meta.get("xattn") else []):
        if getattr(l, "is_xattn", False): l.block.load_state_dict(part(f"xattn.{i}."))
    return enc.to(dtype)

# %% ../nbs/03_models.ipynb #8f0169c6
def merged_encoder(model:EncoderDecisionModel) -> nn.Module:
    "The encoder with any adapters merged in (a copy; the model keeps its adapters)"
    enc = model.encoder
    if hasattr(enc, "merge_and_unload"): return copy.deepcopy(enc).merge_and_unload()
    return enc

# %% ../nbs/03_models.ipynb #9e745411
def laya_temperatures(cfg:dict) -> dict:
    "Laya's per-type and per-bucket temperatures in sysone's form"
    t = {QTYPE_NAMES[i]: float(v) for i, v in enumerate(cfg.get("temperature", [1.0, 1.0, 1.0]))}
    return t | {k: float(v) for k, v in (cfg.get("temperature_by_options") or {}).items()}

def _laya_dir(src, subfolder=None, revision=None):
    if Path(src).exists(): return Path(src) / (subfolder or "")
    from huggingface_hub import snapshot_download
    pre = f"{subfolder}/" if subfolder else ""
    d = snapshot_download(src, revision=revision, allow_patterns=[pre + p for p in
                          ("rl_agent_config.json", "model.safetensors", "tokenizer/*", "encoder/*")])
    return Path(d) / (subfolder or "")

def _laya_parts(d:Path):
    "The config, encoder config and tokenizer of a Laya checkpoint folder"
    cfg = json.loads((d / "rl_agent_config.json").read_text())
    ecfg = AutoConfig.from_pretrained(d / "encoder") if (d / "encoder").exists() else AutoConfig.from_pretrained(cfg["encoder"])
    tok = AutoTokenizer.from_pretrained(d / "tokenizer") if (d / "tokenizer").exists() else AutoTokenizer.from_pretrained(cfg["encoder"])
    return cfg, ecfg, tok

def _laya_encoder(d:Path, ecfg, sd=None):
    "The encoder of a Laya checkpoint, from its `encoder.*` tensors"
    if sd is None:
        from safetensors.torch import load_file
        sd = load_file(str(d / "model.safetensors"))
    enc = AutoModel.from_config(ecfg, dtype=torch.float32)
    missing, _ = enc.load_state_dict({k[len("encoder."):]: v.float() for k, v in sd.items() if k.startswith("encoder.")}, strict=False)
    missing = [k for k in missing if k not in (getattr(enc, "_tied_weights_keys", None) or {}) and "rotary" not in k]
    if missing: raise ValueError(f"{d}: the checkpoint lacks encoder weights {missing[:3]}")
    return enc

def load_laya(src:str, subfolder:str|None=None, revision:str|None=None):
    "An `EncoderDecisionModel`, its tokenizer, template and temperatures from a Laya checkpoint"
    from safetensors.torch import load_file
    if subfolder is None: src, subfolder = split_repo(src)
    d = _laya_dir(src, subfolder, revision)
    cfg, ecfg, tok = _laya_parts(d)
    sd = load_file(str(d / "model.safetensors"))
    act = "act_head.2.weight" in sd and sd["act_head.2.weight"].shape[0] == 2        # a trained act head, not an export's constant one
    head = DecisionHead(ecfg.hidden_size, layers=cfg.get("head_layers", 2), act=act)
    head.load_state_dict({k: v.float() for k, v in from_laya_names(sd).items() if act or not k.startswith("act_head.")})
    template = RowTemplate.preset("laya", tokenizer=tok, max_len=cfg.get("max_len", 512), head_max_len=cfg.get("head_max_len", 192))
    spec = EncoderSpec(cfg["encoder"], ecfg, tok, template=template, source="laya-checkpoint")
    model = EncoderDecisionModel(_laya_encoder(d, ecfg, sd), head, spec).eval()
    return model, tok, template, laya_temperatures(cfg)

# %% ../nbs/03_models.ipynb #82a17d33
def _laya_spec(id:str, revision:str|None=None, **kw) -> EncoderSpec:
    repo, sub = split_repo(id)
    d = _laya_dir(repo, sub, revision)
    cfg, ecfg, tok = _laya_parts(d)
    template = RowTemplate.preset("laya", tokenizer=tok, max_len=cfg.get("max_len", 512), head_max_len=cfg.get("head_max_len", 192))
    def loader(spec, dtype=None, **kw):
        enc = _laya_encoder(d, ecfg)
        return enc.to(dtype) if dtype is not None else enc
    return EncoderSpec(id, ecfg, tok, revision=revision, source="laya-checkpoint", template=template, loader=loader)

ENCODER_SOURCES.append(("laya", lambda id, revision=None: _is_laya(*split_repo(id)), _laya_spec))

# %% ../nbs/03_models.ipynb #7b9b655f
def laya_state_dict(model:EncoderDecisionModel, temperatures:dict|None=None, dtype=None) -> dict:
    "The model's weights under Laya's parameter names, loadable by `laya.Agent`"
    enc = merged_encoder(model)
    d = model.head.width
    sd = {f"encoder.{k}": v for k, v in enc.state_dict().items()}
    sd |= to_laya_names(model.head.state_dict())
    if not getattr(model.head, "act", False):    # Laya's format always has an act head: without one, a constant one
        sd |= {"act_head.0.weight": torch.zeros(256, d + 4), "act_head.0.bias": torch.zeros(256),
               "act_head.2.weight": torch.zeros(1, 256), "act_head.2.bias": torch.zeros(1)}
    t = temperatures or {}
    sd["temperature"] = torch.tensor([clamp_temperature(t.get(n, 1.0)) for n in ("choice", "score", "noul")])
    sd = {k: v.detach().to("cpu").contiguous() for k, v in sd.items()}
    return {k: v.to(dtype) if dtype is not None and v.is_floating_point() else v for k, v in sd.items()}

def is_laya_compatible(model:EncoderDecisionModel, template:RowTemplate, tfms=(), tokenizer=None) -> bool:
    "Whether an export can also be written in Laya's format: Laya's row and budgets, Laya's head, no inference transforms"
    t, h = template, model.head
    family = getattr(getattr(model.encoder, "config", None), "model_type", None)
    tok = getattr(tokenizer, "tokenizer", tokenizer)
    specials = (tok.cls_token, tok.sep_token, tok.sep_token, tok.mask_token) if tok is not None else ("[CLS]", "[SEP]", "[SEP]", "[MASK]")
    return (t.row == RowTemplate.preset("laya").row and t.option == "{mask} {text}" and t.option_sep == ""
            and (t.start, t.sep, t.end, t.mask) == specials and t.truncate == "auto"
            and t.option_tokens == 48 and h.scorer_kind in ("laya", "mlp") and h.nhead == max(1, h.width // 64)
            and h.readout == "anchor" and h.query is None
            and family == "modernbert" and not h.standardize and not any(not x.train_only for x in tfms))

# %% ../nbs/30_gliner_encoder.ipynb #a5464746
from .template import RowTemplate as _RowTemplate

# %% ../nbs/30_gliner_encoder.ipynb #fb5926a0
_EMBED_KEYS = ("embeddings.word_embeddings.weight", "embeddings.tok_embeddings.weight")

def is_gliner_checkpoint(src:str, revision:str|None=None) -> bool:
    "Whether `src` (a folder or Hub repo) is a GLiNER2 checkpoint: an extractor config and an encoder_config folder"
    p = Path(src)
    if p.exists():
        if not ((p / "config.json").exists() and (p / "encoder_config" / "config.json").exists()): return False
        c = json.loads((p / "config.json").read_text())
    else:
        if str(src).startswith(("/", ".")): return False
        try:
            from huggingface_hub import hf_hub_download, file_exists
            if not file_exists(src, "encoder_config/config.json", revision=revision): return False
            c = json.loads(Path(hf_hub_download(src, "config.json", revision=revision)).read_text())
        except Exception: return False
    return c.get("model_type") == "extractor" or "architecture" in c

def _gliner_file(src, name, revision=None) -> Path:
    p = Path(src) / name
    if p.exists(): return p
    from huggingface_hub import hf_hub_download
    return Path(hf_hub_download(src, name, revision=revision))

def _gliner_dir(src, revision=None) -> Path:
    if Path(src).exists(): return Path(src)
    from huggingface_hub import snapshot_download
    return Path(snapshot_download(src, revision=revision, allow_patterns=["config.json", "encoder_config/*", "model.safetensors",
                                                                          "tokenizer*", "special_tokens_map.json", "added_tokens.json", "*.model"]))

def load_gliner_encoder(src:str, revision:str|None=None, dtype=None):
    "The encoder of a GLiNER2 checkpoint, built from `encoder_config` and loaded strictly from `model.safetensors`"
    from safetensors import safe_open
    d = _gliner_dir(src, revision)
    cfg = AutoConfig.from_pretrained(d / "encoder_config")
    kw = {"attn_implementation": "eager"} if cfg.model_type in ("deberta-v2", "deberta") else {}
    enc = AutoModel.from_config(cfg, **kw)
    with safe_open(str(d / "model.safetensors"), "pt") as f:
        names = list(f.keys())
        prefix = next((n[:-len(k)] for n in names for k in _EMBED_KEYS if n.endswith(k)), None)
        if prefix is None: raise ValueError(f"{src}: no embedding matrix found among the checkpoint's tensors")
        sd = {n[len(prefix):]: f.get_tensor(n) for n in names if n.startswith(prefix)}
    missing, unexpected = enc.load_state_dict(sd, strict=False)
    if missing or unexpected:
        raise ValueError(f"{src}: partial encoder load (prefix {prefix!r}): missing {missing[:3]}, unexpected {unexpected[:3]}")
    enc = enc.float()
    return enc.to(dtype) if dtype is not None else enc

# %% ../nbs/30_gliner_encoder.ipynb #36475066
def _gliner_spec(id:str, revision:str|None=None, **kw) -> EncoderSpec:
    d = _gliner_dir(id, revision)
    cfg, tok = AutoConfig.from_pretrained(d / "encoder_config"), AutoTokenizer.from_pretrained(d)
    t = _RowTemplate.preset("gliner")
    if t.max_len > getattr(cfg, "max_position_embeddings", t.max_len): t = t.replace(max_len=cfg.max_position_embeddings)
    return EncoderSpec(id, cfg, tok, revision=revision, source="gliner2-checkpoint", template=t,
                       loader=lambda spec, dtype=None, **kw: load_gliner_encoder(id, revision, dtype))

ENCODER_SOURCES.insert(0, ("gliner2", is_gliner_checkpoint, _gliner_spec))

# %% ../nbs/30_gliner_encoder.ipynb #4292e62a
class GlinerCheckpoint(Checkpoint): "A GLiNER2 checkpoint: its classifier MLP starts a `gliner2` scorer"

def gliner_warm_start(head:DecisionHead, ckpt:GlinerCheckpoint, *, strict:bool=True) -> DecisionHead:
    "Copy a GLiNER2 checkpoint's classifier MLP into a `gliner2` scorer, and zero the type embedding"
    if head.scorer_kind != "gliner2": raise ValueError("a GLiNER2 warm start needs DecisionHead(..., scorer='gliner2')")
    src = ckpt.src
    t = read_tensors(str(_gliner_dir(src)) if Path(src).exists() else src, "model.safetensors", select=lambda k: k.startswith("classifier."))
    last = max(int(k.split(".")[1]) for k in t)          # 2 on span checkpoints, 3 on boundary ones (a dropout before it)
    sd = {"0.weight": t["classifier.0.weight"], "0.bias": t["classifier.0.bias"],
          "2.weight": t[f"classifier.{last}.weight"], "2.bias": t[f"classifier.{last}.bias"]}
    head.scorer.load_state_dict({k: v.float() for k, v in sd.items()})
    with torch.no_grad(): head.type_emb.weight.zero_()
    return head

CHECKPOINTS.insert(0, (lambda src, subfolder=None: subfolder is None and is_gliner_checkpoint(src), GlinerCheckpoint))
warm_start.register(gliner_warm_start)