"""NeoMME-260M under the sysone head (its tokens, image rows built with two-axis positions, and its methods of sysone's generic functions), and the multimodal application, which takes its defaults from whichever encoder it runs.

Docs: https://sgaseretto.github.io/sysonelib/neomme.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/20_neomme.ipynb.

# %% auto #0
__all__ = ['ENCODER', 'neomme_positions', 'image_block', 'build_processor_rows', 'neomme_inputs', 'neomme_image_side',
           'decision_learner']

# %% ../nbs/20_neomme.ipynb #5451df02
import torch

from .core import *
from .template import *
from .data import TypedDecisions
from .models import *
from .learner import PRESETS, Learner, default_preset
from .learner import decision_learner as _decision_learner
from transformers import NeoMMEConfig, NeoMMEProcessor
from .inference import Decider
from .cache import FeatureCache        # and the verbs the cache adds to Learner, `fit_linear` among them

# %% ../nbs/20_neomme.ipynb #eb1478c8
def neomme_positions(n:int, image_at:int|None=None, h:int=0, w:int=0) -> torch.Tensor:
    "NeoMME's two-axis position ids for a row of `n` tokens whose image marker sits at `image_at` (an h × w grid)"
    if image_at is None: return torch.arange(n).expand(2, -1).clone()
    d = image_at - 1                                            # the <doc> that opens the image
    pos = torch.zeros(2, n, dtype=torch.long)
    pos[:, :image_at + 1] = torch.arange(image_at + 1)          # text before, <doc> and the marker: the diagonal
    r = torch.arange(h).repeat_interleave(w + 1); c = torch.arange(w + 1).repeat(h)
    g0, g1 = image_at + 1, image_at + 1 + h * (w + 1)
    pos[0, g0:g1], pos[1, g0:g1] = d + 2 + r, d + 2 + c         # patches, and each row's <row> after them
    s = d + 2 + max(h, w + 1)                                   # text after the grid starts past both axes
    pos[:, g1:] = torch.arange(s, s + n - g1)
    return pos

# %% ../nbs/20_neomme.ipynb #c968b812
def image_block(builder:RowBuilder, image):
    "The ids, patches and grid of one image: `<doc>`, `<img>`, then a row of patch placeholders and `<row>` per grid row"
    tok = builder.tok
    feat = builder.processor.image_processor(images=[image], return_tensors="pt")
    h, w = (int(v) for v in feat["image_grid_hw"][0])
    ids = [tok.document_token_id, tok.image_token_id] + ([tok.image_token_id] * w + [tok.row_token_id]) * h
    return ids, feat["pixel_values"], h, w

def build_processor_rows(processor:NeoMMEProcessor, builder:RowBuilder, record:dict, *, skip_errors:bool=False) -> list:
    "Rows of a transformed record for a NeoMME-style processor: text by the builder's budgets, the image as a patch grid"
    images = record.get("images") or []
    if len(images) > 1: raise ValueError("a NeoMME row holds one image")
    tok, ps = builder.tok, processor.image_processor.patch_size
    for name in ("document_token", "row_token"):
        s = getattr(tok, name, None)
        if s and s not in builder.extra_scrub: builder.extra_scrub.append(s)
    if images: ids_img, pixels, h, w = image_block(builder, images[0])
    else: ids_img, pixels, h, w = None, torch.zeros(0, 3 * ps * ps), 0, 0
    gold, rows = record.get("gold") or {}, []
    for qid, q, ids, markers, image_at, spans in builder._layout(record, ids_img, skip_errors):
        target, label = q.target(gold.get(qid))
        rows.append(Row(ids, markers, q.qtype, target, label, meta={"qid": qid, "case": record.get("id")},
                        extras={"position_ids": neomme_positions(len(ids), image_at, h, w), "pixel_values": pixels},
                        spans=spans, answerable=q.answerable(gold.get(qid))))
    return rows

processor_rows.register(build_processor_rows)

# %% ../nbs/20_neomme.ipynb #a33eef42
def neomme_inputs(config:NeoMMEConfig, inputs:dict) -> dict:
    "NeoMME's inputs: position ids as (2, batch, length), and no `pixel_values` when no row of the batch has an image"
    kw = dict(inputs)
    pos = kw.get("position_ids")
    if pos is not None and pos.dim() == 3 and pos.shape[1] == 2: kw["position_ids"] = pos.transpose(0, 1).contiguous()
    pv = kw.get("pixel_values")
    if pv is not None and pv.shape[0] == 0: kw.pop("pixel_values")
    return kw

encoder_inputs.register(neomme_inputs)

# %% ../nbs/20_neomme.ipynb #302215e1
ENCODER = "ModernVBERT/modernvbert"       # the default since 2026-09-30, NeoMME-260M before: section 8 says why

def neomme_image_side(processor:NeoMMEProcessor) -> int:
    "NeoMME's default image side: 1,024 pixels on the long side, for the pages and screenshots it reads"
    return 1024

default_image_side.register(neomme_image_side)

def decision_learner(data:TypedDecisions, encoder=ENCODER, train="head", cache="auto", template=None, image_side="auto",
                     head:str|None=None, dtype=torch.float32, standardize:bool=True, cache_dtype:str="float32", **kw) -> Learner:
    "A multimodal `Learner` for any encoder with an adapter (ModernVBERT by default), with the encoder's template, image side and batching"
    spec = encoder if isinstance(encoder, EncoderSpec) else EncoderSpec.from_pretrained(encoder)
    template = template if template is not None else spec.template.name     # the family's preset, whatever the data was bound to before
    if image_side == "auto": image_side = default_image_side(spec.processor)
    if cache == "auto": cache = "masks" if train == "head" and head in (None, "mlp", "linear") and not kw.get("head_layers") else None
    per_row = prepare_processor(spec.processor, image_side)                 # a tiling processor makes several images of one
    if per_row > 1:           # the vision tower's batch is rows × images per row: fewer rows keep it the size of one image's
        base = PRESETS[kw.get("preset") or default_preset()]
        shrink = ("per_device_eval_batch_size",) if cache else ("per_device_train_batch_size", "per_device_eval_batch_size")
        for k in shrink:      # with cached anchors, only the batches that fill the cache run the vision tower
            if k in base: kw.setdefault(k, max(1, base[k] // per_row))
    if not any(isinstance(t, Image) and not getattr(t, "_added", False) for t in data.tfms):   # the caller's own Image transform is kept
        img = Image(side=image_side); img._added = True       # this call's side, also when an earlier call added one to the same data
        data.tfms = [img] + [t for t in data.tfms if not getattr(t, "_added", False)]
    head = head or "mlp"     # Laya's scorer on the anchors in every regime; Laya's two-layer head trained from scratch collapsed on small image tasks
    return _decision_learner(data, spec, train=train, cache=cache, template=template, head=head, dtype=dtype, standardize=standardize,
                             cache_dtype=cache_dtype, **kw)
