"""ProtST under the sysone head: its two towers loaded from tensors alone, zero-shot typed answers from its joint space, and the protein application, where the protein is a side stream beside a text row.

Docs: https://sgaseretto.github.io/sysonelib/protein.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/22_protein.ipynb.

# %% auto #0
__all__ = ['ENCODER', 'TOKENIZERS', 'is_protst', 'protst_config', 'protst_tensors', 'protst_tokenizers', 'ProtST', 'load_protst',
           'clean_sequence', 'protein_specials', 'ProteinEmbedder', 'TextEmbedder', 'zero_shot', 'stream_encoder',
           'protst_spec', 'decision_learner']

# %% ../nbs/22_protein.ipynb #9b9eeab4
import json
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import torch
import torch.nn as nn
from transformers import AutoTokenizer, BertConfig, BertModel, EsmConfig, EsmModel

from .core import *
from .template import Stream, TokenStream
from .data import TypedDecisions
from .models import *
from .zeroshot import Embedder, SimilarityDecider
from .learner import Learner
from .learner import decision_learner as _decision_learner
from .cache import FeatureCache        # and the verbs the cache adds to Learner

# %% ../nbs/22_protein.ipynb #ced09b50
ENCODER = "MilaDeepGraph/ProtST-ESM1b"
TOKENIZERS = {"protein": "facebook/esm1b_t33_650M_UR50S", "text": "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract"}

def _file(id:str, name:str, revision:str|None=None) -> Path:
    "A file of a local folder, or of a Hub repo (downloaded once, then read from the cache)"
    if Path(id).exists():
        if not (Path(id) / name).exists(): raise FileNotFoundError(Path(id) / name)
        return Path(id) / name
    from huggingface_hub import hf_hub_download
    return Path(hf_hub_download(id, name, revision=revision))

def is_protst(id:str, revision:str|None=None) -> bool:
    "Whether `id` (a folder or a Hub repo) holds a ProtST checkpoint: a config whose model_type is 'protst'"
    try: return json.loads(_file(id, "config.json", revision).read_text()).get("model_type") == "protst"
    except Exception: return False

def protst_config(id:str=ENCODER, revision:str|None=None) -> SimpleNamespace:
    "The checkpoint's configuration: its model type, and the ESM and BERT configs of its towers"
    cfg = json.loads(_file(id, "config.json", revision).read_text())
    return SimpleNamespace(model_type="protst", protein_config=EsmConfig(**cfg["protein_config"]), text_config=BertConfig(**cfg["text_config"]))

def protst_tensors(id:str=ENCODER, revision:str|None=None) -> dict:
    "The checkpoint's tensors: `model.safetensors` if there is one, else `pytorch_model.bin` read with `weights_only=True` (tensors, no code), memory-mapped"
    try: f = _file(id, "model.safetensors", revision)
    except Exception: f = _file(id, "pytorch_model.bin", revision)
    if f.suffix == ".safetensors":
        from safetensors.torch import load_file
        return load_file(str(f))
    return torch.load(f, map_location="cpu", weights_only=True, mmap=True)

def protst_tokenizers(id:str=ENCODER, protein:str|None=None, text:str|None=None) -> tuple:
    "The protein and the text tokenizer: the folder's own (`protein_tokenizer/`, `text_tokenizer/`), else ESM-1b's and PubMedBERT's"
    def pick(kind, given):
        if given is not None: return given
        own = Path(id) / f"{kind}_tokenizer"
        return str(own) if own.exists() else TOKENIZERS[kind]
    return AutoTokenizer.from_pretrained(pick("protein", protein)), AutoTokenizer.from_pretrained(pick("text", text))

# %% ../nbs/22_protein.ipynb #2ab62800
def _tower(cls, config, sd:dict, prefix:str, dtype):
    "A transformers tower built from its config and the tensors under `prefix`; nothing is initialised at random"
    from transformers.utils import logging as hf_logging
    part = {k[len(prefix):]: v for k, v in sd.items() if k.startswith(prefix)}
    bar = hf_logging.is_progress_bar_enabled(); hf_logging.disable_progress_bar()
    try: m, info = cls.from_pretrained(None, config=config, state_dict=part, add_pooling_layer=False, dtype=dtype, output_loading_info=True)
    finally:
        if bar: hf_logging.enable_progress_bar()
    if info["missing_keys"] or info["unexpected_keys"]:
        raise ValueError(f"{prefix}: the checkpoint misses {sorted(info['missing_keys'])[:3]} and has unused {sorted(info['unexpected_keys'])[:3]}")
    return m.eval()

def _proj(sd:dict, prefix:str, dtype) -> ProjMLP:
    "A ProtST projection head (dense → ReLU → out_proj) as a `ProjMLP`"
    w1, w2 = sd[prefix + "dense.weight"], sd[prefix + "out_proj.weight"]
    m = ProjMLP([w1.shape[1], w1.shape[0], w2.shape[0]])
    m.load_state_dict({"0.weight": w1, "0.bias": sd[prefix + "dense.bias"], "2.weight": w2, "2.bias": sd[prefix + "out_proj.bias"]})
    return m.to(dtype).eval()

class ProtST(nn.Module):
    "ProtST's two towers and the heads that project their pooled vectors into one space: ESM over proteins, BERT over text"
    def __init__(self, esm:nn.Module, bert:nn.Module, protein_proj:ProjMLP, text_proj:ProjMLP, logit_scale:float,
                 protein_tokenizer, text_tokenizer, config=None, id:str|None=None, revision:str|None=None):
        super().__init__()
        self.esm, self.bert, self.protein_proj, self.text_proj = esm, bert, protein_proj, text_proj
        self.logit_scale, self.protein_tokenizer, self.text_tokenizer = logit_scale, protein_tokenizer, text_tokenizer
        self.config, self.id, self.revision = config, id, revision

    def __repr__(self):
        pc, tc = self.esm.config, self.bert.config
        n = sum(p.numel() for p in self.parameters())
        return (f"ProtST({self.id} · protein: ESM {pc.num_hidden_layers} × {pc.hidden_size} · text: BERT {tc.num_hidden_layers} × "
                f"{tc.hidden_size} · joint space {self.protein_proj.dims[-1]} · scale {self.logit_scale:.3g} · {n / 1e6:,.1f}M params · "
                f"{next(self.parameters()).dtype} on {self.device})")

    @property
    def device(self) -> torch.device: return next(self.esm.parameters()).device

def load_protst(id:str=ENCODER, revision:str|None=None, dtype=torch.float32, device=None,
                protein_tokenizer:str|None=None, text_tokenizer:str|None=None) -> ProtST:
    "ProtST from a Hub repo or a folder: transformers' ESM and BERT filled with the checkpoint's tensors (its modeling code is not run)"
    config, sd = protst_config(id, revision), protst_tensors(id, revision)
    esm = _tower(EsmModel, config.protein_config, sd, "protein_model.esm.", dtype)
    bert = _tower(BertModel, config.text_config, sd, "text_model.bert.", dtype)
    pp, tp = _proj(sd, "protein_model.protein_mlp.", dtype), _proj(sd, "text_model.text_mlp.", dtype)
    scale = float(sd["logit_scale"].float().exp())
    del sd
    p = ProtST(esm, bert, pp, tp, scale, *protst_tokenizers(id, protein_tokenizer, text_tokenizer), config=config, id=str(id), revision=revision)
    return p.to(device) if device is not None else p

# %% ../nbs/22_protein.ipynb #10aabbbb
def clean_sequence(s) -> str:
    "A protein sequence as ESM's tokenizer reads it: one-letter codes in capitals, no spaces"
    return "".join(str(s).split()).upper()

def protein_specials(tok) -> tuple:
    "The ids a protein's mean leaves out: its tokenizer's cls, eos and pad"
    return tuple(i for i in (tok.cls_token_id, tok.eos_token_id, tok.pad_token_id) if i is not None)

@torch.no_grad()
def _pooled(side:SideEncoder, ids:list, pad:int, batch_size:int, device) -> np.ndarray:
    "A side encoder's pooled vectors for lists of token ids, batched by length, in eval mode, in the input order"
    modes = [(m, m.training) for m in side.modules()]       # the towers may be shared: each module gets its own mode back
    side.eval()
    out, order = [None] * len(ids), sorted(range(len(ids)), key=lambda i: len(ids[i]))
    try:
        for i in range(0, len(order), batch_size):
            chunk = order[i:i + batch_size]; L = max(len(ids[j]) for j in chunk)
            x = torch.full((len(chunk), L), pad, dtype=torch.long); m = torch.zeros_like(x)
            for r, j in enumerate(chunk): x[r, :len(ids[j])] = torch.tensor(ids[j]); m[r, :len(ids[j])] = 1
            v = side(x.to(device), m.to(device))[1].float().cpu().numpy()
            for r, j in enumerate(chunk): out[j] = v[r]
    finally:
        for m, t in modes: m.training = t
    return np.stack(out)

class ProteinEmbedder(Embedder):
    "Protein sequences to ProtST's protein embeddings: ESM over the residues (cropped as the `protein` stream crops them), their mean, projected"
    def __init__(self, protst:ProtST, max_len:int=1024, crop:str="ends", batch_size:int=8):
        self.protst, self.batch_size = protst, batch_size
        self.stream = TokenStream("protein", protst.protein_tokenizer, max_len=max_len, crop=crop)
        self.side = SideEncoder(protst.esm, protein_specials(protst.protein_tokenizer), proj=protst.protein_proj)
    def __repr__(self): return f"ProteinEmbedder({self.stream.max_len} tokens, crop {self.stream.crop!r}, batches of {self.batch_size})"
    def embed(self, items):
        ids = [self.stream.build(clean_sequence(s))[self.stream.columns[0]] for s in items]
        return _pooled(self.side, ids, self.protst.protein_tokenizer.pad_token_id, self.batch_size, self.protst.device)

class TextEmbedder(Embedder):
    "Texts to ProtST's text embeddings, as its zero-shot example makes them: [CLS] and the text's tokens (no [SEP]), their mean, projected"
    def __init__(self, protst:ProtST, max_len:int=128, batch_size:int=32):
        self.protst, self.max_len, self.batch_size = protst, max_len, batch_size
        tok = protst.text_tokenizer
        self.side = SideEncoder(protst.bert, (tok.cls_token_id, tok.sep_token_id, tok.pad_token_id), proj=protst.text_proj)
    def embed(self, items):
        tok = self.protst.text_tokenizer
        ids = [[tok.cls_token_id] + tok(str(t), add_special_tokens=False, truncation=True, max_length=self.max_len)["input_ids"] for t in items]
        return _pooled(self.side, ids, tok.pad_token_id or 0, self.batch_size, self.protst.device)

def zero_shot(protst:ProtST, prompt:str="{text}", proteins:Embedder|None=None, texts:Embedder|None=None, state_key:str="sequence",
              max_len:int=1024, crop:str="ends", **kw) -> SimilarityDecider:
    "A zero-shot decider on ProtST: an option's logit is ProtST's scale times the cosine between the protein's embedding and the option text's"
    return SimilarityDecider(proteins or ProteinEmbedder(protst, max_len, crop), texts or TextEmbedder(protst), scale=protst.logit_scale,
                             prompt=prompt, state_key=state_key, **({"batch_size": 64, "name": "protst"} | kw))

# %% ../nbs/22_protein.ipynb #b4e97c29
FAMILIES["protst"] = ("auto", r"text\.encoder\.layer\.\d+\.attention\.(self\.(query|key|value)|output\.dense)")

def stream_encoder(protst:ProtST) -> StreamEncoder:
    "ProtST as a stream encoder: BERT reads the row, and ESM reads the `protein` stream, pooled and projected as for zero-shot"
    return StreamEncoder(protst.bert, {"protein": SideEncoder(protst.esm, protein_specials(protst.protein_tokenizer), proj=protst.protein_proj)})

def protst_spec(protst:ProtST|str=ENCODER, revision:str|None=None, protein_len:int=1024, crop:str="ends",
                protein_tokenizer:str|None=None, text_tokenizer:str|None=None, **kw) -> EncoderSpec:
    "The spec of ProtST: its text tokenizer for the row, a `protein` stream on its protein tokenizer, and the stream encoder, loaded when asked for"
    if isinstance(protst, ProtST):
        bundle, id, revision, config = protst, protst.id, protst.revision, protst.config
        ptok, ttok = protst.protein_tokenizer, protst.text_tokenizer
        loader = lambda spec, dtype=None, **kw: stream_encoder(bundle.to(dtype=dtype) if dtype is not None else bundle)
    else:
        id, config = str(protst), protst_config(str(protst), revision)
        ptok, ttok = protst_tokenizers(id, protein_tokenizer, text_tokenizer)
        loader = lambda spec, dtype=torch.float32, **kw: stream_encoder(load_protst(id, revision, dtype=dtype or torch.float32,
                                                                                    protein_tokenizer=protein_tokenizer, text_tokenizer=text_tokenizer))
    return EncoderSpec(id, config, ttok, revision=revision, source="protst", loader=loader,
                       streams=[TokenStream("protein", ptok, max_len=protein_len, crop=crop)])

ENCODER_SOURCES.append(("protst", is_protst, protst_spec))

# %% ../nbs/22_protein.ipynb #8c6d3371
def decision_learner(data:TypedDecisions, encoder=ENCODER, train="head", cache="auto", head:str="pair", query:str|None="stream:protein",
                     sequence_key:str="sequence", protein_len:int=1024, crop:str="ends", standardize:bool=True,
                     cache_dtype:str="float32", **kw) -> Learner:
    "A protein `Learner`: ProtST with the protein as a side stream, a head that scores each option against the protein, cached features for frozen towers"
    spec = encoder if isinstance(encoder, EncoderSpec) else protst_spec(encoder, protein_len=protein_len, crop=crop)
    if not any(isinstance(t, Stream) for t in data.tfms):
        s = Stream(sequence_key, "protein"); s._added = True
        data.tfms = [s] + list(data.tfms)
    if cache == "auto": cache = "masks" if train == "head" and not kw.get("head_layers") else None
    return _decision_learner(data, spec, train=train, cache=cache, head=head, query=query, standardize=standardize,
                             cache_dtype=cache_dtype, **kw)
