"""What a model was trained with: the code and its commit, the packages, the hardware, the data, the model's settings and every fit, collected when a learner exports and kept in `sysone.json`.

Docs: https://sgaseretto.github.io/sysonelib/record.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05a_record.ipynb.

# %% auto #0
__all__ = ['KEY_PACKAGES', 'RUN_MARKERS', 'public_url', 'git_info', 'entry_point', 'package_version', 'environment',
           'installed_packages', 'cpu_name', 'memory_gb', 'accelerator', 'run_context', 'hardware', 'hub_sha',
           'data_record', 'jsonable', 'non_default_args', 'lora_config', 'thin', 'public_tracking_uri', 'tracking_info',
           'training_record']

# %% ../nbs/05a_record.ipynb #1218cedf
import dataclasses, datetime, enum, hashlib, json, os, platform, re, subprocess, sys
from importlib import metadata
from pathlib import Path

import torch

import sysone

# %% ../nbs/05a_record.ipynb #d9f7af5c
def _git(args:list, cwd) -> str|None:
    try: r = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError): return None
    return r.stdout.strip() if r.returncode == 0 else None

def public_url(url:str|None) -> str|None:
    "A URL without the credentials some remotes carry (`https://user:token@host/...`)"
    return re.sub(r"(?<=://)[^@/]+@", "", url) if url else None

def git_info(path=".") -> dict|None:
    "The commit, branch, remote and uncommitted changes of the git repository holding `path`, or None outside one"
    root = _git(["rev-parse", "--show-toplevel"], path)
    if root is None: return None
    changed = [l[3:] for l in (_git(["status", "--porcelain"], root) or "").splitlines()]
    try: diff = subprocess.run(["git", "diff", "HEAD"], cwd=root, capture_output=True, timeout=120).stdout
    except (OSError, subprocess.SubprocessError): diff = b""
    return {"repo": Path(root).name, "commit": _git(["rev-parse", "HEAD"], root), "branch": _git(["rev-parse", "--abbrev-ref", "HEAD"], root),
            "remote": public_url(_git(["config", "--get", "remote.origin.url"], root)), "dirty": bool(changed),
            "changed": changed[:50], "n_changed": len(changed), "diff_sha256": hashlib.sha256(diff).hexdigest() if diff else None}

# %% ../nbs/05a_record.ipynb #021e7424
def _notebook_path() -> str|None:
    try:
        from IPython import get_ipython
        ip = get_ipython()
    except ImportError: return None
    if ip is None: return None
    return ip.user_ns.get("__vsc_ipynb_file__") or ip.user_ns.get("__session__") or None

def entry_point() -> dict|None:
    "The notebook or script that is running: its name, relative to its git repository, and its SHA-256"
    p = os.environ.get("SYSONE_ENTRY") or os.environ.get("JPY_SESSION_NAME") or _notebook_path()
    if not p and sys.argv and sys.argv[0].endswith(".py"): p = sys.argv[0]
    if not p: return None
    p = Path(p)
    if not p.is_file(): return {"name": p.name}
    p = p.resolve()
    root = _git(["rev-parse", "--show-toplevel"], p.parent)
    name = str(p.relative_to(root)) if root and p.is_relative_to(root) else p.name
    return {"name": name, "sha256": hashlib.sha256(p.read_bytes()).hexdigest()}

# %% ../nbs/05a_record.ipynb #767e71ec
KEY_PACKAGES = ("sysone", "torch", "transformers", "peft", "accelerate", "datasets", "huggingface_hub", "tokenizers", "safetensors",
                "numpy", "fastcore", "plum-dispatch", "torch_xla", "torch-neuronx", "mlflow", "sagemaker")

def package_version(name:str) -> str|None:
    try: return metadata.version(name)
    except metadata.PackageNotFoundError: return None

def environment() -> dict:
    "Python, the operating system, the versions of `KEY_PACKAGES` that are installed, and CUDA's"
    pk = {}
    for n in KEY_PACKAGES:
        v = package_version(n)
        if v is not None: pk[n] = v
    return {"python": platform.python_version(), "implementation": platform.python_implementation(),
            "os": f"{platform.system()} {platform.release()}", "packages": pk, "cuda": torch.version.cuda,
            "cudnn": torch.backends.cudnn.version() if torch.cuda.is_available() else None}

def installed_packages() -> list:
    "Every installed distribution as `name==version`, sorted: the lines of an export's `environment.txt`"
    seen = {}
    for d in metadata.distributions():
        n = d.metadata["Name"]
        if n and n.lower() not in seen: seen[n.lower()] = f"{n}=={d.version}"
    return sorted(seen.values(), key=str.lower)

# %% ../nbs/05a_record.ipynb #91558fdd
def _sysctl(key:str) -> str|None:
    try: r = subprocess.run(["sysctl", "-n", key], capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.SubprocessError): return None
    return r.stdout.strip() or None

def cpu_name() -> str|None:
    "The host CPU's model name"
    if sys.platform == "darwin": return _sysctl("machdep.cpu.brand_string")
    try:
        for l in Path("/proc/cpuinfo").read_text().splitlines():
            if l.startswith("model name"): return l.split(":", 1)[1].strip()
    except OSError: pass
    return platform.processor() or None

def memory_gb() -> float|None:
    "The host's memory"
    try: import psutil
    except ImportError: return None
    return round(psutil.virtual_memory().total / 2**30, 1)

def accelerator() -> dict:
    "What a model trains on here: CUDA devices and their memory, a TPU, a Neuron device, Apple's MPS (unified memory), or the CPU"
    if torch.cuda.is_available():
        ps = [torch.cuda.get_device_properties(i) for i in range(torch.cuda.device_count())]
        return {"kind": "cuda", "devices": [p.name for p in ps], "memory_gb": [round(p.total_memory / 2**30, 1) for p in ps],
                "capability": f"{ps[0].major}.{ps[0].minor}"}
    if os.environ.get("PJRT_DEVICE") == "TPU" or os.environ.get("TPU_ACCELERATOR_TYPE"):
        return {"kind": "tpu", "devices": [os.environ.get("TPU_ACCELERATOR_TYPE", "tpu")]}
    if os.environ.get("NEURON_RT_VISIBLE_CORES") or Path("/dev/neuron0").exists(): return {"kind": "neuron"}
    if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available(): return {"kind": "mps", "devices": [cpu_name()], "memory_gb": [memory_gb()]}
    return {"kind": "cpu"}

RUN_MARKERS = (("colab", "COLAB_RELEASE_TAG"), ("kaggle", "KAGGLE_KERNEL_RUN_TYPE"), ("sagemaker", "TRAINING_JOB_NAME"), ("sagemaker", "SM_CURRENT_HOST"))

def run_context() -> dict:
    "Where this process runs: the backend and id of a sysone job, else Colab, Kaggle or SageMaker by their variables, else local"
    if os.environ.get("SYSONE_JOB"):
        try: return json.loads(os.environ["SYSONE_JOB"])
        except json.JSONDecodeError: return {"backend": "unknown", "job": os.environ["SYSONE_JOB"]}
    for name, var in RUN_MARKERS:
        if os.environ.get(var): return {"backend": name}
    return {"backend": "local"}

def hardware() -> dict:
    "The accelerator, the host and where the run happens"
    return {"accelerator": accelerator(), "host": {"cpu": cpu_name(), "cores": os.cpu_count(), "memory_gb": memory_gb(),
            "system": platform.system(), "machine": platform.machine()}, "run": run_context()}

# %% ../nbs/05a_record.ipynb #c9ef5b8d
def hub_sha(repo:str, revision:str|None=None, repo_type:str="dataset") -> str|None:
    "The commit a Hub repo's revision points to, or None offline or on any error"
    try:
        from huggingface_hub import HfApi, constants
        if constants.HF_HUB_OFFLINE: return None
        info = HfApi().repo_info(repo, revision=revision, repo_type=repo_type, timeout=10)
        return info.sha
    except Exception: return None

def data_record(data) -> dict:
    "Where a `TypedDecisions`' cases came from, each split's size and fingerprint, its template, transforms, sampler and seed"
    src = dict(data.source or {})
    if src.get("kind") == "hub" and src.get("id") and "sha" not in src: src["sha"] = hub_sha(src["id"], src.get("revision"))
    splits = {k: {"cases": len(v), "fingerprint": getattr(v, "_fingerprint", None)} for k, v in data.cases.items() if v is not None}
    t = data.builder.template if data.builder is not None else data.template
    return {"source": src or None, "splits": splits, "template": t if isinstance(t, str) else getattr(t, "name", None),
            "transforms": [type(x).__name__ for x in data.tfms], "sampler": repr(data.sampler) if data.sampler is not None else None,
            "seed": data.seed}

# %% ../nbs/05a_record.ipynb #1497c19d
def jsonable(v):
    "A value as JSON can hold it: enums by value, containers element by element, anything else by `str`"
    if isinstance(v, enum.Enum): return v.value
    if v is None or isinstance(v, (str, int, float, bool)): return v
    if isinstance(v, (list, tuple, set, frozenset)): return [jsonable(x) for x in (sorted(v, key=str) if isinstance(v, (set, frozenset)) else v)]
    if isinstance(v, dict): return {str(k): jsonable(x) for k, x in v.items()}
    return str(v)

def non_default_args(args) -> dict:
    "The `TrainingArguments` that differ from transformers' defaults, as JSON values; paths, directories and tokens are left out"
    out = {}
    for f in dataclasses.fields(type(args)):
        if f.name in ("output_dir", "run_name") or "token" in f.name or "dir" in f.name: continue
        if f.default is not dataclasses.MISSING: default = f.default
        elif f.default_factory is not dataclasses.MISSING: default = f.default_factory()
        else: default = dataclasses.MISSING
        v = getattr(args, f.name, None)
        try: same = default is not dataclasses.MISSING and v == default
        except Exception: same = False
        if not same: out[f.name] = jsonable(v)
    return out

def lora_config(model) -> dict|None:
    "The LoRA settings of a model's encoder, when it has adapters"
    cfg = getattr(model.encoder, "peft_config", None)
    if not cfg: return None
    d = next(iter(cfg.values())).to_dict()
    keep = ("peft_type", "r", "lora_alpha", "lora_dropout", "target_modules", "bias", "use_rslora", "use_dora", "modules_to_save")
    return {k: jsonable(d[k]) for k in keep if k in d}

def thin(xs:list, n:int=500) -> list:
    "At most `n` evenly spaced items of `xs`, the first and the last among them"
    if len(xs) <= n: return list(xs)
    return [xs[round(i * (len(xs) - 1) / (n - 1))] for i in range(n)]

# %% ../nbs/05a_record.ipynb #721d269a
def public_tracking_uri(uri:str|None) -> str|None:
    "A tracking URI without local paths or credentials: `file` or `sqlite` for local stores, the address of a server, an ARN as it is"
    if not uri: return None
    if uri.startswith(("file:", "/", ".")) or re.match(r"^[A-Za-z]:\\", uri): return "file"
    if uri.startswith("sqlite:"): return "sqlite"
    return public_url(uri)

def tracking_info(learn=None) -> dict|None:
    "The MLflow run that logged a training: what a tracking callback kept on the learner, else the active run, else None"
    if learn is not None and getattr(learn, "tracking", None): return learn.tracking
    mlflow = sys.modules.get("mlflow")
    if mlflow is None: return None
    try: run = mlflow.active_run()
    except Exception: return None
    if run is None: return None
    return {"mlflow": {"run_id": run.info.run_id, "experiment_id": run.info.experiment_id,
                       "tracking_uri": public_tracking_uri(mlflow.get_tracking_uri())}}

# %% ../nbs/05a_record.ipynb #f21e7d22
def training_record(learn) -> dict:
    "What trained a learner's model, and how to train it again: code, environment, hardware, data, model, fits, tracking, and what it continued"
    m = learn.model
    shipped = json.loads(os.environ.get("SYSONE_SOURCE") or "{}")      # in a job: the checkout it was sent from
    sys_git = git_info(Path(sysone.__file__).parent) or shipped.get("sysone_git")
    cwd_git = git_info() or shipped.get("git")
    return {
        "recorded": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "code": {"git": cwd_git, "sysone_git": sys_git if sys_git and (cwd_git or {}).get("commit") != sys_git["commit"] else None,
                 "entry": entry_point()},
        "environment": environment(),
        "hardware": hardware(),
        "data": data_record(learn.data),
        "model": {"encoder": m.spec.id if m.spec is not None else None, "regime": m.regime, "lora": lora_config(m),
                  "params": m.n_params()},
        "training": {"preset": learn.preset, "loss": getattr(learn.loss, "__name__", type(learn.loss).__name__),
                     "lr": jsonable(learn.lr), "seed": learn.args.seed, "args": non_default_args(learn.args),
                     "fits": list(getattr(getattr(learn, "fit_log", None), "fits", [])),
                     "history": {"loss": thin(learn.recorder.losses), "eval": jsonable(learn.recorder.metrics)}},
        "tracking": tracking_info(learn),
    } | ({"resumed_from": learn.resumed_from} if getattr(learn, "resumed_from", None) else {})     # a learner from load_learner
