"""Row templates, transforms and the row builder: how a state and one typed question become one token row with an anchor in front of every option.

Docs: https://sgaseretto.github.io/sysonelib/template.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_template.ipynb.

# %% auto #0
__all__ = ['LAYA_ROW', 'SPECIALS', 'transform', 'Transform', 'tfms_to_json', 'tfms_from_json', 'apply_tfms', 'Regex', 'Lower',
           'Field', 'Truncate', 'Shuffle', 'load_image', 'Image', 'Stream', 'RowTemplate', 'RowBuilder',
           'processor_rows', 'default_image_side', 'prepare_processor', 'TokenStream', 'stream_from_json', 'show_row']

# %% ../nbs/01_template.ipynb #1d7501af
import copy, hashlib, importlib, json, random, re, string, warnings
from pathlib import Path

from fastcore.basics import patch, store_attr

from .core import *

# %% ../nbs/01_template.ipynb #41b69167
_TRANSFORMS = {}

def transform(name:str):
    "Register a `Transform` subclass under `name` so exports that use it stay loadable"
    def _inner(cls):
        cls.name = name
        _TRANSFORMS[name] = cls
        return cls
    return _inner

class Transform:
    "Base class: `__call__(record) -> record`, `to_json()`, and `train_only` for augmentation"
    name, train_only = None, False
    def __call__(self, record:dict) -> dict: return record
    def to_json(self) -> dict:
        return {"name": self.name, **{k: v for k, v in vars(self).items() if not k.startswith("_")}}
    def __repr__(self):
        args = ", ".join(f"{k}={v!r}" for k, v in self.to_json().items() if k != "name")
        return f"{self.name}({args})"
    @staticmethod
    def from_json(d:dict):
        "The transform described by `d` (a `to_json()` result)"
        d = dict(d); name = d.pop("name")
        if name not in _TRANSFORMS: raise ValueError(f"unknown transform {name!r}; register it with @sysone.transform({name!r})")
        return _TRANSFORMS[name](**d)

def tfms_to_json(tfms) -> list: return [t.to_json() for t in tfms or []]
def tfms_from_json(ds) -> list: return [Transform.from_json(d) for d in ds or []]

def apply_tfms(tfms, record:dict, train:bool=False) -> dict:
    "Run `tfms` over a record; `train_only` ones only when `train`"
    for t in tfms or []:
        if t.train_only and not train: continue
        record = t(record)
    return record

# %% ../nbs/01_template.ipynb #e8a066fc
def _map_text(obj, f):
    if isinstance(obj, str): return f(obj)
    if isinstance(obj, dict): return {k: _map_text(v, f) for k, v in obj.items()}
    if isinstance(obj, list): return [_map_text(v, f) for v in obj]
    return obj

def _map_record(record, f, state=True, instructions=True, options=True):
    "A copy of `record` with `f` applied to the chosen text fields"
    r = dict(record)
    if state: r["state"] = _map_text(r["state"], f)
    if instructions or options:
        qs = {}
        for qid, q in r["questions"].items():
            q = dict(q)
            if instructions and isinstance(q.get("instructions"), str): q["instructions"] = f(q["instructions"])
            crit = q.get("criteria")
            if options and isinstance(crit, dict): q["criteria"] = {k: _map_text(v, f) for k, v in crit.items()}
            elif options and isinstance(crit, list) and q.get("type") == "score": q["criteria"] = [_map_text(v, f) for v in crit]
            qs[qid] = q
        r["questions"] = qs
    return r

# %% ../nbs/01_template.ipynb #e2dee7ef
@transform("Regex")
class Regex(Transform):
    "Replace `pattern` with `repl` in the state, the instructions and the option descriptions"
    def __init__(self, pattern:str, repl:str="", state:bool=True, instructions:bool=True, options:bool=True):
        store_attr(); self._re = re.compile(pattern)
    def __call__(self, record):
        return _map_record(record, lambda s: self._re.sub(self.repl, s), self.state, self.instructions, self.options)

@transform("Lower")
class Lower(Transform):
    "Lower-case the state, the instructions and the option descriptions"
    def __init__(self, state:bool=True, instructions:bool=True, options:bool=True): store_attr()
    def __call__(self, record): return _map_record(record, str.lower, self.state, self.instructions, self.options)

# %% ../nbs/01_template.ipynb #3c919b6c
class _JSONFormatter(string.Formatter):
    def format_field(self, value, spec):
        if isinstance(value, (list, dict)) and not spec: return json.dumps(value, ensure_ascii=False)
        return super().format_field(value, spec)

@transform("Field")
class Field(Transform):
    "Render a dict state to text with a format string, e.g. `Field(state='{page[title]}\\n{page[text]}')`"
    def __init__(self, state:str): store_attr()
    def __call__(self, record):
        s = record["state"]
        if not isinstance(s, dict): return record
        return {**record, "state": _JSONFormatter().vformat(self.state, (), s)}

@transform("Truncate")
class Truncate(Transform):
    "Cut the state text to `state_chars` characters, keeping the start (`side='right'`) or the end"
    def __init__(self, state_chars:int, side:str="right"): store_attr()
    def __call__(self, record):
        s = record["state"]
        if not isinstance(s, str): s = render_state(s)
        if len(s) > self.state_chars: s = s[:self.state_chars] if self.side == "right" else s[-self.state_chars:]
        return {**record, "state": s}

# %% ../nbs/01_template.ipynb #cfa24bc1
@transform("Shuffle")
class Shuffle(Transform):
    "Shuffle the options of choice questions (training only by default)"
    def __init__(self, options:bool=True, train_only:bool=True, seed:int=0): store_attr(); self._epoch = 0
    def set_epoch(self, epoch:int): self._epoch = int(epoch)
    def __call__(self, record):
        if not self.options: return record
        rng = random.Random(f"{self.seed}:{self._epoch}:{record.get('id', render_state(record['state'])[:200])}")
        qs = {}
        for qid, q in record["questions"].items():
            crit = q.get("criteria")
            if q.get("type") == "choice" and crit:
                items = list(crit.items()) if isinstance(crit, dict) else [(c, None) for c in crit]
                rng.shuffle(items)
                q = {**q, "criteria": dict(items)}
            qs[qid] = q
        return {**record, "questions": qs}

# %% ../nbs/01_template.ipynb #1c6fee86
def load_image(img, side:int|None=None):
    "A PIL RGB image from a path, a base64 data URL, bytes or a PIL image, resized so its long side is `side`"
    from PIL import Image as PILImage
    import io, base64
    if isinstance(img, str) and img.startswith("data:image/"): img = PILImage.open(io.BytesIO(base64.b64decode(img.split(",", 1)[1])))
    elif isinstance(img, (str, Path)): img = PILImage.open(img)
    elif isinstance(img, (bytes, bytearray)): img = PILImage.open(io.BytesIO(img))
    elif isinstance(img, dict) and "bytes" in img: img = PILImage.open(io.BytesIO(img["bytes"]))
    img = img.convert("RGB")
    if side and max(img.size) != side:
        w, h = img.size; s = side / max(w, h)
        img = img.resize((max(1, round(w * s)), max(1, round(h * s))), PILImage.BICUBIC)
    return img

@transform("Image")
class Image(Transform):
    "Move the image at `state[key]` into `record['images']`, resized to `side` px on the long side"
    def __init__(self, key:str="image", side:int|None=1024): store_attr()
    def __call__(self, record):
        s = record["state"]
        if not isinstance(s, dict): return record
        if s.get(self.key) is None:        # no image: a state that is only text reads as that text all the same
            return {**record, "state": s["text"]} if set(s) - {self.key} == {"text"} else record
        s = dict(s); img = s.pop(self.key)
        text = s.pop("text") if set(s) == {"text"} else (s if s else "")
        return {**record, "state": text, "images": [load_image(img, self.side)]}

# %% ../nbs/01_template.ipynb #13c2fa89
@transform("Stream")
class Stream(Transform):
    "Move `state[key]` out of the text and into the side stream `stream` (named `key` by default), which the encoder reads on its own"
    def __init__(self, key:str, stream:str|None=None): store_attr(); self.stream = stream or key
    def __call__(self, record):
        s = record["state"]
        if not isinstance(s, dict) or s.get(self.key) is None: return record
        s = dict(s); v = s.pop(self.key)
        text = s.pop("text") if set(s) == {"text"} else (s if s else "")
        return {**record, "state": text, "streams": {**(record.get("streams") or {}), self.stream: v}}

# %% ../nbs/01_template.ipynb #6831b764
LAYA_ROW = "{start}{type} question: {instructions}{sep}{options}{sep}{state}{end}"
_ROW_FIELDS = {"start", "sep", "end", "mask", "image", "type", "instructions", "options", "state"}
_OPTION_FIELDS = {"mask", "text"}
SPECIALS = ("start", "sep", "end", "mask", "image")

def _parse(fmt:str, allowed:set):
    "Split a format string into ('lit', text) and ('field', name) pieces"
    out = []
    for lit, name, spec, conv in string.Formatter().parse(fmt):
        if lit: out.append(("lit", lit))
        if name is None: continue
        if name not in allowed: raise ValueError(f"unknown field {{{name}}} in {fmt!r}; use {sorted(allowed)}")
        out.append(("field", name))
    return out

class RowTemplate:
    "How a question and a state are laid out as one row, which special tokens it uses, and the token budgets"
    def __init__(self,
                 start:str|None="[CLS]", # token that opens the row
                 sep:str|None="[SEP]", # token between sections
                 mask:str="[MASK]", # the anchor placed before every option; must be one token
                 end:str|None="[SEP]", # token that closes the row
                 image:str|None=None, # image placeholder token, for processor encoders
                 row:str=LAYA_ROW, # the row's format string
                 option:str="{mask} {text}", # one option's format string; must start with {mask}
                 max_len:int=512, # tokens per row, image positions included
                 head_max_len:int=192, # tokens for the question and its options
                 option_tokens:int=48, # text tokens per option
                 truncate:str="right", # cut long states on the "right", "left", or "auto" (left for conversation lists, as Laya does)
                 option_sep:str="", # text between options; tokenizer rows concatenate the option chunks
                 tfms:list|None=None, # transforms saved with the template
                 name:str|None=None): # preset name, for display
        store_attr(but="tfms"); self.tfms = list(tfms or [])
        self._row, self._option = _parse(row, _ROW_FIELDS), _parse(option, _OPTION_FIELDS)
        if ("field", "options") not in self._row: raise ValueError("a row needs an {options} field")
        if ("field", "state") not in self._row: raise ValueError("a row needs a {state} field")
        if not self._option or self._option[0] != ("field", "mask"):
            raise ValueError("an option must start with {mask}, so truncation never removes the anchor")
        if truncate not in ("right", "left", "auto"): raise ValueError(f"truncate must be 'right', 'left' or 'auto', not {truncate!r}")

    def __repr__(self):
        return (f"RowTemplate({self.name or 'custom'}: {self.row!r}, option={self.option!r}, mask={self.mask!r}, "
                f"budgets {self.max_len}/{self.head_max_len}/{self.option_tokens})")

# %% ../nbs/01_template.ipynb #57731bcf
_TEMPLATE_KEYS = ("start", "sep", "end", "mask", "image", "row", "option", "max_len", "head_max_len",
                  "option_tokens", "truncate", "option_sep")

@patch
def to_json(self:RowTemplate) -> dict:
    "The template as it is written to `sysone.json` (transforms are written beside it)"
    return {k: getattr(self, k) for k in _TEMPLATE_KEYS} | ({"name": self.name} if self.name else {})

@patch(cls_method=True)
def from_json(cls:RowTemplate, d:dict, tfms=None):
    "The template described by a `to_json()` result"
    return cls(**{k: v for k, v in d.items() if k in _TEMPLATE_KEYS + ("name",)}, tfms=tfms)

@patch
def replace(self:RowTemplate, **kw):
    "A copy with some fields changed"
    return RowTemplate(**({k: getattr(self, k) for k in _TEMPLATE_KEYS} | {"tfms": self.tfms, "name": self.name} | kw))

@patch(as_prop=True)
def hash(self:RowTemplate) -> str:
    "A short digest of the template and its transforms, part of the feature-cache key"
    blob = json.dumps({"t": self.to_json() | {"name": None}, "tfms": tfms_to_json(self.tfms)}, sort_keys=True)
    return hashlib.sha1(blob.encode()).hexdigest()[:16]

# %% ../nbs/01_template.ipynb #8d305d38
_PRESETS = {
    "laya": dict(start="[CLS]", sep="[SEP]", mask="[MASK]", end="[SEP]", row=LAYA_ROW, option="{mask} {text}",
                 max_len=512, head_max_len=192, option_tokens=48, truncate="auto"),
    "gliner": dict(start=None, sep="[SEP_TEXT]", end=None, mask="[L]",
                   row="{start}( [P] {type}: {instructions} ( {options} ) ){sep}{state}{end}",
                   option="{mask} {text}", max_len=512, head_max_len=192, option_tokens=48, truncate="right"),
    "neomme": dict(start="<doc>", sep="\n", mask="<mask>", end=None, image="<img>",
                   row="{start}{type} question: {instructions}{sep}{options}{sep}{image}{state}{end}",
                   option="{mask}{text}", option_sep="\n", max_len=2048, head_max_len=384, option_tokens=48, truncate="right"),
    "neomme_page_first": dict(start="<doc>", sep="\n", mask="<mask>", end=None, image="<img>",
                   row="{start}{image}{state}{sep}{type} question: {instructions}{sep}{options}{end}",
                   option="{mask}{text}", option_sep="\n", max_len=2048, head_max_len=384, option_tokens=48, truncate="right"),
    "modernvbert": dict(start="[CLS]", sep="[SEP]", mask="[MASK]", end="[SEP]", image="<image>",
                        row="{start}{type} question: {instructions}{sep}{options}{sep}{image}{state}{end}",
                        option="{mask} {text}", max_len=2048, head_max_len=384, option_tokens=48, truncate="right"),
}

@patch(cls_method=True)
def preset(cls:RowTemplate, name:str, tokenizer=None, **overrides):
    "A named template (`laya`, `gliner`, `neomme`, `neomme_page_first`, `modernvbert`, `auto`), optionally with fields changed"
    if name == "auto" and tokenizer is None:
        raise ValueError("RowTemplate.preset('auto') needs the tokenizer to read its special tokens from")
    if name in ("laya", "auto") and tokenizer is not None:   # Laya's runtime reads cls, sep and mask off the tokenizer
        tok = getattr(tokenizer, "tokenizer", tokenizer)
        found = {r: getattr(tok, f"{r}_token", None) for r in ("cls", "sep", "mask")}
        missing = [f"{r}_token" for r, v in found.items() if not v]
        if missing and name == "auto": raise ValueError(f"the tokenizer defines no {', '.join(missing)}; name a RowTemplate for this encoder")
        kw = _PRESETS["laya"] | ({} if missing else dict(start=found["cls"], sep=found["sep"], end=found["sep"], mask=found["mask"]))
    elif name in _PRESETS: kw = dict(_PRESETS[name])
    else: raise ValueError(f"unknown preset {name!r}; use one of {sorted(_PRESETS) + ['auto']}")
    return cls(**(kw | overrides), name=name)

# %% ../nbs/01_template.ipynb #f7762c2d
def _compile(pieces):
    "Group pieces into segments: ('special', role), ('run', [pieces]), ('options',), ('state',)"
    segs, run = [], []
    def flush():
        nonlocal run
        if run: segs.append(("run", run)); run = []
    for kind, v in pieces:
        if kind == "field" and v in SPECIALS: flush(); segs.append(("special", v))
        elif kind == "field" and v in ("options", "state"): flush(); segs.append((v,))
        else: run.append((kind, v))
    flush()
    return segs

def _is_processor(obj):
    "Whether `obj` is a transformers processor (tokenizer plus image processor) rather than a tokenizer"
    from transformers import ProcessorMixin
    return isinstance(obj, ProcessorMixin)

class RowBuilder:
    "Build rows from records with a tokenizer (or a processor, for multimodal encoders) and a `RowTemplate`"
    def __init__(self, tokenizer, template:RowTemplate|str="laya", tfms:list|None=None, streams=None):
        if isinstance(template, str): template = RowTemplate.preset(template, tokenizer=tokenizer)
        self.processor = tokenizer if _is_processor(tokenizer) else None
        self.tok = tokenizer.tokenizer if self.processor is not None else tokenizer
        self.template, self.tfms = template, list(template.tfms) + list(tfms or [])
        self._row_segs, self._opt_segs = _compile(template._row), _compile(template._option)
        self.ids = self._resolve_specials()
        self.extra_scrub = []   # further token strings to remove from user text (a multimodal encoder's own markers)
        self.streams = {s.name: s for s in (streams.values() if isinstance(streams, dict) else streams or [])}
        self.stats = {"rows": 0, "state_truncated": 0, "options_cut": 0, "dropped": 0}

    def __repr__(self):
        kind = "processor" if self.processor is not None else "tokenizer"
        streams = f", streams={list(self.streams.values())}" if self.streams else ""
        return f"RowBuilder({type(self.tok).__name__} {kind}, {self.template!r}, tfms={self.tfms}{streams})"

# %% ../nbs/01_template.ipynb #80931346
def _single_token_id(tok, s):
    "The id of `s` if the tokenizer knows it as exactly one token, else None"
    if not s: return None
    tid = tok.convert_tokens_to_ids(s)
    if tid is None or (tid == tok.unk_token_id and s != tok.unk_token): return None
    return tid if tok(s, add_special_tokens=False)["input_ids"] == [tid] else None

@patch
def _resolve_specials(self:RowBuilder) -> dict:
    "Token ids of the template's special tokens; the anchor must be one token"
    t, ids = self.template, {}
    for role in SPECIALS:
        s = getattr(t, role)
        ids[role] = _single_token_id(self.tok, s) if s else None
    if ids["mask"] is None:
        raise ValueError(f"the anchor {t.mask!r} is not a single token of this tokenizer; pick a token it knows "
                         f"(its mask token is {getattr(self.tok, 'mask_token', None)!r})")
    return ids

# %% ../nbs/01_template.ipynb #3c87dd40
@patch
def _scrub(self:RowBuilder, s:str) -> str:
    "User text with the anchor and image tokens replaced by spaces"
    for tokstr in [getattr(self.template, r) for r in ("mask", "image")] + self.extra_scrub:
        if tokstr: s = s.replace(tokstr, " ")
    return s

def _render_run(parts, q=None, text=None):
    "The text of a run, and the literal text after its variable field (kept when the run is cut)"
    out, tail, seen = [], [], False
    for kind, v in parts:
        s = v if kind == "lit" else (q.type if v == "type" else q.instructions if v == "instructions" else text)
        out.append(s)
        if kind == "field" and v in ("instructions", "text"): seen, tail = True, []
        elif seen: tail.append(s)
    return "".join(out), "".join(tail)

def _cut(ids, n, tail_ids):
    "At most n ids, keeping the ids of the run's literal tail"
    if len(ids) <= n: return ids
    return ids[:max(0, n - len(tail_ids))] + list(tail_ids)

# %% ../nbs/01_template.ipynb #8f922c6a
@patch
def _encode(self:RowBuilder, texts:list) -> list:
    "Token ids of several texts in one tokenizer call; the empty string has none"
    idx = [i for i, s in enumerate(texts) if s]   # verbose=False: a long state is expected here, the layout truncates it
    enc = self.tok([texts[i] for i in idx], add_special_tokens=False, verbose=False)["input_ids"] if idx else []
    out = [[] for _ in texts]
    for i, ids in zip(idx, enc): out[i] = list(ids)
    return out

@patch
def _question_parts(self:RowBuilder, q:Question):
    "Texts to tokenize for one question: each run of the row, each option's runs"
    q = Question(q.type, self._scrub(q.instructions), q.criteria, q.labels, q.name)
    runs = [_render_run(s[1], q) for s in self._row_segs if s[0] == "run"]
    opts = [[_render_run(s[1], q, self._scrub(o)) for s in self._opt_segs if s[0] == "run"] for o in q.options]
    return runs, opts

# %% ../nbs/01_template.ipynb #4f86125f
@patch
def _assemble(self:RowBuilder, q:Question, run_ids, opt_ids, state_ids, state_is_list=False, image_ids=None):
    "ids, marker positions and the image marker's position for one question, with Laya's budget rules"
    t, image_ids = self.template, list(image_ids or [])
    # 1. options: anchor + at most option_tokens text tokens (per text run, literal tail kept)
    chunks = []
    for runs in opt_ids:
        c, r = [], iter(runs)
        for seg in self._opt_segs:
            if seg[0] == "special": c.append(self.ids[seg[1]])
            elif seg[0] == "run": ids, tail = next(r); c.extend(_cut(ids, t.option_tokens, tail))
        chunks.append(c)
    sep_ids = self._encode([t.option_sep])[0] if t.option_sep else []
    opt_len = lambda: sum(len(c) for c in chunks) + len(sep_ids) * max(0, len(chunks) - 1)
    # 2. squeeze the options if they leave the question fewer than 16 tokens
    budget = t.head_max_len - opt_len()
    if budget < 16:
        per = max(4, (t.head_max_len - 16) // max(1, len(chunks)))
        if any(len(c) > per for c in chunks): self.stats["options_cut"] += 1
        chunks = [c[:per] for c in chunks]
        budget = t.head_max_len - opt_len()
    # 3. the run holding the instructions gets what head_max_len has left
    runs = []
    for (ids, tail), seg in zip(run_ids, [s for s in self._row_segs if s[0] == "run"]):
        has_ins = ("field", "instructions") in seg[1]
        runs.append(_cut(ids, max(8, budget), tail) if has_ins else ids)
    # 4. the state gets the rest of max_len
    specials = lambda role: [] if getattr(t, role) is None else [self.ids[role]] if self.ids[role] is not None else self._encode([getattr(t, role)])[0]
    img_seg = [i for i, s in enumerate(self._row_segs) if s == ("special", "image")]
    if image_ids and not img_seg: raise ValueError("the record has an image, but the template has no {image} field")
    dedupe = bool(image_ids) and img_seg[0] > 0 and self._row_segs[img_seg[0] - 1] == ("special", "start") \
             and self.ids["start"] == image_ids[0]      # the block's leading token already opens the row
    fixed = sum(len(specials(s[1])) for s in self._row_segs if s[0] == "special" and s[1] != "image")
    fixed += sum(len(r) for r in runs) + opt_len() + len(image_ids) - int(dedupe)
    room = max(0, t.max_len - fixed)
    left = t.truncate == "left" or (t.truncate == "auto" and state_is_list)
    if len(state_ids) > room: self.stats["state_truncated"] += 1
    st = state_ids[max(0, len(state_ids) - room):] if left else state_ids[:room]
    # lay the segments out in template order
    ids, markers, spans, r, image_at = [], [], [], iter(runs), None
    for seg in self._row_segs:
        if seg[0] == "special":
            if seg[1] != "image": ids.extend(specials(seg[1]))
            elif image_ids:
                block = image_ids[1:] if ids and ids[-1] == image_ids[0] else image_ids
                image_at = len(ids) + len(block) - len(image_ids) + 1     # the image marker, after its opening token
                ids.extend(block)
        elif seg[0] == "run": ids.extend(next(r))
        elif seg[0] == "state": ids.extend(st)
        else:
            for i, c in enumerate(chunks):
                if i and sep_ids: ids.extend(sep_ids)
                markers.append(len(ids)); spans.append((len(ids) + 1, len(ids) + len(c))); ids.extend(c)
    if image_ids and len(ids) > t.max_len:
        raise ValueError(f"the image takes {len(image_ids)} positions and the row does not fit max_len={t.max_len}; resize the image")
    keep = [i for i, m in enumerate(markers) if m < t.max_len]
    return ids[:t.max_len], [markers[i] for i in keep], image_at, [(s, min(e, t.max_len)) for s, e in (spans[i] for i in keep)]

# %% ../nbs/01_template.ipynb #85fdaebf
@dispatch
def processor_rows(processor:object, builder, record:dict, *, skip_errors:bool=False) -> list:
    "The rows of a transformed record for a multimodal encoder: dispatched on its processor's class, whose adapter adds the method"
    if load_adapter(processor): return processor_rows(processor, builder, record, skip_errors=skip_errors)
    raise ValueError(f"no row builder for a {type(processor).__name__}: register one with `processor_rows.register`")

@dispatch
def default_image_side(processor:object):
    "The side, in pixels, an encoder's images are resized to by default: dispatched on its processor's class (None: as they are)"
    if load_adapter(processor): return default_image_side(processor)
    return None

@dispatch
def prepare_processor(processor:object, side:int|None) -> int:
    "Set a processor up for images of `side` pixels: how many images each row then carries (1, unless the processor tiles)"
    if load_adapter(processor): return prepare_processor(processor, side)
    return 1

@patch
def build_record(self:RowBuilder, record:dict, train:bool=False, skip_errors:bool=False, tfms:bool=True) -> list:
    "One `Row` per question of a record (a case with `state`, `questions`, optional `gold`)"
    record = load_record(record, parse_state=False)
    if tfms: record = apply_tfms(self.tfms, record, train=train)
    if self.processor is not None: return self._add_streams(record, processor_rows(self.processor, self, record, skip_errors=skip_errors))
    gold, rows = record.get("gold") or {}, []
    for qid, q, ids, markers, _, spans in self._layout(record, skip_errors=skip_errors):
        target, label = q.target(gold.get(qid))
        rows.append(Row(ids, markers, q.qtype, target, label, meta={"qid": qid, "case": record.get("id")},
                        spans=spans, answerable=q.answerable(gold.get(qid))))
    return self._add_streams(record, rows)

@patch
def _add_streams(self:RowBuilder, record:dict, rows:list) -> list:
    "Every row of the record gets the inputs of each side stream (a record without one gets the stream's empty input)"
    if not self.streams or not rows: return rows
    vals, ex = record.get("streams") or {}, {}
    for name, s in self.streams.items(): ex |= s.build(vals.get(name))
    for r in rows: r.extras.update(ex)
    return rows

@patch
def _layout(self:RowBuilder, record:dict, image_ids=None, skip_errors:bool=False) -> list:
    "(qid, question, ids, markers, image marker position, option spans) for each question of a transformed record"
    qs = as_questions(record["questions"])
    parts = {qid: self._question_parts(q) for qid, q in qs.items()}
    texts = [self._scrub(render_state(record["state"]))]
    for runs, opts in parts.values():
        for s, tail in runs: texts += [s, tail]
        for o in opts:
            for s, tail in o: texts += [s, tail]
    enc = iter(self._encode(texts))
    state_ids = next(enc)
    out = []
    for qid, q in qs.items():
        runs, opts = parts[qid]
        run_ids = [(next(enc), next(enc)) for _ in runs]
        opt_ids = [[(next(enc), next(enc)) for _ in o] for o in opts]
        ids, markers, image_at, spans = self._assemble(q, run_ids, opt_ids, state_ids, isinstance(record["state"], list), image_ids)
        self.stats["rows"] += 1
        if len(markers) != q.k:
            if not skip_errors: raise ValueError(f"question {qid!r}: its {q.k} options do not fit max_len={self.template.max_len}")
            self.stats["dropped"] += 1; continue
        out.append((qid, q, ids, markers, image_at, spans))
    return out

@patch
def build(self:RowBuilder, state, question, gold=None, name="q") -> Row:
    "The row for one question over one state"
    q = Question.from_dict(question, name=name)
    return self.build_record({"state": state, "questions": {name: q.to_dict()}, "gold": {name: gold}})[0]

# %% ../nbs/01_template.ipynb #fe0d721f
class TokenStream:
    "A side stream tokenized by its own tokenizer; its ids and attention mask ride in every row of the record"
    def __init__(self,
                 name:str, # the stream, as `Stream` names it; its inputs are `{name}_input_ids` and `{name}_attention_mask`
                 tokenizer, # the stream's tokenizer
                 max_len:int=1024, # tokens, special tokens included
                 crop:str="right"): # "right" keeps the start, "left" the end, "ends" the start and the end
        if crop not in ("right", "left", "ends"): raise ValueError(f"crop must be 'right', 'left' or 'ends', not {crop!r}")
        store_attr(); self.stats = {"built": 0, "cropped": 0}
        self.n_special = len(tokenizer("")["input_ids"])
        if max_len <= self.n_special: raise ValueError(f"max_len={max_len} leaves no room beside {self.n_special} special tokens")
        EXTRA_COLLATE[f"{name}_input_ids"] = ("pad_rows", tokenizer.pad_token_id if tokenizer.pad_token_id is not None else 0)
        EXTRA_COLLATE[f"{name}_attention_mask"] = ("pad_rows", 0)

    def __repr__(self): return f"TokenStream({self.name}: {type(self.tokenizer).__name__}, max_len={self.max_len}, crop={self.crop!r})"
    @property
    def columns(self) -> tuple: return (f"{self.name}_input_ids", f"{self.name}_attention_mask")
    def to_json(self) -> dict: return {"kind": "tokens", "name": self.name, "max_len": self.max_len, "crop": self.crop}

    def build(self, value) -> dict:
        "The stream's inputs for one record (just the special tokens when the record has none)"
        text = "" if value is None else str(value)
        full = self.tokenizer(text)["input_ids"]                                  # with the tokenizer's own special tokens
        ids = self.tokenizer(text, add_special_tokens=False)["input_ids"] if text else []
        at = next((i for i in range(len(full) - len(ids) + 1) if full[i:i + len(ids)] == ids), 0)
        head, tail, room = full[:at], full[at + len(ids):], self.max_len - (len(full) - len(ids))
        self.stats["built"] += 1
        if len(ids) > room:
            self.stats["cropped"] += 1
            ids = ids[:room] if self.crop == "right" else ids[-room:] if self.crop == "left" else ids[:room - room // 2] + ids[len(ids) - room // 2:]
        ids = head + ids + tail
        return {self.columns[0]: ids, self.columns[1]: [1] * len(ids)}

def stream_from_json(d:dict, tokenizer):
    "The side stream described by `to_json()`, on `tokenizer`"
    if d.get("kind", "tokens") != "tokens": raise ValueError(f"unknown stream kind {d.get('kind')!r}")
    return TokenStream(d["name"], tokenizer, d.get("max_len", 1024), d.get("crop", "right"))

# %% ../nbs/01_template.ipynb #2f524cb4
def _decode_ids(tok, ids):
    specials = set(getattr(tok, "all_special_ids", []))
    out, buf = [], []
    def flush():
        if buf: out.append(tok.decode(buf).strip()); buf.clear()
    i = 0
    while i < len(ids):
        t = ids[i]
        if t in specials:
            flush(); j = i
            while j < len(ids) and ids[j] == t: j += 1
            s = tok.convert_ids_to_tokens(t)
            out.append(s if j - i == 1 else f"{s}×{j - i}"); i = j
        else: buf.append(t); i += 1
    flush()
    return " ".join(o for o in out if o)

def show_row(row:Row, tok, max_chars:int=300) -> str:
    "A row as readable text, anchors visible, plus its markers, type and length"
    tok = getattr(tok, "tokenizer", tok) if not hasattr(tok, "convert_ids_to_tokens") else tok
    s = _decode_ids(tok, list(row.ids))
    if len(s) > max_chars: s = s[:max_chars * 2 // 3] + " … " + s[-max_chars // 3:]
    streams = "".join(f" · {k.removesuffix('_input_ids')} {len(v)} tokens" for k, v in row.extras.items() if k.endswith("_input_ids"))
    return f"{s}\nmarkers {list(row.markers)} · qtype {QTYPE_NAMES[row.qtype]} · {row.n_tokens} tokens{streams}"

@patch
def show(self:RowBuilder, record:dict, max_chars:int=300):
    "Print the rows of a record"
    for r in self.build_record(record): print(show_row(r, self.tok, max_chars), end="\n\n")

# %% ../nbs/01_template.ipynb #8827cc09
@patch
def to_json(self:RowBuilder) -> dict:
    "The template, transforms and side streams, as written to `sysone.json`"
    return {"template": self.template.to_json(), "tfms": tfms_to_json(self.tfms)} | \
           ({"streams": [s.to_json() for s in self.streams.values()]} if self.streams else {})

@patch(cls_method=True)
def from_json(cls:RowBuilder, d:dict, tokenizer, stream_tokenizers:dict|None=None):
    "The builder described by `to_json()`, on `tokenizer` (and each side stream on its tokenizer in `stream_tokenizers`)"
    streams = [stream_from_json(s, (stream_tokenizers or {})[s["name"]]) for s in d.get("streams") or []]
    return cls(tokenizer, RowTemplate.from_json(d["template"]), tfms_from_json(d.get("tfms")), streams=streams)
