"""Training on TPUs and on AWS Trainium, which compile the model's graph with XLA: batches of fixed shapes, so a graph compiles once and is reused, and the presets for both; and the export of a model for Inferentia2.

Docs: https://sgaseretto.github.io/sysonelib/xla.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/47_xla.ipynb.

# %% auto #0
__all__ = ['OPTION_KEYS', 'XLA_CHECK', 'NEURON_CHECK', 'length_buckets', 'bucket', 'pad_batch', 'StaticCollator', 'max_options',
           'all_answerable', 'side_lengths', 'prepare_xla', 'xla_metrics', 'xla_check_image', 'xla_check',
           'neuron_inputs', 'export_neuron', 'NeuronScorer', 'neuron_check_image', 'neuron_check']

# %% ../nbs/47_xla.ipynb #bf3349bd
import json, os, sys, warnings
from pathlib import Path

import torch
from fastcore.basics import patch

from .core import *
from .data import DecisionCollator
from .models import SideEncoder
from .learner import Learner

# %% ../nbs/47_xla.ipynb #c80d4c1a
def length_buckets(max_len:int, smallest:int=64) -> tuple:
    "The lengths a batch is padded to: powers of two from `smallest`, and `max_len` itself"
    out, n = [], smallest
    while n < max_len: out.append(n); n *= 2
    return tuple(out) + (max_len,)

def bucket(n:int, buckets:tuple) -> int:
    "The smallest bucket that holds `n` (the largest, when none does)"
    return next((b for b in buckets if b >= n), buckets[-1])

OPTION_KEYS = ("marker_pos", "marker_mask", "target", "spans")

def _grow(t, size:int, axis:int, value):
    if t.shape[axis] >= size: return t
    pad = list(t.shape); pad[axis] = size - t.shape[axis]
    return torch.cat([t, torch.full(pad, value, dtype=t.dtype)], axis)

def pad_batch(b:dict, L:int, K:int, pad_id:int=0, sides:dict|None=None) -> Batch:
    "Pad a collated batch: the sequence (and extras that follow it) to length `L`, the options to `K`, each side stream to its length in `sides`"
    l, k = b["input_ids"].shape[1], b["marker_pos"].shape[1]
    if l > L or k > K: raise ValueError(f"a batch of length {l} with {k} options does not fit {L} and {K}")
    out = dict(b)
    out["input_ids"], out["attention_mask"] = _grow(b["input_ids"], L, 1, pad_id), _grow(b["attention_mask"], L, 1, 0)
    for key, how in EXTRA_COLLATE.items():
        kind, value = how if isinstance(how, tuple) else (how, 0)
        if key in b and kind == "pad": out[key] = _grow(b[key], L, -1, value)
    for key in OPTION_KEYS:
        if key in b: out[key] = _grow(b[key], K, 1, 0)
    for name, S in (sides or {}).items():
        for key in (f"{name}_input_ids", f"{name}_attention_mask"):
            if key not in b: continue
            if b[key].shape[1] > S: raise ValueError(f"side stream {name} has {b[key].shape[1]} tokens, more than {S}")
            how = EXTRA_COLLATE.get(key, ("pad_rows", 0))
            out[key] = _grow(b[key], S, 1, how[1] if isinstance(how, tuple) else 0)
    return Batch(out)

class StaticCollator(DecisionCollator):
    "A collator for XLA: rows padded to a length bucket and a fixed number of options, side streams to buckets of their own"
    def __init__(self, pad_id:int=0, buckets:tuple=(512,), options:int=8, side_buckets:dict|None=None):
        super().__init__(pad_id); self.buckets, self.options, self.side_buckets = tuple(buckets), options, dict(side_buckets or {})
    def __call__(self, rows):
        b = super().__call__(rows)
        sides = {n: bucket(b[f"{n}_input_ids"].shape[1], bs) for n, bs in self.side_buckets.items() if f"{n}_input_ids" in b}
        return pad_batch(b, bucket(b["input_ids"].shape[1], self.buckets), self.options, self.pad_id, sides)
    def __repr__(self): return f"StaticCollator(pad_id={self.pad_id}, buckets={self.buckets}, options={self.options}, sides={self.side_buckets})"

# %% ../nbs/47_xla.ipynb #c43db516
def max_options(learn) -> int:
    "The most options of any question in the learner's training and validation rows"
    k = 0
    for split in ("train", "valid"):
        if learn.data.cases.get(split) is None: continue
        ds = learn.dataset(split)
        col = ds["markers"] if hasattr(ds, "column_names") else [r["markers"] for r in ds]
        k = max(k, max((len(m) for m in col), default=0))
    return k

def all_answerable(learn) -> bool:
    "Whether every training row has an answer (a target with some mass)"
    ds = learn.dataset("train")
    ts = ds["target"] if hasattr(ds, "column_names") else [r["target"] for r in ds]
    return all(t is not None and sum(t) > 0 for t in ts)

def side_lengths(learn) -> dict:
    "The longest input of each side stream in the learner's training and validation rows"
    out = {}
    for name in learn.data.builder.streams:
        for split in ("train", "valid"):
            if learn.data.cases.get(split) is None: continue
            ds, key = learn.dataset(split), f"{name}_input_ids"
            col = ds[key] if hasattr(ds, "column_names") and key in ds.column_names else [r.get(key) or [] for r in ds]
            out[name] = max(out.get(name, 0), max((len(x) for x in col), default=0))
    return out

def prepare_xla(learn:Learner, buckets:tuple|None=None, options:int|None=None) -> Learner:
    "Make a learner's batches and step suit XLA: length buckets, fixed options, the loss on whole batches, side encoders without dedup"
    tmpl = learn.data.builder.template
    buckets = buckets or length_buckets(tmpl.max_len)
    sides = {n: length_buckets(L, 64) for n, L in side_lengths(learn).items() if L}
    col = StaticCollator(learn.data.builder.tok.pad_token_id or 0, buckets, options or max_options(learn), sides)
    learn.trainer.data_collator = col
    learn.trainer.all_answerable = all_answerable(learn)
    if not learn.trainer.all_answerable: warnings.warn("some training rows have no answer: the loss indexes them out, which recompiles on XLA")
    for m in learn.model.modules():
        if isinstance(m, SideEncoder): m.dedupe = False
    learn.xla = {"buckets": list(buckets), "options": col.options, "all_answerable": learn.trainer.all_answerable}
    return learn

def xla_metrics() -> dict:
    "PyTorch/XLA's compilation counters (how many graphs were compiled, and how long that took), when torch_xla is loaded"
    if "torch_xla" not in sys.modules: return {}
    import torch_xla.debug.metrics as met
    d = met.metric_data("CompileTime")
    return {"compiles": d[0] if d else 0, "compile_seconds": round(d[1] / 1e9, 2) if d else 0.0}

# %% ../nbs/47_xla.ipynb #494f407a
XLA_CHECK = r'''import json, os, sys
os.environ.setdefault("PJRT_DEVICE", "CPU")
import torch_xla
from sysone.data import TypedDecisions
from sysone.learner import decision_learner
from sysone.xla import prepare_xla, xla_metrics
data = TypedDecisions.from_json(sys.argv[1], valid=0.25, calib=0.2)
learn = decision_learner(data, sys.argv[2], train="head", preset="tpu", logging_steps=1, disable_tqdm=True, bf16=False, calibrate_after_fit=False)
learn.fit(1, lr=1e-3); first = xla_metrics()
learn.fit(1, lr=1e-3); second = xla_metrics()
print("SYSONE-XLA " + json.dumps({"first": first, "second": second, "device": str(next(learn.model.parameters()).device), "xla": learn.xla}))
'''

def xla_check_image(tag:str="sysone-xla-check", platform:str="linux/amd64") -> str:
    "Build a Linux image with torch_xla's CPU device and this sysone, to check that XLA trains with few compilations"
    import subprocess, tempfile
    from sysone.cloud import build_wheel
    ctx = Path(tempfile.mkdtemp(prefix="sysone-xla-")); whl = build_wheel(ctx / "wheels")
    (ctx / "Dockerfile").write_text("FROM python:3.12-slim\nENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1\n"
        'RUN pip install --index-url https://download.pytorch.org/whl/cpu "torch==2.9.0" && pip install "torch_xla==2.9.0"\n'
        "COPY wheels/ /w/\nRUN pip install /w/*.whl\n")
    r = subprocess.run(["docker", "build", "--platform", platform, "-t", tag, str(ctx)], capture_output=True, text=True)
    if r.returncode != 0: raise RuntimeError(f"docker build failed: {r.stdout[-1500:]}{r.stderr[-1500:]}")
    return tag

def xla_check(data, encoder, tag:str="sysone-xla-check", platform:str="linux/amd64") -> dict:
    "Train a learner on PyTorch/XLA's CPU device in a container, two epochs; returns the compilations of each"
    import subprocess, tempfile
    work = Path(tempfile.mkdtemp(prefix="sysone-xla-run-"))
    (work / "check.py").write_text(XLA_CHECK)
    import shutil
    shutil.copy2(data, work / Path(data).name); shutil.copytree(encoder, work / "encoder")
    r = subprocess.run(["docker", "run", "--rm", "--platform", platform, "-v", f"{work}:/w", "-w", "/w", tag,
                        "python", "check.py", Path(data).name, "encoder"], capture_output=True, text=True)
    line = next((l for l in r.stdout.splitlines() if l.startswith("SYSONE-XLA ")), None)
    if line is None: raise RuntimeError(f"the XLA check failed: {(r.stdout + r.stderr)[-2500:]}")
    return json.loads(line[len("SYSONE-XLA "):])

# %% ../nbs/47_xla.ipynb #813649ba
def neuron_inputs(learn, batch:int=1, length:int|None=None) -> tuple:
    "Example inputs of the fixed shapes a Neuron model is compiled for: token ids, attention mask, question kind"
    L = length or learn.data.builder.template.max_len
    return (torch.zeros(batch, L, dtype=torch.long), torch.ones(batch, L, dtype=torch.long), torch.zeros(batch, dtype=torch.long))

def export_neuron(learn, path, batch:int=1, length:int|None=None, target:str|None=None) -> Path:
    "Compile the encoder and the head's position scores for Inferentia2 or Trainium, at fixed shapes, beside an export in `path`"
    try: import torch_neuronx
    except ImportError: raise ImportError("export_neuron needs the Neuron SDK: pip install torch-neuronx --extra-index-url https://pip.repos.neuron.amazonaws.com") from None
    from sysone.inference import PositionScores
    path = Path(learn.export(path)) if not (Path(path) / "sysone.json").exists() else Path(path)
    if target: os.environ["NEURON_PLATFORM_TARGET_OVERRIDE"] = target
    mod = PositionScores(learn.model.float().eval().cpu())
    ex = neuron_inputs(learn, batch, length)
    traced = torch_neuronx.trace(mod, ex)
    torch.jit.save(traced, str(path / "model.neuron.pt"))
    meta = json.loads((path / "sysone.json").read_text())
    meta["neuron"] = {"file": "model.neuron.pt", "batch": batch, "length": ex[0].shape[1], "target": target or os.environ.get("NEURON_PLATFORM_TARGET_OVERRIDE")}
    (path / "sysone.json").write_text(json.dumps(meta, indent=2, default=str))
    return path

class NeuronScorer:
    "Run a model compiled by `export_neuron`: pads each batch to its compiled shapes"
    def __init__(self, path):
        import torch_neuronx  # noqa: F401  (registers the Neuron runtime with torch.jit)
        self.meta = json.loads((Path(path) / "sysone.json").read_text())["neuron"]
        self.model = torch.jit.load(str(Path(path) / self.meta["file"]))
    def __call__(self, input_ids, attention_mask, qtype):
        B, L = self.meta["batch"], self.meta["length"]
        n = input_ids.shape[0]
        if n > B or input_ids.shape[1] > L: raise ValueError(f"a batch of {n} rows of {input_ids.shape[1]} tokens exceeds the compiled {B} × {L}")
        pad = lambda t, v: torch.cat([torch.cat([t, torch.full((t.shape[0], L - t.shape[1]), v, dtype=t.dtype)], 1),
                                      torch.full((B - n, L), v, dtype=t.dtype)], 0)
        q = torch.cat([qtype, torch.zeros(B - n, dtype=qtype.dtype)])
        return self.model(pad(input_ids, 0), pad(attention_mask, 0), q)[:n, :input_ids.shape[1]]

# %% ../nbs/47_xla.ipynb #a77fc217
NEURON_CHECK = r'''import json, os, sys
os.environ.setdefault("PJRT_DEVICE", "CPU")     # no Neuron device here: XLA's own device is the CPU; neuronx-cc compiles for the target
from pathlib import Path
from sysone.data import TypedDecisions
from sysone.learner import decision_learner
from sysone.xla import export_neuron
data = TypedDecisions.from_json(sys.argv[1], valid=0.25, calib=0.2)
learn = decision_learner(data, sys.argv[2], train="head", preset="cpu", logging_steps=1, disable_tqdm=True, calibrate_after_fit=False)
out = export_neuron(learn, Path("/w/neuron-jev"), batch=1, length=int(sys.argv[3]), target=sys.argv[4])
meta = json.loads((out / "sysone.json").read_text())["neuron"]
print("SYSONE-NEURON " + json.dumps(meta | {"bytes": (out / meta["file"]).stat().st_size}))
'''

def neuron_check_image(tag:str="sysone-neuron-check", platform:str="linux/amd64") -> str:
    "Build a Linux image with the Neuron SDK's compiler and this sysone, to check that `export_neuron` compiles"
    import subprocess, tempfile
    from sysone.cloud import build_wheel
    ctx = Path(tempfile.mkdtemp(prefix="sysone-neuron-")); build_wheel(ctx / "wheels")
    (ctx / "Dockerfile").write_text("FROM python:3.12-slim\nENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1\n"
        'RUN pip install --index-url https://download.pytorch.org/whl/cpu "torch==2.9.0" && pip install "torch_xla==2.9.0"\n'
        'RUN pip install --extra-index-url https://pip.repos.neuron.amazonaws.com "torch-neuronx==2.9.*" neuronx-cc\n'
        'RUN pip install "islpy==2026.1"\n'      # neuronx-cc 2.27 asks for islpy~=2026.1, and 2026.2 changed a function it calls'
        # torch-neuronx loads the Neuron runtime (libnrt) even to compile, and the runtime comes from AWS's apt repository
        "RUN apt-get update && apt-get install -y --no-install-recommends gnupg wget ca-certificates && "
        "wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | gpg --dearmor > /usr/share/keyrings/neuron.gpg && "
        'echo "deb [signed-by=/usr/share/keyrings/neuron.gpg] https://apt.repos.neuron.amazonaws.com noble main" > /etc/apt/sources.list.d/neuron.list && '
        "apt-get update && apt-get install -y --no-install-recommends aws-neuronx-runtime-lib && "
        "(apt-get install -y --no-install-recommends libarchive13t64 || apt-get install -y --no-install-recommends libarchive13) && "   # the compiler's backend
        "rm -rf /var/lib/apt/lists/*\n"
        "ENV LD_LIBRARY_PATH=/opt/aws/neuron/lib\n"
        "COPY wheels/ /w/\nRUN pip install /w/*.whl\n")
    r = subprocess.run(["docker", "build", "--platform", platform, "-t", tag, str(ctx)], capture_output=True, text=True)
    if r.returncode != 0: raise RuntimeError(f"docker build failed: {r.stdout[-1500:]}{r.stderr[-1500:]}")
    return tag

def neuron_check(data, encoder, length:int=64, target:str="inf2", tag:str="sysone-neuron-check", platform:str="linux/amd64") -> dict:
    "Train a learner in a Linux container and compile it for a Neuron target with `export_neuron`; returns the compiled model's record"
    import shutil, subprocess, tempfile
    work = Path(tempfile.mkdtemp(prefix="sysone-neuron-run-"))
    (work / "check.py").write_text(NEURON_CHECK)
    shutil.copy2(data, work / Path(data).name); shutil.copytree(encoder, work / "encoder")
    r = subprocess.run(["docker", "run", "--rm", "--platform", platform, "-v", f"{work}:/w", "-w", "/w", tag,
                        "python", "check.py", Path(data).name, "encoder", str(length), target], capture_output=True, text=True)
    line = next((l for l in r.stdout.splitlines() if l.startswith("SYSONE-NEURON ")), None)
    if line is None: raise RuntimeError(f"the Neuron check failed: {(r.stdout + r.stderr)[-3000:]}")
    return json.loads(line[len("SYSONE-NEURON "):])
